### ISSUE TITLE
How to.. HTTP 429: Break shared circuit for specified time?

### ISSUE THREAD

**Issue by Rast1234** [App-vNext/Polly#1035]
Hi! I'm trying to handle HTTP 429 responses. They usually tell how long a client should wait with `Retry-After` header. I'd like to avoid calling this endpoint again while it's already "locked out", so i thought i need a `CircuitBreaker`, which can be shared across all calls to the endpoint. However, i can't change CB's timeout based on response.

Looking at `WaitAndRetry`, there is a timeout selector delegate, but i don't need to retry. Also i'm not sure if shared WaitAndRetry will block other calls to wait until something triggered waiting. Is sharing a WaitAndRetry documented and i missed it somewhere?

There's also `Bulkhead` which is shared and can be used to lock out the resource but it's basically a semaphore and i didn't figure out how to utilize it in my scenario. Also, waiting queue there is a nice thing to have on a CircuitBreaker too (for my case): if resource is locked out for some time, calls can wait together in a limited queue instead of failing.

So, looks like i want something strange and probably orthogonal to existing Policies. Is there some way to achieve it without hacks like stacking a bunch of policies together passing state and specific exceptions around?

**Comment by PeterCsalaHbo** [comment]
If I understand you correctly then you want to
- use a CB which should stay in Open state by respecting the `Retry-After` header
- and suspend retries until the CB is broken

Let's start with second part
```cs
static IAsyncPolicy<HttpResponseMessage> GetCircuitBreakerPolicy()
{
    return Policy<HttpResponseMessage>
        .HandleResult(res => res.StatusCode == HttpStatusCode.TooManyRequests)
        .CircuitBreakerAsync(3, TimeSpan.FromSeconds(2),
           onBreak: (dr, ts, ctx) => { ctx[SleepDurationKey] = ts; },
           onReset: (ctx) => { ctx[SleepDurationKey] = null; });
}
```
```cs
static IAsyncPolicy<HttpResponseMessage> GetRetryPolicy()
{
    return Policy<HttpResponseMessage>
    .HandleResult(res => res.StatusCode == HttpStatusCode.TooManyRequests)
    .Or<BrokenCircuitException>()
    .WaitAndRetryAsync(4,
        sleepDurationProvider: (c, ctx) =>
        {
            if (ctx.ContainsKey(SleepDurationKey))
                return (TimeSpan)ctx[SleepDurationKey];
            return TimeSpan.FromMilliseconds(200);
        },
        onRetry: (dr, ts, ctx) => { });
}
```
So, basically you can pass sleep duration information from the CB to the Retry via a context.
For more details please check this [SO thread](https://stackoverflow.com/a/69551471/13268855).
___
The first part
```cs
var cb = Policy<HttpResponseMessage>
    .HandleResult(res => res.StatusCode == System.Net.HttpStatusCode.TooManyRequests)
    .CircuitBreaker(1, TimeSpan.FromSeconds(0),
    onBreak: (dr, __) => {
        var retryAfterHeader = dr.Result?.Headers?.RetryAfter;
        TimeSpan sleep = retryAfterHeader != null ? retryAfterHeader.Delta.Value : TimeSpan.FromSeconds(2);
        Thread.Sleep(sleep);
    },
    onReset: () => { },
    onHalfOpen: () => { });
```
The CB was not designed for dynamic break this workaround relies on the current implementation of the CB.
For more details please check this [SO thread](https://stackoverflow.com/a/69605142/13268855)

**Comment by Rast1234** [comment]
Thank you! Wow that's complex. I get your idea with retries checking on context and CB changing the context value, no way i could've figured that out myself :)

I thought maybe i'm missing something, but turns out my scenario just doesn't align with instruments provided by Polly, unfortunately.
