### ISSUE TITLE
Thanks !!!

### ISSUE THREAD

**Issue by michael-wolfenden** [App-vNext/Polly#105]
Just wanted to say thanks to @joelhulen and crew and especially @reisenberger for all your amazing work on Polly. You have really taken the reigns and made it a far greater library than I could ever have. Look forward to seeing what you guys have in store for the future.

**Comment by joelhulen** [comment]
Thanks, @michael-wolfenden! We're just trying to build on top of this excellent library that you graciously shared with us and the community as a whole. I do what I can to help coordinate and drive efforts, but most of the credit must go to @reisenberger for really taking it to the next level. We've also had a few other great contributors along the way, such as @kristianhald, @nedstoyanov, @yevhen, and @nelsonghezzi.

As far as the future, I'd love it if you could offer your opinion on the [roadmap](https://github.com/App-vNext/Polly/wiki/Polly-Roadmap) via the [associated issue](https://github.com/App-vNext/Polly/issues/90)!

**Comment by reisenberger** [comment]
@michael-wolfenden Thanks, but: none of this would exist if it weren't for the elegant simplicity of your original idea! :smile:  

Our aim is to continue to grow Polly in that same spirit: each policy does one thing well, simple to configure, easy to comprehend.
