### ISSUE TITLE
Update project website in GitHub to HTTPS

### ISSUE THREAD

**Issue by martincostello** [App-vNext/Polly#1050]
**Summary**: 

The link to the Polly website in GitHub currently points to an HTTP URL:

![image](https://user-images.githubusercontent.com/1439341/223977279-68433d7b-03a8-4858-9c1e-3ce4c5dfacc9.png)

This then gives you this warning in Chrome as there is no HTTP->HTTPS redirection in place:

![image](https://user-images.githubusercontent.com/1439341/223977343-62fdac40-44af-4f01-9705-b46c21ffd77c.png)

We should update the GitHub website URL to be to the HTTPS version which doesn't have this warning:

![image](https://user-images.githubusercontent.com/1439341/223977532-4350633d-6a88-42bc-a88e-328332c83e53.png)

Assigning to Joel as he has the appropriate permissions to resolve.

**Expected behavior**: 

User is directed to the website using HTTPS.

**Actual behaviour**:

User is directed to the website using HTTP.

**Steps / Code to reproduce the problem**: 

N/A

**Comment by joelhulen** [comment]
Great catch! I had updated the main readme to use HTTPS, but I forgot about the area in the info box to the right of the project repo. I've updated this.
