### ISSUE TITLE
Readme improvement

### ISSUE THREAD

**Issue by postb99** [App-vNext/Polly#1054]
Hello, I think that step 2 contains a lot of code snippets, thus I had some troubles finding step 3, a lot of scroll... and this made me loose some time understanding how to execute some code through the configured policy. Sorry for this user issue.

Maybe step 2 can present only one code snippet and the other policy names/behaviors/samples could be listed/linked after code snippet... after main steps in the Readme?

After reading again, the samples are a bit more detailed than table at step 1 (Retry and RetryForever vs only Retry) and they are linked from the table as quick start. I fully agree to keep all quick starts in the Readme itself.

Hoping I'm clear, best regards,

Step 2: https://github.com/App-vNext/Polly#step-2--specify-how-the-policy-should-handle-those-faults
Step 3: https://github.com/App-vNext/Polly#step-3--execute-code-through-the-policy

**Comment by martincostello** [comment]
We are aiming to improve the README as part of the v8 release.
