### ISSUE TITLE
Infrastructure for strategies - async delegates for Events, Predicates, Generators

### ISSUE THREAD

**Issue by martintmk** [App-vNext/Polly#1067]
# Handling of different result types

Various implementations of `ResilienceStrategy` use callbacks to provide or request information from user. The callbacks are generic and support any type of result. Most strategies will use the following types of callbacks:

- **Predicates**: These return `true` or `false` values based on the input. The input can be the result of an user-callback or some exception. For example, to determine whether we should retry the user-callback for a specific result.
- **Events**: These are events raised when something important happens. For example when a timeout occurs.
- **Generators**: These generate a value based on the input. For example, a retry delay before the next retry attempt.

All callbacks are asynchronous and return `ValueTask`. They provide the following information to the user:

- `ResilienceContext`: the context of the operation.
- Result type: for what result type is the strategy being executed.
- Callback arguments: Additional information about the event. Using arguments is preferable because it makes the API more stable. If we decide to add a new member to the arguments, the call sites won't break.

Each callback type has an associated class that can be reused across various strategies. For example, see the `Predicates` class and the usage of the `RetryStrategyOptions.ShouldRetry` property:

``` csharp
public Predicates ShouldRetry { get; set; } = new();
```

``` csharp
var options = new RetryStrategyOptions();
options
    .ShouldRetry
    .Add<HttpResponseMessage>(result => result.StatusCode == HttpStatusCode.InternalServerError) // inspecting the result
    .Add(HttpStatusCode.InternalServerError) // particular value for other type
    .Add<MyResult>(result => result.IsError)
    .Add<MyResult>((result, context) => IsError(context)) // retrieve data from context for evaluation
    .AddException<InvalidOperationException>() // exceptions
    .AddException<HttpRequestMessageException>() // more exceptions
    .AddException(error => IsError(error)) // exception predicates
    .Add<MyResult>(async (result, context) => await IsErrorAsync(result, context)); // async predicates
```

In the preceding sample you see that `ShouldRetry` handles the following scenarios:

- Asynchronous predicates;
- Synchronous predicates;
- Concrete value results;
- Custom function-based callbacks;
- Different result types;
- Exception types or exception-based predicates;

We can just polish these and move to the official branch.

**Comment by PeterCsalaHbo** [comment]
This asynchronous predicate can be handy in some situation. BUT it might also encourage people to perform database lookups or network requests which could take time. 

The current design embraces simple and quick evaluation of trigger firing. With async predicates the consumers of the library might put there complex and time-consuming logic.

I might overthink this intention of misuse, but the potential is there.
