### ISSUE TITLE
Digital signing of DLL in GitHub Actions

### ISSUE THREAD

**Issue by claudy** [App-vNext/Polly#1102]
**Is your feature request related to a problem? Please describe.**
Currently, the Polly.dll in the NuGet package does not have a digital signature. A digital signature would aid in verifying its authenticity and integrity.

**Describe the solution you'd like**
The DLLs can be digitally signed after compilation as a part of the GitHub Actions in build.yml.
[Nate McMaster's instructions](https://natemcmaster.com/blog/2018/07/02/code-signing/) are detailed and helpful.
[Documentation of SignTool.exe](https://github.com/dotnet/docs/blob/main/docs/framework/tools/signtool-exe.md) might be useful.
[Chrissy LeMaire](https://blog.netnerds.net/2022/06/signing-powershell-modules-github-actions/) has an article about digitally signing PowerShell scripts in GitHub Actions, which might be partially relevant.

**Additional context**
This came about because a security audit of 3rd party dependencies found missing digital signatures. Polly was one of the dependencies missing a digital signature. The assertion is that a DLL should be digitally signed to ensure integrity of the DLL's contents, i.e. it was not tampered with by a malicious actor.

**Comment by martincostello** [comment]
The ability to sign the DLL is not the main difficultly here.

The process to acquire one and the monetary cost to do so would be.

**Comment by claudy** [comment]
After consideration of options, my company decided to grant an exception for Polly in the security audit. Maybe someday there will be a service similar to Let's Encrypt for code-signing purposes. For most open-source projects, code-signing certificates are too expensive and provide maintainers little to no benefit.

**Comment by joelhulen** [comment]
Reopening since we are revisiting the digital signing issue.

**Comment by martincostello** [comment]
This was resolved by #1269 and [v7.2.4](https://github.com/App-vNext/Polly/releases/tag/7.2.4) is Authenticode signed.
