### ISSUE TITLE
The build is broken in Windows because of testhost connection

### ISSUE THREAD

**Issue by martintmk** [App-vNext/Polly#1154]
**Summary**: 

Any [windows build](https://github.com/App-vNext/Polly/actions/runs/4783994471/jobs/8504927828?pr=1153) fails with the following error:

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
vstest.console process failed to connect to testhost process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
Data collector 'Blame' message: The specified inactivity time of 10 seconds has elapsed. Collecting hang dumps from testhost and its child processes.
Data collector 'Blame' message: Dumping 4816 - testhost.
Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.
```

Seems to be a problem with nuget cache:
https://github.com/microsoft/vstest/issues/2108

We might disable this in Windows in the meantime to unblock.

@martincostello

**Comment by martincostello** [comment]
Happy for you to turn off the package caching as part of #1153 if it's causing issues.

**Comment by martintmk** [comment]
Thanks, that would help :)

**Comment by martintmk** [comment]
@martincostello, I believe this problem is undeterministic as I was able to merge the PR above. However the builds will be unstable until we fix this.

**Comment by martintmk** [comment]
@martincostello 

After too many build failures I gave this thread a quick read:
https://github.com/microsoft/vstest/issues/2952

And there was a mention of `--blame-hand-timeout` that I knew we added recently (around that time this instability started)

So I commented this piece in the cake build:

```
// Commented, because it causes random crashes on Windows
// ArgumentCustomization = args => args.Append($"--blame-hang-timeout 10s")
```
'And now, the Windows build is finally passing. I quess we have to live without the command-line option above or just disable it on windows.
