### ISSUE TITLE
Pull request automation?

### ISSUE THREAD

**Issue by martincostello** [App-vNext/Polly#1167]
To aid in the maintenance of Polly (dependabot updates, .NET SDK updates), it would be good to harness GitHub Actions and the GitHub API to perform some tasks automatically to reduce some of the human element.

The initial automation I'd like to add are:

- [Approve dependabot updates](https://github.com/martincostello/dotnet-patch-automation-sample/blob/main/.github/workflows/dependabot-approve.yml) (based on an allow-list) - example pull request https://github.com/justeattakeaway/httpclient-interception/pull/551
- [Updating the .NET SDK](https://github.com/martincostello/dotnet-patch-automation-sample/blob/main/.github/workflows/update-dotnet-sdk.yml) - example pull request https://github.com/martincostello/dotnet-patch-automation-sample/pull/107
- [Auto-approve .NET SDK updates](https://github.com/martincostello/dotnet-patch-automation-sample/blob/main/.github/workflows/approve-and-merge.yml) - example pull request https://github.com/martincostello/dotnet-patch-automation-sample/pull/107
- [Marking old issues and pull requests as stale](https://github.com/actions/stale#readme)

To get the most out of this, the first three ideas for automation needs to run as a GitHub user or app (bot), rather than use `GITHUB_TOKEN`, which has limitations in terms of triggering actions ([docs](https://docs.github.com/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow)) - otherwise CI runs aren't queued-up.

Assuming others are happy with these ideas, we'd just need a bot (or two; one to edit, one to approve) created in App-vNext (`pollybot`, `polly-reviewer`? ideas for better names welcome) and a private key to exchange for an access token to act on the bot's behalf added to the GitHub Actions secrets in this repo.

**Comment by martintmk** [comment]
@joelhulen, I really like @martincostello suggestion here. Would save us a lot of time. Can we try to go ahead with this?

**Comment by joelhulen** [comment]
I'm game. What do I need to do?

**Comment by martincostello** [comment]
To do this, _roughly_ these steps:

1. Create a GitHub application to be a "reviewer" in the App-vNext organisation scoped to the Polly repo. The app will be private so it isn't possible to install to any other organisation. The app needs the following repository permissions to be able to review and merge pull requests:
    - Read and write Contents
    - Read and write Pull requests
    - Read and write Workflows
1. Generate a private key for the reviewer GitHub app
1. Add the reviewer application ID and private key into the GitHub Actions secrets for the Polly repository
1. Create a GitHub application to be the "updater" in the App-vNext organisation scoped to the Polly repo. The app will be private so it isn't possible to install to any other organisation. The app needs the following repository permissions to push commits and create pull requests:
    - Read and write Contents
    - Read and write Pull requests
1. Generate a private key for the updater GitHub app
1. Add the updater application ID and private key into the GitHub Actions secrets for the Polly repository
1. Bonus points for setting the avatar for 

After those are set up I can do the pull requests based on the examples I linked to to use the bots to add the automation.

Happy to do a quick call with you to walk through doing the steps of setting up the apps if that's easier.
