### ISSUE TITLE
Passing IServiceProvider to AddTransientHttpErrorPolicy like AddPolicyHandler

### ISSUE THREAD

**Issue by mehdihadeli** [App-vNext/Polly#1182]
Hi,
Could we have `IServiceProvider` as one of the parameters in `AddTransientHttpErrorPolicy` lambda expression, like something we have in `AddPolicyHandler`?

**Comment by martincostello** [comment]
This functionality is part of dotnet/aspnetcore ([docs](https://learn.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.pollyhttpclientbuilderextensions), not Polly.

Please file an issue there for this request.
