### ISSUE TITLE
Original Circuit Breaker Documentation Typo

### ISSUE THREAD

**Issue by vermiceli** [App-vNext/Polly#1189]
I'm reading the circuit breaker documentation, and I believe there is a typo in the text

> * If the faults exceed a certain threshold, the circuit will break (open).
>   * The original Polly CircuitBreaker will break after N consecutive actions executed through the policy have thrown any handled exception, where N is the int exceptionsAllowedBeforeBreaking the policy was configured with.

Shouldn't the phrase `thrown any handled exception` be `thrown any unhandled exception`?

**Comment by vermiceli** [comment]
I believe I now understand the word handled here to refer to the exception specified in `Handle` method and not in the `try/catch` sense.  I think that's confusing as you can use Circuit Breaker with `HandleResult`.  Perhaps the phrasing should say

> after N consecutive actions executed through the policy have thrown any handled exception/result by the policy, where N is the int exceptionsAllowedBeforeBreaking the policy was configured with

I'm not too familiar with the correct vocabulary to clearly state this.

**Comment by martincostello** [comment]
What about this?

> after N consecutive actions executed through the policy have thrown any exception/result handled by the policy, where N is the int exceptionsAllowedBeforeBreaking the policy was configured with

**Comment by vermiceli** [comment]
I guess I don't want to overspeak to the property.  Does this property `exceptionsAllowedBeforeBreaking` only work for `.Handle<Exception>` instead of `HandleResult`?

> actions executed through the policy have thrown any exception/result handled by the policy

To me, it feels weird to say a result is "thrown".

**Comment by martincostello** [comment]
What would you suggest instead then?

**Comment by vermiceli** [comment]
I now see there are multiple extension methods depending on whether `.HandleResult` is called or `Handle`.  In `HandleResult`, the parameter is named `handledEventsAllowedBeforeBreaking` and not `exceptionsAllowedBeforeBreaking`.  The document is exclusively talking about `exceptionsAllowedBeforeBreaking`, so I think in the context, it is best to leave the documentation as it is.  It could be updated to add information about `handledEventsAllowedBeforeBreaking`, but the current text seems fine for me now that I have a fuller context.
