### ISSUE TITLE
Call an authenticate method before retrying

### ISSUE THREAD

**Issue by reisenberger** [App-vNext/Polly#122]
@robertbaker asked under a separate issue (moving here as worth calling out as own issue!)

> I have a scenario for web requests.
> 
> Say I make a httpClient call that throws a 403. On a 403, I want to 
> call my authenticate method first then retry the method.
> 
> I don't think this is possible currently with polly. If it is please give me an example!

**Comment by reisenberger** [comment]
Hey @robertbaker.  This came up on StackOverflow recently, but I think the q has been deleted.  It's  very possible.  Configure a policy with an `onRetry` delegate.  The `onRetry` delegate is called before the next try.  In the `onRetry` delegate, call your authentication method.

The code at the top of #107 gives an example.  [#107 uncovered an async sequencing issue, now fixed, but the code example matches your need I think!]

Let us know if you need any further assistance!

**Comment by reisenberger** [comment]
@robertbaker  If an additional issue is that `HttpClient` returns 403 as a status code rather than throws an exception, `HttpResponseMessage.EnsureSuccessStatusCode()` can be used to make that an exception, as described [here](http://www.asp.net/web-api/overview/advanced/calling-a-web-api-from-a-net-client).  This provides a way of getting Polly to handle outcomes from `HttpClient` calls that might be _either_ exceptions (eg timeouts) or status codes.  There's a sketch of an async example using continuations [here](https://github.com/App-vNext/Polly/issues/121#issuecomment-225166950).

We are looking at allowing Policies to handle return values as well as exceptions natively - see #14, and wider discussion in the [Roadmap](https://github.com/App-vNext/Polly/wiki/Polly-Roadmap).  Any feedback you have towards this feature would be welcome!  Thanks.

**Comment by robertbaker** [comment]
Thanks, I'll try to implement this soon.

**Comment by reisenberger** [comment]
@robertbaker No problem.  @PhilipAnthonyMurray was essentially working on sthg similar I think.  We are doing the same thing in-house and achieved this pattern against both straight http authentication and SAML authentication: but the pattern isn't any more complicated than outlined above.

**Comment by reisenberger** [comment]
@adamhathcock You raised OAuth and Polly on #90, see this thread #122. One pattern is to use the `onRetry` delegate (which gets executed between tries), so, in its simplest schematic form, something like:

```csharp
var authorisationEnsuringPolicy = Policy
  .Handle<AuthorizationException>()
  .Retry(1, onRetry: (e, i) => RefreshAuthorization());

authorisationEnsuringPolicy.Execute(() => DoSomethingThatRequiresAuthorization());
```

**Comment by adamhathcock** [comment]
Thanks @reisenberger I was sure there was some way to do it without having to bring in some kind of new concept.

**Comment by reisenberger** [comment]
Closing historic issue.  Fully documented [on wiki](https://github.com/App-vNext/Polly/wiki/Retry#other-uses-for-retry)
