### ISSUE TITLE
EnsureSuccess for PolicyResult

### ISSUE THREAD

**Issue by michalczerwinski** [App-vNext/Polly#1238]
When replacing try/catch block with Polly equivalent one has to manually check the result and make sure there is no exception:

```CSharp
    var policy = Policy
        .Handle<InvalidDataException>()
        .RetryAsync(3, (e, r) => Console.WriteLine($"Retry no {r}"));

    var policyResult = await policy.ExecuteAndCaptureAsync(async () =>{ /*...*/});

    if (policyResult.Outcome == OutcomeType.Successful)
    {
        return policyResult.Result;
    }
    else throw new SomeException(policyResult.FinalException);

```
It would be nice to be able to do this instead:
```CSharp

   policyResult.EnsureSuccess();
   return policyResult.Result;
```

**Comment by martincostello** [comment]
@martintmk Is there anything that would essentially fulfil this request in v8?

**Comment by martintmk** [comment]
There is low-level method in V8 to retrieve the outcome:
https://github.com/App-vNext/Polly/blob/main/src/Polly.Core/ResilienceStrategy.TResult.Async.cs#L104

I think we can add this helper method to Outcome in V8. It will be useful.

**Comment by PeterCsalaHbo** [comment]
This can be easily done via extension method(s):
```cs
public static void EnsureSuccess(this PolicyResult result) 
{
     if (result.Outcome == OutcomeType.Failure) 
        throw new SomeException(result.FinalException)
}

public static void EnsureSuccess<TResult>(this PolicyResult<TResult> result) 
{
     if (result.Outcome == OutcomeType.Failure) 
        throw new SomeException(result.FinalException)
}
```

**Comment by martintmk** [comment]
The V8 `Outcome<T>` now contains the `EnsureSuccess`. For V7 you can use the @PeterCsalaHbo  suggestion.
