### ISSUE TITLE
pollytalk.org not working

### ISSUE THREAD

**Issue by martincostello** [App-vNext/Polly#1256]
I just spotted that the Slack badge in the repo README wasn't working, and further investigation lead me to find that http://pollytalk.org is returning HTTP 500s.

Should it work, or is it obsolete and we should just remove the badge? If it _should_ work it also looks like it doesn't enable HTTPS as using that instead of HTTP gives a certificate error.

**Comment by abe-101** [comment]
in the meantime is there an alternative how to join the slack?

**Comment by martincostello** [comment]
@joelhulen Are you intending to fix pollytalk at some point, or should we just remove any references to it and consider it dead?

I think the only thing that needs updating if we kill it is this:

https://github.com/App-vNext/Polly/blob/5634c302501a849c5ade30e1c0a9b6c61a4bfbfd/CONTRIBUTING.md?plain=1#L9

**Comment by joelhulen** [comment]
The project that I based this off of is dead. I will take a look again and see if there's some new replacement. The whole idea is that we can simplify the process to join our Slack channel and also get a count of Slack users. If there's a simpler way to get people on Slack that does not include the badge, then I think we can live with that. Will dig in and report back.

**Comment by kaplanlior** [comment]
Is there any alternative way to join the Polly's slack channel? 
The join link isn't publish, just the sign it to existing users.

**Comment by kaplanlior** [comment]
@martincostello can you please reopen this issue ?

> Is there any alternative way to join the Polly's slack channel? The join link isn't publish, just the sign it to existing users.
> 
> Seems like a common problem - I saw this service is used by k8s for the same goal. https://communityinviter.com/apps/kubernetes/community

@martincostello can you please reopen this issue ?
