### ISSUE TITLE
Reorganize the source folders

### ISSUE THREAD

**Issue by martintmk** [App-vNext/Polly#1281]
I was thinking to better align with other .NET projects we can split the root `/src` folders into:

- `/src`: now only contains `Polly` libraries 
- `/test`
- `/bench`: benchmarks
- `/samples`: samples folder we can introduce

These folders will be in the root repo folder. Additionally, the `Polly.sln` will also be located in the root folder.

Each of these folders can then contain the respective `Directory.Build.props` and `Directory.Target.props`. I think this change can simplify and unify the navigation within the repo. 

@joelhulen, @martincostello WDYT, shall I give this a go?

**Comment by martincostello** [comment]
I'd be happy with that (particularly that there's so many projects now).

I would suggest raising everything one level as well though and having everything in the root, rather than /src/src, /src/test etc. if we do make this change.

**Comment by joelhulen** [comment]
Agree with @martincostello on his suggestion. Overall, I think this is a great idea!
