### ISSUE TITLE
Introduce `samples` folder

### ISSUE THREAD

**Issue by martintmk** [App-vNext/Polly#1291]
We should introduce the `samples` folder that contains various basic examples of `Polly` usage. For example:

- `ResilienceStrategy`
- `Telemetry`
- `DependencyInjection`
- `Registry`
 
Each sample will have `Program.cs` at the root and package reference to respective latest `Polly` packages.

Then for more advanced scenarios the README.md at the root can reference more examples at:
https://github.com/App-vNext/Polly-Samples

@joelhulen, @martincostello Any other ides how we can structure this?

**Comment by martincostello** [comment]
This sounds like a good idea to me - maybe have a seperate `.sln` file in that `samples` directory that has all those projects in it?

If we keep it separate from (most) of the main build we can avoid being too strict on it for the purpose of style etc. over making the samples easier to read (as well as referencing Polly from NuGet rather than source), but we should add the extra solution into the CI so we keep it healthy. We could always add in a conditional bit of MSBuild scripting that makes it easy to switch to Polly-from-source instead of NuGet in the sample project(s).

**Comment by martintmk** [comment]
Haven't thought about having the separate sln for samples folder, but I like the idea. We will simply show how Polly is used from the perspective of consumer. 

We can still cross-reference those sample projects from the main solution if needed.

**Comment by PeterCsalaHbo** [comment]
Just thinking out loud. 

Can you guys organize the samples in the way that they are grouped based on their difficulty? 
- **Entry level**: simple examples which are showing the easiness of usage of a single policy
  - For example: How to use use retry?
- **Intermediate level**: a bit more advanced samples which are showing integration of multiple policies 
  - For example: How to combine Retry, Circuit Breaker and Timeout policies for HttpClient?
- **Advanced level**: complex examples which are covering close to real-world  scenarios
  - For example: How to use policy for refresh token scenario? 
  
 I have a lots of sample projects (mainly targeting V7) from StackOverflow questions. 
 I would be more than happy to convert them to V8 and contribute here.

**Comment by martincostello** [comment]
I'd forgotten about that repo. It's a bit unloved (I think), so maybe it's a good idea to rejuvenate it and retain the separation.

Maybe we could just have one very-basic sample in the repo, and then just point off there for the larger corpus?

**Comment by joelhulen** [comment]
Yeah, it's not obvious for people to find, apparently. We need to make it more discoverable. I like the idea of doing a basic sample in the repo and pointing to the separate one for people to easily find.

**Comment by martintmk** [comment]
> Remember, we already have https://github.com/App-vNext/Polly-Samples. Do you think we should use that as the basis for the new solution in the main repo? The reason I like this separate is because you don't have to pull down everything to run samples.
> 
> If we decide to keep all the samples in the main Polly repo, then we should sunset the Polly-Samples repo and point people to the Samples folder that has a separate `.sln`. I also like the idea of having the Entry, Intermedia, and Advanced-level examples.

Oh, I was completely unaware about that one. I would say it makes sense to reuse it. I guess then this PR can be abandoned:

https://github.com/App-vNext/Polly/pull/1295
