### ISSUE TITLE
Upgrade the `Polly.Samples` repo to V8

### ISSUE THREAD

**Issue by martintmk** [App-vNext/Polly#1300]
We should cleanup, polish and upgrade https://github.com/App-vNext/Polly-Samples to V8.

**Comment by peter-csala** [comment]
If there is no other volunteer you can assign to me.

**Comment by martincostello** [comment]
That would be most appreciated ❤️

**Comment by martincostello** [comment]
I've moved this out to the v8.1.0 milestone as this doesn't block us from releasing.

**Comment by peter-csala** [comment]
I think we have finished with the migration. I'm moving to close the Issues on the Samples repository.
