### ISSUE TITLE
Polly V8 Release Checklist

### ISSUE THREAD

**Issue by martintmk** [App-vNext/Polly#1302]
Before officially releasing Polly V8 we should close the following issues:

- [x] #1091 
- [x] #1301 
- [x] #1130
- [x] #1110 
- [x] #1280 
- [x] #1233
- [x] #1291 
- [x] #1303 
- [x] #1304
- [x] #1090
- [x] #1312
- [x] #1601 

For 8.1 release:

- [ ] #1070
- [ ] #1141

For consideration:

- [ ] #1300 
- [x] #1132 - ~this brings non-trivial [performance hit](https://github.com/App-vNext/Polly/blob/main/bench/BenchmarkDotNet.Artifacts/results/Polly.Core.Benchmarks.BridgeBenchmark-report-github.md). We should determine whether to wait and do it later as a part of code-cleanup once more people switch to V8.~
- [x] #1133 - is this something we even want in V8 (passive timeout can lead to non-cancellable background tasks that can overwhelm the system)

@martincostello , @joelhulen Have I missed anything? Any additional tasks to add?

**Comment by martincostello** [comment]
Moved to v8.1.0 milestone as we've done everything for 8.0.0 now (except for #1599)
