### ISSUE TITLE
[V8] ShouldHandle, ShouldRetry etc. predicates should have reasonable defaults

### ISSUE THREAD

**Issue by adsamcik** [App-vNext/Polly#1313]
Currently when using the new API, it is required to specify `ShouldHandle` predicate for CircuitBreaker, `ShouldRetry` predicate for Retry and probably more.

I think it would be beneficial to have some reasonable default predicates so that users don't need to specify it every time. For example I would consider reasonable default to handle all requests that throw exceptions (other than `OperationCancelledException`).

Also it would be nice to have the defaults for Http scenarios (handling 5xx requests), because these will be common as well.

**Comment by martintmk** [comment]
Yeah, I agree here, let's address this in alpha2. Would provide a nice out-of-box experience.
