### ISSUE TITLE
[Beta] Support .NET Core 1.0 RTM tools preview 2

### ISSUE THREAD

**Issue by reisenberger** [App-vNext/Polly#132]
# Support .NET Core 1.0 RTM tools preview 2

## Major issues

We will not as of now merge a Tools-Preview-2 solution to the master Polly branch, given the [state of flux of the tooling](https://blogs.msdn.microsoft.com/dotnet/2016/05/06/net-core-rc2-improvements-schedule-and-roadmap/) (project.json will go away) and that dependencies we use (fluent assertions; xunit) are also naturally in flux at this time. 

Instead .NET Core 1.0 RTM Tools Preview 2 support will initially be provided out of this issue rather than a [PR on master](https://github.com/App-vNext/Polly/pull/51); shortly likely to merge to a branch on App-vNext/Polly and public beta packages.

Keeping this for now outside master should allow other feature development to continue in master without disruption from chasing the moving target of .NET Core tooling.

## Status and issues 02 July 2016

[1] Polly can target .NET Standard 1.6 to support .NET Core 1.0 RTM
[2] xunit2 runner console [does not yet support/target .NET Standard](https://github.com/xunit/xunit/issues/872).  Therefore, the test assembly for .NET Standard 1.6 must (currently) target .NetCoreApp, Version=v1.0  **UPDATE**: Denis Doomen and Oren Novotny advise that having tests target target .NetCoreApp, Version=v1.0  is the correct approach as-is and does not need changing.
[3] xunit2 runner console targeting .NetCoreApp, Version=v1.0 is [pre-release](https://www.nuget.org/packages/xunit.runner.visualstudio/2.2.0-beta2-build1149) at this time
[4] [pre-release version of Nuget.exe 3.5](https://dist.nuget.org/index.html) is needed in the build.cake to [handle the platform keyword in project.json](http://stackoverflow.com/questions/37358046/unknown-keyword-platform-when-restoring-in-visual-studio)
[5] xunit unit tests on the new .NET Standard 1.6 Polly.dll pass in Visual Studio, but **cannot (yet) be run as part of the project cake build script**.  This is due to failure copying the relevant xunit and fluent-assertions components to the build output directory.  ([possible-related-issue](https://github.com/NuGet/Home/issues/1084), [possible-related-issue](https://github.com/dotnet/cli/issues/2902), [solution-here-not-working](http://stackoverflow.com/questions/33951362/new-net-project-json-project-copying-pre-built-native-dlls-to-the-output-di/33952463#33952463), [solution-here-not-working](https://github.com/NuGet/Home/wiki/%5BSpec%5D-Content-v2-for-project.json), [solution-here-not-working](https://github.com/NuGet/Home/wiki/%5BSpec%5D-Managing-dependency-package-assets), [solution-here-not-working](https://oren.codes/2016/02/08/project-json-all-the-things/), [possibility via a post-build-script](http://stackoverflow.com/a/37911234/4151019) but the syntax is in flux.

**UPDATE** on [5]: getting .NET Core tests to run in cake script

+ [Project json post-compile step syntax flux description](https://github.com/dotnet/cli/issues/3094).  Using "postcompile" in place of "postbuild" worked but executed at an unexpected time (after each project compile?).  
+ Possible instead to copy all xunit and fluentassertions dotnet-tfm dlls using a batch file or cake `CopyFiles(...)`.  But led to `System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime , Version=4.1.0.0 ... or one of its dependencies.`  **Electing to park this again** until the tooling is more settled: we need robust build tools to replace project.json which handle transitive dependencies properly.

## Alternative

An entire alternative would be to convert the existing PCL 259 package to NetStandard 1.0 as described in [Oren Novotny's article](https://oren.codes/2016/06/23/portable-is-dead-long-live-netstandard/).  We would like to trial this, but it may still (as of now) face the issue of not having xunit net-standard test support.

**Comment by reisenberger** [comment]
@SamuelEnglard @mattwoberts / anyone else interested: [This branch on my local fork](https://github.com/reisenberger/Polly/tree/beta-core10tpv2-DotNetCore10RTMToolsPreview2) is the first beta of .NET Core 1.0 RTM Tools Preview 2 support based on all the issues mentioned above and @SamuelEnglard's earlier prototype (thanks!).  It should support  .NET Core 1.0 RTM based on Polly v4.3.0.

This [Polly.4.4.0-beta-core10tpv2-0001--60e495a.zip](https://github.com/App-vNext/Polly/files/344452/Polly.4.4.0-beta-core10tpv2-0001--60e495a.zip) continas the generated nuget packages.

@SamuelEnglard @mattwoberts / anyone: Would you be able to test these Nuget packages in your .NET Core apps and advise if they work, or any probs?  Based on feedback @joelhulen or I may then promote them to betas on nuget.

@SamuelEnglard As you said elsewhere, various package refs needed updating for RTM.  Feel free to comment if you see any other significant differences from what you have trialled.

Thanks

**Comment by reisenberger** [comment]
@ThreeSevenths Also alerting you on this based on #39: feel free to trial the new .NET Core 1.0 RTM support.

**Comment by SamuelEnglard** [comment]
Back at work so giving this a look. First thing to note is I only updated to support 1.3, as I don't think we to require 1.6. Otherwise looks good

**Comment by reisenberger** [comment]
hi @SamuelEnglard ! Very many thanks for all your input (and contribs so far).  Let me know how the package testing goes!  

Also happy to hear if you spot any other differences in construction between the package I made (based on Polly v4.3.0) and your earlier prototype.  (I wanted to create a fresh package to get a feel for the latest tooling and see what June 27 releases might have added, broadly the end result seemed fairly similar to yours, but happy for all feedback! ...)

Re:

>I only updated to support 1.3 as I don't think we to require 1.6.

I was following [Mapping the .NET Platform Standard to platforms](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms), which seemed to label .NET Core app as should map to .NET Standard 1.6?

On the other hand, Polly itself (if you take out the `SerializationInfo` constructors for Exceptions) (as Polly.Pcl does), is fully PCL259 compatible, thus fully `.NET Standard 1.0` compatible.  So we _should_ also be able to go with a `.NET Standard 1.0` package (which also supports the portable Xamarin etc targets).  I've posted a `.NET Standard 1.0` package under #133.  I'd be extremely grateful if you could also feedback whether that package plays with your ASP.NET Core webapps (it should).

Thanks!

(And @mattwoberts If you're able to join in on this too, all feedback gratefully received!)

**Comment by reisenberger** [comment]
Hey @SamuelEnglard @mattwoberts Did you have any time to try out the Polly .Net Core beta nuget packages posted in this thread? (Or the ones in #133 ?)  Thank you so much @SamuelEnglard for your kicking off with the first prototype! (the draft readme credits you as contributing).

**Comment by SamuelEnglard** [comment]
@reisenberger I've been pulled into side issues so I haven't been able to test this week. Thanks for the credit!

**Comment by reisenberger** [comment]
@SamuelEnglard Completely understood.  _Do_ give us a shout (or anyone else) if you do get a chance / have any feedback on the early packages, otherwise @joelhulen will probably push them out to nuget when he has some availability.

**Comment by mattwoberts** [comment]
Hi, sorry I've been all over the place this week, had to abandon porting my app to core for now. I hope to get some time to play next week and if so I'll take a look at this!

**Comment by reisenberger** [comment]
@mattwoberts Sure thing, we know how it goes :wink: All feedback gratefully received if you get the chance!

**Comment by reisenberger** [comment]
Closing in favour of the [v5.0.1-release](https://github.com/App-vNext/Polly/issues/164), which also supports `.NET Standard 1.0`
