### ISSUE TITLE
Improve the handling of Outcome in V8

### ISSUE THREAD

**Issue by martintmk** [App-vNext/Polly#1328]
Currently, the `Outcome<T>` is created as:

``` csharp
var outcome = new Outcome<HttpResponseMessage>(new HttpResponseMessage(HttpStatusCode.Ok));
```
In Polly V8 there are many places where the delegate need a function that returns ValueTask<Outcome<T>>:

``` csharp
var task = new ValueTask<Outcome<HttpResponseMessage>>(new Outcome<HttpResponseMessage>(new HttpResponseMessage(HttpStatusCode.Ok)));
```

The syntax gets a little obscure so I am thinking how we can simplify this handling. 

How about introduce the `Outcome` static class that will be used to create instances of `Outcome<T>` ?

``` csharp
public static class Outcome
{
    public static Outcome<TResult> Result<TResult>(TResult value) => new(value);

    public static ValueTask<Outcome<TResult>> ResultTask<TResult>(TResult value) => new(Result(value));

    public static Outcome<TResult> Exception<TResult>(Exception exception) => new(exception);

    public static ValueTask<Outcome<TResult>> ExceptionTask<TResult>(Exception exception) => new(Exception<TResult>(exception));
}
```

Now the usage becomes:
``` csharp
var outcome = Outcome.Result(new HttpResponseMessage(HttpStatusCode.Ok));
var task = Outcome.ResultTask(new HttpResponseMessage(HttpStatusCode.Ok));
```
We can take advantage of automatic type resolution. The constructors on `Outcome<T>` would be hidden and using the `Outcome` static class would be the only way to create instances of generic outcome.

This could also clean-up the V8 code a bit. 

Contributes to #1324 and #1301.

@martincostello , @joelhulen, @PeterCsalaHbo Your thoughts, should I give this a shot?

**Comment by martincostello** [comment]
Maybe call it `FromResult()`, like `Task.FromResult()`? Otherwise seems reasonable to me.

**Comment by martintmk** [comment]
@martincostello Any suggestions for the method that returns `ValueTask` based outcome? I don't want to put `Async` suffix there because then the analyzers recommend it when it's not relevant?

How about this?

``` csharp
public static ValueTask<Outcome<TResult>> FromResultAsTask<TResult>(TResult value) => new(Result(value));
```
Or maybe allow this syntax?

``` csharp
Outcome.FromResult("some-value").AsValueTask();
```

**Comment by martincostello** [comment]
FromResultAsTask is the best option, I think.

**Comment by PeterCsalaHbo** [comment]
For me the `FromResult` and `FromResultAsTask` seem fine.
```cs
public static class Outcome
{
    public static Outcome<TResult> FromResult<TResult>(TResult value) => ...;
    public static ValueTask<Outcome<TResult>> FromResultAsTask<TResult>(TResult value) => ...;
    public static Outcome<TResult> FromException<TResult>(Exception exception) => ...;
    public static ValueTask<Outcome<TResult>> FromExceptionAsTask<TResult>(Exception exception) => ...;
}
```

I think the `AsValueTask` would make sense if some API would return an `Outcome<TResult>` but you need to wrap it into a `ValueTask` to be compatible with other APIs. But as you said the V8 is async by nature so, if there is no API which returns `Outcome<TResult>` then having a single method, which combines the `Outcome` and `ValueTask` wrappings, eases the usage IMHO.
