### ISSUE TITLE
[Beta] Support .NET Standard 1.0

### ISSUE THREAD

**Issue by reisenberger** [App-vNext/Polly#133]
This issue attempts the avenue marked **Alternative** in #132 : convert the PCL 259 package to make a `netstandard1.0` offering for Polly, rather than the `netstandard1.6` offering in #132.  _Rationale_: A `netstandard1.0` offering will have wider applicability ([lower netstandard versions support wider targets](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md)). 

## Status and issues 02 July 2016

[1] The pre-requisite step described in [Oren Novotny's article](https://oren.codes/2016/06/23/portable-is-dead-long-live-netstandard/) of moving from packages.config to project.json (per an [earlier article](https://oren.codes/2016/02/08/project-json-all-the-things/)) worked, and was pushed as commit [bc66df8](https://github.com/reisenberger/Polly/commit/bc66df8e03c6c396dbae4e91b8653c3de55a8539) to [this branch on my local fork](https://github.com/reisenberger/Polly/tree/beta-netstandard10).

[2] The subsequent step in the [original article](https://oren.codes/2016/06/23/portable-is-dead-long-live-netstandard/) of moving projects from PCL259 to target instead `netstandard1.0` works for both `Polly.Pcl` and `Polly.Pcl.Specs`.

[3] But, as expected, [while we are awaiting xunit supporting netstandard](https://github.com/xunit/xunit/issues/872) and [FluentAssertions .NET Standard support](https://github.com/dennisdoomen/FluentAssertions/issues/431), testing is blocked in a catch22:

- (i) If we make `Polly.Pcl.Specs` target  `netstandard1.0` we cannot run the xunit tests. (per commit [ea462f7](https://github.com/reisenberger/Polly/commit/ea462f79eed3242df1e5cd255e5965dc83829d03))  **UPDATE 04 July 2016** Dennis Doomen and Oren Novotny advise against this approach: test libraries should not target .NET standard, but a specific target framework.

- (ii) If we don't make `Polly.Pcl.Specs` target `netstandard1.0` but `Polly.Pcl` does, `Polly.Pcl.Specs` cannot reference `Polly.Pcl` (obviously meaning again the tests cannot be run).  (per commit [9d55469](https://github.com/reisenberger/Polly/commit/9d554695212190b4ae96a519142c069fa6cb8f83)).
**UPDATE 04 July 2016**: Something like this approach is recommended.  Need to update approach to testing.

~~~This means that as-of today we cannot deliver a `netstandard1.0` Polly library _unit-tested in the tfm in which it is delivered_.  Such a package is thus vulnerable to the (unlikely-_but-possible_) eventuality that something breaks because the underlying BCL implementation has changed.~~~

**Comment by reisenberger** [comment]
**Early beta package for .NET Standard 1.0** support...

[This branch on my local fork](https://github.com/reisenberger/Polly/tree/beta-netstandard10) is a first beta of .NET **Standard** 1.0 support, taking account of issues mentioned earlier in this thread.  It should support  .NET Standard 1.0 based on Polly v4.3.0.  Unit-testing within .NET Standard is (for now only) omitted in generating the Net Standard 1.0 package while awaiting support from unit-testing dependencies (see earlier comment), _but the Polly codebase otherwise remains unchanged from the fully tested v4.3.0_. 

This [Polly.4.5.0-beta-netstandar-0001--a9acf76.zip](https://github.com/App-vNext/Polly/files/344757/Polly.4.5.0-beta-netstandar-0001--a9acf76.zip) contains the generated nuget packages.

These packages are provided as early betas for anyone wanting to take their portable / Xamarin / Windows Phone etc apps straight to .NET Standard 1.0 with Polly: _feedback gratefully received_.  Packages may be promoted to nuget after suitable testing.

@SamuelEnglard @mattwoberts : I would be exceptionally grateful if you were able also to test these Nuget packages also in your .NET Core apps and feed back?   .NET Standard 1.0 offering wider support than .NET Standard 1.6 (==.NET Core 1.0), these packages _should_ also work in .NET Core apps, per Microsoft doco.  

Many thanks

**Comment by reisenberger** [comment]
@ry8806 great to see your :+1: on the Polly .Net Standard 1.0 nuget package.  We're keen to hear any feedback before putting the packages out more widely on nuget - the package is playing well for you then? any problems?  And would love to hear details of what kind of project you have it plugged into.  Thanks!

**Comment by ry8806** [comment]
hi, yeh, the packages work great for me (am using the "unsigned" one).

I'm currently using Polly in a large .Net Core Web App (due to go-live at the end of the year) - as the back-end will be making json http calls to other endpoints - I'm using Polly to handle any failures and retry appropriately.

I'm also using Polly in a "private Universal App"  - more specifically on a Raspberry Pi2 running Windows 10 IoT at home. This app makes polling http calls (about 8 per minute) and Polly (again) helps with retrying after exceptions (again due to go-live end of the year - hopefully).............
Got a busy few months ahead of me :)

**Comment by adamhathcock** [comment]
Any chance for a beta package to get pushed to nuget?

**Comment by reisenberger** [comment]
>Any chance for a beta package to get pushed to nuget?

@joelhulen owns the nuget side for AppvNext, I'll see if @joelhulen is available for this?  Apologies for the delay.

**Comment by adamhathcock** [comment]
Any update on RTM support?

**Comment by reisenberger** [comment]
Hi @adamhathcock .  The .NET Standard packages posted in this thread and #132 should support .Net Standard / Core RTM versions as released by Microsoft end June/beginning July.  We've labelled our nuget packages 'beta' because the tooling support for running the xunit tests against the package was fairly problematic when I tried it 02 July (haven't had a chance to look again since) (if anyone wants to work on this, please say), so I don't want to merge this to Polly master yet. The content of the packages is however no different from the previous fully-tested versions: the only change necessary for .NETStandard support was to remove the serialization across AppDomains for Polly's custom exceptions.

If it's about getting the existing packages in this thread and #132 on to nuget labelled as beta packages, I'll ping @joelhulen again about that.  Apologies for the delay on this.

**Comment by adamhathcock** [comment]
I'm fine with the beta status.  It sounds good to me.  I was just hoping to get the packages on nuget :)

It's a pain because if I use the `import` statement on Polly then not only does the current package using Polly have to have it, then all downstream packages do too.

**Comment by BrianVallelunga** [comment]
I'd also appreciate a beta version on Nuget to ease testing, building. I'm porting an app to .NET Core 1.0 right now.

**Comment by SamuelEnglard** [comment]
Just wanted to give an update from my side: I've been switched from the project that is using Polly so I can't really comment on how it's going anymore but from what I know they're having no issues

**Comment by adamhathcock** [comment]
Pinging @joelhulen too :)

**Comment by joelhulen** [comment]
Sorry, everyone. I've been on travel and away from any computers for six
weeks. I should be able to create and publish the beta packages in the next
couple of days.

**Comment by devlead** [comment]
@reisenberger tested your fork and beta-netstandard10 with our Cake build scripts and haven't found any issues yet, perhaps you should have an MyGet feed for alpha releases? Allot easier to test when you can pull using nuget.

**Comment by moswald** [comment]
So until this makes it to nuget/myget, how does one reference a local version of this beta package? I can't seem to figure it out. 😢

**Comment by joelhulen** [comment]
The 4.5 beta release packages for both signed and unsigned have been posted to nuget.org. Be sure to check the box in your NuGet package manager that allows you to view pre-release versions.

**Comment by reisenberger** [comment]
Closing in favour of the [v5.0.1-release](https://github.com/App-vNext/Polly/issues/164), which also supports `.NET Standard 1.0`
