### ISSUE TITLE
Remove CancelAfter and Delay from internal TimeProvider

### ISSUE THREAD

**Issue by martincostello** [App-vNext/Polly#1348]
Attempting to rebase #1144 for .NET 8 and to consume `TimeProvider` from NuGet (and use the new `FakeTimeProvider` implementation) things get complicated because there are various tests that rely on `TimeProvider` having a virtual `CancelAfter()` and `Delay()` method that can be overridden in the tests.

https://github.com/App-vNext/Polly/blob/a9bf3e95a37ff9c98ca02c8ca395f91645ffe5d8/src/Polly.Core/ToBeRemoved/TimeProvider.cs#L53-L57

The real implementation instead has extension methods (which we can't mock) which are `TimeProvider.Delay()` and `TimeProvider.CreateCancellationTokenSource()`.

To make the switch over for .NET 8 simpler, we should sync the current internal implementation to be source compatible with the .NET 8 rather than rely on methods which won't exist. That way, the tests will not need to change much and the switch over should be a lot cleaner.

**Comment by martincostello** [comment]
Bonus of trying to use use `FakeTimeProvider` in our tests is that I found this bug: https://github.com/dotnet/extensions/issues/4115

**Comment by martintmk** [comment]
Thanks for reporting this. We should definitely sync the implementations to reduce the size of #1144 PR.

Our `TimeProvider` should include the `CreateTimer` method:
https://github.com/dotnet/runtime/blob/cfe30c057debbdd9ad21b36ae61062dbe72a1f83/src/libraries/Common/src/System/TimeProvider.cs#L156

We should also port the extensions:
https://github.com/dotnet/runtime/blob/cfe30c057debbdd9ad21b36ae61062dbe72a1f83/src/libraries/Microsoft.Bcl.TimeProvider/src/System/Threading/Tasks/TimeProviderTaskExtensions.cs#L13

All above made as internal and in a single file to simplify the sharing. Once .NET 8 is out we can nuke it and just use the standard package on lower frameworks. 

.NET 8 target will still have no dependencies.

**Comment by martincostello** [comment]
Yeah I was trying to do that but I got stuck once I tried to refactor the tests to account for not using those members added extra 😅

If next week you could take a look at that then I can rebase #1144 onto main and slim it down.
