### ISSUE TITLE
How do I hook my code to a retry?

### ISSUE THREAD

**Issue by orlandow** [App-vNext/Polly#135]
I have a method that takes a `RetryPolicy` and a piece of code and executes it using the policy.

I want to also run some other code to log every time a retry happens.

Since the `RetryPolicy` is already created, it is too late to call the method
```c#
public static RetryPolicy Retry(this PolicyBuilder policyBuilder, int retryCount, Action<Exception, int> onRetry);
```

Is there a way to achieve this?

**Comment by reisenberger** [comment]
Hi @orlandow 
>Is there a way to achieve this?

The current approach to policy configuration produces immutable policies with private properties, so hooking into/appending to a previously-configured `onRetry` is not available.  

There could be future possibilities via Polly exposing the `onRetry` as a delegate that one could `+=` extras onto. Although the signature of `onRetry` differs across retry policies, so it would probably have to be moved to an eventing model with some `OnRetryEventArgs` common to all types.  [NB The [forward roadmap](https://github.com/App-vNext/Polly/issues/90) is quite full at the moment so I don't have a date/guarantee for this.]

Do you have control over the code configuring the `RetryPolicy`s?  Obviously a number of options if you do.  I like the injection (passing-policy-from-elsewhere) model - we do the same in some of our in-house uses of Polly where I work - but we just wire the logging in where we configure.

**Comment by reisenberger** [comment]
@orlandow Here is another possibility which would achieve what you are after with the current Polly.  In the case where you have no control over the passed `RetryPolicy`, you can still inject some code around the delegate:

```csharp
public void YourInvokerMethod(RetryPolicy retryPolicy, Action action) // don't know your exact signature - making this up
{
  int tries = 0;
  retryPolicy.Execute(() => 
  {
    tries++;
    if (tries > 1) { /* log some retry info */ };
    action();
  }
}

**Comment by orlandow** [comment]
Thanks for the quick reply.

> Do you have control over the code configuring the `RetryPolicy`s?

No, we have a small "commands" library inspired by Hystrix's and wanted to add some "retrying", "circuit breaking" capabilities.

We learned about Polly, and your [roadmap](https://github.com/App-vNext/Polly/issues/90) aligns with what we want from our library, but we have a lot of legacy code depending on our commands at the moment and also have some features like persistence, logging, monitoring.

We decided to use Polly as a dependency and instead of wrapping it just inject a Policy as a parameter.

The thing is: we have centralized logging and monitoring and a lot of services using commands to talk between them, we rely on the standards and can't let it to the users to remember hooking that code. We even considered having some sort of `.MyRetry` extension, but it's easy to miss and use the real one :wink:.

I think we'll go with wrapping Polly for now.

Great library. Thanks.

**Comment by orlandow** [comment]
(Sorry, I missed your [other reply](https://github.com/App-vNext/Polly/issues/135#issuecomment-231217798), went offline and my `live.github.com` died)

Hmm... interesting... that could work for retries... but it'd be much more work for the circuit breaker part... `OnClose`, `OnOpen`, `OnHalfOpen`...
