### ISSUE TITLE
FEATURE: Timeout policy

### ISSUE THREAD

**Issue by reisenberger** [App-vNext/Polly#137]
# Proposal: Timeout policy
## Purpose

To provide a timeout for goverened actions.  Acts both as a user-experience enhancing and resilience strategy.
## Scope
- A **non-exception handling** **resilience** policy.
- Support all sync and async variants
- Support non-result-returning invocations (`Action`) and result-returning (`Func<TResult>`)
- Support `Execute(...)` and `ExecuteAndCapture(...)` variants.  
- Add cancellation support for sync variants.
## Configuration syntax

``` cssharp
TimeoutPolicy timeoutPolicy = Policy
  .Timeout(TimeSpan timeout);

TimeoutPolicy<TResult> timeoutPolicy = Policy<TResult>
  .Timeout(TimeSpan timeout);
```

(and similar async forms)
## Execution principles and syntax

The first intention of a timeout is to return back to the caller within a defined period, on the assumption the underlying operation appears not likely to succeed.

A second (but not secondary!) consideration is, in co-operation with the timed-out operation, to release resources used by the timed-out operation.  _Not_ actively releasing timed-out resources could lead to a build up of unreleased resources - especially in circumstances where throughput means new similar requests would immediately take the place of the timed-out ones. 
#### Adding synchronous delegate execution with cancellation

For similar reasons, Polly will not unilaterally terminate/abort threads of timed-out synchronous actions: doing so could leave resources unreleased.  Polly should only engage in co-operative cancellation.  This means we need to add new overloads of the sync `.Execute()` delegates taking a `CancellationToken`:

``` cssharp
// TResult sync form, synchronous with cancellation 
TResult result = timeoutPolicy
  .Execute(Func<CancellationToken, TResult> action, CancellationToken token);

// void sync form with cancellation
timeoutPolicy
  .Execute(Action<CancellationToken> action, CancellationToken token);
```

These (and similar) new overloads will have to be supported by _all_ policies, in order for cancellation on sync calls to be able to take effect across a `PolicyWrap`.
#### Asynchronous delegate execution with cancellation

Cancellation support is already in place for the async forms: 

```
// TResult async form 
TResult result = timeoutPolicy
  .ExecuteAsync(Func<Task<CancellationToken, TResult>> executionFunc, CancellationToken token);

// void async form
timeoutPolicy
  .ExecuteAsync(Func<CancellationToken, Task> executionFunc, CancellationToken token);
```
#### Decision: Enforce cancellation usage?

It would be an option to _enforce_ the use of overloads taking `CancellationToken`s when a timeout policy is in use.  Having the `TimeoutPolicy` throw an `InvalidOperationException` on overloads of `Execute/Async()` not taking a `CancellationToken`, while an aggressive approach, would make clear Polly's recommendation.   

There will be circumstances where users have no control over invoked code, where cancellation support in the invoked delegates is not possible.  If overloads taking a `CancellationToken` were enforced, such code could still be executed by ignoring the `CancellationToken` (but it would possibly make for ugly-reading code).

Views?
## Operation
- Use `CreateLinkedTokenSource()` to combine the caller's cancellation token with a timeout cancellation token such that the user delegate can be cancelled by either. 
- Invoke `executionFunc`.  
- If the configured timeout elapses before `executionFunc` returns:
  - cancellation token cancels to allow `executionFunc` to terminate quickly / release resources.
  - throw an `ExecutionTimeout : ExecutionRejected` exception.
- If `executionFunc` raises any kind of fault: rethrow / pass fault result to caller.  
# Comments?

Comments?  Alternative suggestions?  Extra considerations to bear in mind?  

Have scenarios to share where you'd use this? (could inform development)

**Comment by brunolauze** [comment]
I think we should provide a more dynamic way to provide timeout than just TimeSpan, just a Func<TimeSpan> would be good enough. The idea here is to enable Hystrix like pattern where Timeout is managed across micro-services calls in a budget manner. Of course, we don't want Polly to implement any of this logic, but to only provide a way to extend the timeout value. Also, adding configuration based policy would also required to think how to provide dynamic timeout value out of it.

![Hystrix Model](https://blog.micro.mu/assets/images/good-timeouts.png)



### Configuration syntax

`TimeoutPolicy timeoutPolicy = Policy.Timeout(TimeSpan timeout)`
`TimeoutPolicy<TResult> timeoutPolicy = Policy<TResult>.Timeout(TimeSpan timeout);`
`TimeoutPolicy timeoutPolicy = Policy.Timeout(Func<TimeSpan> timeout);`
`TimeoutPolicy<TResult> timeoutPolicy = Policy<TResult>.Timeout(Func<TimeSpan> timeout);`


(and similar async forms)

**Comment by reisenberger** [comment]
@brunolauze @mfjerome Thank you for offering (in off-github discussion) to work on this feature: I've just added you as assignees :wink: . Please (and anyone else interested) come back with any further thoughts/questions...

@brunolauze It may be easier to work on the async variant first, as the cancellation support is already in place for async.

**Comment by reisenberger** [comment]
@brunolauze Re:

>a more dynamic way to provide timeout than just TimeSpan, just a Func would be good enough

This sounds like a very interesting idea, I'll have a deeper think about it!

**Comment by brunolauze** [comment]
@reisenberger  I would recommand not enforcing CancellationToken having overloads to keep everything as it is. We would wrap any non cooperative execution with cancel checks.

(cancellationToken) => { cancellationToken.ThrowIfCancelled(); action(); cancellationToken.ThrowIfCancelled(); }

While recommanding using full cooperation cancellation pattern while using Timeout or Wrap Policies.

The thinking behind this conclusion is that full cooperative cancellation might not be always possible, as upstream calls might not support it even if the middleware action handles it. Knowing that some calls might be spinning cpu cycles for nothing while not implementing it fully. That would be a tradeoff against legacy code.

A suggestion also ready to deprecate it and phase it out later on if revisited. 

Thanks for the comments

**Comment by reisenberger** [comment]
Hey @brunolauze 
I am happy (I think this is the route you are suggesting) if our conclusion for now is:

[1] We do not at this stage _enforce_ the use of CancellationToken overloads on sync calls.  (IE We do not throw `InvalidOperationException` or similar on `timeoutPolicy.Execute( /* a sync action not taking a Cancellationtoken */ )`

[2] But we do _support_ (and recommend!) the use of CancellationToken overloads on sync calls.  (**NB** This will require adding overloads taking `CancellationToken` to the sync `.Execute/AndCapture/Async(...)` overload collection, and amending the sync engine of every existing (retry; circuitbreaker; others upcoming) to support cancellation.  Either you or I can do the work of weaving CancellationToken into the rest of sync Polly - discuss later, unless you already close to it? - it's fairly routine and there is a pattern to follow from use of CancellationToken in async overloads and policy engines, but it does touch a lot of code.)

[3] We document very clearly the risks of wrapping a sync action not supporting co-operative cancellation in a timeout.

---

(Discussion: I wanted to 'put out there' in the proposal the idea of actually throwing on invoking a sync action without cancellationtoken through a timeout policy, to gauge reaction, but per all our comments so far, it does feel quite aggressive, and there will always be legacy code which can't support it, so people would only end up with an (ugly) fake cancellation parameter anyway.  So current conclusion: permit, but _document risks clearly_!)

**Comment by brunolauze** [comment]
I added 3 commits as a tentative for Timeout Policy [timeout-policy](https://github.com/brunolauze/Polly/commits/timeout-policy) to ensure having impl, specs and cooperative cancellation separated. Thanks for the comments.

**Comment by reisenberger** [comment]
@brunolauze Many thanks for all this!  I will hope to review and provide comments in the next few days!

**Comment by reisenberger** [comment]
@brunolauze, Thank you for getting stuck into these policies.  Some comments for taking  `Timeout` forward:
 
The [same comments as for Throttle](https://github.com/App-vNext/Polly/issues/138#issuecomment-235113051) apply about being able to simplify:
 
+ `Timeout` is non-exception-handling, so exception and result predicates can be removed, and syntax be static methods on `Policy`
+ State is per-policy, so the `policyStateFactory` and related `TimeoutState` classes can be removed
 
`CreateLinkedTokenSource()`: The idea was to link the user's passed-in `cancellationToken` with a `CancellationToken` set to auto-cancel after the timeout period. That combined token can then be passed downstream meaning all downstream code (wrapped policies or the user's delegate) gets the benefit of co-operative cancellation from either the user's cancellation token or timeout.  Adapting from a concise receipe from [Stephen Cleary’s Concurrency Cookbook] (http://shop.oreilly.com/product/0636920030171.do) (great book btw!): 

```csharp
var timeoutToken = new CancellationTokenSource(timeout).Token;
using (var combinedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, timeoutToken))
{
    return await action(combinedCts.Token).ConfigureAwait // etc
    // needs some try-catch (OperationCanceledException) around the above line and throw the TimeoutException if the OperationCanceledException is due to timeoutToken
}
``` 

Once the predicates go, the `return default(TResult)` should disappear from the ends of the implementations?  The only exit paths should be return the result of the downstream delegate, throw the timeout exception, or let other exceptions propagate back to the caller.
 
_Async implementation:_ we need to use `async/await` throughout (rather than eg `BeginInvoke`), so that we can honour `continueOnCapturedcontext` on the `await`s.

_Sync implementation:_  Did you have thoughts on `Task.Run()`/`StartNew()` versus `BeginInvoke()`?  I prefer `Task.Run()` for conciseness, and [some benchmarking](http://stackoverflow.com/questions/22686467/use-task-run-instead-of-delegate-begininvoke/24572745#24572745) suggests it is faster (it would be nice to do our own benchmarking too - perhaps something for later).  
 
@brunolauze What do you think?  Are you happy to take forward per above?
