### ISSUE TITLE
Improve synchronous support of resilience strategies 

### ISSUE THREAD

**Issue by martintmk** [App-vNext/Polly#1417]
Investigate how we can improve the synchronous executions support for resilience strategies and avoid sync-over-async pattern. We should consider these optimizations mainly for hot-path executions.  

For example,  hedging strategy that does sync-over-async for pending tasks. Although in hedging the asynchronous execute methods should be preferred, we can also optimize for synchronous scenarios relatively easily. 

The key is to use `Task.WaitAny` APIs instead of `Task.WhenAny`. The former allows us to avoid the sync-over-async.
This can be done post V8 release as an optimalization as synchronous execution will work even now, although with degraded performance.

**Comment by martincostello** [comment]
@martintmk Anything left to do here?

**Comment by martintmk** [comment]
Let's close it and reopen if someone complains. People that use synchronous execution should not expect their code will be as scalable as for async executions.
