### ISSUE TITLE
Confusing log entries when builder instance name not set

### ISSUE THREAD

**Issue by martincostello** [App-vNext/Polly#1435]
Using Polly 8.0.0-alpha.7 where a builder has no name set, slightly confusing log messages are emitted. Messages are emitted with empty pairs of square brackets (e.g. `Retry[]`) which look like arrays, but aren't, and it isn't clear what they signify.

For example.

```
[2023-07-26 11:14:11Z] info: Polly[3]
      Execution attempt. Source: 'Test/Retry[]/Test/Retry', Operation Key: 'Test.ExecuteAsync', Result: '42', Handled: 'False', Attempt: '1', Execution Time: '0.0991'
[2023-07-26 11:14:11Z] warn: Polly[2]
      Resilience strategy executed. Source: 'Test/Retry[]', Operation Key: 'Test.ExecuteAsync', Result Type: 'Int32', Result: '42', Execution Health: 'Unhealthy', Execution Time: 115.0517ms
[2023-07-26 11:14:11Z] warn: Polly[2]
      Resilience strategy executed. Source: 'Test/CircuitBreaker/ExecuteAsync[]', Operation Key: 'Test.ExecuteAsync', Result Type: 'Int32', Result: '42', Execution Health: 'Unhealthy', Execution Time: 117.2939ms
[2023-07-26 11:14:11Z] warn: Polly[2]
      Resilience strategy executed. Source: 'Test/Timeout[]', Operation Key: 'Test.ExecuteAsync', Result Type: 'Int32', Result: '42', Execution Health: 'Unhealthy', Execution Time: 119.5119ms
[2023-07-26 11:14:11Z] warn: Polly[2]
      Resilience strategy executed. Source: 'Test/RateLimit[]', Operation Key: 'Test.ExecuteAsync', Result Type: 'Int32', Result: '42', Execution Health: 'Unhealthy', Execution Time: 119.5671ms
[2023-07-26 11:14:11Z] warn: Polly[2]
      Resilience strategy executed. Source: 'Test/ExecuteAsync[]', Operation Key: 'Test.ExecuteAsync', Result Type: 'Int32', Result: '42', Execution Health: 'Unhealthy', Execution Time: 119.5794ms
```

The log messages are being emitted from here:

https://github.com/App-vNext/Polly/blob/b38e6c43bd4647a6e34b4e636f62c674139a22f5/src/Polly.Extensions/Telemetry/Log.cs#L11-L28

When elements of the log message are null, should be maybe replace them with a constant like `(unset)` or similar? Or should we change the format of the source to emit empty parts and be constructed in code behind an `IsEnabled(LogLevel)` check then just passed to the template as `'{Source}'`?

**Comment by martintmk** [comment]
> When elements of the log message are null, should be maybe replace them with a constant like (unset) or similar?
Possibly or just use the common `(null)` marker.

`(null)[(null)]/MyStrategy` or maybe use `/(null)/(null)/MyStrategy` format. Wdyt?

> Or should we change the format of the source to emit empty parts and be constructed in code behind an IsEnabled(LogLevel) check then just passed to the template as '{Source}'?

When structured logging is used it's nice to have to filter only based on builder, instance or strategy. Merging everything into source limits that scenario.
