### ISSUE TITLE
document thread safety

### ISSUE THREAD

**Issue by kbilsted** [App-vNext/Polly#146]
I am about to be sharing a policy across several threads. The readme does not describe anything in relation to thread safety. Looking at the code, it seems to be thread safe. But I think it would be great if the readme clearly could state that the code is supposed to be thread safe - or whether that is a job for the user of the library.

**Comment by reisenberger** [comment]
Hi @kbilsted  The existing policies (retry and circuit-breaker) are fully thread-safe, and the intention is that the [forthcoming wider resilience policies](https://github.com/App-vNext/Polly/wiki/Polly-Roadmap#a-wider-resilience-framework) will be thread-safe too.

Thread-safety is documented [here in the wiki](https://github.com/App-vNext/Polly/wiki/Some-policy-patterns#reusing-policies-and-thread-safety), but a good idea to pull that out more clearly into the readme - thanks for pointing this out.

**Comment by reisenberger** [comment]
There's a little more depth on thread-safety also in these links for each of [retry](https://github.com/App-vNext/Polly/wiki/Retry#thread-safety) and [circuit-breaker](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker#thread-safety-and-locking).

**Comment by kbilsted** [comment]
Those links are really nice. Perhaps a short section on threadsafety should go into the readme along with those links.
