### ISSUE TITLE
Replace Moq

### ISSUE THREAD

**Issue by martincostello** [App-vNext/Polly#1470]
Given recent developments with Moq as of version 4.20.0, we should remove it and replace with another library.

[NSubstitue](https://nsubstitute.github.io/) seems like a good _substitue_.

I'm going to work on this today unless someone has any strong opinions about an alternative library to use in its place.

**Comment by martintmk** [comment]
Are there any plans to fork the Moq? 
Maybe in the meantime, we can freeze the versions and wait for some "official forked package".

I have not used NSubstitute personally, so I can't comment on that. It seems some folks find it cleaner compared to Moq. 

If the switch is straightforward, we can get away with that.

**Comment by adamnova** [comment]
There is already an issue for creating a migration tool: https://github.com/nsubstitute/NSubstitute/issues/720

I would probably wait and see in this case, how it develops. The latest version of Moq no longer has that dependency, so I would say it's not immediate concern.

**Comment by martincostello** [comment]
Thanks for the link, I'll bear that in mind for the future. I have however just finished locally converting the code over 😅

**Comment by adamnova** [comment]
I am looking at the PR and to be honest, I like the syntax more than Moq. Never used NSubstitute before.
