### ISSUE TITLE
Github readme getting started

### ISSUE THREAD

**Issue by ragavendra** [App-vNext/Polly#1504]
**Summary**: 
In the README.md, the Getting started says install the package like `dotnet add package Polly` but this does not include methods like `PolicyRegistry`

When I tried `dotnet add package Microsoft.Extensions.Http.Polly`, I have and other methods.

**Expected behavior**: 
Should the line be like `dotnet add package Microsoft.Extensions.Http.Polly`

**Actual behaviour**:
Line is  `dotnet add package Polly`

**Steps / Code to reproduce the problem**: 
1. Do  `dotnet add package Polly`
2. Try typing `using Polly.Registry;`, you should get compile error.

**Comment by martincostello** [comment]
The PolicyRegistry class is definitely in the Polly assembly: https://github.com/App-vNext/Polly/blob/main/src/Polly/Registry/PolicyRegistry.cs

**Comment by ragavendra** [comment]
I was switching from one package to the other, might be the intellisense took time to update. However I had to add `Microsoft.Extensions.Http.Polly` to my ASP .NET application as `Polly` alone did not have `AddPolicyRegistry` like in the below code to load it as a service.
```
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddPolicyRegistry(new PolicyRegistry()
{
});
```
It is nice to have `dotnet add package Microsoft.Extensions.Http.Polly` in the readme as well to make it more complete.

**Comment by martincostello** [comment]
Those extensions aren't part of the core library and are optional, so we wouldn't list it as part of the basic instructions for getting started.

The additional packages are covered in the [section about HttpClientFactory](https://github.com/App-vNext/Polly#using-polly-with-httpclient-factory-from-aspnet-core-21).
