### ISSUE TITLE
Refine the build targets for V8

### ISSUE THREAD

**Issue by martintmk** [App-vNext/Polly#1534]
Looking on our build targets in #1360 it looks like:

``` 
<TargetFrameworks>net8.0;net7.0;net6.0;netstandard2.0;net472;net462</TargetFrameworks>
```

Can we trim these down? 

For example:

- Drop `net472` (not necessary since we have `net462`)
- Drop `net6.0` and `net7.0` in favor of `netcoreapp3.1`?

**Comment by martincostello** [comment]
Maybe we just drop `net7.0` if we're not actively using anything from it?
