### ISSUE TITLE
CircuitBreaker Execute without exception

### ISSUE THREAD

**Issue by vknapp** [App-vNext/Polly#154]
At the moment `CircuitBreakerPolicy `will throw an exception when you run `Execute `and the circuit is open.

This is very time consuming and too expensive for us - maybe you could offer an `Execute `overload which simply returns false, maybe as some `PolicyResult`?

**Comment by reisenberger** [comment]
Hi @vknapp.  There is a relatively easy way to handle this in existing Polly.  A `CircuitBreakerPolicy` publicly exposes its state, so you could use a construct like below to avoid exceptions while the circuit is open:

```csharp
if (breaker.State != breakerState.Open && breaker.State != breakerState.Isolated)
{
  breaker.Execute(...)
}
```

I have documented this (in slightly more detail) on the [CircuitBreaker wiki page](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker).

(I prefer this to offering a bespoke `Execute(...)` overload only applying to the circuit-breaker.  To date, we have managed to keep Execute overloads common to all policies, and this is an important foundation for the forthcoming features on the [Roadmap](https://github.com/App-vNext/Polly/wiki/Polly-Roadmap), the [PolicyWrap](https://github.com/App-vNext/Polly/issues/140) in particular.  Very happy for any feedback on those roadmap features, btw!)

Thanks for your interest in Polly!

**Comment by vknapp** [comment]
Thank you for your answer. I was aware of that, just asked for your opinion because you advised against it 

> in a highly concurrent environment.

 
However in my case I can handle this. Thanks for a very usefull tool!

**Comment by reisenberger** [comment]
No problem at all @vknapp !  A really good question (how to reduce the exception load on open circuits), so it's made for a useful clarification of the doco (and we've kept the gotchas of that idiom clear in the doco too, so users can use the idiom with open eyes, as it were).  Thanks again for bringing this up!
