### ISSUE TITLE
PollyTalk.org return Internal Server Error

### ISSUE THREAD

**Issue by vdekercd** [App-vNext/Polly#1551]
**Summary**: 

PollyTalk.org return Internal Server Error

**Expected behavior**: 

The PollyTalk site works

**Actual behaviour**:

PollyTalk.org return Internal Server Error

**Steps / Code to reproduce the problem**: 

[Go to PollyTalk site](https://www.pollytalk.org)

**Comment by martincostello** [comment]
Duplicate of #1256.

**Comment by vdekercd** [comment]
My bad! Sorry.
