### ISSUE TITLE
Unit testing retry policies with timeout intervals

### ISSUE THREAD

**Issue by jiimaho** [App-vNext/Polly#156]
Currently I don't see a way to unit test a retry policy if you use the time-based retry policy.

Let's say you use the following approach, and this code below is part of your method that does a few more things than executing the policy itself.

_Some code here..._
```
Policy
  .Handle<DivideByZeroException>()
  .WaitAndRetry(new[]
  {
    TimeSpan.FromSeconds(30),
    TimeSpan.FromSeconds(60),
    TimeSpan.FromSeconds(120)
  }, (exception, timeSpan) => {
    // do something    
  }); 
```
_Some code here...._

How would I test what happens _after_ we have re-tried 3 times? I don't want to wait more than one minute in my tests. Thanks for your suggestions.

**Comment by reisenberger** [comment]
Hi @jiimaho  A good strategy for this could be Dependency Injection: 

+ Refactor to inject the Policy into the method/class using it (whether by constructor/property/method-parameter injection - doesn't matter).  
+ In your production code, inject the real policy you want to use.  
+ In your test code, inject an equivalent policy that doesn't do any waiting, eg `Retry(3) // etc`

**Comment by jiimaho** [comment]
Hi @reisenberger and thanks for your quick reply. I actually just found what I was looking for in Polly itself!

`SystemClock.Sleep` allows me to mock the internal timer for Polly, which causes the sleeps to really not sleep.

**Comment by reisenberger** [comment]
Hi @jiimaho Yes, that's absolutely right.  That's exactly the way we handle it within Polly's own specs, to allow tests to run instantly where time-delays are involved: specs either substitute `SystemClock.UtcNow` or `SystemClock.Sleep` , depending on whether the policy-under-test is waiting passively for time to pass elsewhere (as in `CircuitBreaker` moving to half-open) or actively controlling the delay (as in `WaitAndRetry`).  

You can see an example test [here](https://github.com/App-vNext/Polly/blob/a0bc69fed1f078c469159ed36ba8426d368a7cc5/src/Polly.SharedSpecs/WaitAndRetrySpecs.cs#L325).

(It's slightly questionable whether `SystemClock` should really be public ... that inherited from before AppvNext stewardship of Polly ... `SystemClock` is really an internal concern ... but it does have this benefit for user testing.)

Thanks for your interest in Polly!

**Comment by jiimaho** [comment]
@reisenberger I think it's good to let consumers of the Polly API be able to provide a time-provider. If this should be done through `SystemClock `or not i'm not sure, however in our scenario it's perfect for testability.

**Comment by rog1039** [comment]
@reisenberger I agree with @jiimaho in that there should be a supported way to manipulate the passage of time. We'll try using SystemClock in our unit tests. 

A good example of a library which allows the user to modify the flow of time is the ReactiveExtensions project. They provide schedulers that can be used control the flow of time which makes testing various scenarios relating to time passage very easy, repeatable, and makes unit tests very quick (Can simulate minute/hours/days/etc of time passage instantly). 

See here 
[http://www.introtorx.com/Content/v1.0.10621.0/16_TestingRx.html#TestScheduler](TestScheduler) for more information.

Thanks!

**Comment by reisenberger** [comment]
Thanks for that @rog1039 . The ability to manipulate Polly’s abstracted, ambient-context SystemClock is intended to provide exactly this: you can manipulate time so that tests which would otherwise incur a time delay, don’t. See the many tests within the existing codebase which do this. 

Let us know how you get on with that - or if you can envisage ways it could be improved (I can envisage some - as ever, with trade-offs)
