### ISSUE TITLE
Fix Binskim warning

### ISSUE THREAD

**Issue by sbanni** [App-vNext/Polly#1617]
**Issue**

When I run Binskim I get this warning:

##[warning]1. BinSkim Warning BA2004 - File: Symbols/Polly.dll.  
  Tool: BinSkim: Rule: BA2004 (EnableSecureSourceCodeHashing). https://github.com/microsoft/binskim/blob/main/docs/BinSkimRules.md#rule-BA2004EnableSecureSourceCodeHashing
  'Polly.dll' is a managed binary compiled with an insecure (SHA-1) source code hashing algorithm. SHA-1 is subject to collision attacks and its use can compromise supply chain integrity. Pass '-checksumalgorithm:SHA256' on the csc.exe command-line or populate the project <ChecksumAlgorithm> property with 'SHA256' to enable secure source code hashing.

**Describe your proposed or preferred solution**:
Add <ChecksumAlgorithm>SHA256</ChecksumAlgorithm> to the project file

**Any additional info?**
https://github.com/microsoft/binskim/blob/main/docs/BinSkimRules.md#rule-BA2004EnableSecureSourceCodeHashing

**Comment by martincostello** [comment]
What version of Polly did you scan? Was it the latest stable version?

Do you know what the easy fix for this is via an MSBuild property and would you like to submit a PR to do so?

The docs suggest passing a flag directly to the C# compiler, but our build process doesn't directly invoke the compiler as it goes through the .NET SDK to do so.

**Comment by sbanni** [comment]
Adding `<ChecksumAlgorithm>SHA256</ChecksumAlgorithm>` should be all that is needed.

I can submit a PR if I get some free time, unless someone else can get to it first.

**Comment by martincostello** [comment]
Feel free - it's a one-liner and I don't have access to a computer for a day or so yet.

**Comment by martintmk** [comment]
Shall this change be included in v8 release?

**Comment by martincostello** [comment]
I would have thought so, yes.
