### ISSUE TITLE
Polly's Circuit Breaker and Azure client SDKs

### ISSUE THREAD

**Issue by francischeung** [App-vNext/Polly#162]
Most of the Azure client SDKs perform their own retry logic. If I wanted to use Polly's circuit breaker with an Azure client, would you suggest that the Polly circuit breaker just detect exceptions that the Azure client raises?

```
            var breaker = Policy
              .Handle<DocumentClientException>()
              .CircuitBreakerAsync(2, TimeSpan.FromMinutes(1));

            await breaker.ExecuteAsync(async () =>
            {
                await documentClient.CreateDocumentAsync(documentCollectionUri, document);
            });
```

**Comment by reisenberger** [comment]
Hi @francischeung Yes, that's a completely valid way to proceed, to combine Polly's circuit-breaking with Azure's built-in retry logic, and your code sample looks perfect for this.

---

When Polly v5.0 is launched in the next four weeks or so, there may be other factors to consider regarding using Azure's retries versus Polly's.  Polly v5.0 is adding a whole host of [wider resilience features](https://github.com/App-vNext/Polly/wiki/Polly-Roadmap#a-wider-resilience-framework), and the ability to combine all those resilience strategies into a [PolicyWrap](https://github.com/App-vNext/Polly/issues/140).   For certain combinations of Polly resilience strategies, the most logical place for retry is going to be somewhere in the middle of the policy wrap ... something like:

```
PolicyWrap wrap = Policy.Wrap(fallback, cache, retry, circuitBreaker, timeout, bulkhead);
wrap.ExecuteAsync(async () => ... );
```

Placing a retry in the midst of Polly's (forthcoming) wider resilience strategies like this, could be done with Polly's Retry policies but not Azure's.

We are aiming to have v5.0 as an alpha nuget release in week beginning 24 October.

Hope this helps.

**Comment by reisenberger** [comment]
Closing historic issue.
