### ISSUE TITLE
Retry and Wait is occurring for exceptions not mapped in the Policy declaration

### ISSUE THREAD

**Issue by BrendonPasquimTR** [App-vNext/Polly#1636]
**Summary**: 
When using Polly to retry and wait SFTP operations (using SSH.NET library), retry is triggered for [SshAuthenticationException](https://github.com/sshnet/SSH.NET/blob/fdd113022bec2a4fc322841280f21d1881783402/src/Renci.SshNet/Common/SshAuthenticationException.cs), even thought it was not configured in the Policy.

PS: [SshAuthenticationException](https://github.com/sshnet/SSH.NET/blob/fdd113022bec2a4fc322841280f21d1881783402/src/Renci.SshNet/Common/SshAuthenticationException.cs) is derived from SshException, so seems like inheritance is triggering retries.

**Expected behavior**: 
SshAuthenticationException should not trigger a wait period and retry. It should throw right away.

**Actual behaviour**:
Retry and wait occurs when SshAuthenticationException is thrown.

**Steps / Code to reproduce the problem**: 

```
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Polly;
using Renci.SshNet.Common;
using System;

namespace SFTP.Tester
{
    [TestClass]
    public class RetryTest
    {
        [TestMethod]
        public void Retry()
        {
            int count = 0;

            var policy = Policy
                .Handle<SshConnectionException>()
                .Or<SshOperationTimeoutException>()
                .Or<SshException>()
                .WaitAndRetry(
                    retryCount: 2,
                    sleepDurationProvider: (_) => TimeSpan.FromSeconds(5),
                    onRetry: (ex, _) => count++);

            try
            {
                policy.Execute(() => throw new SshAuthenticationException());
            }
            catch (Exception)
            {
                //It was expected 0 retries, since SshAuthenticationException is
                //not declared in the Policy exception list.
                Assert.AreEqual(0, count);
            }
        }
    }
}

```

Am I missing something about the Retry and Wait policy? I didn't find much about this scenario in the documention.

**Comment by martincostello** [comment]
Polly by default handles exceptions that are of _or are derived from_ the type specified (i.e. if `exception is MyExceptionType` evaluates to `true`).

For your use case you will need to use a delegate to configure the logic of what to handle:

```csharp
var policy = Policy
    .Handle<SshConnectionException>()
    .Or<SshOperationTimeoutException>()
    .Or<SshException>(exception => exception is not SshAuthenticationException) // Or whatever meets your needs
```

**Comment by BrendonPasquimTR** [comment]
Thank you @martincostello for your prompt response. I tested your suggestion, and it solved the problem.
