### ISSUE TITLE
GitHub link is missing from pollydocs navbar

### ISSUE THREAD

**Issue by martincostello** [App-vNext/Polly#1656]
I noticed that pollydocs.org doesn't have a link to the Polly repo in its navbar.

I did a bit of digging, but I couldn't work out why or how to turn it on - seems it should _Just Work™️_

We should try and work out why and fix it to make it easier to get here from the documentation.

## Polly's navbar

![image](https://github.com/App-vNext/Polly/assets/1439341/119a7273-1295-4f8f-8dda-f7cbbd86703c)

## docfx's navbar

![image](https://github.com/App-vNext/Polly/assets/1439341/5e4c463a-972f-4b35-93f3-9455f4e8e56c)

**Comment by martincostello** [comment]
@adamnova Do you know why this might be?

**Comment by adamnova** [comment]
I don't think that is actually a feature of DocFx. It seems to be added through custom template: https://dotnet.github.io/docfx/docs/template.html?tabs=modern#template-variables

In the source code they render the links like so 

```
 function renderCore() {
    const icons = html`
      <form class="icons">
        ${window.docfx.iconLinks?.map(i => html`<a href="${i.href}" title="${i.title}" class="btn border-0"><i class="bi bi-${i.icon}"></i></a>`)}
        ${themePicker(renderCore)}
      </form>`

    render(html`${menu} ${icons}`, navbar)
  }
```

I managed to get it running so if you want I can create a PR for that

**Comment by martincostello** [comment]
Thanks! I assumed it was a _Just Works_ thing that came by default.

It being custom would explain why I couldn't find it in the docs 😄

**Comment by adamnova** [comment]
I actually thought so as well and had to dig through the source code to see that it's just kind of a hidden feature. No idea why it's not supported through metadata.

**Comment by martincostello** [comment]
Confirmed working (with a cache bust in Chrome) - thanks again for fixing!
