### ISSUE TITLE
[up-for-grabs] PolicyResult should expose a ExceptionDispatchInfo on platforms that support it

### ISSUE THREAD

**Issue by ronnieoverby** [App-vNext/Polly#171]
It would be awesome if the captured policy result included ExceptionDispatchInfo that would allow throwing the final exception while preserving the original state of the exception.

https://msdn.microsoft.com/en-us/library/system.runtime.exceptionservices.exceptiondispatchinfo(v=vs.110).aspx

Without this, the developer is forced to wrap `FinalException` property in a new exception to preserve the original stack trace before "rethrowing".

**Comment by reisenberger** [comment]
Hey @ronnieoverby 
Something like this would certainly be possible.

A question though: Would simply using the existing `.Execute/Async()` overloads meet your need?  Using `.Execute/Async()`, any 'FinalException' is propagated by the policy with its original stack trace, rather than captured into a `PolicyResult`.  (Marginally more efficient also - one less capture-rethrow.)

(You might have other reasons for wanting to stick with `ExecuteAndCapture()` - please feel free to come back to me on this, if the suggestion to switch to `.Execute/Async()` doesn't solve it for you.)

**Comment by ronnieoverby** [comment]
I looked at doing that first. It just makes my code messier than I like (mainly because I have to declare result variable outside of `try{ }`.

More on what I propose:

New property on `PolicyResult` called `FinalExceptionDispatchInfo`.

Existing property getter `PolicyResult.FinalException` is reimplemented as `return FinalExceptionDispatchInfo?.SourceException;`

New method `PolicyResult.ThrowUnhandledException` is implemented as:
``` c#
if (configAttempt.ExceptionType == ExceptionType.Unhandled)
    configAttempt.FinalExceptionDispatchInfo.Throw();
```

I haven't looked at any Polly code yet, but I imagine this is a pretty simple change (except maybe for platforms that don't support ExceptionDispatchInfo, if any don't. I'd even be willing to take a stab at it, if you agree with what I'm proposing.

**Comment by reisenberger** [comment]
@ronnieoverby This makes sense.  The Polly team is deeply geared to the launch of v5.0-alpha for Dev Intersections next week, so I'll come back to you on this once that's out the way.  Thanks.

**Comment by reisenberger** [comment]
@ronnieoverby Thanks for your patience with this.  The Polly v5.0 targets are decided now, so we would be happy to take a PR on this, if you are interested in providing one.  Any PR should be based on a fork of the [v5.0-alpha branch](https://github.com/App-vNext/Polly/tree/v5.0-alpha), and might then make it into v5.0.3 RTM.  

Re:

>New property on `PolicyResult` called `FinalExceptionDispatchInfo`

Sounds good.

>New method `PolicyResult.ThrowUnhandledException`

Sounds good.  How about we name it `PolicyResult.RethrowUnhandledException` ?

>Existing property getter PolicyResult.FinalException is reimplemented as 
>return FinalExceptionDispatchInfo?.SourceException;

Is there a benefit to doing this, you are aware of, over the existing implementation?  [MSDN documentation](https://msdn.microsoft.com/en-us/library/system.runtime.exceptionservices.exceptiondispatchinfo.sourceexception(v=vs.110).aspx) states "It is not intended to be used by application code."

Many thanks!

**Comment by reisenberger** [comment]
Marking this 'up-for-grabs'.

Polly v5.0.3 RTM is now released, so PR directly against master (no longer v5.0-alpha)

**Comment by reisenberger** [comment]
I believe it is not necessary to add this feature within Polly; it is provided by the BCL as [`ExceptionDispatchInfo.Capture(Exception)`](https://msdn.microsoft.com/en-us/library/system.runtime.exceptionservices.exceptiondispatchinfo.capture.aspx)
