### ISSUE TITLE
[Bug]: ExceptionsAllowedBeforeBreaking is not working.

### ISSUE THREAD

**Issue by ks1990cn** [App-vNext/Polly#1716]
### Describe the bug

Hi,

I've downstream API which is throwing error and another API which is calling this endpoint through HTTPClient. I am setting ExceptionsAllowedBeforeBreaking = 2 and after two consecutive errors circuit breaker should stop calling downstream endpoint. But we keep on getting same exception thrown by downstream endpoint. 

### Expected behavior

Circuit breaker should work for `ExceptionsAllowedBeforeBreaking `property when it exceeds more than defined errors.

### Actual behavior

Getting same error from downstream API, looks like circuit breaker doesn't work here.

Attaching GIF for reference.

Here Downstream API have endpoint which throws error and Debugging.API is consuming downstream API through HttpClient and Polly.

![Circuitbreaker Polly](https://github.com/App-vNext/Polly/assets/29522704/9d7b21fc-e674-49ab-b7d5-bb9ead69c1b1)

### Steps to reproduce

1. Bug can be replicated by https://ocelot.readthedocs.io/en/latest/features/qualityofservice.html

2. Just create 2 API, call endpoint of one API through another using HTTPClient and setup `ExceptionsAllowedBeforeBreaking = 2`. Make sure to through exception from downstream API and see circuitbreaker not working.

### Polly version

8.0.0

### .NET Version

7.0

**Comment by martincostello** [comment]
Please provide a minimal runnable repro for your issue as code, ideally in a GitHub repository we can easily clone and run.

**Comment by ks1990cn** [comment]
> Please provide a minimal runnable repro for your issue as code, ideally in a GitHub repository we can easily clone and run.

To run locally:
1.) Clone https://github.com/ks1990cn/Ocelot/tree/ts/issue_1550
2.) Multiple setup startup projects - Debugging.API + Debugging.Downstream.
3.) From postman hit - `http://localhost:{portNumberOfDebugging.API}/fu`

Here` Debugging.API/fu` will hit `/fileUpload` of Debugging.Downstream endpoint because Debugging.API is using Ocelot with Polly.

**Comment by ks1990cn** [comment]
Closing this, it was configuration issue.
