### ISSUE TITLE
[Feature request]: Add more telemetry into the Rate limiter strategy

### ISSUE THREAD

**Issue by radek-vlacil** [App-vNext/Polly#1723]
### Is your feature request related to a specific problem? Or an existing feature?

It would be nice to have a metric which would show how is the rate limiter impacting our request flow. Could you please add metrics which would at least show current queue size. Other metrics like current active requests or queued request count would also help.

### Describe the solution you'd like

Just use standard approach you use for other metrics.

**Comment by martintmk** [comment]
In Polly we are only reporting events after rejection by rate-limiter happens. What you want is to actively monitor the rate limiter used by the Polly. This can be archived by the following pseudo-code:

``` csharp 
var meter = new Meter("my.limiter");
 
using var registry = new ResiliencePipelineRegistry<string>();
 
registry.GetOrAddPipeline("rate-limiter-pipeline", (builder, context) =>
{
    var cancellation = new CancellationTokenSource();
    var limiter = new ConcurrencyLimiter(new ConcurrencyLimiterOptions
    {
        PermitLimit = 100,
        QueueLimit = 100
    });
 
    builder.AddRateLimiter(new RateLimiterStrategyOptions
    {
        RateLimiter = args => limiter.AcquireAsync(1, args.Context.CancellationToken)
    });
 
    _ = Task.Run(async () => {
        while (!cancellation.IsCancellationRequested)
        {
            var statisitcs = limiter.GetStatistics();
 
            // report metrics here
 
            await Task.Delay(1000, cancellation.Token);
        }
    });
 
    context.OnPipelineDisposed(() =>
    {
        cancellation.Cancel();
        limiter.Dispose();
    });
});
```

Example above:

- Registers `rate-limiter-pipeline` with a rate limiter strategy.
- Creates a rate limiter strategy manually and registers active monitoring of it by pushing metrics to custom `my-limiter`

Ideally, `System.RateLimiting` APIs would produce native telemetry, however, that is a feature request to https://github.com/dotnet/runtime.

I don't think we need to do add anything new to Polly at this stage. If there are similar requests to this we might update our docs.
