### ISSUE TITLE
[Clarification]: Hedging contexts 

### ISSUE THREAD

**Issue by peter-csala** [App-vNext/Polly#1727]
### Is your feature request related to a specific problem? Or an existing feature?

While I was playing with hedging strategy I realized that we have `PrimaryContext` and `ActionContext` on [`OnHedgingArguments<TResult>` struct](https://github.com/App-vNext/Polly/blob/main/src/Polly.Core/Hedging/OnHedgingArguments.cs).

It is unclear:
- what is difference between the two 
  - I did not find the documentation comment really helpful
- when to use which
  - hedging documentation does not even mention primary only the `ActionContext` 

### Describe the solution you'd like

I think we could improve on the documentation comments also on the hedging documentation page.

**Comment by martintmk** [comment]
Because of the nature of hedging strategy, there might be multiple parallel actions being executed. To avoid race conditions we "duplicate" the original context passed to the strategy (primary) and provide it as an argument to action generator.

When hedging finishes we merge the context that was used for accepted action and merge it back to original context.

**Comment by peter-csala** [comment]
It seems like we have some sort of fork-join model (or fan-out + fan-in). And that raises a lots of questions:
- Are we talking about shallow or deep copy?
- What happens during the merger if the primary and the action context have the same key with different values?
- What happens during the merger if the action context contains a soft-delete (the value is set to `null`)? 
-  Since action generator is called before the `OnHedging`, will the changes on the `ActionContext` from the action generator be available in the `OnHedging` delegate?
- ...

So, my main point here is that without proper documentation i think it is easy to misuse these contexts.

Because V8 is already out we could not perform a renaming but `RequestContext` and `HedgedRequestContext` might be a better name IMHO. (_For me the `Primary` prefix indicates that there could/should be a `Secondary` as well._)

**Comment by martintmk** [comment]
@peter-csala I have created a #1749 to improve docs regarding the contexts.
