### ISSUE TITLE
[Feature request]: AOT compatibility

### ISSUE THREAD

**Issue by davidfowl** [App-vNext/Polly#1732]
### Is your feature request related to a specific problem? Or an existing feature?

Polly is at the core of [Microsoft.Extensions.Http.Resilience](https://github.com/dotnet/extensions/tree/main/src/Libraries/Microsoft.Extensions.Http.Resilience) and we'd like the libraries that depend on this package and polly itself to work in AOT environments.

### Describe the solution you'd like

Add `<IsAotCompatible>true</IsAotCompatible>` to the project files and work through the AOT issues. I've run a project that has a dependency and saw this:

```
  ILC: Method '[Polly.Core]Polly.Utils.Pipeline.CompositeComponent+DelegatingComponent.ExecuteCore<__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`2<__Canon,__Canon>>>>>>(Func`3<Resi
  lienceContext,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`2<__Canon,__Canon>>>>>,ValueTask`1<Outcome`1<__Canon>>>,ResilienceContext,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__
  Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`2<__Canon,__Canon>>>>>)' will always throw because: Failed to load type 'Polly.Utils.Pipeline.PipelineComponent' from assembly 'Polly.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=c8a
  3ffc3f8f825cc'
ILC : AOT analysis warning IL3054: Polly.Utils.Pipeline.CompositeComponent.DelegatingComponent.ExecuteCore<__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`2<__Canon,__Canon>>>>>>(Fun
c`3<ResilienceContext,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`2<__Canon,__Canon>>>>>,ValueTask`1<Outcome`1<__Canon>>>,ResilienceContext,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Ca
non,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`2<__Canon,__Canon>>>>>): Generic expansion to 'Polly.Utils.Pipeline.PipelineComponent.ExecuteCore<__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__C
anon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`2<__Canon,__Canon>>>>>>>(Func`3<ResilienceContext,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,
ValueTuple`2<__Canon,__Canon>>>>>>,ValueTask`1<Outcome`1<__Canon>>>,ResilienceContext,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`3<__Canon,__Canon,ValueTuple`2<__Canon,__Canon>>>>>>)' w
as aborted due to generic recursion. An exception will be thrown at runtime if this codepath is ever reached. Generic recursion also negatively affects compilation speed and the size of the compilation output. It is advisable to remove the source of the generic recursi
on by restructuring the program around the source of recursion. The source of generic recursion might include: 'Polly.Utils.Pipeline.PipelineComponent.ExecuteCore<TResult,TState>(Func`3<ResilienceContext,TState,ValueTask`1<Outcome`1<TResult>>>,ResilienceContext,!!1)',
'Polly.Utils.Pipeline.ComponentWithDisposeCallbacks.ExecuteCore<TResult,TState>(Func`3<ResilienceContext,TState,ValueTask`1<Outcome`1<TResult>>>,ResilienceContext,!!1)', 'Polly.Utils.Pipeline.CompositeComponent.ExecuteCore<TResult,TState>(Func`3<ResilienceContext,TStat
e,ValueTask`1<Outcome`1<TResult>>>,ResilienceContext,!!1)', 'Polly.Utils.Pipeline.CompositeComponent.ExecuteCoreWithoutTelemetry<TResult,TState>(Func`3<ResilienceContext,TState,ValueTask`1<Outcome`1<TResult>>>,ResilienceContext,!!1)', 'Polly.Utils.Pipeline.CompositeCom
ponent.ExecuteCoreWithTelemetry<TResult,TState>(Func`3<ResilienceContext,TState,ValueTask`1<Outcome`1<TResult>>>,ResilienceContext,!!1)', 'Polly.Utils.Pipeline.CompositeComponent.<ExecuteCoreWithTelemetry>d__13`2', 'Polly.Utils.Pipeline.ExternalComponent.ExecuteCore<TR
esult,TState>(Func`3<ResilienceContext,TState,ValueTask`1<Outcome`1<TResult>>>,ResilienceContext,!!1)', 'Polly.Utils.Pipeline.ReloadableComponent.ExecuteCore<TResult,TState>(Func`3<ResilienceContext,TState,ValueTask`1<Outcome`1<TResult>>>,ResilienceContext,!!1)', 'Poll
y.Utils.Pipeline.CompositeComponent.DelegatingComponent.ExecuteCore<TResult,TState>(Func`3<ResilienceContext,TState,ValueTask`1<Outcome`1<TResult>>>,ResilienceContext,!!1)', 'Polly.Utils.Pipeline.CompositeComponent.DelegatingComponent.<>c__6`2' [C:\dev\git\eShop\src\Or
dering.BackgroundTasks\Ordering.BackgroundTasks.csproj]
```

cc @MichalStrehovsky

**Comment by martincostello** [comment]
Interesting - we did investigate this as part of #1110 and thought we were good for the v8 release (at least for all the new assemblies). We must have missed something or introduced a regression.

**Comment by davidfowl** [comment]
Are the assemblies marked with `<IsAotCompatible>true</IsAotCompatible>`?

**Comment by MichalStrehovsky** [comment]
The Roslyn analyzer (that gets added with `<IsAotCompatible>true</IsAotCompatible>`) doesn't have the generic cycle detector so it wouldn't help in this case. This can only be detected by the AOT compiler currently. It requires a whole program analysis.

Does this compile with a warning, or does it even manage to crash the compiler?

**Comment by martincostello** [comment]
> IsAotCompatible

Looks like these were the ones we already added (we [tweaked them a bit](https://github.com/App-vNext/Polly/pull/1144/files#diff-6886410be312c01bc4684d1a95ecea94c6a79ff54f2494794d78bfc361aaa14e) for our .NET 8 branch too):

https://github.com/App-vNext/Polly/blob/9b2b170388518e46da6de4bdd15a7dd1d823d246/src/Polly.Core/Polly.Core.csproj#L13-L16

I guess we weren't aware there were additional options we needed to turn on as part of our testing.

I'll take a look into this today.

Assuming it's a quick fix, do you folks still have time to take a new release for the dotnet/extensions stuff for RTM? If not, we can just roll whatever fixes are needed into our 8.1.0 release which we're aiming to release once we can depend on 8.0.0 itself for support for `TimeProvider`.

**Comment by MichalStrehovsky** [comment]
The reduced issue is this:

```csharp
using System;

PipelineComponent p = new DelegatingComponent(null, null);
p.ExecuteCore<int, int>(state => default, default);


class PipelineComponent
{
    public virtual TResult ExecuteCore<TResult, TState>(Func<TState, TResult> callback, TState state)
    {
        return default;
    }
}

class DelegatingComponent : PipelineComponent
{
    PipelineComponent _component;
    PipelineComponent _next;

    public DelegatingComponent(PipelineComponent component, PipelineComponent next)
    {
        _component = component;
        _next = next;
    }

    public override TResult ExecuteCore<TResult, TState>(Func<TState, TResult> callback, TState state)
    {
        return _component.ExecuteCore(static (state) =>
        {
            return state._next.ExecuteCore(state.callback, state.state);
        },
        (_next, callback, state));
    }
}
```

Notice that `DelegatingComponent.ExecuteCore<TResult, TState>` introduces a call to `ExecuteCore<TResult, (PipelineComponent, Func<TState, TResult>, TState)>`. This is introducing a generic recursion. The generic recursion needs to be broken somehow.

More about this here: https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/warnings/il3054

Here's two samples that I know of that fixed a similar issue in different codebases:
* https://github.com/npgsql/npgsql/pull/4095
* https://github.com/dotnet/reactive/pull/1116

**Comment by martincostello** [comment]
I'm still doing some poking around, but from doing `dotnet new webapiaot` to get a template project I can reference against Polly's source and throwing in a few snippets of Polly code I don't seem to be getting any IL3054 warnings.

Can you point me at a sample project somewhere I can adapt to be part of our build to use to validate native AOT support?

**Comment by martincostello** [comment]
Where I've gotten to so far is in [this branch in my fork](https://github.com/martincostello/Polly/tree/aot-support).

If I run the following it builds with no trim warnings:

```terminal
$ dotnet publish .\test\Polly.AotTest\Polly.AotTest.csproj --tl
MSBuild version 17.8.0+6cdef4241 for .NET
Restore complete (0.9s)
  Polly.Core net6.0 succeeded (1.3s) → src\Polly.Core\bin\Release\net6.0\Polly.Core.dll
  Polly.RateLimiting net6.0 succeeded (1.4s) → src\Polly.RateLimiting\bin\Release\net6.0\Polly.RateLimiting.dll
  Polly.Extensions net6.0 succeeded (1.5s) → src\Polly.Extensions\bin\Release\net6.0\Polly.Extensions.dll
  Polly.AotTest succeeded (24.1s) → test\Polly.AotTest\bin\Release\net8.0\win-x64\publish\

Build succeeded in 28.4s

```

**Comment by martincostello** [comment]
Pasting in https://github.com/App-vNext/Polly/issues/1732#issuecomment-1782466692 I can force a IL3053 warning which gives me something to iterate on for now.

**Comment by davidfowl** [comment]
Thanks for looking at this @martincostello !

**Comment by martincostello** [comment]
@davidfowl I'm planning on publishing Polly 8.1.0 release tomorrow which contains a couple of changes that should resolve your AoT warnings.

If you'd like to try out a prerelease version in the meantime, there should be some NuGet packages attached to [this CI build](https://github.com/App-vNext/Polly/actions/runs/6696605545) once it completes in ~30 minutes.
