### ISSUE TITLE
[Question]: How to override default ResiliencePipeline defined and used by a 3rd party library 

### ISSUE THREAD

**Issue by atomaras** [App-vNext/Polly#1741]
### What are you wanting to achieve?

I am trying to add resilience to my reusable libraries (distributed as nuget packages) that make outbound http calls . 
Think basic transient http fault handling like retries on ServiceUnavailable etc.
I also want to allow clients of these libs to be able to override the default behavior (default named resilience pipelines) through dependency injection.
For example, lets say the library author (i.e. me) added resilience handing only for 500 http responses through a named pipeline called "transient-http-error-handling". My clients though (apps like web apis etc) realize down the line that they _also_ need me to handle RequestTimeouts (408) and TooManyRequests (429). How can they override my library's default behavior without needing me?

I looked at the source code but I am having a hard time figuring out how to do it.

### What code or approach do you have so far?

```
var services = new ServiceCollection();

// What the library registers
const string libPipelineName = "transient-http-error-handling";
services.AddResiliencePipeline<string, HttpResponseMessage>(libPipelineName,
    (b) =>
    {
        b.AddRetry(new RetryStrategyOptions<HttpResponseMessage>()
        {
            ShouldHandle =
                new PredicateBuilder<HttpResponseMessage>()
                    .HandleResult(r => (int)r.StatusCode >= 500),
            BackoffType = DelayBackoffType.Exponential,
            UseJitter = true, // Adds a random factor to the delay
            MaxRetryAttempts = 4,
            Delay = TimeSpan.FromSeconds(3),
        });
    });

var sp = services.BuildServiceProvider();

// How the library uses it
var pipelineProvider = sp.GetRequiredService<ResiliencePipelineProvider<string>>();
var p = pipelineProvider.GetPipeline<HttpResponseMessage>(libPipelineName);

var ctx = ResilienceContextPool.Shared.Get("libOperation");
try
{
    var resp = await p.ExecuteAsync(
        callback: async _ =>
        {
            // simulate a transient error
            return new HttpResponseMessage(HttpStatusCode.InternalServerError);
        },
        context: ctx);
}
finally
{
    ResilienceContextPool.Shared.Return(ctx);
}
```

How can clients of this library change this to handle more cases without having to recompile the lib?

**Comment by martintmk** [comment]
Hey @atomaras , please check this test that very closely resembles your scenario:

https://github.com/App-vNext/Polly/blob/95b217b1ad5716ab96317e00531bbfe95a81ac68/test/Polly.Extensions.Tests/Issues/IssuesTests.OverrideLibraryStrategies_1072.cs#L13


The idea behind is that the first one that configures the strategy wins, so the adopter of you library can simply override the pipeline that you use by registering resilience pipeline first. 

Then there is a use-case where you just want to provide the option to change the defaults of your pre-defined pipeline. In that case I suggest to expose library-specific options: 

``` csharp
public class MyLibraryPipelineOptions
{
    public RetryStrategyOptions<HttpResponseMessage> Retry { get; set; } = new ()
        {
            ShouldHandle =
                new PredicateBuilder<HttpResponseMessage>()
                    .HandleResult(r => (int)r.StatusCode >= 500),
            BackoffType = DelayBackoffType.Exponential,
            UseJitter = true, // Adds a random factor to the delay
            MaxRetryAttempts = 4,
            Delay = TimeSpan.FromSeconds(3),
        }
}
```

And just use options patter to register and resolve these for your pipeline.

**Comment by atomaras** [comment]
Understood. Thank you!
