### ISSUE TITLE
[Feature request]: Speed-up the build by executing the mutation tests in a separate workflow

### ISSUE THREAD

**Issue by martintmk** [App-vNext/Polly#1755]
### Is your feature request related to a specific problem? Or an existing feature?

I think we can speed-up the build by extracting the mutation steps from https://github.com/App-vNext/Polly/blob/main/.github/workflows/build.yml into separate workflows.

### Describe the solution you'd like

I believe we can introduce two new workflows:

- `mutation-tests-core.yml` - in this workflow we would test all new Polly v8 projects.
- `mutation-tests-legacy.yml` - in this workflow we would test only Polly project.

This way the mutation tests is decreased by half on top of of reduced build times. With this change our PR builds could be done in less than 20 minutes.

**Comment by martincostello** [comment]
Suggest `core` not `v8`, then we don't need to rename it if we get to Polly 9.

**Comment by rorypierce** [comment]
So I should probably familiarize myself with the code base first... But as somebody trying to get a 10k meter perspective: would you be able to clarify a mutation test in the context of this particular project/build pipeline? I've done a reasonable amount of TDD and or PDD (pain driven development lol ) but I haven't seen the word "mutation" used in software parlance since I was taking genetic algorithms in undergrad (just to clarify my context). Thanks.

**Comment by martincostello** [comment]
The mutation tests are currently run by this cake task, which uses [Stryker](https://github.com/stryker-mutator/stryker-net) to run pmutations](https://stryker-mutator.io/docs/) on our different unit test projects:

https://github.com/App-vNext/Polly/blob/98f29c84d476f37d94b50ceac618494509a807e7/build.cake#L170

**Comment by xwu1-woolworthslimited** [comment]
Hi @martintmk I am happy to take this if nobody is working on,
Just want a bit clarification about the suggested solution as below.
As I can see currently we ran following mutation tests:
https://github.com/App-vNext/Polly/blob/4e7d099c30447c71e992d61aacf40a7616562bf6/build.cake#L179-L183

Is that only the last line `Polly.proj` belongs to legacy workflow and all the rest belongs to core workflow?

**Comment by ShawnWu33** [comment]
Hi @martintmk I am happy to take this if nobody is working on,
Just want a bit clarification about the suggested solution as below.
As I can see currently we ran following mutation tests:
https://github.com/App-vNext/Polly/blob/4e7d099c30447c71e992d61aacf40a7616562bf6/build.cake#L179-L183
Is that only the last line `Polly.proj` belongs to legacy workflow and all the rest belongs to core workflow?
