### ISSUE TITLE
[Feature request]: Consider dowgrading Microsoft.Extensions.Options dependency for older targets

### ISSUE THREAD

**Issue by jirikopecky** [App-vNext/Polly#1786]
### Is your feature request related to a specific problem? Or an existing feature?

I need to support older code that targets .NET Framework. I am using Polly for resiliency and would like to bump it to v8. But `Polly.Extensions` depends on `Microsoft.Extensions.Options` v2.2.0 which is out of support. Please consider downgrading to v2.1.x, which is still [supported on .NET Framework](https://dotnet.microsoft.com/en-us/platform/support/policy/aspnet/2.1-packages).

### Describe the solution you'd like

`Polly.Extensions` should depend on `Microsoft.Extensions.Options` >= 2.1.0

**Comment by martincostello** [comment]
As part of #1144 which is going to be merged tomorrow once .NET 8.0 is released, we will be updating the references to 8.0.0.

Those versions should still be compatible with .NET Framework, and will be supported by Microsoft for at least 3 years.
