### ISSUE TITLE
[Question]: Migration guidance for IHttpClientFactory and Microsoft.Extensions.Resilience

### ISSUE THREAD

**Issue by kmcclellan** [App-vNext/Polly#1788]
### What are you wanting to achieve?

I want to migrate to Polly V8, but I am using `Microsoft.Extensions.Http.Polly` in many places, [which is now deprecated](https://learn.microsoft.com/dotnet/core/resilience/). The [migration guide](https://www.pollydocs.org/migration-v8.html) doesn't appear to have any guidance on this.

### What code or approach do you have so far?

The replacement for `Microsoft.Extensions.Http.Polly` (`Microsoft.Extensions.Resilience.Http`) is still in prerelease as of now, so it looks like I need to wait before I can upgrade.

**Comment by martincostello** [comment]
Check out this discussion for links to the documentation for the new libraries, which are likely to be out of prerelease tomorrow with the release of .NET 8: https://github.com/App-vNext/Polly/discussions/1657

Both extension libraries are maintained by the .NET team, so I would expect migration documentation to come from them rather than us.

**Comment by martincostello** [comment]
Also, Polly v8 can be used with the previous extensions as-is with no problem.

**Comment by joelhulen** [comment]
Once the new [Microsoft.Extensions.Http.Resilience](https://www.nuget.org/packages/Microsoft.Extensions.Http.Resilience) comes out of pre-release mode, I plan to migrate one of my projects to it from the now deprecated version. Depending on how that goes, I might write up a migration doc.

**Comment by kmcclellan** [comment]
Makes sense. For some reason I didn't realize that the v7 types were all still included in v8. Thanks for the quick reply.

**Comment by kmcclellan** [comment]
https://github.com/dotnet/extensions/issues/4717
