### ISSUE TITLE
[Feature request]: Implement Clone functionality for the policies

### ISSUE THREAD

**Issue by TymurMirzaiev** [App-vNext/Polly#1797]
### Is your feature request related to a specific problem? Or an existing feature?

I'm collecting a dictionary of the same policies with different keys in order to use circuit state matching by that key.

I need to create Policies and then WrapAsync with each other everytime intead of just using .Clone.

### Describe the solution you'd like

I want to be able to use .Clone like this:

AsyncPolicyWrap<HttpResponseMessage> policyWrap = new ... ;

var samePolicyWrap = policyWrap.Clone();

**Comment by martincostello** [comment]
This is not something we're going to be implementing in the v7 API surface - unless there's a very good reason to change it, it's now effectively "done" and is just for backwards compatibility.

Have you tried the new v8 API surface to achieve the same goals?

**Comment by martintmk** [comment]
Please take a look at resilience pipeline registry and complex pipeline keys in v8 which allow the the concept of "cloning":

https://www.pollydocs.org/advanced/dependency-injection.html#complex-pipeline-keys

Essentially, this allows you to have multiple instances of pipeline per each circuit breaker.

**Comment by TymurMirzaiev** [comment]
Actually I use separate class, which I register as a singleton

```
public class MyPolicy
{
    private IConcurrentPolicyRegistry<string> _policies { get; } = new PolicyRegistry();

    public AsyncPolicyWrap<HttpResponseMessage> this[string url]
    {
        get
        {
            // TODO: Check is it possible to clone Policy somethow
            return _policies.GetOrAdd<AsyncPolicyWrap<HttpResponseMessage>>(url, GetWebhookPolicy());
        }
    }
```

Then I inject this object to the needed Controller/Query/Command whatever and use like this
```
var myPolicy = injectedMyPolicy[myRequest.MyKey]
myPolicy.Execute(myRequest.MyKey)
```

So I just to avoid building the same policy everytime in this method GetWebhookPolicy()

**Comment by martintmk** [comment]
> So I just want to avoid building the same policy everytime in this method GetWebhookPolicy()

If you use the `ResiliencePipelineRegistry` it will transparently cache the instances associated with complex keys, so it should be very fast too. You just need to use the v8 API and your scenario will work just fine.

**Comment by TymurMirzaiev** [comment]
@martintmk I mean GetWebhookPolicy() builds a policy with the same rules each time, so each instance has own ref.

_it will transparently cache the instances associated with complex keys_
I'm not sure it really matters anything in my case.

I'm thinking is there any mechanism like PolicyBuilder which is more optimized for this purpose. So I could do something like this:

MyPolicyBuilder.Build()

**Comment by martintmk** [comment]
@TymurMirzaiev 

In v8 your example becomes:

``` csharp
public class MyPipeline
{
    private ResiliencePipelineRegistry<string> _pipelines { get; } = new();

    public ResiliencePipeline<HttpResponseMessage> this[string url]
    {
        get
        {
            // TODO: Check is it possible to clone Policy somethow
            return _pipelines.GetOrAddPipeline<HttpResponseMessage>(url, (builder, _) => GetWebhookPipeline(builder));
        }
    }
}
```

This way,  the pipelines ara cached for each URL.. Remember that cloning is essentially the same as calling `GetWebhookPipeline` multiple times.

**Comment by TymurMirzaiev** [comment]
@martintmk Thank you for the explanation!

**Comment by TymurMirzaiev** [comment]
@martintmk I'm wondering how ResiliencePipelineRegistry behaves, looks like it lives within an application scope, but in case if my application was running on different pods, then I would get separate instance of ResiliencePipelineRegistry, therefore I need some external storage, right?
