### ISSUE TITLE
[Bug]: NuGet packages have default description since v8

### ISSUE THREAD

**Issue by ErisApps** [App-vNext/Polly#1812]
### Describe the bug

Probably a silly "bug" ticket to open, but since version 8.x of Polly, the new and existing packages have `Package Description` in their description metadata property.

### Expected behavior

The packages have a message that describes what the package does.
The v7 package of Polly, for example, had the following text: `Polly is a library that allows developers to express resilience and transient fault handling policies such as Retry, Circuit Breaker, Timeout, Bulkhead Isolation, and Fallback in a fluent and thread-safe manner.`

### Actual behavior

Package description is `Package Description`

### Steps to reproduce

Compare https://nuget.info/packages/Polly/7.2.4 vs https://nuget.info/packages/Polly/8.0.0

### Exception(s) (if any)

Not applicable

### Polly version

8.0.0 and higher

### .NET Version

Not applicable

**Comment by martincostello** [comment]
Thanks for reporting this - it looks like this information got lost as part of the v8 restructuring of the project for multiple NuGet packages. We'll get this fixed for the next release.
