### ISSUE TITLE
[Bug]: Rebus messages aren't being published in the OnRetry

### ISSUE THREAD

**Issue by Felipe379** [App-vNext/Polly#1825]
### Describe the bug

To be short, whenever I try to publish any [Rebus](https://github.com/rebus-org/Rebus) message inside the OnRetry, the message is not published.

### Expected behavior

Rebus message should have been published, regardless if it's inside the OnRetry.

### Actual behavior

Rebus message isn't being published when it's inside the OnRetry.

### Steps to reproduce

Say that we have a process to determine which kind of vehicle we received and according to the type, send different messages

```C#
...
public async Task VehicleHandler(VehicleMessage vehicleMessage)
{
	switch case (vehicleMessage.Type)
	{
		case when (Car):
			_bus.Publish(new CarMessage { ... });
			break;
		case when (Truck):
			_bus.Publish(new TruckMessage { ... });
			break;
		case when (Bike):
			_bus.Publish(new BikeMessage { ... });
			break;
		...
	}
	...
}
```

Different vehicles type should send different messages due to different processes and services.

```C#
...

private readonly GetCarDataService _getCarDataService;

...

public async Task CarHandler(CarMessage carMessage)
{
	...
	var data = await _getCarDataService.GetVehicleData(carMessage.Plate);
	...
}

```

Those different services inherits from a generic vehicle service, because each one have different implementations for the method GetData().

```C#
public class GetCarDataService : VehicleService<Request, Response>
{
	public override Task<Response> GetData(string plate)
	{
		try
		{
			...
		}
		catch (Exception ex)
		{
			throw new Exception(ex);
		}
	}
}
```

The VehicleService has an absctract GetData() method which should be overriden. The method GetVehicleData() should be called so the retry pipeline can be applied.

```C#
public abstract class VehicleService<TRequest, TResponse>
{
	...

	public abstract Task<TResponse> GetData(string plate);

	public async Task<TResponse> GetVehicleData(string plate)
	{
		var policy = BuildRetryPipeline();
		var result = await policy.ExecuteAsync(async (cancellationToken) =>
		{
			return await GetData(plate);
		}, cancellationToken);

		await _bus.Publish(new VehicleDataStatisticsMessage { ... })

		return result;
	}

	private ResiliencePipeline BuildRetryPipeline()
	{
		var pipeline = new ResiliencePipelineBuilder().AddRetry(new RetryStrategyOptions
		{
			ShouldHandle = new PredicateBuilder().Handle<Exception>(),
			MaxRetryAttempts = 5,
			Delay = TimeSpan.FromSeconds(10),
			BackoffType = DelayBackoffType.Constant,
			OnRetry = async args =>
			{
				await _bus.Publish(new VehicleDataStatisticsMessage { ... })
				return;
			}
		}).Build();
		return pipeline;
        }

	...
}
```

The issue happens when it tries to publish the VehicleDataStatisticsMessage. While the one GetVehicleData() is published with success, the one in OnRetry isn't.

Keep in mind this is just an example code.

### Polly version

8.2.0

### .NET Version

net6.0

**Comment by martincostello** [comment]
- Are you able to provide a minimal reproducible example that compiles (e.g. a test in our repo, or a public repository you can link us to) that shows the issue without getting Rebus involved?
- Is the issue that the code isn't being invoked in `OnRetry`, or that it is but then you don't see anything published? If the latter, is it that an exception is being thrown somewhere when you try to re-publish?
- Is there anything being logged by Polly that might hint at what's going on in your application regarding the retry (or lack of it)?

**Comment by Felipe379** [comment]
> * Are you able to provide a minimal reproducible example that compiles (e.g. a test in our repo, or a public repository you can link us to) that shows the issue without getting Rebus involved?
> * Is the issue that the code isn't being invoked in `OnRetry`, or that it is but then you don't see anything published? If the latter, is it that an exception is being thrown somewhere when you try to re-publish?
> * Is there anything being logged by Polly that might hint at what's going on in your application regarding the retry (or lack of it)?

> The issue is happening when publishing with Rebus. The in the OnRetry runs, but no message ever shows up. I don't have any public repo link.
> The code in OnRetry is being invoked, but the message doesn't seems to ever be published. However with the message outside of the retry policy, as shown in the GetVehicleData(), it's being published with success.
> I don't see anything being logged by Polly in the console, no exceptions or anything.

**Comment by martincostello** [comment]
> I don't have any public repo link.

We can try and look to repro an `OnRetry` not working in our own tests, but I would have _thought_ we have test cases for that scenario. If we can't reproduce it, then we'll need you to create a working repro to be able to investigate it further - otherwise we'd have to look to you to debug it further on your end with your own running system and Rebus involved to see what's going on.

> I don't see anything being logged by Polly in the console, no exceptions or anything similar.

To rule it out, if you add a `try-catch` to the code in your `OnRetry` handler, does an exception get caught? That would help distinguish between "nothing happens" and "it throws and that gets lost somewhere so it appears nothing is happening".

**Comment by martintmk** [comment]
> The code in OnRetry is being invoked, but the message doesn't seems to ever be published. However with the message outside of the retry policy, as shown in the GetVehicleData(), it's being published with success.

To me it seems that this might be Rebus issue. I suggest to investigate with them. Maybe try to check if setting `continueOnCapturedContext` to `true` makes any difference (https://www.pollydocs.org/advanced/resilience-context.html#resilient-context-pooling) if for whatever reason the `Rebus` uses synchronization context to propagate some inner states between executions. 

Otherwise I feel we won't be able to help you further on this issue.

**Comment by Felipe379** [comment]
> > The code in OnRetry is being invoked, but the message doesn't seems to ever be published. However with the message outside of the retry policy, as shown in the GetVehicleData(), it's being published with success.
> 
> To me it seems that this might be Rebus issue. I suggest to investigate with them. Maybe try to check if setting `continueOnCapturedContext` to `true` makes any difference (https://www.pollydocs.org/advanced/resilience-context.html#resilient-context-pooling) if for whatever reason the `Rebus` uses synchronization context to propagate some inner states between executions.
> 
> Otherwise I feel we won't be able to help you further on this issue.

Thanks, but that doesn't seems to have worked. Here is a similar code that I've tried to use:

```C#
public abstract class VehicleService<TRequest, TResponse>
{
	...

	private ResiliencePropertyKey<IBus> _key1 = new("key-test");

	public abstract Task<TResponse> GetData(string plate);

	public async Task<TResponse> GetVehicleData(string plate)
	{	
		var context = ResilienceContextPool.Shared.Get(
			operationKey: "key-test",
			continueOnCapturedContext: true,
			cancellationToken: cancellationToken
		);

		context.Properties.Set(_key1, _bus);

		var policy = BuildRetryPipeline();
		var result = await policy.ExecuteAsync(async context =>
		{
			return await GetData(plate);
		}, context);

		await _bus.Publish(new VehicleDataStatisticsMessage { ... })

		return result;
	}

	private ResiliencePipeline BuildRetryPipeline()
	{
		var pipeline = new ResiliencePipelineBuilder().AddRetry(new RetryStrategyOptions
		{
			ShouldHandle = new PredicateBuilder().Handle<Exception>(),
			MaxRetryAttempts = 5,
			Delay = TimeSpan.FromSeconds(10),
			BackoffType = DelayBackoffType.Constant,
			OnRetry = async args =>
			{
				if (args.Context.Properties.TryGetValue(_key1, out var bus))
				{
					await bus.Publish(new VehicleDataStatisticsMessage { ... });
				}

				return;
			}
		}).Build();
		return pipeline;
	}

	...
}
```

If no one can reproduce the issue, what I can try to do is to create a project which tries to reproduce the issue.

**Comment by martintmk** [comment]
> If no one can reproduce the issue, what I can try to do is to create a project which tries to reproduce the issue.

This would be great! But please try to drop any `Rebus`-related pieces as it something we won't be able to fix.

**Comment by Felipe379** [comment]
> > If no one can reproduce the issue, what I can try to do is to create a project which tries to reproduce the issue.
> 
> This would be great! But please try to drop any `Rebus`-related pieces as it something we won't be able to fix.

I'm not sure how supposed to drop any Rebus-related pieces if the issue is about code not being published when running with Polly.

**Comment by martincostello** [comment]
If the problem only happens with Rebus and there's no other way to replicate it, then that strongly hints it's a Rebus issue.

**Comment by Felipe379** [comment]
Just to give this issue a closure, I did crate a separated project and tried to reproduce the issue, but that wasn't able to do it.

So I asume the issue is somewhere in our project's configuration.
