### ISSUE TITLE
[Question]: Adding Typed ResiliencePipeline to ResiliencePipelineRegistry?

### ISSUE THREAD

**Issue by maciej-redzik** [App-vNext/Polly#1826]
### What are you wanting to achieve?

Hello,

I am currently migrating my Polly v7 implementation to Polly v8.

After breaking changes from v7 to v8, I've created my new ResilencePipeline with Retry & Timeout (with type HttpResponseMessage). Howewer, if ResilencePipeline is using generic type -> it cannot be added to ResilencePipelineRegistry...

Is above error it prevents me from adding generic ResilencePipeline by design or is it an error? Are there any other alternative ways to have central repo of generic Resilence pipelines?

### What code or approach do you have so far?

In previous Polly I've used following code which worked fine for me:

```CSharp
public class PolicyHelper
{
    private static readonly TimeSpan[] RetryScheme =
    {
        TimeSpan.FromSeconds(1),
        TimeSpan.FromSeconds(2),
        TimeSpan.FromSeconds(6),
        TimeSpan.FromSeconds(12)
    };

    public static AsyncRetryPolicy<HttpResponseMessage> RetryPolicy = Policy.Handle<HttpRequestException>()
        .OrResult<HttpResponseMessage>(x => !x.IsSuccessStatusCode)
        .WaitAndRetryAsync(RetryScheme, (response, timeSpan, retryCount, context) =>
        {
            if (response.Exception != null)
            {
                Console.WriteLine($"Error during http call: {response.Exception.Message}");
                Console.WriteLine($"Inner exception: {response.Exception.StackTrace}");
            }
            if (response.Result != null)
            {
                Console.WriteLine($"Returned response message: {response.Result.Content.ReadAsStringAsync().Result}");
                Console.WriteLine($"Status code: {response.Result.StatusCode}");
            }

            return Task.CompletedTask;
        });
}
```

And during startup of my app, I was able add following simple policy with code below:

```CSharp
IPolicyRegistry<string> registry = services.AddPolicyRegistry();
registry.Add("StandardHttpResilience", PolicyHelper.RetryPolicy);
```

New code (not working):

```CSharp
ResiliencePipeline<HttpResponseMessage> standardHttpPipeline = new ResiliencePipelineBuilder<HttpResponseMessage>()
            .AddRetry(new RetryStrategyOptions<HttpResponseMessage>
            {
                ShouldHandle = new PredicateBuilder<HttpResponseMessage>()
                    .Handle<Exception>()
                    .HandleResult(static result => !result.IsSuccessStatusCode),
                Delay = TimeSpan.FromSeconds(3),
                MaxRetryAttempts = 3,
                BackoffType = DelayBackoffType.Constant,
                OnRetry = static args =>
                {
                    Console.WriteLine($"Attempted retry no. {args.AttemptNumber}, {args.Context.OperationKey}");
                    return default;
                }
            })
            .AddTimeout(TimeSpan.FromSeconds(45))
            .Build();

        ResiliencePipelineRegistry<string> registry2 = new ResiliencePipelineRegistry<string>();
        registry2.GetOrAddPipeline("StandardHttpResilience", builder => builder.AddPipeline(standardHttpPipeline));
```

The message I am getting from IDE is:
"Cannot resolve method 'AddPipeline(Polly.ResiliencePipeline<System.Net.Http.HttpResponseMessage>)', candidates are:   Polly.ResiliencePipelineBuilder AddPipeline<ResiliencePipelineBuilder>(this Polly.ResiliencePipelineBuilder, Polly.ResiliencePipeline) (in class ResiliencePipelineBuilderExtensions)   Polly.ResiliencePipelineBuilder<System.Net.Http.HttpResponseMessage> AddPipeline<HttpResponseMessage>(this Polly.ResiliencePipelineBuilder<System.Net.Http.HttpResponseMessage>, Polly.ResiliencePipeline<System.Net.Http.HttpResponseMessage>) (in class ResiliencePipelineBuilderExtensions)"

### Additional context

A am using dotnet 8, and package Polly 8.2.0

**Comment by martintmk** [comment]
@maciej-redzik 

In your code just change:
``` csharp
registry2.GetOrAddPipeline("StandardHttpResilience", builder => builder.AddPipeline(standardHttpPipeline));
```

To:

``` csharp
registry2.GetOrAddPipeline<HttpResponseMessage>("StandardHttpResilience", builder => builder.AddPipeline(standardHttpPipeline));
```

The `standardHttpPipeline` is generic over `HttpResponseMessage`, so you need to use generic `GetOrAddPipeline` method.

**Comment by maciej-redzik** [comment]
Hi @martintmk,

It works! Thank you :)
