### ISSUE TITLE
[Question]: Difference between Hedging: Fallback mode and Fallback strategy

### ISSUE THREAD

**Issue by silkfire** [App-vNext/Polly#1827]
### What are you wanting to achieve?

I was reading up on the new Hedging strategy, particulary about the [Fallback mode](https://www.pollydocs.org/strategies/hedging#fallback-mode) and realized that it seems to be very similar if not identical to the conventional Fallback strategy.

Am I correct or am I missing some subtle details in my reasoning?

### What code or approach do you have so far?

N/A

### Additional context

N/A

**Comment by peter-csala** [comment]
In case of fallback mode the hedging strategy can execute more than one attempts depending on the number set to the `MaxHedgedAttempts` property.

For example if `MaxHedgedAttempts` is set to 3 then your initial attempt could fail, your first retry attempt could fail as well, while the 2nd retry attempt could succeed.

So, it is more like a combination of retry and fallback. In case of retry you re-execute the same action over and over. In case of fallback you can provide a substitute action. In case of hedging you can perform multiple attempts with the same or a custom action (`ActionGenerator`).

**Comment by silkfire** [comment]
Thanks for the detailed explanation. I understand much better now!
