### ISSUE TITLE
FUNDING.yml

### ISSUE THREAD

**Issue by sebastienros** [App-vNext/Polly#1835]
In order to suggest Polly for Microsoft open-source funding nominations it would help to point to a FUNDING.yml file with GH sponsors members. I understand that this might be controversial because who should be in it, not everyone can technically accept GH sponsorship (some countries can't), who deserve it.

An option could be to allow anyone from the top N over contributors at all times or in the last year.
It's also ok to just agree that it's too controversial and ignore it.

**Comment by martincostello** [comment]
Asked Joel about this on Slack in December:

> We've always avoided adding funding options because it seems to open up cans of worms.

As the FOSS round for this year is over, will close.

**Comment by martincostello** [comment]
FYI we have GitHub Sponsors configured now.
