### ISSUE TITLE
Mixing retry with timeout

### ISSUE THREAD

**Issue by aliostad** [App-vNext/Polly#184]
Hi,

Thanks for a great library.

I need to be able to mix preemptive timeout (i.e. consider a call failed if it times out within a budgeted timeout period rather than default longer call timeouts such as SQL or HTTP) with transient failure handling. 

So does `Polly` support preemptive timeout? If yes how and if no, would you accept PR for it?

**Comment by reisenberger** [comment]
hi @aliostad .  You should be able to do this (if I've understood right) with Polly v5.0's new [Timeout policy](https://github.com/App-vNext/Polly/wiki/Timeout), then using the new [PolicyWrap](https://github.com/App-vNext/Polly/wiki/PolicyWrap) to combine in a retry policy:

```csharp
TimeoutPolicy timeout = Policy.Timeout(myTimeOverallBudget); 
RetryPolicy retry = Policy.Handle<WhateverException>.Retry(/* my retry choices */);
PolicyWrap retryWithTimeout = timeout.Wrap(retry); // Wrap them in the other order if you want the timeout per call, not per overall strategy
retryWithTimeout.Execute(() => DoSomething());
```

(Just an example: you can do all that both sync/async, for generic `<TResult>` executions/policies too, and for all flavours of retry.)

More:
+ [Timeout syntax summary](https://github.com/App-vNext/Polly/tree/v5.0-alpha#timeout) in the v5.0-alpha readme
+ [Timeout policy deep doco](https://github.com/App-vNext/Polly/wiki/Timeout) on wiki
+ [PolicyWrap deep doco](https://github.com/App-vNext/Polly/wiki/PolicyWrap) including [recommendations for combining policies for timeout to be overall, or per try](https://github.com/App-vNext/Polly/wiki/PolicyWrap#ordering-the-available-policy-types-in-a-wrap)
+ [blog post re new Polly v5.0 features](http://www.thepollyproject.org/2016/10/25/polly-5-0-a-wider-resilience-framework/)

Polly v5.0 is [in alpha on nuget](https://www.nuget.org/packages/polly).  Expecting RTM sometime in the next 2-3 weeks.  No change to above features expected for RTM.

Let us know if that gets you going, or if we can help more.  All feature feedback welcome!

**Comment by aliostad** [comment]
That sounds great. 

Is there a way to adapt the timeout based on a the percentile of the existing response times?

**Comment by reisenberger** [comment]
@aliostad  `TimeoutPolicy` has a configuration overload taking a `Func<TimeSpan>`, so certainly possible to configure a policy where you can vary the timeouts in real-time (thanks to @brunolauze and @mfjerome for this original idea).  
 
Re percentiles of existing response times, Polly does not yet provide these stats, but emitting such events/metrics is a major part of the [forward roadmap](https://github.com/App-vNext/Polly/wiki/Polly-Roadmap#emit-events-andor-statistics) for 2017 (taking Polly in the metrics/dashboarding direction which Hystrix offers for Java).

@aliostad  Are you (/any teams you work with) interested in being involved in the metrics development effort?  It's a major piece of work, which will benefit for more community resource.  

There’s already been prior discussion [on our slack channel](https://pollytalk.slack.com/archives/general/p1474650367000048), and some folks from Canada and Pivotal in the US are interested, too.

**Comment by aliostad** [comment]
Hi,

This is exactly what I am looking for. I considered porting Hysterix but I knew you guys done work in the area so preferred to see if this were available. 

We heavily do metrics, ingesting 1TB of logs a day in ASOS - the overall architecture is Microservices not too different from that of Netflix and Uber. I will join you on the conversations.

Thanks once again for the hard work. Keep it up.
