### ISSUE TITLE
BreakDurationGenerator not passed to CircuitStateController

### ISSUE THREAD

**Issue by martincostello** [App-vNext/Polly#1850]
There is an issue with this. When you call AddCircuitBreaker(options), having specified BreakDurationGenerator. It does not pass the generate to the CircuitStateController. So the resulting circuitbreaker will use the default 5 seconds fixed duration.

_Originally posted by @adminnz in https://github.com/App-vNext/Polly/issues/1776#issuecomment-1846438825_

**Comment by adminnz** [comment]
Not sure what more to add,  the BreakDurationGenerator get passed to the controller.

So if you do:
```
        ResiliencePipeline = new ResiliencePipelineBuilder()
           .AddCircuitBreaker(new CircuitBreakerStrategyOptions
           {
               BreakDurationGenerator = args => ValueTask.FromResult(TimeSpan.FromMinutes(args.FailureCount)),
               MinimumThroughput = Settings.CircuitBreakerMinimumThroughput,
               FailureRatio = Settings.CircuitBreakerFailureRatio,
               SamplingDuration = Settings.CircuitBreakerSamplingDuration,
               StateProvider = CircuitBreakerStateProvider,
               OnClosed = OnCircuitClosed,
               OnOpened = OnCircuitOpened,
               OnHalfOpened = OnHalfOpened
           })
           .Build();
```

The resulting ResiliencePipline circuit breaker will not use the BreakDurationGenerator. Instead it will use the default 5 second BreakDuration.

**Comment by martincostello** [comment]
Thanks - it was a concrete code snippet I was after so that we can use it to build up a unit test.
