### ISSUE TITLE
[Feature request]: Add ConfigureResiliencePipelineRegistry to IServiceCollection

### ISSUE THREAD

**Issue by damienhoneyford** [App-vNext/Polly#1855]
### Is your feature request related to a specific problem? Or an existing feature?

I am trying to add Resilience Pipelines from configuration via the DI container but my key is a Type and at the point of adding the Pipelines, it hasn't been loaded yet and I would rather not blindly load any Type and Assembly that someone adds to the configuration for obvious reasons.

### Describe the solution you'd like

Some other services have a 'Configure' method which allow services to be configured at a later point (e.g. Open Telemetry has `ConfigureOpenTelemetryMeterProvider(IServiceCollection, Action<IServiceProvider, MeterProviderBuilder>))` which can be called to perform additional configuration right before the MeterProvider is initialized).

I believe that my issue could be more easily resolved by adding a method such as:

```csharp
ConfigureResiliencePipelineRegistry<TKey>(IServiceCollection, Action<IServiceProvider, ResiliencePipelineRegistry<TKey>>)
```

This way I could add the Registry initially, then Configure it in a separate step which would be executed later, by which time the types that are being referenced will likely have been automatically loaded, and if not, can be safely ignored.

### Additional context

As a work around I could Add the Registry initially and then once `WebApplicationBuilder.Build()` is called I could add an additional method call which gets the `IServiceProvider` from the built application to perform this configuration, but this is 'messy' and doesn't quite sit with the concept of registering related services in a single extension method, which is what I'm trying to do via my own extension method which loads and validates the configuration, then adds the Resilience Pipelines as needed.

**Comment by martincostello** [comment]
This seems reasonable to me - what do you think @martintmk?

**Comment by martintmk** [comment]
I think the proposal addresses reasonable feature-gap. The only downside is ambiguity of `ConfigureResiliencePipelineRegistry` method that suggests (by the name) that `ResiliencePipelineRegistryOptions<TKey>` should be accepted. Instead, what it really does is to populate already configured registry with a new resilience pipelines.

How about this?

``` csharp
public static IServiceCollection AddResiliencePipelineRegistry<TKey>(
    this IServiceCollection services,
    Action<ResiliencePipelineRegistryOptions<TKey>> configure,
    Action<InitializeResiliencePipelineRegistryContext<TKey>> initialize)
    where TKey : notnull
{
}

public class InitializeResiliencePipelineRegistryContext<TKey>(ResiliencePipelineRegistry<TKey> registry, IServiceProvider serviceProvider)
    where TKey : notnull
{
    public ResiliencePipelineRegistry<TKey> Registry => registry;

    public IServiceProvider<TKey> ServiceProvider => serviceProvider;
}
```

Here, we are just adding a new overload for `AddResiliencePipelineRegistry` that also allows initializing the registry (for advanced scenarios). It can be called as many times as needed and allows populating the registry. 

``` csharp
services.AddResiliencePipelineRegistry<string>(_ => { }, context =>
{
    context.Registry.TryAddBuilder("my-pipeline-1", (builder, _) => builder.AddTimeout(TimeSpan.FromSeconds(1)));
    context.Registry.TryAddBuilder("my-pipeline-2", (builder, _) => builder.AddTimeout(TimeSpan.FromSeconds(1)));
    context.Registry.TryAddBuilder("my-pipeline-3", (builder, _) => builder.AddTimeout(TimeSpan.FromSeconds(1)));
});

services.AddResiliencePipelineRegistry<string>(_ => { }, context =>
{
    context.Registry.TryAddBuilder("my-pipeline-4", (builder, _) => builder.AddTimeout(TimeSpan.FromSeconds(1)));
    context.Registry.TryAddBuilder("my-pipeline-5", (builder, _) => builder.AddTimeout(TimeSpan.FromSeconds(1)));
    context.Registry.TryAddBuilder("my-pipeline-6", (builder, _) => builder.AddTimeout(TimeSpan.FromSeconds(1)));
});
```

(first callback configures the options, but we don't want to modify those, so I just provided empty lambda).

Wdyt, could this work for you?

**Comment by damienhoneyford** [comment]
I agree that the naming of `ConfigureResiliencePipelineRegistry` does leave some ambiguity, and given that the implementation (at least the intial one I hurried together) contains very similar code to the `AddResiliencePipeline` methods, it likely would be better named something akin to those.  I did initially consider naming the method `AddResiliencePipelines` but felt like it was more in-keeping with other libraries to use 'Configure...'.

The big drawback for me in your proposed implementation, @martintmk, is that it works directly with the `ResiliencePipelineRegistry` class, which means it misses out on all the goodness available in the `AddResiliencePipelineContext` class -- possibly which could be introduced via a method on your proposed `InitializeResiliencePipelineRegistryContext` class though.

**Comment by martintmk** [comment]
I like the `AddResiliencePipelines<TKey>`, since it's something that it actually does. It's pretty unambiguous. 

It can accept callback that has access to `AddResiliencePipelinesContext<TKey>` on which there are the following methods:

``` csharp
void AddResiliencePipeline(
   TKey key,
   Action<ResiliencePipelineBuilder, AddResiliencePipelineContext<TKey>> configure);

void AddResiliencePipeline<TResult>(
   TKey key,
   Action<ResiliencePipelineBuilder<TResult>, AddResiliencePipelineContext<TKey>> configure);
```

Should support your and more-advanced scenarios pretty well.
