### ISSUE TITLE
feature request: code-only nuget package for Polly

### ISSUE THREAD

**Issue by SurajGupta** [App-vNext/Polly#187]
This is a feature request for nuget package that installs Polly as code, instead of an assembly dependency.  In that way, Polly does not need to propagate up a chain of dependencies and can be isolated to where it's actually used.

A convention that I've used is to install the code into a folder that starts with a period (e.g. '.Polly'), so it's clear that that code is not the consumer's code.

You can install this nuget package as an example:
OBeautifulCode.Math.ThreadSafeRandom

The installed file will be ignored by StyleCop and CodeAnalysis because the header and how the class is decorated.

**Comment by reisenberger** [comment]
Thanks @SurajGupta for this interesting suggestion.  Unfortunately, for Polly, it seems non-trivial to set this up compared with the example you quoted and other similars (eg [TinyIoc](https://www.nuget.org/packages/TinyIoC/)).  

+ Polly uses [Visual Studio 2015 Shared Projects](https://blogs.msdn.microsoft.com/dotnet/2014/04/21/sharing-code-across-platforms/) combined with [#if compiler directives](https://msdn.microsoft.com/en-us/library/ew2hz0yd.aspx) and compilation constants, in limited ways, to support its non-.Net-Standard targets.  
  - This means simply incorporating the [Polly.Shared](https://github.com/App-vNext/Polly/tree/master/src/Polly.Shared) folder into a user's project 'as is' will not work.
  - Some kind of install scripting (Powershell; [nuget transforms](https://docs.nuget.org/ndocs/create-packages/source-and-config-file-transformations)?) might be needed either to inject appropriate compilation constants into the user's project files (if acceptable) or to process the `#if` statements or to `#define` constants in ways appropriate for the user's target.   
+ [ExcludeFromCodeCoverageAttribute](https://msdn.microsoft.com/en-us/library/system.diagnostics.codeanalysis.excludefromcodecoverageattribute(v=vs.110).aspx) appears [not supported in .NET Standard until .Net Standard 2.0](https://apisof.net/catalog/System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute); but .NET Standard 1.0 is currently an important constituency, for our portable users and .NET Core.
+ Polly consists of 100 `.cs` files, not just one; so the custom-attributing would inject noise throughout (and need maintaining accurately going forward); not just be a one-off addition.

At the moment, we're not seeing the complexity involved as adding enough value.  

Very happy though for further community input, if anyone is aware of a simpler approach?

And: Will leave this issue open for a period, so other community can +1 if seen as an important feature.

**Comment by SurajGupta** [comment]
Thanks for the thoughtful reply!  All good points.  Lets see if anyone else has some ideas.

**Comment by reisenberger** [comment]
Closing due to lack of response, and because not really practicable (/worth the complexity/maintenance effort) for a project Polly's size.  (It would be hard for the raw-code-inclusion approach to come close to a dll-package-manager’s ease of use for incorporating, and updating.)
 
Please re-open if anyone thinks that line of thinking is missing something, though.
