### ISSUE TITLE
[Question]: Polly 8.2.0 Why Timeout not effective?

### ISSUE THREAD

**Issue by JiaLinYou** [App-vNext/Polly#1872]
### What are you wanting to achieve?

Why is the output statement of the OnTimeout method not printed after requesting the TestTimeoutSync method?
I have used Thread.Sleep(2000), and TimeSpan.FromSeconds(1)
So I think there should be a timeout after the request, but it didn't.
May I ask how to use new ResilienePipelineBuilder().AddTimeout() ?

![image](https://github.com/App-vNext/Polly/assets/96672802/fd49e5cc-3898-4b1e-b1ef-0b6e11281c8c)

### What code or approach do you have so far?

[HttpGet]
        [Route("TestTimeoutSync")]
        public string TestTimeoutSync()
        {
            try
            {
                ResiliencePipeline pipeline = new ResiliencePipelineBuilder()
                    .AddTimeout(new TimeoutStrategyOptions
                    {
                        //Timeout = TimeSpan.FromSeconds(1),
                        TimeoutGenerator = args =>
                        {
                            return new ValueTask<TimeSpan>(TimeSpan.FromSeconds(1));
                        },
                        OnTimeout = static args =>
                        {
                            Console.WriteLine($"Execution timed out after {args.Timeout.TotalSeconds} seconds.");
                            return default;
                        }
                    }).Build();

                var result = pipeline.Execute(static () =>
                {
                    var res = TheadSleep();
                    Console.WriteLine(res);
                    return res;
                });
                return result;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return "TestTimeoutSync timeout!";
        }

        public static string TheadSleep()
        {
            Thread.Sleep(2000);
            return "This is TheadSleep";
        }

**Comment by martincostello** [comment]
What output _do_ you see?

**Comment by JiaLinYou** [comment]
I can see this
![image](https://github.com/App-vNext/Polly/assets/96672802/1a9edac4-a512-4c6b-9173-06d32b8ae9a1)

**Comment by martincostello** [comment]
Even on synchronous code paths, you should still observe the `CancellationToken` associated with the invocation, otherwise the operation will still complete.

This is noted in the documentation: https://www.pollydocs.org/strategies/timeout.html

**Comment by JiaLinYou** [comment]
Yes, I have saw the document several times, But when I use CancellationToken
![image](https://github.com/App-vNext/Polly/assets/96672802/8fe0d49a-1ccc-41c0-bb65-51c71b948e70)

Or use CancellationToken.None
![image](https://github.com/App-vNext/Polly/assets/96672802/d6a62cc9-3d8d-4dc3-b091-c9a3b82f33b3)

Or use cancellationToken
![image](https://github.com/App-vNext/Polly/assets/96672802/835279be-25c3-4f83-a07b-587b5a375553)

so what should I do?

**Comment by martincostello** [comment]
You need to add a parameter to your lambda to accept the `CancellationToken` that is passed to the method as shown in the sample, e.g. `static (ct) => ...`.

See the API documentation (or IntelliSense in the IDE) for the different delegate types for the different overloads of `Execute()`, for example: https://www.pollydocs.org/api/Polly.ResiliencePipeline-1.html#Polly_ResiliencePipeline_1_Execute__1_System_Func_System_Threading_CancellationToken___0__System_Threading_CancellationToken_

**Comment by JiaLinYou** [comment]
Thanks for you help. Now it will print "TheadSleep have been canceled" after timeout, but still unable to print 234 lines of code.
May I ask if my CancellationToken usage is incorrect.
![image](https://github.com/App-vNext/Polly/assets/96672802/deec13da-c9c5-4b0b-828d-e10bac826898)

**Comment by martincostello** [comment]
You should call the [ThrowIfCancellationRequested()](https://learn.microsoft.com/dotnet/api/system.threading.cancellationtoken.throwifcancellationrequested) method in your `ThreadSleep()` method instead of branching based on the value of the `IsCancellationRequested` property.

**Comment by JiaLinYou** [comment]
Thanks for your help, now ThreadSleep() method will throw OperationCanceledException and the OnTimeout method able to print.

However, after timeout, the console can see the exception message thrown, which is a normal phenomenon, right? Because we terminate the execution of the TheadSleep() method by throwing an exception, so it is reasonable for the console to display abnormalities, we don't need to worry either right?

**Comment by martincostello** [comment]
Well now the timeout is working as expected, and timing out if more than 2 seconds is spent in your method, so there's an unhandled exception caused by that timeout.

If you don't want _that_ exception to bubble up into the controller method, then you need to catch/handle it in a manner appropriate to your use case (retry, fallback, whatever).

Ultimately the timeout is designed to just short-circuit and stop resources being "wasted" spending "too long" doing something, they're not a way to try and make something more likely to succeed (like, say, retries) in of itself.
