### ISSUE TITLE
[Feature request]: Relax validation of TimeoutStrategyOptions.Timeout

### ISSUE THREAD

**Issue by jasper-d** [App-vNext/Polly#1884]
### Is your feature request related to a specific problem? Or an existing feature?

Currently, there is a validation attribute on `TimeoutStrategyOptions.Timeout` that requires a timeout to be in the range of [00:00:01, 1.00:00:00]. This is probably reasonable for most operations, but for some a min timeout of 1s might be to long.

I have tests that are rather slow because they need to use the min timeout of 1s.

### Describe the solution you'd like

It would be nice if the lower limit could be set to 0 or 1ms so that users are free to choose a timeout that is appropriate for their use case.

**Comment by martintmk** [comment]
This is reasonable request. We can decrease the minimum accepted timeout value.

I feel like 1ms is too low. How about 10ms? (still can be decreased later if necessary)

**Comment by jasper-d** [comment]
Thanks for the prompt response. I'm not sure if any enforced lower limit will work in all cases, but 10ms would definitely help me to cut test execution time down to some reasonable level :)

**Comment by martintmk** [comment]
> Thanks for the prompt response. I'm not sure if any enforced lower limit will work in all cases, but 10ms would definitely help me to cut test execution time down to some reasonable level :)

Fyi, Polly also supports `TimeProvider`, and you can use `FakeTimeProvider` to speed-up and fake the passage of time:

``` csharp
var timeProvider = new FakeTimeProvider
{
    AutoAdvanceAmount = TimeSpan.FromSeconds(10)
};

var pipeline = new ResiliencePipelineBuilder { TimeProvider = timeProvider }
    .AddTimeout(TimeSpan.FromSeconds(5))
    .Build();

await pipeline.ExecuteAsync(async token =>
{
    await Task.Delay(100000, token);
});
```

**Comment by jasper-d** [comment]
Nice, that's even better :)
