### ISSUE TITLE
[Feature request]: Adding Polly.Telemetry event for being out of retries

### ISSUE THREAD

**Issue by mgrandi** [App-vNext/Polly#1915]
### Is your feature request related to a specific problem? Or an existing feature?

We are utilizing Polly.Telemetry to track when our polly resilience pipelines with a RetryStrategy experience retries with a OnRetry event, however that doesn't run when the pipeline is out of retries

It seems relatively simple to add the Telemetry reporting call (and a new constant in RetryConstants) in the actual implementation here: https://github.com/App-vNext/Polly/blob/main/src/Polly.Core/Retry/RetryResilienceStrategy.cs

### Describe the solution you'd like

The only alternative that i see is to have our helper method wrap two Resilience pipelines so that the outer one can catch the outer pipeline running out of retries , but that seems like extra work + memory that would be more easily solved by adding another `_telemetry.Report` call here: https://github.com/App-vNext/Polly/blob/main/src/Polly.Core/Retry/RetryResilienceStrategy.cs#L79C1-L79C135

**Comment by mgrandi** [comment]
i can do the changes myself as a pull request, i mainly wanted to get feedback on if there is some reason why this wasn't done in the first place before I take the time to submit a pull request + tests + documentation

**Comment by martintmk** [comment]
Hey @mgrandi 

Please check the `ExecutionAttemptArguments` that can help you here:

https://www.pollydocs.org/api/Polly.Telemetry.ExecutionAttemptArguments.html

We can just add property such as IsLastAttempt or MaxAttempts to that struct and it will have everything you need to handle this case.

**Comment by mgrandi** [comment]
Thanks for the quick reply:

I think that would be good to have, although not quite what i had in mind, as that would show when you are on the last attempt but have not executed that attempt yet, and I"m interested in the case of when the Pipeline is out of attempts and is propagating the failure to the user

however stepping through this in Linqpad shows me that there are way more resilience events than I was expecting, and something close to what I think i am looking for is the `PipelineExecuted` event with an `Outcome` that has a `Value` that has Exception filled in

So I guess I don't need a new feature after all as the `PipelineExecuted` event seems to have what I need. Although maybe a new event for "the outcome was an exception" might make it more clear, or adding documentation around all the available Telemetry events (since they seem to be hard to come by, I personally didn't see that `PipelineExecuted` was an event until I logged them all with Linqpad)

**Comment by martintmk** [comment]
@mgrandi, it seems that you have found a workaround so I am closing this issue.
