### ISSUE TITLE
[Question]: Is Polly compatible with Unity ?

### ISSUE THREAD

**Issue by athpon** [App-vNext/Polly#1919]
### What are you wanting to achieve?

I'm trying to use retry pattern in my multiplayer unity game where sometime the message was out of sync or out of order.
And might as well use it to wrap UnityWebRequest.
How ever my problem is the unity editor give me an error when using retry (I didn't test other strategy)

My target build is WebGL, Android, IOS, Windows.
So another question does Polly create a thread internally ? If so I can't use it in my WebGL (not support)

### What code or approach do you have so far?

```
ResiliencePipelineBuilder pipeline = new ResiliencePipelineBuilder();
pipeline.AddRetry(new RetryStrategyOptions()
{
    Delay = TimeSpan.FromSeconds(1)
});

ResiliencePipeline resiliencePipeline = pipeline.Build();


resiliencePipeline.Execute(() =>
{
    //this just change object name
    name = $"SOME NAME";
});
```

When I run the code I got an error but the name of object did change

> FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
Polly.Utils.Pipeline.BridgeComponent`1[T].ConvertValueTask[TTo] (System.Threading.Tasks.ValueTask`1[TResult] valueTask, Polly.ResilienceContext resilienceContext) (at <14423ddbceb8489194237dd7d9d7ad65>:0)
Polly.Utils.Pipeline.BridgeComponent`1[T].ExecuteCore[TResult,TState] (System.Func`3[T1,T2,TResult] callback, Polly.ResilienceContext context, TState state) (at <14423ddbceb8489194237dd7d9d7ad65>:0)
Polly.Utils.Pipeline.CompositeComponent.ExecuteCoreWithoutTelemetry[TResult,TState] (System.Func`3[T1,T2,TResult] callback, Polly.ResilienceContext context, TState state) (at <14423ddbceb8489194237dd7d9d7ad65>:0)
Polly.Utils.Pipeline.CompositeComponent.ExecuteCore[TResult,TState] (System.Func`3[T1,T2,TResult] callback, Polly.ResilienceContext context, TState state) (at <14423ddbceb8489194237dd7d9d7ad65>:0)
Polly.Utils.Pipeline.PipelineComponent.ExecuteCoreSync[TResult,TState] (System.Func`3[T1,T2,TResult] callback, Polly.ResilienceContext context, TState state) (at <14423ddbceb8489194237dd7d9d7ad65>:0)
Polly.ResiliencePipeline.Execute (System.Action callback) (at <14423ddbceb8489194237dd7d9d7ad65>:0)

So I'm currently unsure if it gonna work in release build.

### Additional context

![image](https://github.com/App-vNext/Polly/assets/33125578/edfcb9a6-7e36-4231-840f-05002d54e9c3)

**Comment by martincostello** [comment]
Polly makes extensive use of `{Value}Task{<T>}` in its code, but does not explicitly manage threads.

I don't have any experience of Unity, and it is not a scenario we test for.

The error messages would suggest that it is not supported.

**Comment by athpon** [comment]
Thank you, Guess I'll have to look for a work around.

**Comment by eirikwah** [comment]
See https://github.com/slimshader/Unity.Polly, which states:

> Port of [Polly](https://github.com/App-vNext/Polly) library for Unity based on UniTask
> 
> This version is based of [v7.2.4](https://github.com/App-vNext/Polly/tree/7.2.4) of the Polly library as it has no external dependancies on netstandard 2.1 which is perfect for Unity.
