### ISSUE TITLE
[Bug]: Retry doesn't happen with FakeTimerProvider.Advance

### ISSUE THREAD

**Issue by rcollette** [App-vNext/Polly#1932]
### Describe the bug

When using FakeTimerProvider in unit tests, retries configured in a ResiliencyPipeline are not executed.

### Expected behavior

After initial execution fails, and after calling `FakeTimerProvider` with a period that is longer than the specify retry Delay, the second execution should start.

### Actual behavior

Nothing.

### Steps to reproduce

Minimal reproduction 
https://github.com/rcollette/PollyRetryFakeTimeProviderIssue

This also contains few basic unit tests using Cancellation tokens and Delays to confirm basic premise of testing time based async code.

### Polly version

8.2.1

### .NET Version

8.0.101

**Comment by rcollette** [comment]
Asked on Stackoverflow as well.
https://stackoverflow.com/questions/77876331/why-is-task-delay1-necessary-to-advance-clock-when-unit-testing-with-net-time/77880346?noredirect=1#comment137313518_77880346

**Comment by martintmk** [comment]
I believe I encountered similar issue where the time won't advance. If you look at our code, there is really nothing special, we are just calling `Delay`:

https://github.com/App-vNext/Polly/blob/727164748c2ff971eaca79c34d13f54e563b2c3b/src/Polly.Core/Retry/RetryResilienceStrategy.cs#L96

Which in turn calls:
https://github.com/App-vNext/Polly/blob/727164748c2ff971eaca79c34d13f54e563b2c3b/src/Polly.Core/Utils/TimeProviderExtensions.cs#L19

I suspect the problem might be in `FakeTimeProvider` in https://github.com/dotnet/extensions

**Comment by peter-csala** [comment]
I was playing a bit with your MRE and here are my observations:

1.  Changing the `_timeProvider.Advance` parameter or the number of calls: test still fails
```cs
// Option A
_timeProvider.Advance(TimeSpan.FromMilliseconds(1));

// Option B
_timeProvider.Advance(TimeSpan.FromMilliseconds(1_000_000));

// Option C
for(int i=0; i < 10; i++)
    _timeProvider.Advance(TimeSpan.FromMilliseconds(1_000));

//...

// Option Z
while(!result.IsCompleted)
    _timeProvider.Advance(TimeSpan.FromMilliseconds(1_000_000));
```

2. Rewriting your `PollyRetry` to use C# built-in features:  test still fails
```cs
public async Task<int> RetryWithoutPolly(double delaySeconds, double cancellationSeconds)
{
    CancellationTokenSource cts = new(TimeSpan.FromSeconds(cancellationSeconds), timeProvider);

    var callback = async () => {
        attempts++;
        await Task.Delay(TimeSpan.FromSeconds(delaySeconds), timeProvider, cts.Token);
        if (attempts < 2)
        {
            throw new InvalidOperationException();
        }
    };

    attempts = 0;
    for(int attempt = 0; attempt < 3; attempt++) //MaxRetryAttempts
    {
        try
        {
            await callback();
        }
        catch(InvalidOperationException) // ShouldHandle
        {
            // Trigger retry and sleep before new attempt
            await Task.Delay(TimeSpan.FromSeconds(attempts), cts.Token); //Delay with Linear backoff
        }
    }

    return attempts;
}
```
3. Rewriting the previous sample code to do not utilize`CancellationTokenSource`:  test still fails
```cs
public async Task<int> RetryWithoutPolly(double delaySeconds)
{
    var callback = async () => {
        attempts++;
        await Task.Delay(TimeSpan.FromSeconds(delaySeconds), timeProvider, CancellationToken.None);
        if (attempts < 2)
        {
            throw new InvalidOperationException();
        }
    };

    attempts = 0;
    for(int attempt = 0; attempt < 3; attempt++) //MaxRetryAttempts
    {
        try
        {
            await callback();
        }
        catch(InvalidOperationException) // ShouldHandle
        {
            // Trigger retry and sleep before new attempt
            await Task.Delay(TimeSpan.FromSeconds(attempts)); //Delay with Linear backoff
        }
    }

    return attempts;
}
```

So, I think this bug is not related to Polly.

**Comment by martintmk** [comment]
Thanks @peter-csala for confirming. I think we should close this in favor of https://github.com/dotnet/extensions/issues/4912

**Comment by rcollette** [comment]
@martintmk @martincostello @peter-csala - Would be helpful to thumb up https://github.com/dotnet/extensions/issues/4912, so that someone doesn't come along and create a duplicate of this issue here since it won't be as visible in the closed state.

The sooner that is resolved the better for all.
