### ISSUE TITLE
[Feature request]: Integrate / add support for Lunar Proxy (backend resilience strategy)

### ISSUE THREAD

**Issue by kaplanlior** [App-vNext/Polly#1949]
### Is your feature request related to a specific problem? Or an existing feature?

Using Polly is a great solution. In some cases, we'd like to keep the option to adapt / change the resilience strategy or its parameters (e.g. number of retries, timeouts) on the fly. That could be for debugging purposes or in need to react to an external event. With Polly, these changes require a code update, build cycle, and a deployment of the binaries.

### Describe the solution you'd like

We'd like to suggest an integration from Polly to Lunar Proxy in order to allow the developer to delegate some decisions to Lunar or to allow Lunar to add on top of the resilience  measures defined by Polly - e.g. changing the fallback values without code redeployment.

This can be done with Lunar, an API egress proxy - https://github.com/TheLunarCompany/lunar (an Open Source project under MIT license)

### Additional context

We saw a case where a similar change was required for multiple uses / deployments of code that used Polly. We'd like to allow the developer to plan (in advance) cases / API calls which leave more flexibility instead of coding the strategy & its parameters.

**Comment by martincostello** [comment]
Which version of Polly are you using?

Version 8.x.x of Polly, via Polly.Core, uses configuration objects and can reload itself when configuration sources change, allowing configuration to be dynamically changed at runtime without changing the code (assuming you bind it to configuration in the first place).

**Comment by kaplanlior** [comment]
Thank Martin for the ultra quick response. 

I didn't find it in the documentation / migration info.
Only https://www.pollydocs.org/migration-v8.html#configuring-strategies-in-v8 while the change log mentions "Options-based configuration"

**Comment by martincostello** [comment]
The documentation for reloads is here: [_Dynamic reloads_](https://www.pollydocs.org/pipelines/resilience-pipeline-registry.html?q=reload#dynamic-reloads)

You can see some usage of it in this sandbox application I have:

- [Configuring reloading](https://github.com/martincostello/polly-sandbox/blob/31cec1bf243eb59d63e7e749543a3f98a9069ed4/src/PollySandbox/Extensions/ResilienceExtensions.cs#L56)
- [Test that validates behaviour when configuration changed](https://github.com/martincostello/polly-sandbox/blob/31cec1bf243eb59d63e7e749543a3f98a9069ed4/tests/PollySandbox.Tests/IntegrationTests.cs#L127-L153)
