### ISSUE TITLE
[Question]: Combine WaitAndRetry with WaitAndRetryForever

### ISSUE THREAD

**Issue by bfany365** [App-vNext/Polly#1980]
### What are you wanting to achieve?

I want to retry to handle an Exception for at most one minute with ExponentialBackoff then after that one minute, retry forever with x minute delay. 

I used the wrap policy, but only the "forever" policy runs. 

### What code or approach do you have so far?

`  var retryPolicy = Policy
      .Handle<Exception>()
      .WaitAndRetry(
          retryCount: 5, 
          sleepDurationProvider: retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)),
          onRetry: (exception, retryCount, context) => {
              Console.WriteLine($"Retrying ({retryCount} of 5) after exception: {exception.Message}");
          })
      ;

  // Add an indefinite retry with fixed delay (starting at 5 minutes)
  var indefiniteRetryPolicy = Policy
      .Handle<Exception>() // Retry on any exception (customize as needed)
      .WaitAndRetryForever(retryAttempt => TimeSpan.FromMinutes(1), onRetry: (exception, retryCount, context) => {
          Console.WriteLine($"Retrying for ever");
      });

  // Combine both policies
  return Policy.Wrap(retryPolicy, indefiniteRetryPolicy);`

**Comment by peter-csala** [comment]
Could you please elaborate on this part:
> I want to retry to handle an Exception for at most one minute with ExponentialBackoff

What does `one minute` mean in this scenario?
- The overall execution (including the original attempt, the retries and the penalties)
- The exponential back-off's calculated delay reaches/crosses the 1 minute threshold
- or something else?

**Comment by bfany365** [comment]
I would like to retry 5 times, and if it reaches one minute after retries, run the second policy for ever, with delay of one minute.

I could find a solution using only WaitAndRetryForever reading https://stackoverflow.com/a/66176256. 

However I wonder why it is not possible with wrap policy.

**Comment by peter-csala** [comment]
If you combine two retry policies then the following happens:
1. You exhaust the retry attempts of your inner policy
2. Inner could not handle it, so the handling bubbles up to the outer
3. Outer policy's next retry attempt kicks in and the inner policy **resets** itself

So, if you setup your policies like this:
```cs
var retryPolicy = Policy
    .Handle<Exception>()
    .WaitAndRetry(
        retryCount: 5,
        sleepDurationProvider: retryAttempt => TimeSpan.FromMilliseconds(Math.Pow(2, retryAttempt)),
        onRetry: (exception, retryCount, context) => {
    	    Console.WriteLine($"Retrying ({retryCount} of 5) after exception: {exception.Message}");
    });

var indefiniteRetryPolicy = Policy
    .Handle<Exception>()
    .WaitAndRetryForever(
        retryAttempt => TimeSpan.FromSeconds(1), 
        onRetry: (exception, retryCount, context) => {
            Console.WriteLine($"Retrying for ever");
    });

var combinedPolicy = Policy.Wrap(indefiniteRetryPolicy, retryPolicy);
combinedPolicy.Execute(() => throw new Exception());
```

then the output will be something similar:
```none

Retrying (00:00:00.0020000 of 5) after exception: Exception of type 'System.Exception' was thrown.
Retrying (00:00:00.0040000 of 5) after exception: Exception of type 'System.Exception' was thrown.
Retrying (00:00:00.0080000 of 5) after exception: Exception of type 'System.Exception' was thrown.
Retrying (00:00:00.0160000 of 5) after exception: Exception of type 'System.Exception' was thrown.
Retrying (00:00:00.0320000 of 5) after exception: Exception of type 'System.Exception' was thrown.
Retrying for ever
Retrying (00:00:00.0020000 of 5) after exception: Exception of type 'System.Exception' was thrown.
Retrying (00:00:00.0040000 of 5) after exception: Exception of type 'System.Exception' was thrown.
Retrying (00:00:00.0080000 of 5) after exception: Exception of type 'System.Exception' was thrown.
Retrying (00:00:00.0160000 of 5) after exception: Exception of type 'System.Exception' was thrown.
Retrying (00:00:00.0320000 of 5) after exception: Exception of type 'System.Exception' was thrown.
Retrying for ever
...
```

If you switch the wrapping order like this 
```
var combinedPolicy = Policy.Wrap(retryPolicy, indefiniteRetryPolicy);
```

then the output will be something similar:
```none
Retrying for ever
Retrying for ever
Retrying for ever
Retrying for ever
...
```
____

So, my suggested solution on StackOverflow did not use two policies for the above demonstrated reasons. The proposed solution is a workaround to deal with a limitation of V7 API. 

In case of V8 you can simply use the `MaxDelay` property to cap the calculated delays and retry forever. For further information please check this [related documentation page](https://www.pollydocs.org/strategies/retry.html#defaults).

**Comment by bfany365** [comment]
Thanks @peter-csala , I am using V6 and here is my solution: 

`public static IEnumerator<TimeSpan> ExponentialBackOff(TimeSpan initialDelay, int retryCount, double factor = 2.0, bool fastFirst = false) {
            if (initialDelay < TimeSpan.Zero) throw new ArgumentOutOfRangeException(nameof(initialDelay), initialDelay, "should be >= 0ms");
            if (retryCount < 0) throw new ArgumentOutOfRangeException(nameof(retryCount), retryCount, "should be >= 0");
            if (factor < 1.0) throw new ArgumentOutOfRangeException(nameof(factor), factor, "should be >= 1.0");

            if (retryCount == 0)
                yield break;

            int i = 0;
            if (fastFirst) {
                i++;
                yield return TimeSpan.Zero;
            }

            double ms = initialDelay.TotalMilliseconds;
            for (; i < retryCount; i++, ms *= factor) {
                yield return TimeSpan.FromMilliseconds(ms);
            }
        }

        public static IEnumerator<TimeSpan> MaxedAt(this IEnumerator<TimeSpan> backOff, TimeSpan maxDelay) {
            TimeSpan result;

            // Assumes increasing values
            while ((result = backOff.Next()) < maxDelay) {
                yield return result;
            }

            yield return maxDelay;
        }`

Then I call it like this: 

` var delays = BackOff.ExponentialBackOff(RetryToConnectDelay, 
                retryCount: MaxRetryToConnectAttempts, factor: ExponentialFactor).MaxedAt(ForeverRetryIntervalDuration);

            var retryPolicy = Policy
                .Handle<Exception>()
               .WaitAndRetryForever(
                    (retry, context) => delays.Next(), onRetry: (exception, retry, timeSpan, ctx) => {
                        // log
                    });`

**Comment by peter-csala** [comment]
As far as I understand your code you just did the same thing, added the capping logic into the delay generation.

Do you have any further question or can we close this issue?

**Comment by bfany365** [comment]
@peter-csala 
Thanks it helped and we can close the issue.
