### ISSUE TITLE
Failover rather than circuit-breaker

### ISSUE THREAD

**Issue by aliostad** [App-vNext/Polly#199]
Hi,

Thanks for a great library.
I have a need for my code to fail-over to secondary source rather than circuit-break, when failures happen (and then if that fails, to the tertiary source, etc). So the conditions for triggering similar to circuit-breaker but actions different. I guess I could implement this as a chain of circuit-breakers but I would like to know if you already have covered this scenario.

Thanks
Ali

**Comment by reisenberger** [comment]
Hi @aliostad, we implemented exactly this pattern in the microservices architecture where I currently work. 

A simple approach is use the **onBreak delegate** of CircuitBreaker to cycle through a list of available sources, eg

```
int sourceToUse = 0; 
CircuitBreakerPolicy breaker = Policy
    .Handle<Whatever>( ... )
    .CircuitBreaker( // or AdvancedCircuitBreaker
        exceptionsAllowedBeforeBreaking: /* whatever */,
            durationOfBreak: /* whatever. See note below about TimeSpan.Zero */, 
            onBreak: (e, i) => { sourceToUse = (sourceToUse + 1) % numberOfSourcesAvailable; /* or whatever, to make next call address the next available source */ }
        );
```    

(very simple example - can all be sync or async; more sophisticated approaches for selecting the initial or next source, whatever)

At the call-site wrap `breaker.Execute(/* execute using sourceToUse */)` in your own `while` loop or Polly retry policy.

You said failover _rather than_ circuit-break?  If you don't want the circuit actually to break, just set  `durationOfBreak` to `Timespan.Zero`: `onBreak` will still fire, but the next caller will find the circuit closed still.

Alternatives:

+ Wrap the circuit-breaker in a `Policy.Handle<BrokenCircuitException>().Retry(/* whatever retry policy you want */)`, configure the `onRetry` delegate of the retry policy to cycle the sources, similar to `onBreak` above.
+ Use [Fallback policy](https://github.com/App-vNext/Polly/wiki/Fallback) or a chain of fallback policies.  Fallback's usual purpose is to provide a substitute response for a failed operation, but can also be used to provide an alternative failover execution.  

`FallbackPolicy` (in this context) probably more appropriate for folks with a simple 1->2 primary->secondary failover, or known-length chain of failovers.   

The `onBreak`/`onRetry` approach cycling through a list of sources otoh can also scale if you're adding/removing sources from the mix dynamically, eg horizontal-scaling for load, which is nice.

Let us know if that gets you going, or if we can help more!  Thanks

**Comment by aliostad** [comment]
Thank you for detailed response 👍 

This can cover my scenario so would be using it :)
