### ISSUE TITLE
[Feature request]: No explicit timeout in new regex functionality 

### ISSUE THREAD

**Issue by mokarchi** [App-vNext/Polly#1995]
### Is your feature request related to a specific problem? Or an existing feature?

[Regex - Deny of Service (ReDoS)](https://www.meziantou.net/regex-deny-of-service-redos.htm)

### Describe the solution you'd like

Is there any plan to support specifying a MatchTimeout property to ensure that we do not have to face any regex DOS attacks?

**Comment by martincostello** [comment]
Could you point to where this would be relevant in our code?
