### ISSUE TITLE
[Question]: Request services from `AddTransientHttpErrorPolicy`

### ISSUE THREAD

**Issue by alexrosenfeld10** [App-vNext/Polly#1998]
### What are you wanting to achieve?

This is possible:
```csharp
    .AddPolicyHandler((provider, message) =>
    {
           var logger = provider.GetRequiredService<ILogger>();
```

but I can't seem to find an equivalent here:
```csharp
    .AddTransientHttpErrorPolicy(policyBuilder => policyBuilder
... snip ...
        ,
        onRetry: (outcome, timespan, retryAttempt, context) =>
```

Am I missing something? Or is this a gap?

### What code or approach do you have so far?

See above for code

**Comment by martincostello** [comment]
This is a question for the ASP.NET Core team -the `AddTransientHttpErrorPolicy()` method lives in the [Microsoft.Extensions.Http.Polly](https://www.nuget.org/packages/Microsoft.Extensions.Http.Polly) NuGet package which is part of the ASP.NET Core repository: [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/blob/099bc84939fec64e803ec173dac6aa8ceb46a8cc/src/HttpClientFactory/Polly/src/DependencyInjection/PollyHttpClientBuilderExtensions.cs#L215).

I'm not sure how much appetite they would have for adding a new method overload though, as that package is superseded by the [new resilience libraries](https://learn.microsoft.com/dotnet/core/resilience/http-resilience?tabs=dotnet-cli) which are built on top of the new Polly v8 API and come from the [dotnet/extensions](https://github.com/dotnet/extensions) repository.

**Comment by alexrosenfeld10** [comment]
Got it - I've moved over to those new libs, they're very nice. That said, they are missing some features as well, like getting access to the request message / request method.

Still very nice improvement though. I'll close this out.
