### ISSUE TITLE
Expose success/fail/call count states for policies

### ISSUE THREAD

**Issue by lakario** [App-vNext/Polly#201]
There doesn't seem to be a way to get an overall number of calls, failures and successes on a given policy. Reviewing the code, it looks like it's up to the individual policy's implementation to track any counts which it may need for it's own logic (like the AdvancedCircuitController's IHealthMetrics). Is this data not tracked because of some technical challenge, or is it just not needed by the framework?

I'd like to use Polly in conjunction with a dashboard which displays overall health data (like the Netflix example), but needing to add an additional layer around Polly for tracking call counts is less than ideal.

**Comment by reisenberger** [comment]
For those wanting to follow this, further discussion on metrics in Polly is evolving [on our slack channel](https://pollytalk.slack.com/archives/general/p1483982717000052) .

(We will also cross-post back to Github, when there are substantive proposals to discuss)

Also, the Polly roadmap sets out the [initial envisaged architecture for metrics in Polly](https://github.com/App-vNext/Polly/wiki/Polly-Roadmap#emit-events-andor-statistics), along with some [related discussion against a previous PR](https://github.com/App-vNext/Polly/pull/149#issuecomment-245125723)

**Comment by reisenberger** [comment]
Pulled out a fresh issue, #326, to bring this to the top of the visibility pile.

**Comment by reisenberger** [comment]
Closing as now covered by #326
