### ISSUE TITLE
[Feature request]: StrategyHelper, DisposeHelper, TimeProviderExtensions, TaskHelper should be public not internal

### ISSUE THREAD

**Issue by mhsimkin** [App-vNext/Polly#2039]
### Is your feature request related to a specific problem? Or an existing feature?

If you need to add a new strategy and want to use StrategyHelper.ExecuteCallbackSafeAsync, DisposeHelper.TryDisposeSafeAsync, TimeProviderExtensions::DelayAsync, TaskHelper::GetResult you can't as they are marked internal.

### Describe the solution you'd like

StrategyHelper, DisposeHelper, TimeProviderExtensions should be made public.

### Additional context

Referencing [this ](https://github.com/App-vNext/Polly/discussions/2022)discussion with @peter-csala. After taking the provided code and building a simple test application I determined that the functionality provided by chaining strategies didn't work the way I needed.

I decided to build my own strategy, using the [RetryResilienceStrategy<T>](https://github.com/App-vNext/Polly/blob/main/src/Polly.Core/Retry/RetryResilienceStrategy.cs) as a starting point.  Unfortunately, the three (3) classes indicated above are marked as internal, therefore I had to create my own implementation.

I should be able to use these classes in my strategy to minimize my introduction in bugs and to allow the Polly team to resolve any issues that might requite these methods in the indicated classes to be updated.

**Comment by martincostello** [comment]
We can consider making it easier for people to extend things, but it's unlikely we'd expose these types as-is.

**Comment by peter-csala** [comment]
> I determined that the functionality provided by chaining strategies didn't work the way I needed.

Could you please elaborate what is missing? How do you want to implement your own custom retry strategy?

**Comment by mhsimkin** [comment]
I will add a reply to the discuss of what the issues were.

**Comment by martintmk** [comment]
I agree with @martincostello , it's unlikely that we will expose these primitives as we want to keep our API surface as thin as possible. Most of these are quite simple, so copy & paste is your friend.

**Comment by peter-csala** [comment]
@mhsimkin Hi Márc, as you have indicated in the discussion the proposed solution worked for you. Can you please close this issue because as far as I can tell your feature request is not necessary anymore.

I'm planning to add the code to the `samples` and document it under the `extensibility` section next week.

**Comment by mhsimkin** [comment]
This is no longer needed as @peter-csala and I have come up with a working solution.  Please see [this discussion](https://github.com/App-vNext/Polly/discussions/2022) for the details.
