### ISSUE TITLE
[Question]: How to use ExecuteAsync In VB.Net?

### ISSUE THREAD

**Issue by ricfwolff** [App-vNext/Polly#2045]
### What are you wanting to achieve?

Sorry to bring VB.Net... But some of us still need to work with it. :)

I'm trying to add Polly v8 to a vb.net project, but I'm facing a compiler error when I try to use the ExecuteAsync method:

<img width="754" alt="image" src="https://github.com/App-vNext/Polly/assets/9446182/ba43734e-47e1-4a1f-913a-989e3f66f657">

I noticed the ExecuteAsync method returns "ValueTask" instead of "Task". And it looks like that might be the problem...

### What code or approach do you have so far?

I also noticed that I can exchange ExecuteAsync for Execute and the compiler will stop complaining about it, but there's another post here on your GitHub explaining that we shouldn't do it, and anyway I tried and my RetryStrategy does not work. :(

Could someone please point me to what I'm doing wrong?

Thank you!

**Comment by ricfwolff** [comment]
It does not work :(
Because it's expecting the _callback_ to be of ValueTask:

<img width="548" alt="image" src="https://github.com/App-vNext/Polly/assets/9446182/46afa94d-7041-4dd6-8d91-03262d930857">


But I cannot modify the callback because it'll throw compiler errors as well.
I'm not sure what's wrong here... 

Maybe a question for StackOverflow instead.

**Comment by ricfwolff** [comment]
Good idea, I'll try that out and let you know. Thanks!

**Comment by martincostello** [comment]
I just tried this out locally and it seems to work:

```vb
Imports System.Threading
Imports Polly

Module Program
    Sub Main()
        Demo().Wait()
    End Sub

    Async Function Demo() As Task
        ' The ResiliencePipelineBuilder creates a ResiliencePipeline
        ' that can be executed synchronously or asynchronously
        ' and for both void and result-returning user-callbacks.
        Dim pipeline = New ResiliencePipelineBuilder().AddTimeout(TimeSpan.FromSeconds(5)).Build()

        ' Synchronously
        pipeline.Execute(Sub()
                             ' Do something synchronously
                         End Sub)

        Await pipeline.ExecuteAsync(Function(token)
                                        Return New ValueTask(MyAsyncCallback(token))
                                    End Function, CancellationToken.None).AsTask()
    End Function

    Function ExecuteAsync(pipeline As ResiliencePipeline, callback As Func(Of CancellationToken, ValueTask), cancellationToken As CancellationToken) As Task
        Return pipeline.ExecuteAsync(callback, cancellationToken).AsTask()
    End Function

    Async Function MyAsyncCallback(token As CancellationToken) As Task
        Console.WriteLine("Waiting for 1 second")
        Await Task.Delay(1000, token)
    End Function
End Module
```

**Comment by ricfwolff** [comment]
I was able to make it work using the idea you gave me (code below for future vb.net sad fellows).
But, in my situation, I'll have to write too much code for what I'm trying to attempt (which is just retry up to 5 times when connection in the pool is lost). So I'll make my own simpler method to handle it, only because I was using only 1% of Polly's feature. It's not Polly's fault, it's my bad legacy code. :)

Thank you!

```vb.net
    Protected Async Function GetDataFromDBToDataTableAsync(sql As String, Optional param As OracleParameter() = Nothing) As Task(Of DataTable)
        Dim callback As Func(Of CancellationToken, ValueTask(Of DataTable)) =
            Function(token)
                Return New ValueTask(Of DataTable)(ThingFunction(sql, param))
            End Function

        Dim returnData = Await RetryStrategy.ExecuteAsync(callback)

        Return returnData
    End Function

    Async Function ThingFunction(sql As String, Optional param As OracleParameter() = Nothing) As Task(Of DataTable)
        Dim result As New DataTable

        Using conn = New OracleConnection(L3ConnectionString)
            Using sqlCommand = New OracleCommand(sql, conn)
                sqlCommand.CommandTimeout = 600
                sqlCommand.BindByName = True

                If (param IsNot Nothing AndAlso param.Length > 0) Then
                    sqlCommand.Parameters.AddRange(param)
                End If

                Using dataAdapter As New OracleDataAdapter(sqlCommand)
                    Await Task.Run(Sub() dataAdapter.Fill(result))
                End Using
            End Using

            conn.Close()
        End Using
        Return result
    End Function

```

**Comment by ricfwolff** [comment]
Thank you! 

Yes, it works. But VB asks for too much code. 

Thank you anyway! I hope to migrate this code to C# soon. :)

**Comment by martincostello** [comment]
Thanks for asking the question - I wasn't aware that `ValueTask` is difficult to use in VB.NET (and F#!) compared to C#.

I've created #2046 to extend our documentation for future consumers using those languages.
