### ISSUE TITLE
[Question]: How to respect 429 errors and Retry-After headers in Polly v8?

### ISSUE THREAD

**Issue by dylanmccurry-msft** [App-vNext/Polly#2047]
### What are you wanting to achieve?

How do you properly configure Polly to respect 429 status codes with a Retry-After header? I've checked what examples I can find and read through the documentation, but I can't seem to get it working.

I am using a dotnet core 8 project with Polly 8.2.1.

### What code or approach do you have so far?

Within my startup, I have something like this:

```
// moved here for brevity
private static IAsyncPolicy<HttpResponseMessage> GetRetryPolicy()
{
    return HttpPolicyExtensions
        .HandleTransientHttpError()
        .OrResult(response => response.StatusCode == HttpStatusCode.TooManyRequests &&
                              response.Headers.RetryAfter is not null)
        .WaitAndRetryAsync(
            retryCount: 3,
            sleepDurationProvider: (retryCount, response, context) =>
            {
                Console.WriteLine("sleepDurationProvider...");
                return response.Result.Headers.RetryAfter.Delta.Value; // TimeSpan.FromMilliseconds(waitDuration); 
            },
            onRetryAsync: (response, timespan, retryCount, context) =>
            {
                Console.WriteLine("OnRetryAsync...");
                return Task.CompletedTask;
            });
}


// register services, etc
serviceCollection.AddHttpClient("Retry").AddPolicyHandler(policyBuilder => GetRetryPolicy());
```

I am then trying to use the client to invoke requests. I have mocked up a server that responds with 429 and Retry-After set to a value of 10 (10 seconds). Here's a sample of how I am invoking the request from an example class:

```
public class Example : IExample
{
    private readonly IHttpClientFactory _httpClientFactory;

    public Example(IHttpClientFactory httpClientFactory)
    {
        _httpClientFactory = httpClientFactory;
    }

    public async Task<T?> SendAsync<T>(HttpRequestMessage request)
    {
        using var client = _httpClientFactory.CreateClient("Retry");
        var req = new HttpRequestMessage(HttpMethod.Post, "localhost:8000/some/test/endpoint")
        {
            Content = ... // content to post
        };
        using var response = await client.SendAsync(req);
        
        if (!response.IsSuccessStatusCode)
        {
            throw new Exception("An error occurred communicating with the endpoint.");
        }
        
        // process the result and return data
    }
}
```

### Additional context

From what I can tell, the policy is not executed. Only one request makes it to my test server and then dotnet proceeds to execute, which throws an exception due to a non-successful status code.

**Comment by dylanmccurry-msft** [comment]
I'm realizing my solution has a mix of Polly v7 and Polly v8 in it. Seems that HttpPolicyExtensions is a v7 thing. Is there an equivalent way of doing this in v8?

**Comment by dylanmccurry-msft** [comment]
Thanks Martin, can you confirm if that Resilience extension package aligns with the samples I am seeing here? https://github.com/App-vNext/Polly/blob/main/samples/Retries/Program.cs

**Comment by martincostello** [comment]
Our samples are simpler than the Microsoft resilience extensions, but the underlying implementation should be broadly similar.

**Comment by peter-csala** [comment]
The new Microsoft resilience packages are not exposing similar functionality like what we had in case of V7 like `HandleTransientHttpErrors`.

Just a few days ago a similar question was raised on StackOverflow: https://stackoverflow.com/questions/78254528/whats-alternative-of-httppolicyextensions-handletransienthttperror-in-new-polly.

It is quite straightforward to implement the same in V8

```cs
var options = new RetryStrategyOptions<HttpResponseMessage>
{
    ShouldHandle = static args => args.Outcome switch
    {
        { Exception: HttpRequestException } => PredicateResult.True(),
        { Result.StatusCode: HttpStatusCode.RequestTimeout} => PredicateResult.True(),
        { Result.StatusCode: >= HttpStatusCode.InternalServerError } => PredicateResult.True(),
        _ => PredicateResult.False()
    }
};
```

**Comment by martincostello** [comment]
What I was getting was more to just use `AddStandardResilienceHandler()` and automatically integrate it with `HttpClient`, rather than manually configure the strategies.

**Comment by dylanmccurry-msft** [comment]
Here is the solution which I've come up with:

```
    public static IHttpResiliencePipelineBuilder AddRetryResiliencePipeline(this IHttpClientBuilder clientBuilder)
    {
        return clientBuilder.AddResilienceHandler("Retry",
            static builder =>
            {
                // See: https://www.pollydocs.org/strategies/retry.html
                builder.AddRetry(new HttpRetryStrategyOptions
                {
                    // Customize and configure the retry logic.
                    BackoffType = DelayBackoffType.Exponential,
                    MaxRetryAttempts = 6,
                    UseJitter = true,
                    Delay = TimeSpan.FromSeconds(5), // wait 5 seconds and try again by default
                    ShouldHandle = static args =>
                    {
                        // any non-successful status code, go ahead and run again. Maybe this can be improved?
                        return ValueTask.FromResult(!args.Outcome.Result.IsSuccessStatusCode);
                    },
                    DelayGenerator = args =>
                    {
                        // if we have a result, and it has a Retry-After header, use that
                        if (args.Outcome.Result is not null && args.Outcome.Result.Headers.RetryAfter is not null)
                        {
                            var delta = args.Outcome.Result?.Headers?.RetryAfter?.Delta.Value;
                            if (delta != null) // the delta is the amount of time we need to wait
                            {
                                return new ValueTask<TimeSpan?>(delta);
                            }
                        }

                        // Return delay hinted by the retry strategy if we fall through to this point
                        return new ValueTask<TimeSpan?>(default(TimeSpan?));
                    }
                });
            });
    }
```

And you use it like so:

```
builder.services.AddHttpClient<ISomeService, SomeService>().AddRetryResiliencePipeline();
```

**Comment by peter-csala** [comment]
Your code could be optimized like this
```cs
new HttpRetryStrategyOptions
{
    ShouldHandle = static args => args.Outcome switch
    {
        { Result: HttpResponseMessage res } when !res.IsSuccessStatusCode => PredicateResult.True(),
        _ => PredicateResult.False()
    },
    DelayGenerator = static args => new ValueTask<TimeSpan?>(args.Outcome.Result.Headers.RetryAfter?.Delta),
    
    // If RetryAfter not present then use exponential backoff
    BackoffType = DelayBackoffType.Exponential,
    MaxRetryAttempts = 6,
    UseJitter = true,
    Delay = TimeSpan.FromSeconds(5)
}
```
- Using a swtich expression for the `ShouldHandle` is performant and easier extensible than a `ValueTask.FromResult`
- All the branching inside the `DelayGenerator` is unnecessary. You can be sure that you have an `HttpResponseMessage` via the `args.Outcome.Result` because otherwise the `ShouldHandle` won't return true
- This solution depends on an [implementation detail](https://www.pollydocs.org/strategies/retry.html#calculation-of-the-next-delay). If the `DelayGenerator` returns `null` or negative `TimeSpan` then it will use the other properties to generate the new delay.

https://github.com/App-vNext/Polly/blob/4051e2aebe20f4823224a1ca11b517143c874546/src/Polly.Core/Retry/RetryResilienceStrategy.cs#L72

https://github.com/App-vNext/Polly/blob/4051e2aebe20f4823224a1ca11b517143c874546/src/Polly.Core/Retry/RetryHelper.cs#L9

That means it might happen that with a minor version change your retry logic won't fallback to exponential backoff if the `RetryAfter` is not present.

**Comment by martincostello** [comment]
> Unfortunately it appears that the default resiliency handlers from Microsoft do not respect the Retry-After header, at least from what I can tell

@martintmk I thought this was built-in - have I misunderstood all this time?

**Comment by peter-csala** [comment]
> > Unfortunately it appears that the default resiliency handlers from Microsoft do not respect the Retry-After header, at least from what I can tell
> 
> @martintmk I thought this was built-in - have I misunderstood all this time?

https://github.com/dotnet/extensions/blob/5fc05f874f74374749b01e284321168c7b92476a/src/Libraries/Microsoft.Extensions.Http.Resilience/Polly/HttpRetryStrategyOptions.cs#L57

```cs
/// <summary>
/// Gets or sets a value indicating whether to use the <c>Retry-After</c> header for the retry delays.
/// </summary>
/// <value>
/// Defaults to <see langword="true"/>.
/// </value>
/// <remarks>
/// If the property is set to <see langword="true"/> then the generator will resolve the delay
/// based on the <c>Retry-After</c> header rules, otherwise it will return <see langword="null"/> and the retry strategy
/// delay will generate the delay based on the configured options.
/// </remarks>
public bool ShouldRetryAfterHeader
{
    get => _shouldRetryAfterHeader;
    set
    {
        _shouldRetryAfterHeader = value;

        if (_shouldRetryAfterHeader)
        {
            DelayGenerator = args => args.Outcome.Result switch
            {
                HttpResponseMessage response when RetryAfterHelper.TryParse(response, TimeProvider.System, out var retryAfter) => new ValueTask<TimeSpan?>(retryAfter),
                _ => new ValueTask<TimeSpan?>((TimeSpan?)null)
            };
        }
        else
        {
            DelayGenerator = null;
        }
    }
}
```

**Comment by martintmk** [comment]
Hey folks, just couple of my comments since I worked on this directly and supporting the `Retry-After` header was in our minds from the beginning. 

Essentially, the `Polly.Core` supports this scenario by exposing the `DelayGenerator`. The generator can decide to override the delay provided by the Polly or just do no-op by returning `null`. By default,  `DelayGenerator` is null.

For HTTP scenarios, `Microsoft.Extensions.Http.Resilience` exposes `HttpRetryStrategyOptions` where the `DelayGenerator` is initialized by default and handles `Retry-After` header. You even have a property to toggle this behavior on and off:

https://github.com/dotnet/extensions/blob/5fc05f874f74374749b01e284321168c7b92476a/src/Libraries/Microsoft.Extensions.Http.Resilience/Polly/HttpRetryStrategyOptions.cs#L46

@peter-csala 
> The new Microsoft resilience packages are not exposing similar functionality like what we had in case of V7 like HandleTransientHttpErrors.

Actually, we have something very similar:
https://github.com/dotnet/extensions/blob/5fc05f874f74374749b01e284321168c7b92476a/src/Libraries/Microsoft.Extensions.Http.Resilience/Polly/HttpClientResiliencePredicates.cs#L22

This can be used in scenarios where you want to enhance the default handling in `ShouldHandle` predicate:

``` csharp
new HttpRetryStrategyOptions
{

    ShouldHandle = args => args.Outcome switch
    {
        // Reuse the is transient handling
        { } outcome when HttpClientResiliencePredicates.IsTransient(outcome) => PredicateResult.True(),
        // Add more custom handling
        { Exception: InvalidOperationException } => PredicateResult.True(),
        { Result: { StatusCode: System.Net.HttpStatusCode.NotFound } } => PredicateResult.True(),
        _ => PredicateResult.False()
    },
    // Disable the default handling of Retry-After header
    ShouldRetryAfterHeader = false
};
```

**Comment by dylanmccurry-msft** [comment]
Thanks for the context.  So after applying some refactoring, this is what I've come up with:

```
clientBuilder.AddResilienceHandler("Retry",
            static builder =>
            {
                // See: https://github.com/App-vNext/Polly/issues/2047
                // See: https://www.pollydocs.org/strategies/retry.html
                builder.AddRetry(new HttpRetryStrategyOptions
                {
                    ShouldHandle = static args => args.Outcome switch
                    {
                        { Result: { IsSuccessStatusCode: false } } => PredicateResult.True(),
                        _ => PredicateResult.False()
                    },
                    // check if a Retry-After header is present, and respect it
                    ShouldRetryAfterHeader = true,
    
                    // If RetryAfter not present then use exponential backoff
                    BackoffType = DelayBackoffType.Exponential,
                    MaxRetryAttempts = 6,
                    UseJitter = true,
                    Delay = TimeSpan.FromSeconds(5)
                });
            });
```

However- I am wondering if this is just redundant with some default policies now?

**Comment by martintmk** [comment]
> Thanks for the context. So after applying some refactoring, this is what I've come up with:
> 
> ```cs
> clientBuilder.AddResilienceHandler("Retry", static builder =>
> {
>     // See: https://github.com/App-vNext/Polly/issues/2047
>     // See: https://www.pollydocs.org/strategies/retry.html
>     builder.AddRetry(new HttpRetryStrategyOptions
>     {
>         ShouldHandle = static args => args.Outcome switch
>         {
>             { Result: { IsSuccessStatusCode: false } } => PredicateResult.True(),
>             _ => PredicateResult.False()
>         },
>         // check if a Retry-After header is present, and respect it
>         ShouldRetryAfterHeader = true,
> 
>         // If RetryAfter not present then use exponential backoff
>         BackoffType = DelayBackoffType.Exponential,
>         MaxRetryAttempts = 6,
>         UseJitter = true,
>         Delay = TimeSpan.FromSeconds(5)
>     });
> });
> ```
> 
> However- I am wondering if this is just redundant with some default policies now?

You can omit the following properties since these are already default for `HttpRetryStrategyOptions`:

- BackoffType
- UseJitter
- ShouldRetryAfterHeader

**Comment by martintmk** [comment]
Closing as the question has been answered.
