### ISSUE TITLE
Deprecate all packages which are no longer maintained

### ISSUE THREAD

**Issue by thompson-tomo** [App-vNext/Polly#2058]
**Is your feature request related to a problem? Please describe.**
It is not clear on nuget which packages are not being maintained.

**Describe the solution you'd like**
I would like to see that all the no longer maintained packages are marked as deprecated on nuget.org with a note informing users of the packages they should be using.

**review of packages**
- Polly-Signed
- Polly.Extensions.Http
- Polly.Extensions.Http-Signed
- Polly.Net40Async
- Polly.Net40Async-Signed

**Describe alternatives you've considered**
Just accept it

**Additional context**

https://learn.microsoft.com/en-us/nuget/nuget-org/deprecate-packages?darkschemeovr=1

**Comment by martincostello** [comment]
Could you elaborate on which packages you _think_ are no longer maintained, because all the packages published from this repository are.

**Comment by thompson-tomo** [comment]
@martincostello Have just filled in the list of 5 packages, 2 of which are for an archived project so can't create an issue in that project.

**Comment by martincostello** [comment]
Thanks for the list.

@joelhulen, can you mark those as deprecated in NuGet.org?

**Comment by joelhulen** [comment]
@martincostello will do.

**Comment by joelhulen** [comment]
All 5 packages are now marked as deprecated. Thank you for bringing this to our attention!
