### ISSUE TITLE
`LastException` property on CircuitBreaker policies should not expose 'fake' exception

### ISSUE THREAD

**Issue by reisenberger** [App-vNext/Polly#206]
The original implementation of CircuitBreaker used [this fake exception](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/CircuitBreaker/CircuitStateController.cs#L117) as a (more-visible-than-`null`) guard against the condition where the `_lastException` variable was accessed on a circuit not in the open/half-open state.  However, the sequence of state changes and locks in circuit operation should prevent this ever happening.

Now that we expose this property through [CircuitBreakerPolicy.LastException](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/CircuitBreaker/CircuitBreakerPolicy.cs#L35), this 'fake' exception is misleading.  

It would be better replaced by `null`.

**EDIT**: Thanks to @lakario for identifying this.

**Comment by reisenberger** [comment]
Marking this 'up-for-grabs'.  

Initial thoughts are that a solution would probably include: 

+ changing the ['fake exception' line](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/CircuitBreaker/CircuitStateController.cs#L117) to `_lastOutcome =  null`
+ defending against `_lastOutcome == null` as necessary elsewhere

**Comment by lakario** [comment]
Pull request submitted: #207

**Comment by lakario** [comment]
Re-reading your prompt, I see now you prefer nulling _lastOutcome rather than initializing it without an Exception. That certainly makes more sense. Updated pull request forthcoming.
