### ISSUE TITLE
Feedback on library integration with RawRabbit

### ISSUE THREAD

**Issue by pardahlman** [App-vNext/Polly#209]
Hello team - great work with this library and congrats on joining .NET Foundation 👌 !

I'm developing [RawRabbit](https://github.com/pardahlman/RawRabbit), a .NET Core client for RabbitMq. Currently, I'm working on a "plugin" that uses Polly for error handling: https://github.com/pardahlman/RawRabbit/issues/174 

I have a some experience with Polly, but not to the degree that you have. That's why I was wondering if I could get some feedback on how I'm planning to implement this. I have made a first draft, but there is probably things I haven't considered!

### Register policies
Policies are registered through a fluent builder that adds the policies to the execution context (that is passed along through-out the execution).

```csharp
var client = RawRabbitFactory.CreateSingleton(new RawRabbitOptions
{
	Plugins = p => p.UsePolly(c => c
		.UsePolicy(defaultPolicy) // fallback policy
		.UsePolicy(declareQueuePolicy, PolicyKeys.QueueBind)) // used for queue binds
});
```
A specific/custom policy can be registered by specifying a "policy key". Examples of [specific policy keys](https://github.com/pardahlman/RawRabbit/blob/2.0/src/RawRabbit.Enrichers.Polly/PolicyKeys.cs) are 

- Queue Declare
- Queue Bind
- Exchange Declare
- Handler Invokation

If no policy key is provided upon registration, the policy will be the default/fallback policy and used in scenarios where _that_ specific key isn't registered.

### Policy invocation
When calling execute on the policy, relevant `contextData` is passed, so that the retry callback can act on it. Here's an example for [queue declare](https://github.com/pardahlman/RawRabbit/blob/2.0/src/RawRabbit.Enrichers.Polly/Middleware/QueueBindMiddleware.cs#L18-L30)

```csharp
return policy.ExecuteAsync(
	action: ct => base.BindQueueAsync(queue, exchange, routingKey, context, ct),
	cancellationToken: token,
	contextData: new Dictionary<string, object>
	{
		[RetryKey.TopologyProvider] = TopologyProvider,
		[RetryKey.QueueName] = queue,
		[RetryKey.ExchangeName] = exchange,
		[RetryKey.RoutingKey] = routingKey,
		[RetryKey.PipeContext] = context,
		[RetryKey.CancellationToken] = token,
	}
);
```
For this example, I could have a retry policy that catches exceptions thrown by the underlying client and tries to declare the queue based on this

```csharp
var declareQueuePolicy = Policy
	.Handle<OperationInterruptedException>()
	.RetryAsync(async (e, retryCount, ctx) =>
	{
		customCalled = true;
		var defaultQueueCfg = ctx.GetPipeContext().GetClientConfiguration().Queue;
		var topology = ctx.GetTopologyProvider();
		var queue = new QueueDeclaration(defaultQueueCfg) { Name = ctx.GetQueueName() };
		await topology.DeclareQueueAsync(queue);
	});
```
(`ctx` is the dictionary that I've added some extension methods for convenience)

### Other ideas?
That's what I've got. Can you see any other ways for me to leverage Polly, or any other, more preferred ways to work with policies? Any feedback is much appreciated!

**Comment by reisenberger** [comment]
Thanks @pardahlman for the extensive conversation in our slack environment.  Leaving this issue open for a short time, to see if others you've alerted to it, have more to add.  Thanks

**Comment by reisenberger** [comment]
Closing due to lack of input on this channel (discussion moved to the Polly and RawRabbit slack channels)
