### ISSUE TITLE
[Bug]: README has improper grammar, which makes the meaning unclear.

### ISSUE THREAD

**Issue by digimunk** [App-vNext/Polly#2098]
### Describe the bug

"Unlike reactive strategies, proactive strategies do not focus on handling errors by the callbacks might throw or return. They can make pro-active decisions to cancel or reject the execution of callbacks."

What does "...by the callbacks might throw or return" mean?

The first sentence has "proactive," and the second has "pro-active." Please be consistent.

### Expected behavior

Good and consistent grammar

### Actual behavior

Poor and inconsistent grammar

### Steps to reproduce

View the README

**Comment by martincostello** [comment]
The first one looks like it should say "but".

Consistency is good, we must have missed that in review.

A PR to apply those changes is welcome.

**Comment by martincostello** [comment]
Also note that some of our contributors don't speak English as their native language, so things can slip in that might get overlooked during reviews.
