### ISSUE TITLE
[Question]: Polly v8 AddPolicyHandler

### ISSUE THREAD

**Issue by mateusz-jarazny** [App-vNext/Polly#2100]
### What are you wanting to achieve?

I'm trying to implement different policies based on the request URI using the same HttpClient. Previously, I managed this by using the AddPolicyHandler function and its HttpRequestMessage parameter. However, in the new API, I can't find a similar example. Is there any way to get access to the HttpRequestMessage when defining pipeline?

### What code or approach do you have so far?

```cs
.AddPolicyHandler((serviceProvider, request) =>
    request.RequestUri.PathAndQuery.StartsWith("/api/")
        ? Policy<HttpResponseMessage>.HandleResult(result => !result.IsSuccessStatusCode).WaitAndRetryAsync(3, _ => TimeSpan.FromSeconds(1))
        : HttpPolicyExtensions.HandleTransientHttpError().WaitAndRetryAsync(3, _ => TimeSpan.FromSeconds(1));
```

**Comment by peter-csala** [comment]
As far as I know the new [`AddResilienceHandler`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.resiliencehttpclientbuilderextensions.addresiliencehandler?view=net-8.0) does not support this use case.

cc: @martintmk or does it?

**Comment by martintmk** [comment]
@mateusz-jarazny 

You can do something akin to following to allow dynamically changing the pipeline:

``` csharp
var services = new ServiceCollection();

services.AddResiliencePipeline<string, HttpResponseMessage>("pipeline-a", builder =>
{
    // ...
});

services.AddResiliencePipeline<string, HttpResponseMessage>("pipeline-b", builder =>
{
    // ...
});


var builder = services
    .AddHttpClient("my-client")
    .AddHttpMessageHandler(serviceProvider =>
    {
        var pipelineProvider = serviceProvider.GetRequiredService<ResiliencePipelineProvider<string>>();

        return new ResilienceHandler(request =>
        {
            var pipelineName = ExtractPipelineName(request);

            if ( pipelineProvider.TryGetPipeline<HttpResponseMessage>(pipelineName, out var pipeline))
            {
                return pipeline;
            }

            return ResiliencePipeline<HttpResponseMessage>.Empty;
        });
    });
```

The key is to create explicit instance of `ResilienceHandler` that allows selecting the resilience pipeline manually.

cc @peter-csala

**Comment by mateusz-jarazny** [comment]
Thank you @martintmk, it worked!
Closing the issue but maybe the example with `AddHttpMessageHandler` is worth adding to the documentation.
