### ISSUE TITLE
Is there a way to execute an action AFTER a retry in Polly v8?

### ISSUE THREAD

**Issue by FutureTD** [App-vNext/Polly#2104]
### What are you wanting to achieve?

I have a question regarding the retry behavior in Polly v8. I'm currently using Polly to implement retry logic in my C# application.

By default, Polly executes the specified action before each retry attempt. However, I'm wondering if there is a way to configure Polly to execute an action after a retry attempt instead of before.

For example, let's say I have a policy that retries an operation up to 3 times. Is it possible to specify an action that should be executed after each failed retry attempt, rather than before the next retry?

I know the OnRetry is executed before each retry. Im looking for something that is similar to OnRetry but is executed after a failed retry.

I've looked through the Polly documentation but couldn't find a clear answer to this question. Any guidance or examples on how to achieve this would be greatly appreciated.

Thank you in advance for your help!

**Comment by martincostello** [comment]
We don't have a specific event for this. I think the closest would be to use `OnRetry` but ignore the first attempt.

If you have a specific concrete example of what you're trying to achieve with such an event, maybe we can give you some further guidance on how to achieve your end goal.

**Comment by peter-csala** [comment]
The `OnRetry` works in the following way:

```none
0th attempt is executed and failed
OnRetry is called with 0th attempt outcome

1st attempt is executed and failed
OnRetry is called with 1st attempt outcome

2nd attempt is executed and failed
OnRetry is called with 2nd attempt outcome

3rd attempt is executed and failed
```

Is my understanding correct that you want to have something like this?
```none
0th attempt is executed and failed

1st attempt is executed and failed
OnFailedRetry is called with 1st attempt outcome

2nd attempt is executed and failed
OnFailedRetry is called with 2nd attempt outcome

3rd attempt is executed and failed
OnFailedRetry is called with 3rd attempt outcome
```

**Comment by FutureTD** [comment]
> Is my understanding correct that you want to have something like this?
> 
> ```
> 0th attempt is executed and failed
> 
> 1st attempt is executed and failed
> OnFailedRetry is called with 1st attempt outcome
> 
> 2nd attempt is executed and failed
> OnFailedRetry is called with 2nd attempt outcome
> 
> 3rd attempt is executed and failed
> OnFailedRetry is called with 3rd attempt outcome
> ```

Correct, this is what I'm looking for. I Wish to do some logging after each retry not before each retry.

**Comment by peter-csala** [comment]
Could you please check this dotnet fiddle: https://dotnetfiddle.net/vuiN6F ?

Please note that this solution will not provide data about last retry attempt's execution time.

If this is what you are looking for then please let me know and I will explain the code.

**Comment by FutureTD** [comment]
> Could you please check this dotnet fiddle: https://dotnetfiddle.net/vuiN6F ?
> 
> Please note that this solution will not provide data about last retry attempt's execution time.
> 
> If this is what you are looking for then please let me know and I will explain the code.

Yes, that is exactly what I'm looking for.

**Comment by peter-csala** [comment]
The `OnRetry` customer delegate is [being called](https://github.com/App-vNext/Polly/blob/main/src/Polly.Core/Retry/RetryResilienceStrategy.cs#L83) after an unsuccessful attempt and before the strategy goes to sleep. This has two implications which are important from the question perspective:
1. The `OnRetry` is executed after the original attempt's failure as well
2. The `OnRetry` is not executed after the last retry attempt

The below solution tries to address these problems.

## Extend the `RetryStrategyOptions`

Let's add a new customer delegate called `OnFailedRetry`
```cs
public class CustomRetryStrategyOptions<TResult>: RetryStrategyOptions<TResult>
{
    public Func<OnRetryArguments<TResult>, ValueTask>? OnFailedRetry { get; set; }
}
```
This property has the exact same signature as the `OnRetry`. If you want to use this class in your production code please rename `CustomRetryStrategyOptions` to something more meaningful 😊

## Define a custom strategy
One way to tackle the second implication (so calling automatically the `OnFailedRetry` if the last attempt failed) is to wire up a custom strategy into a resilience pipeline. 

```cs
internal sealed class LogAfterStrategy<TResult>: ResilienceStrategy<TResult>
{
    private readonly CustomRetryStrategyOptions<TResult> options;

    public LogAfterStrategy(CustomRetryStrategyOptions<TResult> options)
        => this.options = options;   

    protected override async ValueTask<Outcome<TResult>> ExecuteCore<TState>(
        Func<ResilienceContext, TState, ValueTask<Outcome<TResult>>> callback,
        ResilienceContext context,
        TState state)
    {
       	var outcome = await callback(context, state).ConfigureAwait(context.ContinueOnCapturedContext);

	var shouldRetryArgs = new RetryPredicateArguments<TResult>(context, outcome, options.MaxRetryAttempts);
        var handle = await options.ShouldHandle(shouldRetryArgs).ConfigureAwait(context.ContinueOnCapturedContext);

	if(handle)
	{
	       //ExecutionTime for the last retry is unknown so, I passed TimeSpan.Zero for that
		var args = new OnRetryArguments<TResult>(context, outcome, options.MaxRetryAttempts, TimeSpan.Zero, TimeSpan.Zero);
		await options.OnFailedRetry(args).ConfigureAwait(context.ContinueOnCapturedContext);
	}
        return outcome;
    }
}
```
- This `LogAfterStrategy` receives an `CustomRetryStrategyOptions` instance via its constructor
- Inside its `ExecuteCore`
  - it executes the `callback` which is either the next resilience strategy or the decorated user callback depending on whether it is registered as an outer or as the innermost strategy (respectively) into the pipeline
  - it calls the `ShouldHandle` to decide whether the outcome is considered successful or unsuccessful. The `handle` is `true` if the `outcome` is unsuccessful.
  - it executes the `OnFailedRetry` if the `outcome` was unsuccessful
  - finally it returns the `outcome`

## Wire up pipeline

We want to execute the `OnFailedRetry` customer delegate after the retry strategy exhausted all of its attempts. That means the `LogAfterStrategy` should be the outer strategy and a retry should the inner.

```cs
public static class RetryExtensions
{ 
    public static ResiliencePipelineBuilder<TResult> AddCustomRetry<TResult>(this ResiliencePipelineBuilder<TResult> builder, CustomRetryStrategyOptions<TResult> options)
    {
        return builder
	.AddStrategy(context => new LogAfterStrategy<TResult>(options), options)
        .AddRetry(new() {
            BackoffType = options.BackoffType,
            Delay = options.Delay,
            DelayGenerator = options.DelayGenerator,
	    MaxDelay = options.MaxDelay,
            MaxRetryAttempts = options.MaxRetryAttempts,
	    ShouldHandle = options.ShouldHandle,
            UseJitter = options.UseJitter,
            OnRetry = async args =>
            {
			if(options.OnRetry is {})
			{
				await options.OnRetry(args).ConfigureAwait(args.Context.ContinueOnCapturedContext);
			}
				
			if(options.OnFailedRetry is {} && args.AttemptNumber > 0)
			{
				await options.OnFailedRetry(args).ConfigureAwait(args.Context.ContinueOnCapturedContext);
			}
            }
        });
    }
}
```
- The [registration order does matter](https://www.pollydocs.org/pipelines/index.html#diagrams) so, first we register the `LogAfter` then the `Retry` strategy
- The retry registration does the following things
  - it maps the `CustomRetryStrategyOptions` properties to the `RetryStrategyOptions` properites
  - it executes the `OnRetry` if it is defined
  - it executes the `OnFailedRetry` if it is defined and it was not the original attempt
- To encapsulate (and hide) these strategies bundling we can create a simple extension method

## Usage
```cs
var pipeline = new ResiliencePipelineBuilder<int>()
	.AddCustomRetry(new CustomRetryStrategyOptions<int>
	{
                //All attempt considered unsuccessful
		ShouldHandle = args => PredicateResult.True(), 

                //All attempt considered unsuccessful except the very last one
		//ShouldHandle = args => args.Outcome.Result < 3 ? PredicateResult.True() : PredicateResult.False(),

		Delay = TimeSpan.FromSeconds(0.1),
		MaxRetryAttempts = 3,
		OnFailedRetry = static args =>
		{
			Console.WriteLine($"- Retry attempt failed with: {args.Outcome}.");
			return default;
		}
	})
	.Build();

int i = 0;
_ = pipeline.Execute(() => 
{
	Console.WriteLine($"The callback is called for the {i}th time.");
	return i++; 
});
```

**Comment by FutureTD** [comment]
Absolutely perfect! Thank you.
