### ISSUE TITLE
[Docs]: The main category pages are only available through the breadcrumbs

### ISSUE THREAD

**Issue by anth-git** [App-vNext/Polly#2134]
### Describe the bug

On www.pollydocs.org there are no direct links to category pages, such as `Resilience pipelines`, `Chaos engineering`, etc

For example in order to open `https://www.pollydocs.org/chaos/index.html` one needs to open the `Chaos engineering` menu, then click on `Fault`, and after the page loads, click on `Chaos engineering` from the breadcrumbs.

This is very confusing, because it appears that there is no introduction to the topics.

![image](https://github.com/App-vNext/Polly/assets/6680915/dc547fa9-d4c0-4ba4-b039-5289ed4b0a47)

Also breadcrumbs seem to be backwards.

**Comment by martincostello** [comment]
The fix is for us to update the [table of contents](https://github.com/App-vNext/Polly/blob/main/docs/toc.yml) to add the summary topics at the top of each dropdown.

**Comment by peter-csala** [comment]
Assign to me

**Comment by peter-csala** [comment]
Which one would be the preferred the approach?

## No dropdown on the top, lhs submenu

![Screenshot 2024-05-28 at 16 12 14](https://github.com/App-vNext/Polly/assets/57183693/90705e85-7d57-4cc3-83f4-993063235117)

## Dropdown on the top, clumsy breadcrumb

![Screenshot 2024-05-28 at 16 15 00](https://github.com/App-vNext/Polly/assets/57183693/acd73191-ef9f-4ff9-a714-1e73e536ab6a)

Of course we can use other name to the index page than the parent name

**Comment by martincostello** [comment]
I _think_ I prefer the first option, but there's not much in it.

**Comment by martincostello** [comment]
Thanks for reporting this issue. The documentation was updated by #2136 to resolve this.
