### ISSUE TITLE
[Feature request]: Resilience Event occured logs should be configurable as Warning unless it's the final attempt that failed

### ISSUE THREAD

**Issue by sander1095** [App-vNext/Polly#2162]
### Is your feature request related to a specific problem? Or an existing feature?

Polly reports `Resilience Event occurred ..` logs as Error, even when it's the first attempt that failed and multiple attempts will still be made.

This makes the log show up as an error, possibly setting off alerts even though it isn't really an error until the retry mechanisms have truly failed.

### Describe the solution you'd like

I would like to be able to configure failed retries to get logged as Warning. When the final attempt fails, that could then be logged as an error.

This means that I will only see _true_ errors (that might need investigation) in my error screen.

**Comment by martincostello** [comment]
Have you tried doing this with the changes from #2072 that are in Polly 8.4.0?

**Comment by sander1095** [comment]
I seem to have overlooked that one. I just had a look, but it seems that you can only set the severity based on the (original) Severity and the EventName.  I do not think that is enough to implement this feature request, as I would also need something like `IsFinalAttempt` or `Attempt` and `MaxAttempts`.

Also, I'm using `Microsoft.Extensions.Http.Resilience` instead of a direct dependency on Polly. I do not see a way to do access the TelemetryOptions in the same way when using that package. However, that's an issue related to that package and not Polly directly.

**Comment by peter-csala** [comment]
> I would like to be able to configure failed retries to get logged as Warning. When the final attempt fails, that could then be logged as an error.

This is how currently it works. If the failed attempt is handled from the retry strategy perspective then it will be reported as `Warning` otherwise as `Information`

https://github.com/App-vNext/Polly/blob/5d81f99ef5f523032c17b6b59b32d575ec9dfb06/src/Polly.Core/Telemetry/TelemetryUtil.cs#L27

This behavior is documented [here](https://www.pollydocs.org/strategies/retry.html#telemetry).

**Comment by peter-csala** [comment]
> ... 
> I just had a look, but it seems that you can only set the severity based on the (original) Severity and the EventName. I do not think that is enough to implement this feature request, as I would also need something like `IsFinalAttempt` or `Attempt` and `MaxAttempts`.
> ...
 
The `SeverityProvider` receives a [`SeverityProviderArguments`](https://www.pollydocs.org/api/Polly.Telemetry.SeverityProviderArguments.html) parameter. It is not specify to any strategies so, it won't contain information about the retry's attempt count.

BUT you can use the [`ResilienceContext`](https://www.pollydocs.org/api/Polly.ResilienceContext.html) to exchange information between your retry strategy and between the `SeverityProvider`.

**Comment by martintmk** [comment]
@martincostello

 I am thinking that this might be even good default behavior for retry strategy? Individual attempts are warnings while the final one is error?

**Comment by martincostello** [comment]
I guess that's a reasonable if we have access to the context to know if it's the last attempt.

**Comment by martincostello** [comment]
No update from us. Feel free to open a pull request to propose this change, then we can take a look.

**Comment by peter-csala** [comment]
I'll be off in the next two weeks, but I can start work on this request on the 16th of September week if that's not too late.

**Comment by peter-csala** [comment]
As I can see no one has jump on this request in my absence so, @martincostello please assign this ticket to me.

**Comment by sander1095** [comment]
Sounds good, @peter-csala . I am pretty sure I did see resilience logged as error in non-error cases, but that might be related to Microsoft.Extensions.Http.Resilience and not Polly directly
