### ISSUE TITLE
[Bug]: `GetRetryDelay` goes NEGATIVE after 1025 attempts [High Risk Issue]

### ISSUE THREAD

**Issue by wolfnfox** [App-vNext/Polly#2163]
### Describe the bug

Retry delay goes negative after 1025 retries causing instant retries for all subsequent retry attempts.

The issue stems from the following line which tends to infinity:

```
 double next = Math.Pow(ExponentialFactor, t) * Math.Tanh(Math.Sqrt(PFactor * t));
 ```

This causes the following `formulaIntrinsicValue = Infinity - Infinity;` which in turn returns `NaN` and leads to the negative timespan result.  

### Expected behavior

It continues to respect the maximum retry delay and is impossible for a negative retry to be returned from a resilience pipeline.

### Actual behavior

The next retry delay goes to maximum negative value which causes the resilience execution to retry instantly.  This causes a run away execution pipeline when `Unlimited` number of retries are selected.

### Steps to reproduce

Using the class instances from the Polly directly you can replicate the error using the following simple program:

```
var attempt = 1;
var state = 0d;
var nextTime = TimeSpan.FromSeconds(1);
while (nextTime > TimeSpan.Zero)
{
    nextTime = RetryHelper.GetRetryDelay(DelayBackoffType.Exponential, true, attempt++, TimeSpan.FromSeconds(2), TimeSpan.FromSeconds(30), ref state, RandomUtil.Instance.NextDouble);
    Console.WriteLine($"Attempt {attempt}: {nextTime}");
}
```

Generated output:
```
Attempt 1022: 00:00:30
Attempt 1023: 00:00:30
Attempt 1024: 00:00:30
Attempt 1025: 00:00:30
Attempt 1026: -10675199.02:48:05.4775808
```

### Polly version

8.4.0, main

### .NET Version

net8.0

### Anything else?

Work around is to add the following condition to the `DelayGenerator` function to avoid the overflow scenario:

```
retry.DelayGenerator = static args =>
{
    if (args.AttemptNumber > 1024) { return ValueTask.FromResult<TimeSpan?>(TimeSpan.FromSeconds(30)); }
    return new ValueTask<TimeSpan?>((TimeSpan?)null);
};
```

Identified originally when using the following resilience options in production code:

```
private static RetryStrategyOptions DefaultRetryStrategy => new()
{
    BackoffType = DelayBackoffType.Exponential,
    Delay = TimeSpan.FromSeconds(2),
    MaxDelay = TimeSpan.FromSeconds(30),
    MaxRetryAttempts = int.MaxValue,
    UseJitter = true
};
```

**Comment by wolfnfox** [comment]
Example of run away behaviour; logged output from a test server:

```
2024-06-22T00:45:07.3018022+00:00 [WRN] SignalRClient connection attempt 1021 failed. Retrying in 30 secs.
2024-06-22T00:45:37.3171715+00:00 [WRN] SignalRClient connection attempt 1022 failed. Retrying in 30 secs.
2024-06-22T00:46:07.3226994+00:00 [WRN] SignalRClient connection attempt 1023 failed. Retrying in 30 secs.
2024-06-22T00:46:37.3357127+00:00 [WRN] SignalRClient connection attempt 1024 failed. Retrying in 30 secs.
2024-06-22T00:47:07.4416703+00:00 [WRN] SignalRClient connection attempt 1025 failed. Retrying in -2147483.648 secs.
2024-06-22T00:47:04.5259173+00:00 [WRN] SignalRClient connection attempt 1026 failed. Retrying in -2147483.648 secs.
2024-06-22T00:47:04.5354682+00:00 [WRN] SignalRClient connection attempt 1027 failed. Retrying in -2147483.648 secs.
2024-06-22T00:47:04.5440102+00:00 [WRN] SignalRClient connection attempt 1028 failed. Retrying in -2147483.648 secs.
2024-06-22T00:47:04.5496702+00:00 [WRN] SignalRClient connection attempt 1029 failed. Retrying in -2147483.648 secs.
2024-06-22T00:47:04.5554510+00:00 [WRN] SignalRClient connection attempt 1030 failed. Retrying in -2147483.648 secs.
```

**Comment by peter-csala** [comment]
Your suggested workaround won't help here. If you do specify the `DelayGenerator` then there is an explicit null or less than zero check:

https://github.com/App-vNext/Polly/blob/5d81f99ef5f523032c17b6b59b32d575ec9dfb06/src/Polly.Core/Retry/RetryResilienceStrategy.cs#L72

```cs
var delay = RetryHelper.GetRetryDelay(BackoffType, UseJitter, attempt, BaseDelay, MaxDelay, ref retryState, _randomizer);
if (DelayGenerator is not null)
{
    var delayArgs = new RetryDelayGeneratorArguments<T>(context, outcome, attempt);

    if (await DelayGenerator(delayArgs).ConfigureAwait(false) is TimeSpan newDelay && RetryHelper.IsValidDelay(newDelay))
    {
        delay = newDelay;
    }
}
```
where the `IsValidDelay` is
```cs
public static bool IsValidDelay(TimeSpan delay) => delay >= TimeSpan.Zero;
```

So, if you use `DelayGenerator` then you don't have this problem. 
____
@martincostello  Please assign me this ticket if it is not super urgent. I will have time on Thursday for this.

**Comment by martincostello** [comment]
I was about to pick this up myself, but I'm happy to leave it for you to look into if you want to.

**Comment by peter-csala** [comment]
@martincostello If you have time for this today then take it.

**Comment by wolfnfox** [comment]
Many thanks for the quick turn around on this.  Really really appreciated.
