### ISSUE TITLE
[Question]: How to get the HttpRequest in a callback supplied to stateful policy (e.g. circuit breaker)

### ISSUE THREAD

**Issue by scharnyw** [App-vNext/Polly#2244]
### What are you wanting to achieve?

This question concerns `PolicyHttpMessageHandler` but I think the idea applies generally to other cases as well.

I'm trying to get the input to user delegate (i.e. `HttpRequest`) in the `onBreak` callback in a Circuit Breaker policy. For a non-stateful policy such as retry, I can create a new policy every time and it can capture the request object (which of course is different for every request):

	IAsyncPolicy<HttpResponseMessage> GetPollyPolicy(HttpRequestMessage request)
	{
	    var retryPolicy = Policy<HttpResponseMessage>
	        .Handle<Exception>()
	        // can access request here via closure
	        .RetryAsync((result, count) => logger.LogInformation($"Request: {request}"));

	    return retryPolicy;
	}

	var handler = new PolicyHttpMessageHandler(GetPollyPolicy) { InnerHandler = new HttpClientHandler() };
	var httpClient = new HttpClient(handler);

The problem is that for a stateful policy such as Circuit Breaker, I can't create a new policy with every request because it defeats the purpose. For such cases, what's the recommended way to get hold of `HttpRequest` object in callbacks like `onBreak`? I suppose one way would be to use the `Context` object attached to `HttpRequest` by `PolicyHttpMessageHandler`, but this seems like a sufficiently routine case such that writing our own `DelegatingHandler` to attach state should not be necessary.

	IAsyncPolicy<HttpResponseMessage> GetPollyPolicy(HttpRequestMessage request)
	{
	    var retryPolicy = Policy<HttpResponseMessage>
	        .Handle<Exception>()
	        // this doesn't work as intended because circuit breaker is stateful so one policy instance should be used across requests
	        .CircuitBreakerAsync(5, TimeSpan.FromSeconds(30),
	            (result, time) => logger.LogInformation($"Request: {request}"),
	            () => {});

	    return retryPolicy;
	}

	var handler = new PolicyHttpMessageHandler(GetPollyPolicy) { InnerHandler = new HttpClientHandler() };
	var httpClient = new HttpClient(handler);

### What code or approach do you have so far?

See above.

### Additional context

Using Polly v7.

**Comment by martincostello** [comment]
Use an overload where `onBreak` receives the context such as this one:

https://github.com/App-vNext/Polly/blob/72331dc215259e9788eb7c9adadd3d4c594f0c32/src/Polly/CircuitBreaker/AsyncCircuitBreakerSyntax.cs#L156

Then you can access the `HttpRequest` stored in it by the handler: https://github.com/dotnet/aspnetcore/blob/ef09c065b96af01afa38b82e5b8a35a718685a48/src/HttpClientFactory/Polly/src/PolicyHttpMessageHandler.cs#L172

If this doesn't meet your needs and you don't want to write another handler, consider upgrading to Polly v8 which can be used with the new .NET resilience libraries which build upon our new Polly.Core APIs: https://devblogs.microsoft.com/dotnet/building-resilient-cloud-services-with-dotnet-8/ and https://www.pollydocs.org/strategies/circuit-breaker.html

**Comment by scharnyw** [comment]
> Then you can access the `HttpRequest` stored in it by the handler: https://github.com/dotnet/aspnetcore/blob/ef09c065b96af01afa38b82e5b8a35a718685a48/src/HttpClientFactory/Polly/src/PolicyHttpMessageHandler.cs#L172

Seems that this only stores the previous `HttpResponseMessage` (for cleanup purposes), but not the `HttpRequestMessage`.

**Comment by martincostello** [comment]
https://learn.microsoft.com/dotnet/api/system.net.http.httpresponsemessage.requestmessage

**Comment by scharnyw** [comment]
> https://learn.microsoft.com/dotnet/api/system.net.http.httpresponsemessage.requestmessage

This is not reliable, as `HttpResponseMessage` will only exist if there was a valid HTTP response from upstream. If the network failed for whatever reason, or client timed out, then `HttpResponseMessage` and `HttpResponseMessage.RequestMessage` would not be available.

If it was about accessing `HttpResponseMessage` then it could easily be accessed from `DelegateResult<HttpResponseMessage>` which is available from almost all callbacks, there would be no need to have Context involved.

**Comment by martincostello** [comment]
In that case you'll need to write your own delegating handler and inject it into the HTTP pipeline, or investigate using the resilience libraries with v8 instead which may have the functionality to let you solve your use case without needing to do that.

In either case, HTTP-specific functionality is outside of Polly itself.

**Comment by scharnyw** [comment]
@martincostello That seems to be the case. I'll see if I can get `PolicyHttpMessageHandler` to accept a PR to attach request to the context to make usage easier. Thanks.

**Comment by martincostello** [comment]
> I'll see if I can get PolicyHttpMessageHandler to accept a PR

You can try, but I wouldn't get your hopes up. The new resilience libraries are where new innovation for that space is being invested in, and that library in the aspnetcore repo is basically now just in maintenance mode.

If they did take a PR, there's a good chance it's too late in the .NET 9 release cycle and might have to wait until .NET 10 which won't ship until November 2025.
