### ISSUE TITLE
TimeoutStrategyOptions.TimeoutGenerator docs are incorrect

### ISSUE THREAD

**Issue by wjrogers** [App-vNext/Polly#2266]
The XML comment on the `TimeoutGenerator` property says that returning `TimeSpan.Zero` means "use `Timeout` instead":
https://github.com/App-vNext/Polly/blob/074a14d2f986ffc7f3ba6383f3c9d591f273b229/src/Polly.Core/Timeout/TimeoutStrategyOptions.cs#L30-L31

However, the code has no such logic. Any return value less than or equal to `TimeSpan.Zero` is treated as an infinite timeout:
https://github.com/App-vNext/Polly/blob/a9008fa33fff999086929d1edae5936f8f8d4f67/src/Polly.Core/Timeout/TimeoutResilienceStrategy.cs#L31-L40

**Comment by peter-csala** [comment]
In case of Retry when the `DelayGenerator` returns `null` or  zero or negative timestamp then it falls back to the `Delay` property based calculation. 

https://github.com/App-vNext/Polly/blob/a9008fa33fff999086929d1edae5936f8f8d4f67/src/Polly.Core/Retry/RetryResilienceStrategy.cs#L67-L76

https://github.com/App-vNext/Polly/blob/a9008fa33fff999086929d1edae5936f8f8d4f67/src/Polly.Core/Retry/RetryHelper.cs#L14

I **assume** we wanted to have the something similar for the TimeoutStrategy. BUT now it behaves in the following way:
- If only `Timeout` is defined then that is used
- If only `TimeoutGenerator` is defined then that is used
- If both `Timeout` and `TimeoutGenerator` are defined then `Timeout` is ignored.

**Comment by peter-csala** [comment]
@martincostello Can you close this issue please?
