### ISSUE TITLE
To the repo maintainer(s): Can you create a GitHub release for v5.0.5?

### ISSUE THREAD

**Issue by nathan-alden** [App-vNext/Polly#227]
First of all, thank you so much for this robust retry library! It's a shame this functionality isn't part of .NET Core, but your library fills that gap perfectly. 👍 

I work for a company that has a very strict OSS rules. We are not allowed to use NuGet packages that cannot be tied back to a specific GitHub release. We're currently using Polly 5.0.5 from nuget.org. Do you think it's possible that you could create an official release on GitHub so that we can continue to use your great library? My employer has specific rules about linking NuGet packages to GitHub releases so that the code can be scanned for vulnerabilities.

**Comment by reisenberger** [comment]
@nathan-alden  Thank you for your kind words.  

The release has been created at: https://github.com/App-vNext/Polly/releases/tag/v5.0.5

@joelhulen Any reason not to create such a tag every release?  Suggest we continue to deliver binaries only via nuget, but a tag of the release here does no harm?

@nathan-alden To help users follow what's in a new release, we also aim to tag Issues fixed and PRs merged in each release, with milestones matching the release number.  See, eg https://github.com/App-vNext/Polly/milestone/14?closed=1

**Comment by nathan-alden** [comment]
Very cool, and thank you _so much_ for responding so quickly. I was about to have to start work on my own internal library, which would've been a huge waste of time. Dem corporate policies... 👎

**Comment by nathan-alden** [comment]
To be clear: We still get our binaries from NuGet, but the team that scans OSS dependencies requires a snapshot of the code; i.e., they won't simply scan the NuGet binaries themselves.

**Comment by reisenberger** [comment]
No problem @nathan-alden , makes sense :+1:  , and understand that's needed in some environments.

**Comment by joelhulen** [comment]
@reisenberger @nathan-alden Absolutely no problem with tagging each release. In fact, I've seen many projects do this very thing, and it does help keep code history aligned with their particular version. Thanks for taking care of this!
