### ISSUE TITLE
[Feature request]: Generic version extending non-generic version

### ISSUE THREAD

**Issue by Iyer-Narayan** [App-vNext/Polly#2274]
### Is your feature request related to a specific problem? Or an existing feature?

It would be extremely helpful if generic apis inherited from their corresponding non-generic versions. This would help avoid a lot of duplicate code for the consumers. 

A classic example of this would be `Task<T>` inheriting Task in C#. 

Inheritance:

- [`Object`](https://learn.microsoft.com/en-us/dotnet/api/system.object?view=net-8.0)
- [`Task`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task?view=net-8.0)
- [`Task<TResult>`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task-1?view=net-8.0#:~:text=Inheritance,Task%3CTResult%3E)

### Describe the solution you'd like

Generic apis should inherit from their non-generic apis. 

`ResiliencyPipeline<T>` : `ResiliencyPipeline`
`IAsyncPolicy<T>` : `IAsyncPolicy`

**Comment by martincostello** [comment]
This is something unlikely to be considered at this stage, as it would a huge breaking change.

**Comment by martincostello** [comment]
Thanks for the suggestion, but I'm going to close this as it's not something we can realistically change at this stage as it would be massively breaking for our users.
