### ISSUE TITLE
[Bug]: Timeout not always throwing TimeoutRejectedException

### ISSUE THREAD

**Issue by baconandon** [App-vNext/Polly#2278]
### Describe the bug

I have a pipeline with an inner Retry and an outer Timeout. The Retry needs to perform the operation as many times as possible until it is successful, or the timeout is exceeded.

When the timeout is exceeded however a TimeoutRejectedException is sometimes not thrown.

The pipeline is being run with `ExecuteAsync()`.

(I'm new to Polly so apologies in advance if I'm not understanding how to configure the pipeline correctly. It's the fact that the behaviour is intermittently not what I expect that makes me think this might be a bug...)

### Expected behavior

A TimeoutRejectedException is always thrown when the timeout is exceeded and the retried operation consistently fails.

### Actual behavior

When the code executed by the retry consistently throws an ApplicationException that the Retry recognizes from its `ShouldHandle` options, then _sometimes_ (not always) that ApplicationException is propagated back as the result of an `ExecuteAsync` call.

### Steps to reproduce

This XUnit test - edited since original post to simplify the repro code - consistently fails for me (xunit v2.9.0)

```csharp
public class ReproPollyWeirdness(ITestOutputHelper testOutputHelper)
{
    private const int ShortDelayMillis = 20, TimeoutMillis = 100;
    private const bool ShowOutput = false;
    private record Value(String StringValue);

    private ResiliencePipeline<Value> SetupPipeline()
    {
        return new ResiliencePipelineBuilder<Value>()
            .AddTimeout(new TimeoutStrategyOptions
            {
                Timeout = TimeSpan.FromMilliseconds(TimeoutMillis),
                OnTimeout = _ => WriteLine("Timeout!")
            })
            .AddRetry(new RetryStrategyOptions<Value>
            {
                BackoffType = DelayBackoffType.Constant,
                Delay = TimeSpan.FromMilliseconds(ShortDelayMillis),
                MaxRetryAttempts = Int32.MaxValue,
                OnRetry = _ => WriteLine("Retry!"),
                ShouldHandle = new PredicateBuilder<Value>().Handle<ApplicationException>(),
                UseJitter = true
            })
            .Build();
    }

    private ValueTask WriteLine(string message, bool forceOutput = false)
    {
        if (ShowOutput || forceOutput)
        {
            testOutputHelper.WriteLine(message);
        }

        return default;
    }

    [Fact]
    public async Task ShouldThrowTimeoutRejectedExceptionOnRepeatedRetryFailures()
    {
        var pipeline = SetupPipeline();
        Func<CancellationToken, ValueTask<Value>> foo = _ =>
            throw new ApplicationException("Should be handled by retry strategy"); // simulating my real code

        for (int i = 0; i < 100; i++)
        {
            try
            {
                var bar = await pipeline.ExecuteAsync(foo);
            }
            catch (TimeoutRejectedException)
            {
                // expected
            }
            catch (ApplicationException ex)
            {
                await WriteLine($"Did not throw TimeoutRejectedException on attempt {i} - {ex}", true);
                throw;
            }
        }
    }
}
```

### Exception(s) (if any)

Sample output from the repro code above
```
System.ApplicationException
Should be handled by retry strategy
   at ReproPollyWeirdness.<>c.<ShouldThrowTimeoutRejectedExceptionOnRepeatedRetryFailures>b__8_0(CancellationToken _) in ...
   at Polly.ResiliencePipeline.<>c__10`1.<<ExecuteAsync>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Outcome`1.GetResultOrRethrow()
   at Polly.ResiliencePipeline.ExecuteAsync[TResult](Func`2 callback, CancellationToken cancellationToken)

Did not throw TimeoutRejectedException on attempt 5 - System.ApplicationException: Should be handled by retry strategy
```

### Polly version

8.4.1

### .NET Version

8.0.303

### Anything else?

I have read https://www.pollydocs.org/strategies/timeout.html and the repro code is not canceling the original token

> The timeout strategy operates by wrapping the incoming cancellation token with a new one. Should the original token be canceled, the timeout strategy will transparently honor the original cancellation token without throwing a TimeoutRejectedException.

**Comment by baconandon** [comment]
Here are some screencaps taken at breakpoints in the (Rider-disassembled) Polly code when the test fails:

* RetryResilienceStrategy
![image](https://github.com/user-attachments/assets/26abb7e3-4f13-401b-9742-057d7e7b1f37)

* TimeoutResilienceStrategy
![image](https://github.com/user-attachments/assets/b5128b3e-d112-4ce3-ada3-3e237cf6f26f)
![image](https://github.com/user-attachments/assets/70f9dd6f-2879-4810-945b-8b113c8209cf)
![image](https://github.com/user-attachments/assets/f80bbaeb-e1c4-4b89-b6a8-65a99824ea87)

Hope this helps!

**Comment by martincostello** [comment]
I've just took a look at this in the debugger, and what's happening is that because your handler is failing and not observing the `CancellationToken` passed to it, we prefer returning that outcome to you (_work is failing_) rather than the overall timeout expiring and swallowing that fact (_no progress was made, but we won't tell you why_).

That's with this simplified version of your repro:

```csharp
[Fact]
public async Task Timeout_Not_Throwing_TimeoutRejectedException_2278()
{
    const int IterationTimeoutMs = 20;
    const int TotalTimeoutMs = 100;

    var pipeline = new ResiliencePipelineBuilder<string>()
        .AddTimeout(new TimeoutStrategyOptions
        {
            Timeout = TimeSpan.FromMilliseconds(TotalTimeoutMs),
        })
        .AddRetry(new RetryStrategyOptions<string>
        {
            BackoffType = DelayBackoffType.Constant,
            Delay = TimeSpan.FromMilliseconds(IterationTimeoutMs),
            MaxRetryAttempts = int.MaxValue,
            ShouldHandle = new PredicateBuilder<string>().Handle<InvalidOperationException>(),
            UseJitter = true
        })
        .Build();

    int attempts = 0;

    Func<CancellationToken, ValueTask<string>> foo = token =>
        throw new InvalidOperationException($"Should be handled by retry strategy: attempts = {++attempts}");

    for (int i = 0; i < 100; i++)
    {
        try
        {
            _ = await pipeline.ExecuteAsync(foo);
        }
        catch (TimeoutRejectedException)
        {
            // expected
        }
    }
}
```

```
System.InvalidOperationException : Should be handled by retry strategy: attempts = 26
```

I get a similar result if I add a call to `CancellationToken.ThrowIfCancellationRequested()` to the handler:

```csharp
[Fact]
public async Task Timeout_Not_Throwing_TimeoutRejectedException_2278()
{
    const int IterationTimeoutMs = 20;
    const int TotalTimeoutMs = 100;

    var pipeline = new ResiliencePipelineBuilder<string>()
        .AddTimeout(new TimeoutStrategyOptions
        {
            Timeout = TimeSpan.FromMilliseconds(TotalTimeoutMs),
        })
        .AddRetry(new RetryStrategyOptions<string>
        {
            BackoffType = DelayBackoffType.Constant,
            Delay = TimeSpan.FromMilliseconds(IterationTimeoutMs),
            MaxRetryAttempts = int.MaxValue,
            ShouldHandle = new PredicateBuilder<string>().Handle<InvalidOperationException>(),
            UseJitter = true
        })
        .Build();

    int attempts = 0;

    Func<CancellationToken, ValueTask<string>> foo = async token =>
    {
        token.ThrowIfCancellationRequested();
        throw new InvalidOperationException($"Should be handled by retry strategy: attempts = {++attempts}");
    };

    for (int i = 0; i < 100; i++)
    {
        try
        {
            _ = await pipeline.ExecuteAsync(foo);
        }
        catch (TimeoutRejectedException)
        {
            // expected
        }
    }
}
```

```
System.InvalidOperationException : Should be handled by retry strategy: attempts = 10
```

If I artificially make the handler slower than the timeout using `Task.Delay()` and use the `CancellationToken`, I get the expected behaviour and the test passes:

```csharp
[Fact]
public async Task Timeout_Not_Throwing_TimeoutRejectedException_2278()
{
    const int IterationTimeoutMs = 20;
    const int TotalTimeoutMs = 100;

    var pipeline = new ResiliencePipelineBuilder<string>()
        .AddTimeout(new TimeoutStrategyOptions
        {
            Timeout = TimeSpan.FromMilliseconds(TotalTimeoutMs),
        })
        .AddRetry(new RetryStrategyOptions<string>
        {
            BackoffType = DelayBackoffType.Constant,
            Delay = TimeSpan.FromMilliseconds(IterationTimeoutMs),
            MaxRetryAttempts = int.MaxValue,
            ShouldHandle = new PredicateBuilder<string>().Handle<InvalidOperationException>(),
            UseJitter = true
        })
        .Build();

    int attempts = 0;

    Func<CancellationToken, ValueTask<string>> foo = async token =>
    {
        token.ThrowIfCancellationRequested();
        await Task.Delay(200, token);
        throw new InvalidOperationException($"Should be handled by retry strategy: attempts = {++attempts}");
    };

    for (int i = 0; i < 100; i++)
    {
        try
        {
            _ = await pipeline.ExecuteAsync(foo);
        }
        catch (TimeoutRejectedException)
        {
            // expected
        }
    }
}
```

> the repro code is not canceling the original token

There is no original token in your repro - your repro does not pass a `CancellationToken` to the `ExecuteAsync()` invocation, this means that the token (which you don't use) passed to the handler is the token created by Polly.

If I change the code to create a `CancellationTokenSource` and pass its token to `ExecuteAsync()`, then I get a `TaskCanceledException` instead as the code times itself out via the original token's cancellation:

```csharp
[Fact]
public async Task Timeout_Not_Throwing_TimeoutRejectedException_2278()
{
    const int IterationTimeoutMs = 20;
    const int TotalTimeoutMs = 100;

    var pipeline = new ResiliencePipelineBuilder<string>()
        .AddTimeout(new TimeoutStrategyOptions
        {
            Timeout = TimeSpan.FromMilliseconds(TotalTimeoutMs),
        })
        .AddRetry(new RetryStrategyOptions<string>
        {
            BackoffType = DelayBackoffType.Constant,
            Delay = TimeSpan.FromMilliseconds(IterationTimeoutMs),
            MaxRetryAttempts = int.MaxValue,
            ShouldHandle = new PredicateBuilder<string>().Handle<InvalidOperationException>(),
            UseJitter = true
        })
        .Build();

    int attempts = 0;

    using var cts = new CancellationTokenSource(TimeSpan.FromMilliseconds(75));

    Func<CancellationToken, ValueTask<string>> foo = async token =>
    {
        token.ThrowIfCancellationRequested();
        await Task.Delay(200, token);
        throw new InvalidOperationException($"Should be handled by retry strategy: attempts = {++attempts}");
    };

    for (int i = 0; i < 100; i++)
    {
        try
        {
            _ = await pipeline.ExecuteAsync(foo, cts.Token);
        }
        catch (TimeoutRejectedException)
        {
            // expected
        }
    }
}
```

```
System.Threading.Tasks.TaskCanceledException : A task was canceled.
```

Polly is doing the right thing with expect to the repro (that unconditionally always throws) - it retries until the timeout is up, and then because the handler is failing, it throws the last failure observed (the `ApplicationException` in your case).

The `TimeoutRejectedException` will only be thrown if the user code (`foo` in your repro) causes cancellation - your handler doesn't do this, it just consistently fails until Polly gives up and tells you its failing.

In your original code (not the repro) I suggest you pass the `CancellationToken` to whatever asynchronous work you're performing, or if you can't pass it on for whatever reason (e.g. it's just your code doing a long loop or something) then your code should periodically call `ThrowIfCancellationRequested()` (e.g. at the start of each `for` loop iteration) so that it cooperatively responds to a request to cancellation, either from Polly's timeout strategy, or from any token passed to the strategy invocation itself.

This is essentially [what is called out in the documentation](https://www.pollydocs.org/strategies/timeout.html):

> **Important**
> It is crucial that the user's callback respects the cancellation token. If it does not, the callback will continue executing even after a cancellation request, thereby ignoring the cancellation.

The repro is ignoring cancellation, and thus you only see the errors.

**Comment by baconandon** [comment]
> The repro is ignoring cancellation, and thus you only see the errors.
Got it. Thanks for the detailed reply, and sorry for raising a bug when it was my misunderstanding!
