### ISSUE TITLE
Can not install 5.0.5 on PCL Profile 111 (Xamarin PCL)

### ISSUE THREAD

**Issue by Julien-Mialon** [App-vNext/Polly#228]
Hello,

Polly is unable to install on PCL Profile 111 because of an issue with NETStandard.Library 1.6.0 which can not be installed on Profile 111. This has been fixed in NETStandard.Library 1.6.1, could you update the minimum version of NETStandard.Library in your dependencies ?

Current workaround is to install NETStandard.Library 1.6.1 first and then install Polly. 
Refit had the same issue described here : https://github.com/paulcbetts/refit/issues/282

Thanks

**Comment by reisenberger** [comment]
Salut @Julien-Mialon !  J'ai mis les changes dans cette branche:  https://github.com/reisenberger/Polly/tree/NetStandardReference161
Vous pouvez verifier si ca marche, avant que je fusionne avec master?

If you run `build.bat` from that branch, the build will dump the nuget packages in subfolder `artifacts\nuget-package`.    Let us know if those nuget packages fix the issue for installing against Profile 111, before we merge this to master.

**Comment by Julien-Mialon** [comment]
Salut @reisenberger 

Parfait ! It works perfectly and can be merged.

Thanks

**Comment by reisenberger** [comment]
Merci @Julien-Mialon .  Fusionne!

@joelhulen We're good to release v5.0.6 to nuget from master.  Already tagged as a release in GitHub.

**Comment by joelhulen** [comment]
Will upload later today. Currently traveling. Thanks!
