### ISSUE TITLE
[Feature request]: Indicate time of possible circuit closure in `BrokenCircuitException`

### ISSUE THREAD

**Issue by DL444** [App-vNext/Polly#2284]
### Is your feature request related to a specific problem? Or an existing feature?

Related to #506.

Imagine a worker service pulling messages from a queue (e.g. Azure Service Bus) and issuing circuit-breaker protected calls to downstream HTTP endpoints. If the downstream services go down and the circuit breaks, the worker has no easy way to know when the circuit breaker would possibly become closed again.

#506 recommends applications to stop processing messages for some time, and I would agree. The problem is "for how long". Knowing when the circuit breaker is likely still open without relying on actually performing and failing the request is important for message queue scenarios, because excessive retries and failures can quickly exhaust message delivery limit and deadletter the messages unnecessarily.

Applications can surely take a guess, but it still needs this piece of information to make an informed decision on how long to cease message processing. It wouldn't help if the circuit breaker is configured to break for 2 days and the application blindly guesses 2 hours.

### Describe the solution you'd like

Indicate the time when the circuit breaker can possibly become closed again in `BrokenCircuitException`. Possible API:

```diff
  public class BrokenCircuitException : ExecutionRejectedException
  {
+     public TimeSpan? RetryAfter { get; }
  }
```

This matches `RetryAfter` from `RateLimiterRejectedException`. Pulling it up to `ExecutionRejectedException` is not advisable because it does not apply to all derived exception types.

For `IsolatedCircuitException`, set this to `null`.

**Comment by martintmk** [comment]
@DL444 

I think this would be great addition and relatively straightforward to implement! Are you willing tho give this a shot?

Basically, you just need to update this code:

https://github.com/App-vNext/Polly/blob/a8c64be6c6b8647037130278782ab180bcb8d56b/src/Polly.Core/CircuitBreaker/Controller/CircuitStateController.cs#L308

And to retrieve the value until the CB is blocked you can use:

https://github.com/App-vNext/Polly/blob/a8c64be6c6b8647037130278782ab180bcb8d56b/src/Polly.Core/CircuitBreaker/Controller/CircuitStateController.cs#L20

**Comment by DL444** [comment]
> Are you willing tho give this a shot

Yes, I would like to try that this week.

**Comment by peter-csala** [comment]
> > Are you willing tho give this a shot
> 
> Yes, I would like to try that this week.

Hey if you need some help, please let us know.

**Comment by DL444** [comment]
> Hey if you need some help, please let us know.

Not at this time, I've just been busy. I actually already have a working implementation here, but still need some time to sort out testing.
