### ISSUE TITLE
Shared cool-down period, via WaitAndRetry, when breaching third-party API rate-limit

### ISSUE THREAD

**Issue by rlenders** [App-vNext/Polly#230]
Consider the following: I have a wait-and-retry policy that waits 5 minutes before each retry attempt, and hundreds of threads execute through that policy concurrently. An exception occurs so a thread waits 5 minutes before executing attempting to execute the action again. Meanwhile, the other threads will continue to execute through that policy

In my case those threads will all encounter the same exception, and thus will also have to wait 5 minutes. The problem here is that I don't want the other threads to attempt to execute the action when one of them is already waiting for a retry.

In other words, the first thread that uses the policy and encounters an exception should handle the retries. Meanwhile, other threads should wait until the first thread is done. If the first thread eventually successfully executed the action, have the next waiting thread handle the retry logic. If the first thread failed to execute the action, all threads that execute through that policy should immediately fail as well.

I realize this is a pretty specific use case, so it might not be suitable as an enhancement for Polly. However, if anyone can help me figure out how to use Polly to achieve what I described, that would be greatly appreciated.

**Comment by reisenberger** [comment]
Hi @rlenders and welcome!  I can suggest approaches to this using either Polly `CircuitBreakerAsync` (it has exactly the [one-request-after-cooldown-period semantics](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker#half-open) you want) or Stephen Cleary’s [AsyncManualResetEvent](https://github.com/StephenCleary/AsyncEx/wiki/AsyncManualResetEvent), but first I have a question.  

What is the scale/throughput here?  You mention “hundreds of threads execute through that policy concurrently”, and (in the error case) delaying those executions for 5 minutes.  How many requests do you envisage would gather queuing, during the five-minute period when the request ‘at the head of the queue’ is waiting to make its retry? How large that number is might influence comments on architectures/patterns for this.

**Comment by rlenders** [comment]
I don't know the exact numbers right now, but I can imagine the calls queuing up to multiple thousands. I was successfully able to use `AsyncManualResetEvent` after I failed to use Polly to solve my problem. `CircuitBreakerAsync` seemed not to be the right tool for the job, because when the circuit is broken, it returns immediately (or throws an exception?) instead of waiting and retrying.

I'm still looking for a better solution though, my current implementation using `AsyncManualResetEvent` is not really maintainable. I still have a lot of stuff to figure out regarding timeouts, cancellation, etc.

This specific wait-and-retry strategy I'm implementing is required because I'm accessing a limited API. My real underlying problem of this all is that I don't remotely know what the limits of this API are. Currently I'm trying to gather more information on this API so I can work out a better wait-and-retry strategy.

**Comment by reisenberger** [comment]
Hey @rlenders.  Glad you got something going with [AsyncManualResetEvent](https://github.com/StephenCleary/AsyncEx/wiki/AsyncManualResetEvent)!  Yes, it apparently [doesn't have a wait-with-timeout overload](https://github.com/StephenCleary/AsyncEx/issues/47), though you could use the approaches in comments to that issue, or the [cancellation-token overload+ in the sourcecode](https://github.com/StephenCleary/AsyncEx/issues/47) with a [timing out cancellation token like Polly does in `TimeoutPolicy`](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/Timeout/TimeoutEngineAsync.cs#L32) (although the [AsyncManualResetEvent doco says that overload+ doesn't exist](https://github.com/StephenCleary/AsyncEx/wiki/AsyncManualResetEvent#design-notes)).   

### Possibilities with Polly

To get a combination of retry and circuit-breaker semantics with Polly, you can combine retry and circuit-breaker policies using [PolicyWrap](https://github.com/App-vNext/Polly/wiki/PolicyWrap), or manually.  

```csharp
TimeSpan coolOffPeriod = TimeSpan.FromMinutes(5);
TimeSpan acceptableLatencyOfSuccessfulCall = /* define this */ ; 
DateTimeOffset retryAfter = DateTimeOffset.MinValue;

var breaker = Policy
    .Handle<ExceptionThrownByUnderlyingSystem>() 
    .CircuitBreakerAsync(
        1, // Block other callers as soon as a single occurrence of the governed exception occurs.
        coolOffPeriod, // Nobody can place a call in the cool-off period - and only one thread can retry, when the cool-off period is complete.
        (ex, breakDuration) => { retryAfter = DateTimeOffset.UtcNow.Add(breakDuration); }
    );
var headOfQueueRetry = Policy
    .Handle<ExceptionThrownByUnderlyingSystem>() // First call which causes circuit to break will still throw this.
    .WaitAndRetryAsync(1, i => coolOffPeriod) // Retry only once, as soon as cool-off period has elapsed.  
    );
var behindHeadOfQueueRetry = Policy
    .Handle<BrokenCircuitException>()  // Subsequent calls hitting broken circuit will throw this.
    .WaitAndRetryAsync( 
        1, // Only retry once.
        i => {   
                 TimeSpan remainingWait = (retryAfter - DateTimeOffset.UtcNow) // Programatically determine how long a call arriving during the cool-off period, should wait, so it's retried at the end of the cool-off period. 
                     + acceptableLatencyOfSuccessfulCall;  // But the 'waiting' threads want to give the thread at the head of the queue, enough time for its trial execution to complete successfully, before the waiting threads retry.
                 return remainingWait <= TimeSpan.Zero ? TimeSpan.Zero : remainingWait;
             }
    );
var combinedStrategy = behindHeadOfQueueRetry.WrapAsync(headOfQueueRetry.WrapAsync(breaker));

await combinedStrategy.ExecuteAsync(ct => { /* etc */ }, cancellationToken);

```

Not necessarily a finished solution, but illustrates possibilities.    

Driver behind asking about queue volumes was in case a memory bulge from the multi-1000s requests queuing could be a concern.  There could be lighter-weight ways of pending the queuing requests, if an issue.    Or an upper-bound: maybe a bounded async producer-consumer collection like [AsyncProducerConsumerQueue](https://github.com/StephenCleary/AsyncEx/wiki/AsyncProducerConsumerQueue), or wrap a [BulkheadPolicy](https://github.com/App-vNext/Polly/wiki/Bulkhead) with a large queue into the PolicyWrap?  Or push the requests out to a messaging system (eg if losing them on a crash were an issue) - lots of options

Are there any disadvantages to releasing all the queued requests pretty-much simultaneously, when the cool-off period is up?  With the calculate-when-to-retry approach of the above Polly example, you could introduce some randomisation or regular separation.   


---

If the underlying need is rate-limiting, could something like [Jack Leitch's RateGate](http://www.jackleitch.net/2010/10/better-rate-limiting-with-dot-net/) be useful?  Would it be useful to have something like this as a Polly policy (say, `RateLimitPolicy`), combinable with other Polly policies in a `PolicyWrap`?

Hope some of this is useful!

**Comment by rlenders** [comment]
Thanks for all those links. It seems it's really easy to introduce cancellation/timeouts to any async method.

I tried using `PolicyWrap` to combine wait-and-retry with circuit breaker, but I hadn't thought of using another policy to handle the `BrokenCircuitException`. I will try again using your example.

> Are there any disadvantages to releasing all the queued requests pretty-much simultaneously, when the cool-off period is up? In the calculate-when-to-retry approach of the above Polly example, you could introduce some randomisation or regular separation.

I'm not sure what you mean. Could you elaborate on this?

> If the underlying need is rate-limiting, could something like Jack Leitch's RateGate be useful?

It seems rate limiting is only useful when you know exactly how much requests per timespan are allowed. In my case, I don't know what the limits are, so that's why I'm looking for a solution that kicks in when a specific exception is thrown.

**Comment by reisenberger** [comment]
Hi @rlenders 

>>Are there any disadvantages to releasing all the queued requests pretty-much simultaneously, when the 
>>cool-off period is up? In the calculate-when-to-retry approach of the above Polly example, you could 
>>introduce some randomisation or regular separation.

>I'm not sure what you mean. Could you elaborate on this?

Well, I am in to the realms of speculation here about the third-party API (and speculation may not help: as you rightly point out, your real challenge is to know what the API's rate-limit is!).  I just wondered - if it is a third-party API that limits users according to how often they access it - whether hitting it simultaneously/ very densely with multi-thousand requests might risk triggering a red flag again at their end.

>It seems rate limiting is only useful when you know exactly how much requests per timespan are allowed

Completely.  If you could determine (perhaps by experiment) what the API's rate-limit is, then a rate-limit calling strategy could be useful, because you could put calls through at a (matching) steady throughput, without having to break and potentially queue 1000s.  But as long as you don't know - and in case the API changes its rate limit rules anyway - the wait-and-retry stategy (assuming memory bulge is managed) seems like a very good strategy. :+1: 

Thanks @rlenders for the interesting discussion around a Use Case I hadn't thought of for Polly.  Let us know if you need anything else!

**Comment by reisenberger** [comment]
Closing due to lack of recent activity.  Please re-open if further questions / further support is required.
