### ISSUE TITLE
Invoke OnRetry with the same resilience logic as delegate

### ISSUE THREAD

**Issue by beavis88** [App-vNext/Polly#2314]
### What are you wanting to achieve?

Hello. Is it possible to treat the OnRetry event as a delegate for the Retry strategy using the same resilience pipeline, i.e. OnRetry is treated as part of the pipeline delegate from an error handling perspective? For example, I have 5 retries for some delegate, but OnRetry needs to do some work, which in turn can also throw transient exceptions (the sames as delegate) and I want each such error to be subtracted from the original 5.

### What code or approach do you have so far?

-

**Comment by martincostello** [comment]
No, that's not possible. It would need a lot of complicated book-keeping (what if you wanted to retry in the OnRetry, and then that wanted the same, and so on and so on...?).

You'd either have to use a new pipeline in side your `OnRetry`, or try a different approach such as using a [fallback strategy](https://www.pollydocs.org/strategies/fallback.html) when all your retries are exhausted.
