### ISSUE TITLE
Latest stable 5.0.6 package description incorrectly claims .NET 4.0 compatibility

### ISSUE THREAD

**Issue by dannydwarren** [App-vNext/Polly#233]
Description of 5.0.6: 
Polly is a .NET 4.0 / 4.5 / .NET Standard 1.0 library that allows developers to express resilience and transient fault handling policies such as Retry, Circuit Breaker, Timeout, Bulkhead Isolation and Fallback in a fluent and thread-safe manner.

.NET 4.0 is listed however trying to install in a .NET 4.0 project fails. Note that the dependencies report no .NET 4.0 support, only .NET 4.5.

**Comment by reisenberger** [comment]
Hi @dannydwarren ! Net40 support is provided via [a separate nuget package](https://www.nuget.org/packages/Polly.Net40Async/) (also available as a signed package) as [described in the main Polly readme](https://github.com/App-vNext/Polly#installing-via-nuget).   

.NET4.0 support was [moved wholly out of the main package into this separate package at v5.0.0](https://github.com/App-vNext/Polly/blob/master/src/Polly.nuspec#L62).

**Comment by reisenberger** [comment]
Hi @dannydwarren !  I've removed the .NET4.0 reference from the main `Polly.nuspec`, to make this less confusing.  Thanks for pointing it out!  It will update on Nuget next time we have cause to publish a package.

**Comment by dannydwarren** [comment]
Perfect. Thank you!
