### ISSUE TITLE
[Question]: Are retry budget as described in this excellent article

### ISSUE THREAD

**Issue by buckleyGI** [App-vNext/Polly#2348]
### What are you wanting to achieve?

In this [Good Retry, Bad Retry: An Incident Story](https://medium.com/yandex/good-retry-bad-retry-an-incident-story-648072d3cee6) the strategy of "Retry budget" is described
Retry budget (or adaptive retry): Retries are always allowed, but within a budget, for example, no more than 10% of the number of successful requests. In case of service problems, it can receive no more than 10% of additional traffic.

Reading the polly [documentation ](https://www.pollydocs.org/strategies/index.html) it's not clear that this is present out of the box or can be achieved with combing some of the primitives. It's a great read that article!

### What code or approach do you have so far?

Circuit breaker but it's an all or nothing strategy, not configurable as with Retry Budget.

**Comment by martincostello** [comment]
We don't have _Retry Budget_ as a first-class concept for retries (in fact I've not heard of that as a specific term before).

The concept sounds like a hybrid of our retry, circuit-breaking (the ability to track successful vs. failed operations) and rate-limiting (capping the total throughput) in terms of the strategies we provide.

I'm not sure there would be an easy way to implement this with the library as-is today with our existing strategies without reimplementing/refactoring a lot of the state tracking used by circuit breakers to control whether or not do do retries based on some global state tracking the success vs. failure rate and the overall throughput.
