### ISSUE TITLE
Xamarin.Forms (v2.3.3.193): PCL Compiler Error after added Polly v.5.0.6

### ISSUE THREAD

**Issue by ericbrunner** [App-vNext/Polly#238]
Hi,

Today I added Polly v5.0.6 to my Xamarin.Forms PCL (Xamarin.SDK v2.3.3.193) and get that compiler error

```
1>c:\Source\VSTS\TruckerApp\trucker_rolsped\StoreManager\OfflineSyncStoreManager.cs(20,7,20,12): error CS0246: The type or namespace name 'Polly' could not be found (are you missing a using directive or an assembly reference?)
1>c:\Source\VSTS\TruckerApp\trucker_rolsped\StoreManager\OfflineSyncStoreManager.cs(21,7,21,12): error CS0246: The type or namespace name 'Polly' could not be found (are you missing a using directive or an assembly reference?)
1>  Output Item(s): CscCommandLineArgs= (TaskId:23)
1>Done executing task "Csc" -- FAILED. (TaskId:23)
1>Done building target "CoreCompile" in project "trucker_rolsped.csproj" -- FAILED.: (TargetId:76)
```

I verified that Polly is in references assemblies. I only installed Polly in the PCL because I only need it there.

I put my project config at gist: https://gist.github.com/ericbrunner/636b2f6045e6a78716d3692537c89a0e
Here the Code where I use it: https://gist.github.com/ericbrunner/44fe9d0aeb82227ebc38d2b3b53a32c6

Hope you can help me up right now.

thanks
Eric

**Comment by reisenberger** [comment]
Closing as very similar to #237, under which there is more extensive discussion.  If there are questions specific to this not covered by #237, please feel free to re-open.
