### ISSUE TITLE
[Question]: Configuring Polly Circuit Breaker to Allow Failure Ratio in Half-Open State

### ISSUE THREAD

**Issue by mary-khamoyan** [App-vNext/Polly#2381]
### What are you wanting to achieve?

Hello,

Is there a way to configure Polly’s circuit breaker so that, during the half-open state, it allows a failure ratio rather than transitioning back to open on a single failure? 
The issue I’m encountering is that, with only one test request allowed in the half-open state, a flaky or transient failure causes the circuit to reopen and triggers another wait for the break duration.

Is it possible to make this behavior configurable, or are there alternative approaches to handle transient errors during the half-open state without immediately transitioning to open state?

### What code or approach do you have so far?

Testing example

```
public static CircuitBreakerStrategyOptions<HttpResponseMessage> GetCircuitBreakerStrategyOptions()
{
    return new CircuitBreakerStrategyOptions<HttpResponseMessage>
    {
        ShouldHandle = new PredicateBuilder<HttpResponseMessage>().Handle<TaskCanceledException>().HandleResult(x => x.StatusCode == System.Net.HttpStatusCode.InternalServerError || x.StatusCode == System.Net.HttpStatusCode.ServiceUnavailable),
        FailureRatio = 1d,
        SamplingDuration = TimeSpan.FromSeconds(10), 
        MinimumThroughput = 10,
        BreakDuration = TimeSpan.FromSeconds(30), 
        OnOpened = static args =>
        {
            return ValueTask.CompletedTask;
        },
        OnClosed = args =>
        {
            return ValueTask.CompletedTask;
        },
        OnHalfOpened = args =>
        {
            return ValueTask.CompletedTask;
        }
    };
}
```

**Comment by peter-csala** [comment]
The current implementation does not support this use case (and if my memory serves well none of the previous versions have supported either). The CB allows a single request to pass through (a _probe_) after the `BreakDuration`. Based on the outcome it either transitions into `Open`or into `Closed` state.  

The pattern itself is generic enough to allow the described behavior.  Even [Microsoft Learn](https://learn.microsoft.com/en-us/azure/architecture/patterns/circuit-breaker#solution) describes it this way:

> Half-Open: A limited number of requests from the application are allowed to pass through and invoke the operation. If these requests are successful, it's assumed that the fault that was previously causing the failure has been fixed and the circuit breaker switches to the Closed state (the failure counter is reset). If any request fails, the circuit breaker assumes that the fault is still present so it reverts to the Open state and restarts the timeout timer to give the system a further period of time to recover from the failure.

**Comment by mary-khamoyan** [comment]
@peter-csala Thanks for the clarification!
