### ISSUE TITLE
RetryForever with Wait

### ISSUE THREAD

**Issue by Mark-Broadhurst** [App-vNext/Polly#24]
It would be useful to be able to include a delay while waiting forever.

Currently I'm using int.MaxValue as a work around.

In a similar vein it would be handy to have the error count in the lambda so we can log on a decaying scale, I appreciate that this would eventually throw a Overflow Exception but just a hard cap at int.MaxValue would be fine.

**Comment by sarus** [comment]
Would love to see something like this as well.  Basically an ability to retry with a delay, hit a max delay and then keep retrying at the max delay.

So something like:

Wait 1 Second
Wait 2 Seconds
Wait 5 Seconds
Wait 10 Seconds
Wait 30 Seconds
Wait 60 Seconds
Wait 60 Seconds
Wait 60 Seconds
(Repeat Forever)

Thank you for providing this great library!

**Comment by reisenberger** [comment]
Closed via #79
