### ISSUE TITLE
[Question]: Why doesn't Polly accept StreamContent? 

### ISSUE THREAD

**Issue by tenondra** [App-vNext/Polly#2419]
### What are you wanting to achieve?

When using custom redirect handler, we clone the new redirection request into `StreamContent`. 
My question is, why doesn't polly accept stream content with resoning "StreamContent cannot be cloned."
as it obviously can be cloned? I am trying to figure out if we can use StringContent, but in the meantime - why?

### What code or approach do you have so far?

so far this method of cloning worked with no issues for us

```c#
var memoryStream = new RecyclableMemoryStream(_recyclableMemoryStreamManager);
await request.Content.CopyToAsync(memoryStream).ConfigureAwait(false);
memoryStream.Position = 0;
newRequest.Content = new StreamContent(memoryStream );
```

**Comment by martincostello** [comment]
Where is this exception coming from? Are you sure it's coming from Polly?

**Comment by tenondra** [comment]
oh, sorry, my bad, I thought `AddStandardHedgingHandler` was part of polly, and I was so sure I did not check the namespace.. anyway, if you're interested, it's this code here:
https://github.com/dotnet/extensions/blob/c08790cf79d2d8feaa53751f039f38638741a154/src/Libraries/Microsoft.Extensions.Http.Resilience/Internal/RequestMessageSnapshot.cs#L78
