### ISSUE TITLE
Disposing intermediate results with HandleResult

### ISSUE THREAD

**Issue by georgiosd** [App-vNext/Polly#250]
Hi :)

Let's say you're invoking a method that returns an `IDisposable` value and you're using `Policy.HandleResult` to retry values that have errors.

How would you go about disposing intermediate results (i.e. results between retries)?

Thanks!

**Comment by reisenberger** [comment]
@georgiosd All the variants of retry policies have overloads allowing you to specify an `onRetry` / `onRetryAsync` delegate.  The delegate is invoked when the policy handles an exception or `TResult`.  The handled exception or `TResult` is passed to it as an input parameter.  So, you should be able to hook something into that delegate to receive a `TResult` that has been deemed 'needs a retry', and dispose it.

Let us know if this solves what you need!

**Comment by georgiosd** [comment]
It does, thank you! I hadn't noticed the callback includes `TResult`.
