### ISSUE TITLE
Remove project.json and migrate to new VS2017 .csproj format

### ISSUE THREAD

**Issue by reisenberger** [App-vNext/Polly#258]
Remove use of `project.json` and `dotnet migrate` to new VS2017 .csproj format 

Up-for-grabs: I can (will some point) do this, but my time can also go on new functionality if anyone else wants to pick this off.

**Comment by Kesmy** [comment]
All of the projects can be upgraded to the new format, except PCL.Specs. Do you really want to only upgrade one of them?

**Comment by reisenberger** [comment]
@Kesmy Yes, we want to upgrade them all.  Detailed comments coming on #277.

**Comment by reisenberger** [comment]
Closed by #277
