### ISSUE TITLE
Where is Circuit Breaker State stored?

### ISSUE THREAD

**Issue by nareshkhatri81** [App-vNext/Polly#259]
Hi Team,
i would like to know where Circuit Breaker state is stored.
is it stored in memory ?
is it possible to extend that and store it in external storage like redis ?
i have multiple containers running and if one container has tried calling service and it has tripped the circuit then i don't want other containers to call the service again which is tripped already by one container till circuit is opened again ?

Thanks,
Naresh Khatri

**Comment by reisenberger** [comment]
Hi @nareshkhatri81 .  Thank you for your interest in Polly!  `CircuitState` is stored in memory.  

See #215 for discussion of external storage for Circuit Breaker State.  

One potential issue with just saving the circuit state in Redis is that it could lead to the "single bad node poisons all others" problem discussed [here](https://github.com/App-vNext/Polly/issues/215#issuecomment-274251199).  Thus, discussion for implementing a distributed circuit breaker in Polly has tended towards implementing a quorum-driven approach (break locally if any >=_N_ nodes in the distributed circuit have broken).

**Comment by reisenberger** [comment]
Proposal for DistributedCircuitBreaker now posted as #287

**Comment by reisenberger** [comment]
Closing as duplicate, main discussion now on #287
