### ISSUE TITLE
How to retry logic for up to N minutes?

### ISSUE THREAD

**Issue by darxis** [App-vNext/Polly#261]
Hi,

I would like to write a policy to retry my logic until it succeeds or until a "retry timeout" happen (not a "logic timeout").
With `Policy.Handle<Exception>().Retry(3)` I can tell Polly to retry up to 3 times. What I would like is to `Policy.Handle<Exception>().Retry(TimeSpan.FromMinutes(5))`.

Is there a **clean** way of doing this using Polly API?
Thanks!

**Comment by reisenberger** [comment]
Hi @darxis !

+ [`TimeoutPolicy`](https://github.com/App-vNext/Polly/wiki/Timeout) provides the ability to time out any execution.
+ [`PolicyWrap`](https://github.com/App-vNext/Polly/wiki/PolicyWrap) provides the ability to compose multiple policies into a single policy for later use. 

For your Use Case, wrap a timeout policy around any retry policy you like.  For example, the following should retry with 10 second delays between tries, up to a 5-minute limit:

```
Policy timeoutAfterFiveMinutes = Policy.Timeout(TimeSpan.FromMinutes(5));
Policy retryEveryTenSeconds = Policy.WaitAndRetryForever(() => TimeSpan.FromSeconds(10));
Policy tryEvery10SecondsUpTo5Minutes = timeoutAfterFiveMinutes.Wrap(retryEveryTenSeconds);
// You could create the above all in one statement.  I used interim variables just to make the components clearer.

// Usage
tryEvery10SecondsUpTo5Minutes.Execute(...);
```

Comments to [this stackoverflow question](https://stackoverflow.com/questions/43201898/use-a-specific-timeout-connected-to-a-retrypolicy) include various working dotnetfiddle examples and discussion of further nuances.  Async examples, and for much shorter timescales (because dotnetfiddle limits overall execution time), but the principles are the same.

Let us know if this is what you need!

**Comment by darxis** [comment]
@reisenberger Thanks, this is what I was searching for!

**Comment by TylerNielsen** [comment]
I had a follow up question to this thread. If I'm reading the documentation on Timeout Policy correctly, this may be slightly different than what some users may expect based on OP ask. 

Based on the [Timeout Policy documentation](https://github.com/App-vNext/Polly/wiki/Timeout), it seems that Timeout Policy will cause a synchronous task to be put on a separate thread and abandoned if the timeout is hit. I suspect OP might have been asking for a Policy that would simply _not try again if timeout was reached_, but not necessarily "walk away" from the executing process if it's still going.  If OP wasn't interested in this behavior, I am 😃.

Would there be anyway to let the execution finish but simply not start another retry if the timeout had expired?

**Comment by reisenberger** [comment]
Thanks @TylerNielsen for the question.

>Would there be any way to let the execution finish but simply not start another retry if the timeout had expired?

Yes. Use `TimeoutStrategy.Optimistic` (which operates [only by co-operative cancellation](https://github.com/App-vNext/Polly/wiki/Timeout#optimistic-timeout)) and have your execution simply not honour the `CancellationToken`.  It will then not be interrupted by TimeoutPolicy.  But the retry engine (which [does honour the cancellation token](https://github.com/App-vNext/Polly/blob/4db50346299f62c2373ceba99d2522a8171c9e27/src/Polly/Retry/RetryEngine.cs#L28)) will block any further retry if the timeout has elapsed when a new try is due.

For example:

    public static void Main(string[] args)
    {
        Stopwatch watch = Stopwatch.StartNew();
        var timeoutPolicy = Policy.Timeout(TimeSpan.FromSeconds(4.5)); // TimeoutStrategy.Optimistic by default
        var retryPolicy = Policy.Handle<Exception>().Retry(5, (e, i) => Console.WriteLine("Starting retry " + i + " after elapsed ms: " + watch.ElapsedMilliseconds));
        timeoutPolicy.Wrap(retryPolicy).Execute(() => LongOperation());
    }

    static void LongOperation()
    {
        Console.WriteLine("Starting long task");
        Console.WriteLine("Long work: Delaying 3 seconds");
        Thread.Sleep(TimeSpan.FromSeconds(3));
        Console.WriteLine("Completing long task");
        Console.WriteLine("Oops- no, it's throwing after all...");
        throw new Exception();
    }

([can be tried in .NET Fiddle here](https://dotnetfiddle.net/YN3wl3)), gives this output:

    Starting long task
    Long work: Delaying 3 seconds
    Completing long task
    Oops- no, it's throwing after all...
    Starting retry 1 after elapsed ms: 3033
    Starting long task
    Long work: Delaying 3 seconds
    Completing long task
    Oops- no, it's throwing after all...
    Starting retry 2 after elapsed ms: 6045
    Run-time exception (line 13): The delegate executed through TimeoutPolicy did not complete within the timeout.

Execution is not abandoned after 4.5 seconds; retry 1 is allowed to run to completion, retry 2 is only cued up after 6 seconds; TimeoutPolicy does not abandon execution until it gets a chance at the start of retry 2.  Importantly: if retry 1 had succeeded and was returning a result, the calling code would get that result, not a timeout.  

---

To clarify:

>Based on the Timeout Policy documentation, it seems that Timeout Policy will cause a synchronous task to be put on a separate thread and abandoned if the timeout is hit

That is specific to [`TimeoutStrategy.Pessimistic` for synchronous executions](https://github.com/App-vNext/Polly/wiki/Timeout#additional-notes-pessimistic-timeout-for-sync-executions) only.  To see the difference, if you change the declaration of the policy in the above example to:

    var timeoutPolicy = Policy.Timeout(TimeSpan.FromSeconds(4.5), TimeoutStrategy.Pessimistic);

then you will see instead the behaviour stated as undesirable in your case - that the policy makes the calling thread walk away from waiting for execution after 4.5 seconds.

**Comment by TylerNielsen** [comment]
Thank @reisenberger for the thorough response. I implemented the optimistic strategy as you suggested and see that it's achieving the desired behavior. I guess I had wrongly assumed that I would NEED to implement CancellationToken within the delegate. Thanks again!

**Comment by beavis88** [comment]
@reisenberger 

> Use TimeoutStrategy.Optimistic (which operates only by co-operative cancellation) and have your execution simply not honour the CancellationToken. It will then not be interrupted by TimeoutPolicy. But the retry engine (which does honour the cancellation token) will block any further retry if the timeout has elapsed when a new try is due.

The downside of TimeoutPolicy is it always throws TimeoutRejectedException. What if i need rethrow actual exception like RetryPolicy does?

**Comment by reisenberger** [comment]
See #672
