### ISSUE TITLE
PolicyWrap does not properly support ExecuteAndCapture()

### ISSUE THREAD

**Issue by reisenberger** [App-vNext/Polly#267]
`ExecuteAndCapture/Async()` does not currently give meaningful results on `PolicyWrap`.

`.ExecuteAndCapture(...)` is _intended_ to tell you whether policy execution was successful or failed, defined as:

+ `OutcomeType.Success`: no exception was thrown and return result (if any) was not specified to be handled by the policy
+ `OutcomeType.Failure`: an exception was thrown, or a result was returned which was handled by the policy; subdividing into:
  - `FaultType.ResultHandledByThisPolicy`
  - `FaultType.ExceptionHandledByThisPolicy`
  - `FaultType.UnhandledException`: 

With PolicyWrap, this raises conceptual questions:

+ A PolicyWrap instance does not itself define any exceptions or results to handle; only its constituent policies do.  
+ A PolicyWrap instance may comprise multiple constituent policies, each of which may (by design) handle different exceptions or results.

In that context, we need to define what it means to say a given exception or result was or was not handled by the `PolicyWrap`.

---

## PROPOSAL

`.ExecuteAndCapture(...)` on a `PolicyWrap` should indicate that a given exception or result was handled by the `PolicyWrap` if the outermost policy in the `PolicyWrap` handled it.

**Comment by grokky1** [comment]
Your proposal makes sense.

To address the issue of "which policy does the result relate to", what about 1) providing direct access to the outermost policy, as you've explained, but also 2) include a dictionary which has failure info for each policy, where the key is the policy type or the exception type.

**Comment by reisenberger** [comment]
>Include a dictionary which has failure info for each policy, where the key is the policy type or the exception type (or something like that).

Excellent idea :+1:  : in fact we're planning pretty much that in slightly different form.

When metrics are added to Polly, each policy type will emit events broadly corresponding to where delegate hooks already exist (`onRetry`; `onBreak` etc).  Polly [now carries a Context with each execution](http://www.thepollyproject.org/2017/05/04/putting-the-context-into-polly/).  It is intended that `Context` could (for performance, optionally) capture this stream of events, in addition to any dashboarding that's consuming them.  For those who want to interrogate it programamtically, this would surface chapter-and-verse on 'what the PolicyWrap did internally'.

**Comment by grokky1** [comment]
That sounds really useful. Looking forward to the next version!

**Comment by reisenberger** [comment]
Fix for this issue [coded and pushed to v5.2.1 dev branch](https://github.com/reisenberger/Polly/commit/57d53cf7336196d8fc437d66adf0754dafaf1a2c).  

Hoping to push a few other things into v5.2.1 before releasing this.
