### ISSUE TITLE
Question: Help to distinguish circuitbreaker transition between closed->open from half-open->open

### ISSUE THREAD

**Issue by PilchardFriendly** [App-vNext/Polly#268]
For context, we're using a circuit-breaker to implement a 'liveness-check' on a downstream service.  As long as the down-stream service is available, we have an open-circuit.  This rate-limits the down-stream liveness calls.

We know that the downstream service is available most of the time, so we get a lot of half-open->open transitions.

So:
  closed->open: Our downstream service is up again! Log it!
  half-open->open: The normal state of affairs, different log level
  half-open-closed: Our downstream service just died.  Log it!

How can we detect that middle case?

Cheers

**Comment by reisenberger** [comment]
Hi @PilchardFriendly I think open/closed may be reversed in your question, which may be confusing things.  Open/closed semantics for circuit-breakers (open = blocking, closed = permitting) are opposite to those of a gateway (open = permitting, closed = blocking) .  I've just [extended the circuit-breaker documentation to re-emphasize this, and illustrate why](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker#openclosed-semantics).

If you are looking to detect when the circuit 'recovers' from half-open state to normal, 'healthy' state, that is the half-open->closed transition, and the `onReset` delegate is invoked when that happens - so can be used to detect that case - as [described here](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker#delegates-on-transitions-of-circuit-state--polly-v40).

Let us know if that covers it, or if you need anything else.

**Comment by PilchardFriendly** [comment]
Thanks for the reply.  I agree that I'm describing things in the reversed fashion. 

In *this* case reverse is exactly what i want. An open circuit is healthy, as it means I had a successful health check in the last duration, and don't need to check health again.  A closed circuit to me means the health check failed, i need to reconnect, and retry check for health again.  

I've implemented this and it works fine. I occasionally get false positives, when the circuit is open, but the service is failing.  But I can handle those with retries/timeouts.

So, in *this* case - onReset means my health check failed.

But my question hasn't changed.

How do I tell the difference between a transition from closed->open and from half-open->open?

**Comment by reisenberger** [comment]
@PilchardFriendly  Ok, thanks for the clarification. I see that this implementation intentionally inverts the circuit-breaker to re-purpose it as a quasi-[RateLimitPolicy](https://github.com/App-vNext/Polly/wiki/Polly-Roadmap#rate-limit-policy).

Re:

>How do I tell the difference between a transition from closed->open and from half-open->open?

Two options come to mind:

[1] Polly circuit-breakers could be extended to offer overloads where the `onBreak` delegate takes the transitioning-_from_ state as an input parameter.  This could potentially be useful for standard circuit-breakers too.  I don't have time to work on this immediately (we want to focus dev resource to pick off [major items on the roadmap](https://github.com/App-vNext/Polly/wiki/Polly-Roadmap)), but happy to provide guidance, if you (or anyone else) is interested in taking a whack at a PR?

[2] Without changes to Polly, you could currently distinguish closed->open from half-open->open, by tracking the preceding transition:

+ a sequence `onBreak` -> `onBreak` implies the second represents half-open->open
  - (or `onBreak` -> `onHalfOpen` -> `onBreak` ditto, if you are also tracking `onHalfOpen`)
+ a sequence `onReset` -> `onBreak` implies the second represents closed->open

Hope that helps, but very happy also to answer further questions.

**Comment by PilchardFriendly** [comment]
That's an awesome reply.  Thankyou.

I've written up something like this:...

```
private static readonly object CircuitOpen = new object();
private static readonly object CircuitClosed = new object();
private static void DeDuplicate<T>(ref T monitor, T t, Action act) where T:class
{
     var last = Interlocked.Exchange(ref monitor, t);
     if (!ReferenceEquals(last, t)) act();
 }

// For each circuit breaker
private object _livenessUpCircuitState;
var breakServiceWhenLivePolicy = Policy
    .HandleResult(true)
    .CircuitBreaker(
        handledEventsAllowedBeforeBreaking: 1,
        durationOfBreak: TimeSpan.FromSeconds(1), 
        onBreak:(result, span, ctx) => DeDuplicate(ref _livenessUpCircuitState, CircuitOpen, () => Logger.TraceInformation($"{ctx.PolicyKey} open")),
        onReset:(ctx) => DeDuplicate(ref _livenessUpCircuitState, CircuitClosed, () =>  Logger.TraceWarning($"{ctx.PolicyKey} closed")))
    .WithPolicyKey($"{policyKey}:live-up:circuitBreaker");
```

**Comment by reisenberger** [comment]
Closing.  Have extracted the 'up-for-grabs' item:

> [1] Polly circuit-breakers could be extended to offer overloads where the onBreak delegate takes the transitioning-from state as an input parameter.

more clearly as #325.
