### ISSUE TITLE
Allow Fallback policies to take the handled error as input parameter

### ISSUE THREAD

**Issue by reisenberger** [App-vNext/Polly#278]
There may be cases where it would be useful if [`FallbackPolicy`](https://github.com/App-vNext/Polly/wiki/Fallback) could provide a fallback value based on the exception or result that has just been handled.

Issue #272 illustrates an example.

_Up-for-grabs_: The implementation for this would be very similar to the pattern for #265, whose solution visible [here](https://github.com/reisenberger/Polly/commit/94b41211f9ae8e5c323fbc8712202d2e67cc7e1a).  I can provide more pointers for anyone interested in tackling this.

**Comment by ExtRemo75** [comment]
See Pull request #303, ready for review

**Comment by reisenberger** [comment]
Closed via #303
