### ISSUE TITLE
Question: ISyncPolicyTResult marked internal

### ISSUE THREAD

**Issue by shreyasn995** [App-vNext/Polly#285]
While using Polly for work I noticed that the ISyncPolicy<TResult> interface is marked as internal. I could not find any indication in the documentation or code that this might be intentional, and think that its a bug.

If the decision to make this interface internal was deliberate, what are the reasons?

**Comment by reisenberger** [comment]
@shreyasn995  Thanks for identifying this.  Fixed in #286.

**Comment by reisenberger** [comment]
@shreyasn995 Thanks for identifying. Fix now released to nuget.
