### ISSUE TITLE
Downside of separating Policy and Policy.Result

### ISSUE THREAD

**Issue by cppcraze** [App-vNext/Polly#289]
Separating sync policy and async policy is already a bit not ideal, but regardless of sync or async, separating void/Result based on the return value of the user delegate is not a good choice either.

Think about this common scenario. Nowadays many service provides a SDK besides providing those awesome service. In general the SDK follows OO design and uses structural data to talk with the service. So different functions inside SDK might have different return types. When we want to apply Polly circuit breaker to the SDK, it's hard. Because we need to keep single instance of CircuitBreaker, but single instance of CircuitBreaker can't be used to any user delegate. Are anybody aware of this pain?

Suggestion would be: combine Policy[Async] and Policy[Async]<T> to a single non-template Policy[Async] class and provide both:
    - Execute[Async]: execute a user delegate that doesn't return anything.
    - Execute[Async]<TResult>: execute a user delegate that returns something.

NOTES:  SDK is completely owned by 3rd party. In general it can't be changed.

**Comment by reisenberger** [comment]
@cppcraze Are you using `.Handle<TResult>(...)` clauses?  ie, Do the third-party APIs in your scenario return errors as result-values that you want/need to handle with your policies? 

If not, the non-generic versions of the policies already provide what I think your suggestion asks for.  The non-generic `Policy` already has [void-returning overloads](https://github.com/App-vNext/Polly/blob/53514471b0ab0320d6864ec7fb6afc84d3508b74/src/Polly.Shared/Policy.cs#L31-L149) and [TResult-returning, generic _method_ overloads](https://github.com/App-vNext/Polly/blob/53514471b0ab0320d6864ec7fb6afc84d3508b74/src/Polly.Shared/Policy.cs#L153-L310).

So the same non-generic `CircuitBreakerPolicy` instance can be used for void-returning and for `.Execute/Async<TResult>(...)` for multiple `TResult` types.

--- 

If you (/anyone in the same scenario) has `.Handle<TResult>(...)` clauses in the mix, I can provide further commentary/suggestions.

Some reasons for the existence of the generic-typed `Policy<TResult>` when `.Handle<TResult>(...)` is in use are described in [this wiki page](https://github.com/App-vNext/Polly/wiki/Non-generic-and-generic-policies).  

Having the generic-typed `Policy<TResult>` policies when `.Handle<TResult>(...)` is in use does (as you say) create some of the compromises you describe.  Otoh, _not_ having the generic-typed `Policy<TResult>` policies would create some of the pit-of-failure compromises described in that wiki article.

**Comment by cppcraze** [comment]
@reisenberger, ah, thanks for pointing it out. Sorry, I overlooked the part in PolicyAsync.cs. Yes, it just works the way I want.
