### ISSUE TITLE
Ability to specify a zero retry or new method called NoRetry()

### ISSUE THREAD

**Issue by eldiosyeldiablo** [App-vNext/Polly#29]
My use case is that I am using Polly not as a retry mechanism but instead as a catch exception by type and perform an action.

var policy = Policy
	.Handle<NotImplementedException>(ex => { errorCode = "not implemented"; return true; })
	.Or<Exception>(ex => { errorCode = "server_error"; return true; })
	.NoRetry();
policy
	.Execute(() =>
		{
			throw new ApplicationException("fun");
		}

**Comment by Plasma** [comment]
+1

Would like this just because I have a code path that wants to explicitly disable retries for a certain web request (if it fails, never try a second time etc) and not being able to just pass zero to the retry count is a bit annoying.

**Comment by joelhulen** [comment]
This does seem like a useful scenario. @eldiosyeldiablo, did you end up working around this limitation by cloning the repo and making modifications yourself, or some other way?

**Comment by eldiosyeldiablo** [comment]
Yes I did work around it by doing this. With .net 4.6 exception filters I maybe able to rewrite this.
''' csharp
bool skip = false;
					//Wanted to avoid if else on exception catching logic
					//Polly gets close but its api forces a retry so abusing it a little.
					Policy
						.Handle<SecurityTokenExpiredException>(ex => { errorCode = OAuthErrorCodes.token_expired; return true; })
						.Or<SecurityTokenInvalidAudienceException>(ex => { errorCode = OAuthErrorCodes.invalid_scope; return true; })
						.Or<Exception>(ex => { errorCode = OAuthErrorCodes.server_error; return true; })
						//Ideally retry Zero but Polly does not let you do zero
						.Retry((ex, i) =>
						{
							//Save it for later
							exception = ex;
						})
						.Execute(() =>
						{
							if (skip)
								return;
							skip = true;

'''

**Comment by reisenberger** [comment]
Hi @eldiosyeldiablo @Plasma Many people have requested this (retry count of 0), and there is an open PR #37 which addresses this.  We hope to get this merged soon - please see the comments in #37, and feel free to volunteer to fix it up when the right time comes over the following days ...

**Comment by reisenberger** [comment]
Closed via #37.

Closing given that the retry-zero-times functionality (asked for by several people) has been delivered.  
However, @eldiosyeldiablo , if you feel a wider discussion on exception filtering using Polly is merited, please feel free to comment further!  I agree that exception filters in C# 6.0 will also contribute in this area.
