### ISSUE TITLE
Fallback Policy with dynamic result

### ISSUE THREAD

**Issue by udlose** [App-vNext/Polly#292]
I was wondering if you have any direction on adding request-based data to a Fallback policy for an API.  I have to add some info from the HTTP Headers (specific to each request) to the "default" value returned from the Fallback Policy covering that API.  TIA.

**Comment by reisenberger** [comment]
@udlose . Do you have (iiuc) that HTTP header information in hand in the code before you execute through the policy?  If so, you can achieve what I think you are after by using a `Context` which travels with each call, to pass information between `Execute` and the `fallbackAction` .

All the `Execute/Async/AndCapture()` execute variants have overloads where you can [pass in a `Context`](https://github.com/App-vNext/Polly/blob/eeb03842fd3dbad10557873abd9af26b9abd6707/src/Polly.Shared/PolicyAsync.cs#L307) or [dictionary-like data that will get placed on the `Context`](https://github.com/App-vNext/Polly/blob/eeb03842fd3dbad10557873abd9af26b9abd6707/src/Polly.Shared/PolicyAsync.cs#L319).  

`FallbackPolicy`  has configuration overloads where the `Context` can be an [input parameter to a func that returns the fallback value](https://github.com/App-vNext/Polly/blob/eeb03842fd3dbad10557873abd9af26b9abd6707/src/Polly.Shared/Fallback/FallbackSyntaxAsync.cs#L220).

If that doesn't cover it (I've had to make some assumptions), please do elaborate and we can help further!

Thanks

**Comment by udlose** [comment]
Thank you for your reply!  You understood correctly.  I do have the information available and will take a look at using the `Context`.  The problem I was trying to solve was avoiding the overhead of creating the policies every time they are used and instead create them upfront and cache them.  The problem came when I needed to create a Fallback response that was specific to each request.  I wasn't sure if using the context was the right way to go - or using a lambda for the creation of the Fallback response.  The latter seemed to hang me up though.

**Comment by reisenberger** [comment]
:+1:  @udlose  .  There are some code examples also in this [blog post](http://www.thepollyproject.org/2017/05/04/putting-the-context-into-polly/) (they are based around retry, not fallback, but the concepts are the same).

**Comment by udlose** [comment]
@reisenberger - so I looked at using the `Context` to build the `Fallback`. The problem I have is that I don't have access to the `Context `for the `fallbackValue` parameter - `Context` (from what I've seen) is only available in the event lambdas.  Maybe I'm doing something wrong?

            `var fallbackPolicy = Policy<HttpResponseMessage>
                .Handle<Exception>()
                .FallbackAsync(BuildFallback(), onFallbackAsync: async (result, context) =>
                {
                    await Task.Run(() => _log.Error($"{context.PolicyKey} at {context.ExecutionKey}: fallback value substituted, due to: {result.Exception}."));
                });

            //wrap the circuit breaker with a wait/retry
            var policyWrap = Policy.WrapAsync(waitAndRetryPolicy, circuitBreakerPolicy, fallbackPolicy)
                                    .WithPolicyKey(Key);`

**Comment by reisenberger** [comment]
Hi.  Which version of Polly are you using?  The ability to use context in the fallback delegates was [added in v5.3.0](https://github.com/App-vNext/Polly/blob/master/CHANGELOG.md#530).

**Comment by udlose** [comment]
5.3.1

**Comment by reisenberger** [comment]
Hi @udlose !  What you're after is covered by Fallback configuration overloads which take a `Func` to return the fallback value, rather than a pre-computed value.  

The principle is shown in the [second example here](https://github.com/App-vNext/Polly/wiki/Fallback#tresult-returning-calls) or [here](https://github.com/App-vNext/Polly/tree/eeb03842fd3dbad10557873abd9af26b9abd6707#fallback).

I've just seen the edit [here](https://github.com/App-vNext/Polly/issues/292#issuecomment-321891474).  The Func isn't executed unless needed ([this test demonstrates](https://github.com/App-vNext/Polly/blob/eeb03842fd3dbad10557873abd9af26b9abd6707/src/Polly.SharedSpecs/Fallback/FallbackTResultAsyncSpecs.cs#L121)), so this meets:

>the construction of the Fallback [doesn't] actually occur until/unless the FallbackPolicy is actually executed

A specific async-TResult overload taking `Context` as an input parameter for computing the fallback is [here](https://github.com/App-vNext/Polly/blob/eeb03842fd3dbad10557873abd9af26b9abd6707/src/Polly.Shared/Fallback/FallbackSyntaxAsync.cs#L220).

Using this, you can configure your policy as, eg:

```
var fallbackPolicy = Policy<HttpResponseMessage>
    .Handle<Exception>()
    .FallbackAsync(fallbackAction: async (context, token) => await BuildFallbackAsync(context), onFallbackAsync: async (result, context) =>
    {
        await Task.Run(() => _log.Error($"{context.PolicyKey} at {context.ExecutionKey}: fallback value substituted, due to: {result.Exception}."));
    });
```

**Comment by udlose** [comment]
Thank you. That seems to work!
