### ISSUE TITLE
Polly interface - easy transition?

### ISSUE THREAD

**Issue by tynor88** [App-vNext/Polly#293]
Is it possible to easily transition to the new interfaces provided by Polly, for replacing previous code dependent on the Policy class?

```cs
try
{
	int retryCount = 0;
	await Policy
		.Handle<SqlException>()
		.WaitAndRetryAsync(3, retryAttempt => TimeSpan.FromMilliseconds(0.1 * retryCount++),
			(ex, timeSpan) => {
				_sqlConnection.Close();
			})
		.ExecuteAsync(async () => 
		{
			await _sqlConnection.OpenAsync();
			await _sqlConnection.Query<Test>("SELECT * FROM Test");
		});
}
finally
{
	_sqlConnection.Close();
}
```

How would I both do "WaitAndRetryAsync" and "ExecuteAsync" with IPolicyAsync as I need to make sure to open and close the connection to the DB while retrying?

**Comment by reisenberger** [comment]
@tynor88  Could I ask for some clarifications?

Are you looking to separate policy definition and usage? (ie you define the policy outside this method and pass it in as an `IRetryPolicy` or `IPolicyAsync`).  

In that scenario, you wouldn't be able to close over the `_sqlConnection` variable in the way the posted code does.  The solution to this is to use the `Context` that Polly can flow with each execution.  I can provide further info, but the scenario and solution are essentially the same as in #292.  This [blog post](http://www.thepollyproject.org/2017/05/04/putting-the-context-into-polly/) also gives some code examples.

If that was not the question, could you clarify?

**Comment by tynor88** [comment]
@reisenberger Thanks for getting back, and sorry for not expressing myself clearly enough. 

What I want to achieve, is to make my code more testable by using [DI as described in the wiki](https://github.com/App-vNext/Polly/wiki/Unit-testing-with-Polly#1-i-want-to-unit-test-what-my-code-does-independent-of-polly-policies-i-apply). For that I need to **inject policies** rather than relying on the _Policy_ class directly.

I just cannot seem to figure out how I should structure the above mentioned code, to use the _interfaces_ rather than the _Policy_ class. I primarily use Polly for retrying DB inserts / reads and various API calls.

> Are you looking to separate policy definition and usage? (ie you define the policy outside this method and pass it in as an IRetryPolicy or IPolicyAsync).

Not necessarily - but if this is the only way to get rid of the dependency on the Policy class, then yes. 

> The solution to this is to use the Context that Polly can flow with each execution. I can provide further info, but the scenario and solution are essentially the same as in #292. This blog post also gives some code examples.

Can you provide an example of how to achieve this with SqlConnection?

**Comment by reisenberger** [comment]
>sorry for not expressing myself clearly enough.

Not a problem, just want to make sure our advice is focused on what you need.

Re:
>>Are you looking to separate policy definition and usage? (ie you define the policy outside this method and pass it in as an IRetryPolicy or IPolicyAsync).

>Not necessarily - but if this is the only way to get rid of the dependency on the Policy class, then yes.

Injecting policies to make the code more testable does imply separating policy definition and usage.  Rather than declaring the policy within the given class/method (which means you can't change it for testing), you declare it outside, so that it (the dependency) can be injected.  By having it injected, you can then substitute something else in a test.

And because you've separated policy definition from usage, you can't close over the `_sqlConnection` variable any more, so you have to pass it through Polly's execution `Context`

You don't have to switch to interfaces to use DI - you can inject anything, either declared as a concrete `Policy myPolicy` class or an `IPolicyAsync myPolicy` interface, but interfaces is typical.  

A sketch using the code you provided, and Polly interfaces:

```
// Somewhere outside the method or class you define the policy.  Often at app startup.
// This policy definition shows extracting the _sqlConnection instance from the Context.  At the call site, you'll pass it in.
// You don't need the retryCount variable in your original; Polly provides that as the passed in int retryAttempt

IAsyncPolicy myPolicy = Policy
		.Handle<SqlException>()
		.WaitAndRetryAsync(3, retryAttempt => TimeSpan.FromMilliseconds(0.1 * retryAttempt),
			(ex, timeSpan, context) => {
				 ((SqlConnection)context["sqlConnection"])?.Close();
			})


// Where you're actually using the policy - typically, you might inject it through a class constructor and store it in a private field:
// (but there can be other approaches)

    class MyClassUsingThePolicy
    {
        private IAsyncPolicy _myInjectedPolicy;
        MyClassUsingThePolicy(IAsyncPolicy myInjectedPolicy)
        {
            _myInjectedPolicy = myInjectedPolicy;
        }

        public async void MyMethodUsingThePolicy()
        {
            // Assumption: SqlConnection _sqlConnection is declared and assigned somewhere ... 

            try
            {
                await _myInjectedPolicy
                    .ExecuteAsync(async context =>
                    {
                        var sqlConnection = ((SqlConnection)context["sqlConnection"]);
                        await sqlConnection.OpenAsync();
                        await sqlConnection.Query<Test>("SELECT * FROM Test"); 
                    },
                    new Dictionary<string, object>() { { "sqlConnection", _sqlConnection } } // This uses the `.ExecuteAsync(...)` overload that takes dictionary data that will be placed on the `Context`
                    );
            }
            finally
            {
                _sqlConnection.Close();
            }

        }
```

(A few details weren't provided in your original code sample, like the type of `_sqlConnection` ... adjust if the above assumption is not correct)

When testing, you can then pass in a `IAsyncPolicy myStubPolicy = Policy.NoOpAsync()` to the constructor of `MyClassUsingThePolicy`, instead of the real policy, to stub out the effects of Polly from the test.

**Comment by reisenberger** [comment]
Closing due to lack of further discussion.  Please do re-open if we can help further, however.

**Comment by tynor88** [comment]
@reisenberger thanks for the thorough explanation. I've implemented this in my project which is based on [Dapper](https://github.com/StackExchange/Dapper), [Autofac](https://github.com/autofac/Autofac),[Serilog](https://github.com/serilog/serilog), and [Polly](https://github.com/App-vNext/Polly).

For clarification here are some code examples, someone might find them useful:

PolicyDefinitions.cs:
```csharp
    public static class PolicyDefinitions
    {
        private const int SqlRetryAttempts = 3;

        public static IAsyncPolicy SqlQueryRetryPolicy { get; } =
            Policy
                .Handle<SqlException>()
                .WaitAndRetryAsync(SqlRetryAttempts, retryCount => TimeSpan.FromMilliseconds(0.1 * retryCount),
                    (ex, timeSpan, retryCount, context) =>
                    {
                        ((SqlConnection) context["sqlConnection"])?.Close();
                        ((ILogger) context["logger"])?.Warning(ex, "Error executing sql. Trying again... {RetryAttemptsLeft}/{RetryAttemptsTotal}",
                            SqlRetryAttempts - retryCount + 1, SqlRetryAttempts);
                    });
    }
```
IoC Registration (Autofac):
```csharp
builder.Register(f => PolicyDefinitions.SqlQueryRetryPolicy).As<IAsyncPolicy>().InstancePerDependency();
```
Repository.cs:

```csharp
    public class Repository: IRepository
    {
        private const int DefaulCommandTimeout = 10;
        private readonly ILogger _logger;
        private readonly SqlConnection _sqlConnection;
        private readonly IAsyncPolicy _sqlRetryPolicy;

        public RewriteRulesReadRepository(ILogger logger, SqlConnection sqlConnection, IAsyncPolicy sqlRetryPolicy)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            _sqlConnection = sqlConnection ?? throw new ArgumentNullException(nameof(sqlConnection));
            _sqlRetryPolicy = sqlRetryPolicy ?? throw new ArgumentNullException(nameof(sqlRetryPolicy));
        }

        public async Task<RewriteRuleDb> ReadByIdAsync(Guid rewriteRuleId)
        {
            RewriteRuleDb rewriteRuleDb = null;

            try
            {
                await _sqlRetryPolicy
                    .ExecuteAsync(async context =>
                        {
                            string sql = $"SELECT * FROM {RewriteRulesViewName} WHERE Id = @rewriteRuleId";
                            await _sqlConnection.OpenAsync();
                            rewriteRuleDb = await _sqlConnection.QuerySingleOrDefaultAsync<RewriteRuleDb>(sql, new { rewriteRuleId }, commandTimeout: DefaulCommandTimeout);
                        },
                        new Dictionary<string, object>
                        {
                            {"sqlConnection", _sqlConnection},
                            {"logger", _logger}
                        }
                    );
            }
            finally
            {
                _sqlConnection.Close();
            }

            return rewriteRuleDb;
        }
   }
```
