### ISSUE TITLE
Any way to manually reset the Retry Attempt Count? [/ or handle different exceptions with different retry strategies]

### ISSUE THREAD

**Issue by ryanfollmer** [App-vNext/Polly#306]
I have a method using the HttpClient to call an EventSource API (server sent events), which is a long-running connection. If I have a timeout on a HttpClient class that expires before the Server closes the connection, an error is thrown and the Retry policy re-issues the API request to connect to the API. I'm using WaitAndRetryForeverAsync.

In this scenario, reconnecting to the API is part of the spec: https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events

The issue I need to work around is that the retry attempt count keeps increasing since each timeout is an exception. As soon as the method receives an valid server sent event message (but before a timeout could occur) -> that's essentially considered a success - even though the connection could still be open.

Is there a way to manually reset the retryAttempt count after a message is received and yet still have an exponential backoff like below? Sounds like I would need to keep track of my own success or failure attempt counts?.

```
_retryPolicy = Policy
                .Handle<Exception>(ex => !(ex is EventSourceServiceCancelledException))
                .WaitAndRetryForeverAsync(
                    retryAttempt => TimeSpan.FromSeconds(_retryDelay.Seconds * Math.Pow(2, retryAttempt)), 
                    (exception, calculatedWaitDuration) =>
                    {
                        _logger.LogInformation(Resources.EventSource_Logger_Disconnected, calculatedWaitDuration.TotalMilliseconds, exception);
                    });
```

**Comment by reisenberger** [comment]
@ryanfollmer Briefly, as I am on the road at mo:

+ There isn't a way to reset the internal retry count of `WaitAndRetryForeverAsync()` (but the policy does exit each time an execution succeeds, and the count will be reset to zero for the next invocation through the policy).
+ You could (as you say) maintain and reset your own retry count.
+ You can also handle this kind of scenario purely with Polly, using the fact that [PolicyWrap can nest more than one policy of the same type](https://github.com/App-vNext/Polly/wiki/PolicyWrap#using-the-same-type-of-policy-more-than-once-in-a-wrap).  For instance, you can have an inner retry policy that does exponential backoff, for exceptions for which that's appropriate.  Then wrap that with an outer retry policy which catches the timeouts and retries.  When a timeout hits the outer policy and that triggers its retry, it effectively places a new call through the inner policy, so with a fresh (reset to zero) count for the exponential backoff.

Something like this (pseudo-code):

```
var outerRetry = Policy
    .Handle<Exception>(ex => ShouldResetExponentialBackoffAndRetry(ex))
    .RetryForeverAsync(/* probably no delay or backoff; there's already been a long wait since exceptions caught here are due to a timeout, and it's desired to trigger an immediate reconnection attempt? */);
var innerRetry = Policy
    .Handle<Exception>(ex => ShouldRetryWithBackoff(ex))
    .WaitAndRetryForeverAsync(/* code to retry with backoff */);
var combinedRetry = outerRetry.Wrap(innerRetry);
```

Hope that helps - further questions welcome.

**Comment by ryanfollmer** [comment]
Thank you so much for the feedback!
