### ISSUE TITLE
Help wrapping: retry, 2 circuit, 2 fallback

### ISSUE THREAD

**Issue by iojanblog** [App-vNext/Polly#307]
Hi, I need help with wrapping,

I should execute an action with retry and circuit policies, if it fails then execute fallbackAction with circuit2 policy, if it fails just take a defaultAction.

This is how I implement it today, but I wonder how Wrap policy can help me to achieve the same:

```
private async Task<T> ResilientAsync<T>(Func<Task<T>> action, Func<Task<T>> fallbackAction, Func<Task<T>> defaultAction = null)
{
    try 
    {
        return await _retryPolicy.ExecuteAsync(() => FallbackAsync(action, fallbackAction));
    }
    catch (BrokenCircuitException ex) when (defaultAction != null)
    {
        _logger.LogWarning($"*** default fallback = {ex.InnerException.Message}");
        return await defaultAction();
    }
}


private async Task<T> FallbackAsync<T>(Func<Task<T>> action, Func<Task<T>> fallbackAction) 
{
    try
    {
        return await _circuitPolicy.ExecuteAsync(action);
    }
    catch (BrokenCircuitException ex) when (_fallClient != null)
    {
        _logger.LogWarning($"*** resilient fallback = {ex.InnerException.Message}");
        return await _circuitPolicy2.ExecuteAsync(fallbackAction);
    }
}
```

**Comment by reisenberger** [comment]
@iojanblog I am currently on travel, but could provide a detailed example in a few days' time.

**Comment by reisenberger** [comment]
@iojanblog For a first insight, your pattern:
 
```
try
{
    return await _somePolicy.ExecuteAsync(() => FooAsync<T>()); // for Func<Task<T>> FooAsync()
}
catch (BrokenCircuitException ex) when (/*some condition */)
{
    /* some logging */
    return await SomeFallbackAsync<T>();  // for  Func<Task<T>> SomeFallbackAsync()
}
```
 
can be expressed in a `FallbackPolicy` thus:
 
```
FallbackPolicy _fallbackPolicy = Policy<T>
    .Handle<BrokenCircuitException>(ex => /* some condition */)
    .FallbackAsync(fallbackAction: cancellationToken => SomeFallbackAsync(),
        onFallbackAsync: async delegateResult => { /* some logging using delegateResult.Exception */ });
return await _fallbackPolicy.WrapAsync(_somePolicy).ExecuteAsync(() => FooAsync());
```

**Comment by reisenberger** [comment]
So your first method could be expressed something like:

```
private async Task<T> ResilientAsync<T>(Func<Task<T>> action, Func<Task<T>> fallbackAction, Func<Task<T>> defaultAction = null)
{
    FallbackPolicy<T> outerFallback = Policy<T>
        .Handle<BrokenCircuitException>(ex => defaultAction != null)
        .FallbackAsync(
            fallbackAction: cancellationToken => defaultAction(),
            onFallbackAsync: async delegateResult => {  _logger.LogWarning($"*** default fallback = {delegateResult.Exception.InnerException.Message}"); }
        );

    return await outerFallback.WrapAsync(_retryPolicy).ExecuteAsync(() => FallbackAsync(action, fallbackAction));
}
```

Similarly, the second method could refactor to something like:

```
private async Task<T> FallbackAsync<T>(Func<Task<T>> action, Func<Task<T>> fallbackAction) 
{
     FallbackPolicy<T> innerFallback = Policy<T>
        .Handle<BrokenCircuitException>(ex => _fallClient != null)
        .FallbackAsync(
            fallbackAction: cancellationToken => _circuitPolicy2.ExecuteAsync(fallbackAction),
            onFallbackAsync: async delegateResult => {  _logger.LogWarning($"*** resilient fallback = {delegateResult.Exception.InnerException.Message}"); }
        );

    return await innerFallback.WrapAsync(_circuitPolicy).ExecuteAsync(action);
}
```

So, if you then inlined the second method, you could reduce the whole to:

```
private async Task<T> ResilientAsync<T>(Func<Task<T>> action, Func<Task<T>> fallbackAction, Func<Task<T>> defaultAction = null)
{
    FallbackPolicy<T> outerFallback = Policy<T>
        .Handle<BrokenCircuitException>(ex => defaultAction != null)
        .FallbackAsync(
            fallbackAction: cancellationToken => defaultAction(),
            onFallbackAsync: async delegateResult => {  _logger.LogWarning($"*** default fallback = {delegateResult.Exception.InnerException.Message}"); }
        );

     FallbackPolicy<T> innerFallback = Policy<T>
        .Handle<BrokenCircuitException>(ex => _fallClient != null)
        .FallbackAsync(
            fallbackAction: cancellationToken => _circuitPolicy2.ExecuteAsync(fallbackAction),
            onFallbackAsync: async delegateResult => {  _logger.LogWarning($"*** resilient fallback = {delegateResult.Exception.InnerException.Message}"); }
        );

    return await Policy.WrapAsync(outerFallback, _retryPolicy, innerFallback, _circuitPolicy).ExecuteAsync(action));
}
```

There might be a wrinkle if your compile settings complain (rightly) that this particular `onFallbackAsync` delegate doesn't contain any `await`s (I'm assuming your `_logger` is synchronous).  Apply the usual fixes , returning something like [`Task.CompletedTask`](https://msdn.microsoft.com/en-us/library/system.threading.tasks.task.completedtask.aspx) from a non-async delegate, if necessary.  

Let me know if any of that doesn't work or further qs (am pushing this example out during travel).

Thanks

**Comment by iojanblog** [comment]
Thank you, now everything makes sense when Wrapping, just for reference code now looks like this

    private async Task<T> ResilientAsync<T>(Func<Task<T>> action, Func<Task<T>> fallbackAction, Func<Task<T>> defaultAction = null)
    {
        var outerFallback = Policy
            .Handle<BrokenCircuitException>(ex => defaultAction != null)
            .FallbackAsync(
                fallbackAction: cancelToken => defaultAction(),
                onFallbackAsync: ex => { _logger.LogWarning($"*** default fallback = {ex.InnerException.Message}"); return Task.CompletedTask; }
            );

        var innerFallback = Policy
            .Handle<BrokenCircuitException>(ex => _fallClient != null)
            .FallbackAsync(
                fallbackAction: cancelToken => _circuitPolicy2.ExecuteAsync(fallbackAction),
                onFallbackAsync: ex => {  _logger.LogWarning($"*** resilient fallback = {ex.InnerException.Message}"); return Task.CompletedTask; }
            );

        return await Policy.WrapAsync(outerFallback, _retryPolicy, innerFallback, _circuitPolicy).ExecuteAsync(action);
    }

now that is solved should I close this issue, or let it open ?
