### ISSUE TITLE
Is there a way to programmatically open a circuit breaker?

### ISSUE THREAD

**Issue by udlose** [App-vNext/Polly#309]
I'm creating an "admin" page that will include policy statuses, maybe some perf counters about the policies, and (hopefully) the ability to manually Open and Close any CircuitBreakers (for the purpose of end-to-end testing).

Is there a way to force a CircuitBreaker policy to open?  I see the Reset() method on CircuitBreakerPolicy that causes a cicuit to close - but nothing to force an open.

**Comment by reisenberger** [comment]
Hi @udlose ! The [`Isolate()` method](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker#manual-control--polly-v40) should do what you need.

**Comment by udlose** [comment]
smh - I saw that method but misread the comment as "holds the circuit in its current state until "Reset() is called". My apologies for not correctly RTFM :)
