### ISSUE TITLE
Quick question about using Polly name 

### ISSUE THREAD

**Issue by codemerlin** [App-vNext/Polly#310]
Hi Guys,

First off all, thanks a ton for building such a great lib.

We were planning to build a rest client on top of polly.

Will it be ok with you guys, if we call that package polly rest or something with polly name in it.

**Comment by joelhulen** [comment]
@codemerlin Totally okay with that! Just please be kind enough to link back to the Polly project somewhere :)

Looking forward to checking out your library!
