### ISSUE TITLE
How Polly prevents InvalidOperation exception SendAsync

### ISSUE THREAD

**Issue by v-rosa** [App-vNext/Polly#313]
I trying to understand how polly prevent receiving InvalidOperation exception when tries SendAsync() multiple times without recreating the request message.

> InvalidOperation exception: The request message was already sent. Cannot send the same request message multiple times.

```
protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var policy = Policy.TimeoutAsync(20).WrapAsync(Policy.HandleResult<HttpResponseMessage>
                   (response => IsTransientError(response.StatusCode))
                   .WaitAndRetryAsync(_maximalRetries, retryAttempt => CalculateBackoffDelay(retryAttempt)
                   , (exception, timeSpan, retryCount, context) =>
                        {
                            var msg = $"Retry {retryCount} " +
                            $"of {context.PolicyKey} " +
                            $"at {context.ExecutionKey}, " +
                            $"due to: {exception}.";
                            _logger.Warning(msg);
                        }));
            return policy.ExecuteAsync(() => base.SendAsync(request, cancellationToken));
        
}
```

**Comment by reisenberger** [comment]
@v-rosa I'm assuming that `base` in your code sample refers to `HttpClient`.  

The `InvalidOperation exception: The request message was already sent` is part of the `HttpClient` design; Polly can't change that.  There are numerous suggestions for refreshing/cloning the request on StackOverflow though:

+ https://stackoverflow.com/questions/25047311/
+ https://stackoverflow.com/questions/18000583/
+ https://stackoverflow.com/questions/34222873/
