### ISSUE TITLE
Expose AdvancedCircuitBreaker health details

### ISSUE THREAD

**Issue by udlose** [App-vNext/Polly#319]
I have a CB dashboard I'm creating for monitoring the internals of the advanced circuit breaker(s) we have.  It already includes CircuitState and  button to Isolate and Reset the cb.  What I'd like to have access to are some of the other "internals" that are of interest for monitoring and diagnostics - e.g. internal timer until circuit is reset, current count of throughput, running percentage of failed calls over time x (if that's kept track of).  Is this possible? Thoughts?

**Comment by reisenberger** [comment]
Hi @udlose .  Great question.  The intention is to make this kind of information available to dashboards by [raising events from policies, channelling those events into an Rx stream, and aggregating metrics from the event streams](https://github.com/App-vNext/Polly/wiki/Polly-Roadmap#emit-events-aggregate-metrics-to-dashboards) - to provide a generalised approach for all policies, and the ability to aggregate data (eg overall call latency) spanning the multiple policies of a `PolicyWrap`.

Today I wrote up a first proposal/early thoughts paper to take this forward, expect to publish in next few days: please (anyone else, also) join the [slack channel](https://pollytalk.slack.com/messages/C75LUUM4L/) where we can discuss.

A number of other Polly users (@lakario; @ankitbko ; @seanfarrow; @mfjerome; others?) are all also interested, and @lakario @ankitbko and I each have Rx prototypes floating around.

Related: #201; #149.

**Comment by reisenberger** [comment]
Closing as now covered by #326
