### ISSUE TITLE
Could not install package 'Polly 5.3.1' on .NETPortable,Version=v4.5,Profile=Profile259

### ISSUE THREAD

**Issue by pavan7parekh** [App-vNext/Polly#328]
I am working on Xamarin.Forms. Try to update package from NuGet, I am getting below error:

Could not install package 'Polly 5.3.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by reisenberger** [comment]
Hi @pavan7parekh .  I believe the [video from MVP  Houssem Dellai](https://github.com/App-vNext/Polly#videos) describes how to work round this issue in Xamarin (towards the end of the video).  There is also sample code, demonstrating the approach, with the video.

**Comment by pavan7parekh** [comment]
@reisenberger, Thanks for your quick reply. I see this video but not able to find a solution.

**Comment by reisenberger** [comment]
Hi @pavan7parekh .  Re:

>If I downgrade the version of a package to 5.0.6 then it is working fine

New features in [v5.2.0], meant that from then, Polly only supports .NET Standard 1.1 and above, not .NET Standard 1.0.  .Net Standard 1.1 [is not compatible with PCL259, but instead with PCL111](https://github.com/dotnet/standard/blob/master/docs/versions.md#mapping-pcl-profiles-to-net-standard).  The only difference, as I understand, is that Windows Phone Silverlight is excluded.  Does switching to targeting PCL111 work for your scenario?

**Comment by reisenberger** [comment]
@pavan7parekh Did this solve the problem for you?

**Comment by reisenberger** [comment]
Closing due to lack of further response; please do re-open though, if you need further assistance.
