### ISSUE TITLE
Feature Request: Leaky Bucket

### ISSUE THREAD

**Issue by Minx-SigEp** [App-vNext/Polly#330]
There is currently a proposal on the road map to add a Rate-Limit Policy (https://github.com/App-vNext/Polly/wiki/Polly-Roadmap#rate-limit-policy). Amazon's MWS has a throttling algorithm that I would like to be supported by Polly when the Rate-Limit policy becomes available
http://docs.developer.amazonservices.com/en_US/dev_guide/DG_Throttling.html

**Comment by danroot** [comment]
Another scenario where this is needed is calling Azure Cognitive Services.  Basic plan has a 1/s limit and Standard has a 10/s limit.   Trello has a 300/s limit.  It would be nice to proactively limit the client to play nice with these APIs.  Guidance on alternative (retries) would be nice.

**Comment by joelhulen** [comment]
@danroot I can offer guidance on alternative retries/circuit breaker for dealing specifically with Cognitive Services.

Do you want to create a new issue asking for this? I think it'd be a better place to have that conversation for better discoverability.

**Comment by danroot** [comment]
@joelhulen That would be great.  I'd appreciate any guidance you have on this.  I created #412 for this.

**Comment by reisenberger** [comment]
To avoid noise on the 'up-for-grabs' labels (three similar issues), I'm closing this issue in favour of the similar #260 (and noting the idea of Leaky Bucket there).
