### ISSUE TITLE
Support .NET Standard 2.0

### ISSUE THREAD

**Issue by jelical** [App-vNext/Polly#335]
Hi. 
Is such support is planned? I compiled polly in my fork with netstandard2.0, but part of unittests are inconsistently failing in Timeout and CirquitBreaker tests.

**Comment by joelhulen** [comment]
There is currently no plan to update to .NET Standard 2.0. Polly currently using .NET Standard 1.1, which is fully compatible with projects based on .NET Standard / .NET Core 2.0. Because Polly does not use Standard 2.0 features, there's no benefit to migrating to that version at this time. We like to take the approach, as with other libraries, to use the lowest Standard version possible, while supporting all required features, in order to more widely support projects to which Polly is added. Moving to 2.0 would make Polly less compatible with many other projects currently using it..

**Comment by reisenberger** [comment]
Hi @jelical

My initial reaction was as @joelhulen : the Polly .NET Standard 1.1 binaries/nupkgs should be forward compatible to a .NET Core 2.0 app (I have them referenced like that locally).  However, yes, there's been a lot of pain/flux around the .NET Standard/Core tooling, so v happy to hear if further community input on this.  Could add a .NET Standard 2.0 target if it made a significant difference (feedback, anyone?).  (It wouldn't be part of the impending v5.4.0 release, as we usually keep feature/retargeting releases separate.)

@jelical Re tests:

+ Could you post details of the `SystemClock` change you mention?  Was initially surprised at the idea that a Net Standard 1.1 to 2.0 implementation change could break something (but would obviously like to dig in and look!). 

+ Can you post details of the tests which were failing for you?  Is there a public branch of your port to .NET Standard 2.0 I can look at / pull down, to compare with mine? 

+ Some tests - particularly testing timeouts on `TimeoutPolicy` and a few on `WaitAndRetry` - have to rely on measuring elapsed time within certain tolerances.  These can be vulnerable to timing differences in different environments (we had a [run of failures in AppVeyor](https://github.com/App-vNext/Polly/issues/220)).  If timing-related tests are failing in your local environment, try increasing the tolerances similar to in #197, #168, #167, #212 etc.

  - (Obviously, we try to keep those test tolerances as low as possible, to keep the test suite running fast, but have to raise them to make tests reliable.  And everywhere Polly tests can, they instead abstract out the system clock.) 
 
+ Would love to see details of any other test issues.  (Possible some multi-threaded tests could be vulnerable, eg, to subtle changes in underlying thread-pool behaviour.)

Thanks!

**Comment by jelical** [comment]
Hi, @joelhulen 
Here are details:
The tests affected are CirquitBreaker and Timeout. It is obvious result of the static nature of SystemClock class used: when you are running tests in parallel, any change of SystemClock static properties like here 
![image](https://user-images.githubusercontent.com/5307585/31997075-5f8f8f50-b993-11e7-9913-a78149fd6571.png)
immediatelly breaking everything already running .

I changed SystemClock to use AsyncLocal in the context of netstandard2.0 testing.

Pull request here https://github.com/App-vNext/Polly/pull/337

**Comment by udlose** [comment]
My question is what is the reason to upgrade? Are there features that you want to take advantage of? Hopefully, it is not for the sake of doing so just because it is the latest version. IMO, unless you are taking advantage of some new feature, you are only decreasing your compatibility and enforcing a new requirement upon your consumers - undesirable to a 3rd party nuget.

**Comment by jelical** [comment]
Hi, @udlose. We are not talking about upgrade here. We talking about support for **additional** standard/platform and not dropping netstandard1.1. The reason is compatibility with new technologies and code - exactly the same why you have both polly.net40 and polly.net45.  Netstandard1.1 is **defacto** incompatible with netstandard2.0 development

**Comment by joelhulen** [comment]
I'm still not certain there is a need to add an additional target for Standard 2.0. The Standard library differs from .NET Base Class Libraries (e.g. 4.5), in that Standard is an abstraction of BCL API implementations. Think of it as a set of interfaces. If you created various public interfaces for your application that expose different method signatures for your concrete classes, based on which features you want to expose, then the concept is similar.

Refer to [this chart(https://docs.microsoft.com/dotnet/standard/net-standard#net-implementation-support) on the .NET Standard documentation page. The way the chart reads is, select the .NET implementation you are using for your application (such as .NET Core 2.0). The chart will show you what your implementation version advertises as the highest .NET Standard version it supports, a statement that means it also supports previous versions.

As stewards of a widely used .NET library, it is our responsibility to match up the lowest .NET Standard version that provides all of the APIs our library exposes, allowing us to target the widest range of platforms.

In this documentation, you will find the following guidance:

> The higher the version, the more APIs are available to you. The lower the version, the more platforms implement it. In general, we recommend you to target the lowest version of .NET Standard possible.

You had said that "Using netstandard1.x libraries mixed with netstandard2.0 creates a lot of mess and incompatibilities." Can you please elaborate? This does not seem consistent with official documentation. Are you creating a library of your own, or an application that is targeting .NET Standard 2.0?

**Comment by jelical** [comment]
Correct me if I am wrong, but application can't target netstandard, only netcoreappxxx or netxxx.  I have a big project with more that 50 libraries and web projects, build with netstandard2.0 and net4.6.1, I am in the middle of porting effort. I will try to provide you with more concrete examples soon. But (tl;dr;) when I using 2 different nugets dependent on different versions of netstandard, that leads to conflicts. More than that, when i have multiple library projects in my solution, one is net4.6.1, one is netstandard and both are using polly, they are picking different versions of polly that afterward also have conflicts. Sometimes this  can be solved manually, with remapping, sometimes - no, especially in web projects context. It is too many moving parts actually.

**Comment by joelhulen** [comment]
@jelical We have read the .NET Standard documentation, asked around to members of the Microsoft team, and have looked at a number of high profile NuGet packages, such as Newtonsoft.Json, XUnit, FluentValidation, FluentAssertions, StackExchange.Redis, Rx.Net, Refit, ModernHttpClient, Moq, Nancy, Brighter, BenchmarkDotNet, NUnit, AutoMapper, and Serilog. None of them have added .NET Standard 2.0 as a target when 1.x suffices. As stated before, .NET Standard is an abstraction of underlying .NET frameworks, that says the features targeted in a particular version of .NET Standard is supported by, at minimum, these .NET target versions _and higher_. You are correct in that your projects are likely targeting .NET Core 1.x/2.x or .NET Framework 4.x.

I don't doubt you are having some issue with various versions, and I want to help. But most importantly, I need to validate that what your experiencing is or is not an issue with the Polly library targeting .NET Standard 1.1. Could you please create a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)? Something we can use to reliably reproduce your issue? Then we can move toward a solution from there. As you've stated, you have a lot of moving parts, so it's difficult to reproduce unless we have an example to work from.

**Comment by reisenberger** [comment]
@jelical The existing `SystemClock` implementation is fully compatible with .NET Standard 2.0, just not with parallel tests, as we are obviously already [long aware](https://github.com/App-vNext/Polly/blob/0b733fd8a98e993b7e9856eb6e274d073990bf16/src/Polly.NetStandard11.Specs/Properties/AssemblyInfo.cs#L1).  It would have been relatively easy to fix the parallel test-running at any time; it just never obtained priority against all the [forward functionality](https://github.com/App-vNext/Polly/wiki/Polly-Roadmap).  

When we fix that, I'm thinking we should probably do so in a way consistent against all the compilation targets.  We could also probably avoid the `AsyncLocal` by making the abstracted clock something like a property-injectible dependency on `Policy` with a sensible local default for the production side.  Separating the test threads by property-injecting an instance local to the policy-under-test would likely have less perf impact than introducing the `AsyncLocal`, which also affects production code - though we could micro-benchmark to be sure.

Thanks for digging into this area of the codebase, and thereby creating the reminder about this!

**Comment by nathanchere** [comment]
> I'm still not certain there is a need to add an additional target for Standard 2.0

* as already mentioned for the ".Net Standard" target, in project definition terms at least, you are actually targeting a target .Net Core version, not a target .Net Standard version 
* an additional target in this instance just means one extra folder and .csproj with no impact elsewhere in the codebase
* on a dev machine with .Net Core SDK 2.x but not 1.x, you currently need to change the Polly.NetStandard11.csproj and corresponding spec project to target `netcoreapp2.0` whenever you check out, and explicitly skip that whenever you want to stage changes to commit
* there's no reason *not* to add an additonal target

So considering it makes life that little bit easier for non-Windows-based contributors without needing to install .Net Core SDK 1.x and doesn't have any negative impact elsewhere, I would suggest:

* change the `Polly.NetStandard11.*` folders to be more correctly named `Polly.NetCore11`
* add a Polly.NetCore20 target

**Comment by jelical** [comment]
Hi. Sorry for long delay. Original issue are already not actual - current MS tooling is working great with mixed net standards. I am closing this and cancelling my merge request. Thanks a lot for attention!

**Comment by praveenk2** [comment]
Hi, I'm currently developing a library API which is targeting on the .NET standard 2.0. I would like to leverage the Polly library for transient fault handling and also to handle Retry, Circuit Breaker, Timeout, Bulkhead Isolation, and Fallback in a fluent and thread-safe manner.

1. So based on this thread, can I use the Polly[which stated and mentioned as compatible only to .NET standard 1.1] ?

2. Will there be any issues or risks involved ?

3. Will it requires any modifications, specific handling etc ?

Please kindly let me know.

**Comment by joelhulen** [comment]
@praveenk2 I replied to your question in Slack, but am also responding here for more people to see.
You can absolutely use Polly. .NET Standard 1.1 libraries are compatible with .NET Standard 2.0-based projects. The only real difference is that .NET Standard 2.0 exposes more APIs than 1.1. On this note, there are preliminary plans for Polly version 6.x being built on .NET Standard 2.0.

**Comment by praveenk2** [comment]
Sure, ThankQ @joelhulen.

**Comment by joelhulen** [comment]
@jelical @praveenk2 The latest release of Polly now [targets both .NET Standard 1.1 and 2.0](https://github.com/App-vNext/Polly/issues/446).
