### ISSUE TITLE
Extend `onTimeout/async` delegates to take the thrown `OperationCanceledException` as an input parameter

### ISSUE THREAD

**Issue by reisenberger** [App-vNext/Polly#338]
In `TimeoutStrategy.Pessimistic`,  the timed-out delegate (which the calling thread walks away from) is [passed to `onTimeout/Async` as a `Task`](https://github.com/App-vNext/Polly/wiki/Timeout#pessimistic-timeout-1), when a timeout occurs.  This allows `onTimeout/Async` to clean up (prevent `UnobservedTaskExceptions`), and also possibly capture some logging information about the timed-out task.

In `TimeoutStrategy.Optimistic`, no `Task` can be passed to `onTimeout/Async` representing the timed-out operation, as the execution is inlined (there is no spun-off Task).  The cancelled executed delegate (if we have control over its code) could however pass custom information about its state, at the time of cancellation, by throwing some custom `AnnotatedCancelation : OperationCanceledException` (or some similar method, eg wrapping an `OperationCanceledException` round a custom inner exception).  That exception could contain extra info eg for logging.  However, the [`onTimeout/Async` delegate doesn't currently receive that exception as an input parameter](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/Timeout/TimeoutEngineAsync.cs#L58).

This enhancement proposes  we pass [the captured exception](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/Timeout/TimeoutEngineAsync.cs#L54) to `onTimeout/Async`.  This could facilitate capturing extra info-at-time-of-cancellation, for executed delegates we control, cancelled under `TimeoutStrategy.Optimistic`

**EDIT**: Note that whatever exception is thrown to indicate cancellation is already passed back to calling code as the [inner exception of the `TimeoutRejectedException`](https://github.com/App-vNext/Polly/blob/7bdac691e0f02be9e8cd6c6afe74e2bf030b3616/src/Polly.Shared/Timeout/TimeoutEngine.cs#L72).  Fulfilling this issue would just add it to `onTimeout/Async` also, eg, for logging.

**Comment by reisenberger** [comment]
Very similar implementation pattern to #325

**Comment by hopdizzle** [comment]
I think I'd like to take a crack at this. Just to clarify the ask here, the timeoutAsync func needs to be changed from `Func<Context, TimeSpan, Task, Task>` to something like `Func<Context, TimeSpan, Task, Task, Exception>` and plumbed through the various references. Is that correct?

**Comment by hopdizzle** [comment]
Also, this feature should be done to create new overloads to `TimeoutAsync` that accept the new `Func` definition as to not break backwards compatibility, correct?

**Comment by reisenberger** [comment]
@hopdizzle Cool!  Thank you for coming forward to pick this up!

>create new overloads to TimeoutAsync that accept the new Func definition as to not break backwards compatibility, correct?

Yes.  We _might_ retire older overloads at a later date as part of a major release, but we won't break backwards compat as part of a minor release, which this'll likely go into.

>the timeoutAsync func needs to be changed from `Func<Context, TimeSpan, Task, Task>` to something like `Func<Context, TimeSpan, Task, Exception, Task>` and plumbed through the various references. Is that correct?

Yep.  The rider to that is that we should do the sync variants (sync timeout policy) too.  So the sync implementation has [mechanisms similar to the async one](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/Timeout/TimeoutEngine.cs#L67-L71) , likewise the sync syntax ([here](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/Timeout/TimeoutSyntax.cs#L188) and elsewhere in that file).   Same patterns as async so it should make sense.

Finally, #419 ( /cc @urig ) will be affecting the same syntax files, but there'll be a handful of overloads affected by both sets of  changes.  So whichever PR we take first, the second PR may then just have to take into account anything extra from the first PR.  We can sort that out at the time.

Many thanks again!

**Comment by reisenberger** [comment]
Thanks again @dustyhoppe for implementing this.  You have a credit in the Readme! :grin: Fixed in v6.1.0 which will release to nuget shortly
