### ISSUE TITLE
How to use retry and fallback together?

### ISSUE THREAD

**Issue by romanb52** [App-vNext/Polly#375]
I would like to try an action three times and if it fails then call fallback... For example something like this:

Policy.Handle<TimeoutException>()
                        .WaitAndRetry(retryCount: 7, sleepDurationProvider: (attempt) => { return TimeSpan.FromSeconds(value: Math.Pow(attempt, 2)); })
                        .Execute(action: () => {
                               this.DoTheMagic();
                        }).
                        Fallback(()=>{ this.LogThatMagicWasNotDone();}
                        ;

but it does not work. How to achieve such behavior? Or do I have to insert whole Polly call into my own try-catch statement?
Additionaly, am I able to somehow inject code after every failed attempt? So that I can log for example "Attempt number X: failed"?

Thanks!

**Comment by reisenberger** [comment]
@romanb52 

To combine policies, see [PolicyWrap](https://github.com/App-vNext/Polly/wiki/PolicyWrap).

To run code after each failure, use the overloads of `WaitAndRetry(...)` where you can configure an `onRetry:` delegate - see [readme](https://github.com/App-vNext/Polly#wait-and-retry)

Here's a [similar example in a dotnetfiddle sample](https://dotnetfiddle.net/oKAqdc).

**Comment by reisenberger** [comment]
Closing. If you need further assistance, though, do open another issue - or post a query on our [slack channel](http://www.pollytalk.org/)
