### ISSUE TITLE
CachePolicy does not seem to work with ContextualTtl

### ISSUE THREAD

**Issue by TDabasinskas** [App-vNext/Polly#379]
Hello,

Not sure if I'm doing something incorrectly, but I cannot seem to get a CachePolicy working with `ContextualTtl`. 

For example, I have the following policy, which works just fine:

```csharp
var cachePolicy = Policy.CacheAsync(new MemoryCacheProvider(memoryCache), new RelativeTtl(TimeSpan.FromSeconds(3600)), new DefaultCacheKeyStrategy(),
    onCachePut: (context, key) => logger.LogInformation($"Caching '{key}'."),
    onCacheGet: (context, key) => logger.LogInformation($"Retrieving '{key}' from the cache."),
    onCachePutError: (context, key, exception) => logger.LogWarning(exception, $"Cannot add '{key}' to the cache."),
    onCacheGetError: (context, key, exception) => logger.LogWarning(exception, $"Cannot retrieve '{key}' from the cache."),
    onCacheMiss: (context, key) => logger.LogInformation($"Cache miss for '{key}'."));

policyRegistry.Add("CachedHttpResiliencePolicy", cachePolicy);

profile = await _policyRegistry
    .Get<IAsyncPolicy>("CachedHttpResiliencePolicy")
    .ExecuteAsync(async context => await _peopleApi.GetPerson(username), new Context($"UserProfile-{username}"));
```

The log indicates that the data is being cached successfully:
```
[11:43:35 INF] Cache miss for 'UserProfile-n.surname'.
[11:43:35 INF] Caching 'UserProfile-n.surname'.
```

Anyhow, if I replace the code as following (changing `RelativeTtl` to `ContextualTtl` and providing a `Context` dictionary on execution) so I could be able to customize the cache period, it stops working:

```csharp
var cachePolicy = Policy.CacheAsync(new MemoryCacheProvider(memoryCache), new ContextualTtl(), new DefaultCacheKeyStrategy(),
    onCachePut: (context, key) => logger.LogInformation($"Caching '{key}'."),
    onCacheGet: (context, key) => logger.LogInformation($"Retrieving '{key}' from the cache."),
    onCachePutError: (context, key, exception) => logger.LogWarning(exception, $"Cannot add '{key}' to the cache."),
    onCacheGetError: (context, key, exception) => logger.LogWarning(exception, $"Cannot retrieve '{key}' from the cache."),
    onCacheMiss: (context, key) => logger.LogInformation($"Cache miss for '{key}'."));

policyRegistry.Add("CachedHttpResiliencePolicy", cachePolicy);

profile = await _policyRegistry
    .Get<IAsyncPolicy>("CachedHttpResiliencePolicy")
    .ExecuteAsync(async context => await _peopleApi.GetPerson(username), new Context($"UserProfile-{username}",
        new Dictionary<string, object>{{ContextualTtl.TimeSpanKey, new Ttl(TimeSpan.FromSeconds(3600), false)}}));
```

The log indicates only cache misses:

```
[11:52:39 INF] Cache miss for 'UserProfile-n.surname'.
```

Thank you!

**Comment by reisenberger** [comment]
Hi @TDabasinskas .  It looks like I made a mistake in the `ContextualTtl` documentation: apologies for this.  The released Polly package is good, the documentation just doesn't match it.  Thank you for raising the issue.

Where the documentation [on the wiki](https://github.com/App-vNext/Polly/wiki/Cache#contextualttl) used to read: 

    context[ContextualTtl.TimeSpanKey] = new Ttl(TimeSpan.FromMinutes(5), slidingExpiration: true);

it should have read:

    context[ContextualTtl.TimeSpanKey] = TimeSpan.FromMinutes(5);
    context[ContextualTtl.SlidingExpirationKey] = true; // if desired; if not set, false is assumed

So, your posted code should work if changed as follows:

    .ExecuteAsync(async context => await _peopleApi.GetPerson(username), new Context($"UserProfile-{username}",
        new Dictionary<string, object>{{ContextualTtl.TimeSpanKey, TimeSpan.FromSeconds(3600)}}));

Could you let me know if this resolves the issue for you?

(The wiki documentation has now been updated.)

**Comment by TDabasinskas** [comment]
Hi @reisenberger,

I can confirm, that making the changes you mentioned solve the issue and the items are now being added to cache as expected.

I have another issue, where items are not added to the cache again once they expire, but I guess I'll open  a separate issue for that.

Thank you!

**Comment by reisenberger** [comment]
Thanks @TDabasinskas for the fast confirmation!
