### ISSUE TITLE
How to give a name to a policy?

### ISSUE THREAD

**Issue by joshidp** [App-vNext/Polly#382]
Hi,

Thanks for the effort.

How can I give a name to a policy, e.g. in below code snippet how can I specify a name for the policy, by default Polly is giving a random name.
```

  Policy.Handle<HttpRequestException>(e=>((WebException)e.InnerException).Status== WebExceptionStatus.CacheEntryNotFound)
                    .WaitAndRetryAsync(
                // number of retries
                6,
                // exponential backoff
                retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)),
                // on retry
                (exception, timeSpan, retryCount, context) =>
                {
                    var msg = $"Retry {retryCount} implemented with Pollys RetryPolicy " +
                    $"of {context.PolicyKey} " +
                    $"at {context.ExecutionKey}, " +
                    $"due to: {exception}.";

                    Console.WriteLine(msg);
        })
```

Thanks

**Comment by reisenberger** [comment]
Hi @joshidp   . See [Keys and context data](https://github.com/App-vNext/Polly/wiki/Keys-And-Context-Data#policykey) in the wiki, and the **How specified?** entry for each key.  So:

`.WaitAndRetryAsync( ... ).WithPolicyKey("MyPolicyName");`

**Comment by reisenberger** [comment]
And there are more code examples in the [readme here](https://github.com/App-vNext/Polly#policy-keys-and-context-data)

**Comment by joshidp** [comment]
Thanks
