### ISSUE TITLE
Does Polly support Retry on Aysnc Dapper Query calls?

### ISSUE THREAD

**Issue by duydle** [App-vNext/Polly#384]
We just recently found that wrapping retry logic around async Dapper query call caused IIS to crashed.  I wanted to ask if anyone has come across this before.  Below is what I'm doing:

1. I make my method call with async await
var missingListSubmissionLists = await _dataOpsRepository.GetListsWithMissingListSubmissionsAsync(effectiveDate, dataOpsManagedOnly);

2. Inside the method call, notice this is just a pass-through to DapperExtension.QueryAsyncWithRetry method:
public async Task<DataOpsListsToResolveOverview> GetListsWithMissingListSubmissionsAsync(DateTime effectiveDate, bool dataOpsManagedOnly = true)
        {
            var data = new DataOpsListsToResolveOverview()
            {
                EffectiveDate = effectiveDate                
            };

            using (var conn = new SqlConnection(_connectionString))
            {
                var queryParameters = new DynamicParameters();
                queryParameters.Add("@effectiveDate", effectiveDate);
                queryParameters.Add("@dataOpsManagedOnly", dataOpsManagedOnly);

                var missingListSubmissionLists = await DapperExtension.QueryAsyncWithRetry<MaestroList>(conn, "DataOps_GetListsWithMissingListSubmissions",
                                                                                                CommandType.StoredProcedure,
                                                                                                queryParameters).ConfigureAwait(false);
                data.MaestroLists = missingListSubmissionLists.ToList();
                return data;
            }
        }

3.  Inside QueryAyncWithRetry method which wraps RetryPolicy.RetryForTimeout call
public static async Task<IEnumerable<T>> QueryAsyncWithRetry<T>( IDbConnection dbConnection, string sql, CommandType commandType, DynamicParameters paramList, int maxRetries = 3, int commandTimeout = 120)
        {
            try
            {
                //Need to verify retry when method is implemented
                var result = await (Task<IEnumerable<T>>)RetryPolicy.RetryForTimeout(new Func<
                                                 string,
                                                 object,
                                                 IDbTransaction,
                                                 int?,
                                                 CommandType?,
                                                 Task<IEnumerable<T>>>(dbConnection.QueryAsync<T>),
                                                 maxRetries,
                                                 sql,
                                                 paramList,
                                                 null,
                                                 commandTimeout,
                                                 commandType
                                                 );
                return result;
            }
            catch (Exception ex)
            {
                _logger.Fatal(ex, $"DapperExtenions.QueryAsyncWithRetry<T> failed on {sql}");
                throw;
            }
        }

4.  Inside RetryForTimeout method that wraps my Retry Policy.  Note that this is a generic function that executes method.DynamicInvoke based on the delegate method passed in.

private static Logger _logger = LogManager.GetCurrentClassLogger();
        private static string timeout = "timeout expired";
        private static string deadlock = "deadlock";
        public static object RetryForTimeout(Delegate method, int maxRetries = 3, params object[] args)
        {
            var policy = Policy
                        .Handle<Exception>(ex => ExceptionMiner.FullMessageChain(ex).ToLower().Contains(timeout))
                        .Or<Exception>(ex => ExceptionMiner.FullMessageChain(ex).ToLower().Contains(deadlock))
                        .Retry(maxRetries, (ex, retryCount) =>
                        {
                            _logger.Error(ex, $"Attempting retry {retryCount} of maxRetry {maxRetries} for timeout/deadlock on method {method.Method.Name}.  Parameter List Info: {GetPropertyValues(args)}");
                        });

            try
            {
                var result = policy.Execute(() => method.DynamicInvoke(args));
                return result;
            }
            catch (Exception e)
            {
                //log the exception after maxRetries are reached or there is no retry exception being handled
                _logger.Fatal(e, $"RetryPolicy.Retry failed on method {method.Method.Name}. Parameter List Info: {GetPropertyValues(args)}");
                throw;
            }
        }

5. The result is it causes worker process to crash:
    Application: w3wp.exe
    Framework Version: v4.0.30319
    Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFE6475425F (00007FFE645F0000) with exit code 80131506.

**Comment by duydle** [comment]
After posting this issue, member of my team found this article which answers my question.  http://www.thepollyproject.org/2017/06/09/polly-and-synchronous-versus-asynchronous-policies/

**Comment by reisenberger** [comment]
Yes, async executions currently require using async variants of the policies.

Closing.  Do however open another issue or re-open, if you need further support.
