### ISSUE TITLE
How to use with Unity? [Inversion of Control/Dependency Injection]

### ISSUE THREAD

**Issue by joshidp** [App-vNext/Polly#385]
Hi,

Thanks for the effort.

I am using Polly and need to register policies with Unity IOC. Do I need to create a factory to create Policy[] or there is some inbuilt mechanism?

Thanks

**Comment by reisenberger** [comment]
@joshidp Polly provides a `PolicyRegistry` (see [readme](https://github.com/App-vNext/Polly#policyregistry); [wiki](https://github.com/App-vNext/Polly/wiki/PolicyRegistry)).  

A common pattern using Polly with IoC is to configure policies and place them in the `PolicyRegistry` on startup, and then register the `PolicyRegistry` on the IoC container.  At point of use, retrieve the `PolicyRegistry` isntance by DI/IoC and extract the policy you need from it.

You can use Polly's out-of-box `PolicyRegistry`, or [fulfil the `IPolicyRegistry<TKey>` interface] to design more complex registries if needed.

**Comment by joshidp** [comment]
Thanks for the reply.

How do I use IReadOnlyPolicyRegistry<string> registry inside my class, it's now shown in your example.
`public class MyServiceGateway 
{
    public void MyServiceGateway(..., IReadOnlyPolicyRegistry<string> registry, ...)
    {
       ...
    } 
}`
Currently  I am using Policy[] policies and Policy.Wrap(policies). So not getting how Policy[] will be set.

Thanks

**Comment by reisenberger** [comment]
@joshidp 

`PolicyRegistry` [has `Dictionary<string, Policy>`-like semantics](https://github.com/App-vNext/Polly/wiki/PolicyRegistry#syntax), so is only intended for storing an individual configured `Policy` instance under each key, not `Policy[]`.

If you need a DI mechanism for an array `Policy[] policies`, you will have to roll your own or see if `Policy[]` plays nicely as a type that can be registered on Unity's IoC container, out-of-box.

If however the overall goal is just to obtain a `PolicyWrap` at the call site by DI, you could perhaps refactor to configure the `PolicyWrap` from the `Policy[] policies` at startup.  Then:

+ If you're only using one such `PolicyWrap` across the app/scope of the DI container, register the single `PolicyWrap` on the DI container and pass that single `PolicyWrap` to the call site by DI
+ If using multiple such `PolicyWrap`s across the app:
  - Put each in the `PolicyRegistry` under a different key, and pass the `PolicyRegistry`  to the call site by DI.  ( [A `PolicyWrap` is just another kind of `Policy`](https://github.com/App-vNext/Polly/wiki/PolicyWrap#policywrap-is-a-policy), so you can put `PolicyWrap`s in the `PolicyRegistry`.)  
  - Or use the Unity DI container's ability to [distinguish multiple registrations of the same type, by name](https://msdn.microsoft.com/en-us/library/ff660853).

Re:
>How do I use IReadOnlyPolicyRegistry registry inside my class, it's not shown in your example

This is covered just below under the heading [Use policies from the registry](https://github.com/App-vNext/Polly/wiki/PolicyRegistry#use-policies-from-the-registry).

**Comment by reisenberger** [comment]
Closing ('how do I?' issue without recent response).  However, please do re-open - or start another issue - if you require further assistance.
