### ISSUE TITLE
Unable to get Async Retry Policy to work

### ISSUE THREAD

**Issue by duydle** [App-vNext/Polly#387]
Can someone see what I'm doing wrong below when implementing Async Retry Policy.  This is causing a memory heap exception that crashes my IIS application pool.

1.  I have an Async wrapper method using Dapper.QueryAsync<T>

```
    public static async Task<IEnumerable<T>> QueryAsyncWithRetry<T>(IDbConnection dbConnection, string sql, CommandType commandType, DynamicParameters paramList, int maxRetries = 3, int commandTimeout = 120)
        {
            try
            {
                //Need to verify retry when method is implemented
                var result = await (Task<IEnumerable<T>>)RetryPolicy.RetryForTimeoutAsync<T>(new Func<
                                                 string,
                                                 object,
                                                 IDbTransaction,
                                                 int?,
                                                 CommandType?,
                                                 Task<IEnumerable<T>>>(dbConnection.QueryAsync<T>),
                                                 maxRetries,
                                                 sql,
                                                 paramList,
                                                 null,
                                                 commandTimeout,
                                                 commandType
                                                 );
                return result;
            }
            catch (Exception ex)
            {
                _logger.Fatal(ex, $"DapperExtenions.QueryAsyncWithRetry<T> failed on {sql}");
                throw;
            }
        }
```

2. I create Policy using RetryAsync and ExecuteAsync.

```
    public static async Task<IEnumerable<T>> RetryForTimeoutAsync<T>(Delegate method, int maxRetries = 3, params object[] args)
        {
            var policy = Policy
                        .Handle<Exception>(ex => ExceptionMiner.FullMessageChain(ex).ToLower().Contains(timeout))
                        .Or<Exception>(ex => ExceptionMiner.FullMessageChain(ex).ToLower().Contains(deadlock))
                        .RetryAsync(maxRetries, (ex, retryCount) =>
                        {
                            _logger.Error(ex, $"Attempting retry {retryCount} of maxRetry {maxRetries} for timeout/deadlock on method {method.Method.Name}.  Parameter List Info: {GetPropertyValues(args)}");
                        });

            try
            {
                var result = await policy.ExecuteAsync(() => (Task<IEnumerable<T>>) method.DynamicInvoke(args));
                return result;
            }
            catch (Exception e)
            {
                //log the exception after maxRetries are reached or there is no retry exception being handled
                _logger.Fatal(e, $"RetryPolicy.Retry failed on method {method.Method.Name}. Parameter List Info: {GetPropertyValues(args)}");
                throw;
            }
        }
```

( **EDITED**: by @reisenberger to format code for readability. )

**Comment by udlose** [comment]
@duydle - what is the exact type of the exception?  I'm not clear on what a "memory heap" exception is. 
 What is the exception message?

**Comment by reisenberger** [comment]
@duydle Are you able to create a **Minimal, Complete, and Verifiable example**?  Even if only as a runnable ConsoleApp, rather than something hosted in IIS?  This would greatly help anyone wanting to assist.  [This article](https://stackoverflow.com/help/mcve) is a good guide how, and why it helps get to a solution faster.  Sometimes even just the process of constructing the Minimal, Complete, Verifiable example helps zero in on where the problem is.  

From the raw post, nothing is immediately obvious, but that's obviously from a raw read without being able to run the code.

(_Community comment welcome, if anyone can see something_)

**Comment by duydle** [comment]
@udlose Thanks for the reply.
1. 
    Application: w3wp.exe
    Framework Version: v4.0.30319
    Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFE6475425F (00007FFE645F0000) with exit code 80131506.
 that in particular is a .net clr hard crash

2. Yes it returns a Task.  I don't think it needs to await on that call.  I can try to remove it and see if it fixes the problem.

**Comment by udlose** [comment]
ok:

1. I'm not sure how `DynamicInvoke` plays with an `async` call.  I haven't used it myself and I don't see an `async` version.  So, maybe it's ok but just something that sticks out to me.

2. What version of .NET are you using?

3. Does the instruction pointer (IP) always have the same address?

**Comment by duydle** [comment]
What version of .NET are you using?
.NET v4.6.1
Does the instruction pointer (IP) always have the same address?
Yes, I think so.

**Comment by udlose** [comment]
I had added a couple addtl questions above while you were answering (sorry). Can you respond to those?

I suggest trying to create a MCVE (as @reisenberger mentions).  Also, try simpllifying things by removing the usage of your wrapper first (`RetryPolicy.RetryForTimeoutAsync<T>`) and just use the Polly code.

**Comment by duydle** [comment]
Thanks all for the response.  At the moment, let's close this ticket since I won't be able spend too much time on this issue.  For now we will not implement a retry on async calls.  If I have availability, I will circle back and try to create a reproducible code sample and send your way.  Thanks all for the quick responses.

**Comment by reisenberger** [comment]
If an MVCE is hard to produce, the next best suggestion would obviously be the standard debugging technique: eliminate aspects one-by-one, and see if the problem still reproduces.

+ Keep all the wrappers the same but execute a hand-built function deliberately throwing an exception rather than calling Dapper at all? -> If no longer recurs, something in Dapper is the problem.
+ Keep all the wrapper signatures the same but hand-build a retry function (with `for` or `while` loop)? -> If still occurs, problem is not with Polly, but with something around the DynamicInvoke and signatures, etc

[etc]
