### ISSUE TITLE
SocketException from AdvancedCircuitBreaker

### ISSUE THREAD

**Issue by shagilt** [App-vNext/Polly#390]
I am seeing below exception while using AdvancedCircuitBreaker. It looks like connection was failed. May i know what connection is this? Is there any settings am I missing?

ReportResult encountered error System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 100.79.188.36:443
   <Removed Client Code>
   at Polly.AdvancedCircuitBreakerSyntax.<>c__DisplayClass4_1.<AdvancedCircuitBreaker>b__2(Context ctx, CancellationToken ct)
   at Polly.CircuitBreaker.CircuitBreakerEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldHandleExceptionPredicates, IEnumerable`1 shouldHandleResultPredicates, ICircuitController`1 breakerController)
   at Polly.AdvancedCircuitBreakerSyntax.<>c__DisplayClass4_0.<AdvancedCircuitBreaker>b__1(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute(Action action)
   <Removed Client Code>

**Comment by reisenberger** [comment]
No part of Polly manages its own sockets or connections.  If a `SocketException` is being thrown or a connection is failing, that must be by the code you are executing through the policy.  

If you had configured the circuit-breaker to handle that exception but were not expecting it therefore to be thrown: [A circuit-breaker does not absorb exceptions](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker#exception-handling).  It is a measuring-and-breaking device only.  It measures the rate of exceptions thrown by calls placed through it - to determine whether to break the circuit to protect future calls - _but rethrows all exceptions_.  If you wish faults to be retried, you need to combine a circuit-breaker with a retry policy using [PolicyWrap](https://github.com/App-vNext/Polly/wiki/PolicyWrap).  Examples: [Polly-Samples demo 6 onwards](https://github.com/App-vNext/Polly-Samples); [live dotnetfiddle sample](https://dotnetfiddle.net/Oc9HNL); [diagrammatic explanation in the PolicyWrap wiki](https://github.com/App-vNext/Polly/wiki/PolicyWrap#operation)

Let us know if there is anything else we can help with.

**Comment by shagilt** [comment]
Thank you @reisenberger
