### ISSUE TITLE
Where'd the .NET 3.5 support go

### ISSUE THREAD

**Issue by craigbrett17** [App-vNext/Polly#392]
I understand that for reasons of progress, support for .NET 3.5 was dropped, from searching around the repo this seems to be the reason anyway. That's fine. 

But I assume from my reading that there was a time that 3.5 was supported. How would I go about pulling in a package that supports .NET framework 3.5? And more poiniently to the issue, could this be put in the readme for other people looking for how to do this?

**Comment by craigbrett17** [comment]
v4.3.0 seems to be the last package from my experimentation. A quick note or similar in the readme would just be helpful and may save other people some time.

**Comment by joelhulen** [comment]
@craigbrett17 That is a great idea adding a note about where to find the last version that supports .NET 3.5. I'll update the readme now. Thanks!
