### ISSUE TITLE
4.6.1 Runtime Support

### ISSUE THREAD

**Issue by mkus** [App-vNext/Polly#397]
Does Polly support .net framework 4.6.1 runtime? Can I use it in my own 4.6.1 .net project?

**Comment by joelhulen** [comment]
Absolutely! Polly targets .NET Standard 1.1, which is the lowest .NET Standard version we are able to target while covering all of the .NET APIs that Polly uses. What this means, is that Polly is compatible with as many .NET versions as possible, across multiple platforms, from 4.5 onward. As noted in the [official .NET Standard docs](https://github.com/dotnet/standard/blob/master/docs/versions.md#versioning-rules), one of the primary versioning rules is that they are **additive**, meaning higher versions incorporate all APIs from previous versions, and there are no breaking changes between versions.

I have personally used the latest version of Polly in a .NET 4.6.1 project with no issues.
