### ISSUE TITLE
Implement IAsyncPolicy and IAsyncPolicy<TResult> on NoOpPolicy

### ISSUE THREAD

**Issue by SeanFarrow** [App-vNext/Polly#402]
Currently it is not possible to use NoOpPolicy in unit tests where you are explicitly using IAsyncPolicy and it's generic counterpart. Therefor I am proposing that NoOpPolicy also implement IAsyncPolicy and it's generic equivalent.

**Comment by reisenberger** [comment]
Hi @SeanFarrow  . The following code compiles and runs, so I think that the async interfaces on NoOpPolicy are already available:

            IAsyncPolicy noOp = Policy.NoOpAsync();
            await noOp.ExecuteAsync(async () => { });

            IAsyncPolicy<String> noOpGeneric = Policy.NoOpAsync<string>();
            await noOpGeneric.ExecuteAsync(async () => { return String.Empty; });

When you are wanting to use the async variant of [NoOpPolicy](https://github.com/App-vNext/Polly/wiki/noop), are you declaring it as `Policy.NoOpAsync()`?
