### ISSUE TITLE
Cake build is failing due to Cake.FileHelpers -> Cake.Core version requirement out of sync

### ISSUE THREAD

**Issue by reisenberger** [App-vNext/Polly#416]
Polly Cake build has started failing due to [Cake.FileHelpers not yet updated to match latest Cake.Core version](https://github.com/cake-contrib/Cake.FileHelpers/issues/19).

To prevent transient cake build failures, we should [pin our version of cake](https://cakebuild.net/docs/tutorials/pinning-cake-version) per [widespread](https://github.com/cake-contrib/Cake.FileHelpers/issues/19#issuecomment-369266695) [recommendations](https://help.appveyor.com/discussions/problems/12599-appveyor-builds-have-stopped-working-due-to-cakecore-version).  Or make a PR on Cake.FileHelpers to update, for them.

**Comment by SeanFarrow** [comment]
@reisenberger , Should we upgrade Cake to v2.0.0? This would fix this issue, now that Cake.FileHelpers has been updated.

I've got to do this for the JSon text serialization caching serializer, so am happy to work through other repos if this would help?

**Comment by martincostello** [comment]
We'd be happy to accept a PR to update to the latest version of Cake.
