### ISSUE TITLE
separate functions to different dlls?

### ISSUE THREAD

**Issue by LeafDuan** [App-vNext/Polly#420]
hi joelhulen,

i have a suggestion. do you have any idea to separate functions to different dlls?
eg, Polly.Retry.dll, Polly.CircuitBreaker.dll, Polly.Caching.dll, and so on.

best,
leaf

**Comment by joelhulen** [comment]
What are you trying to accomplish? Are these DLLs generated by your own application, or are you asking how to split up the Polly class library into separate DLLs? If you're referring to your own application, this is done by having separate projects with their own namespace, which build the DLLs when you compile them. If you're talking about doing this with the Polly project, I don't see any benefit of doing this. But I would like to hear more about what you are trying to do.

**Comment by LeafDuan** [comment]
Thanks for your comment.

Because I just want the Retry policy in Polly class library, if separating Polly class library into sepatate DLLs by function, that the DLL the project references will be smaller.

May be I can seperate it from the Polly project.

**Comment by reisenberger** [comment]
Thanks for clarifying @LeafDuan . Splitting Polly into smaller packages would be a reasonable change to consuming the project for our existing large user base, so we probably would want to see wider community demand for this - or more evidence of any problems the current packaging is causing - before changing anything.  Is the 300kb size of the current `Polly.dll` causing memory pressure in any environment?

On the downside, it adds some burden to managing the project; and for those consuming Polly who use more than one Policy type.  

Also, if we followed strict [semver](semver.org) for the split-out packages, we could quickly get into a position where the group of packages (Polly.Retry, Polly.CircuitBreaker, Polly.Bulkhead, Polly.Core, Polly.Timeout etc) designed to work together all had very different rev numbers, which could be confusing. (Or we have to not follow semver and publish updates of package where there is no actual change....). None of these problems is insurmountable, but the advantages of any change would have to outweigh the disadvantages.

One of the beauties of OSS of course is that you can, as you say, make your own fork and split out Retry for yourself!

Welcome further community feedback if others have input to this.

**Comment by LeafDuan** [comment]
Thanks for reply @reisenberger . The current size of `Polly.dll` is very OK. Yeah, it's not convenient to sure which version  packages can work together, if splitting out.
