### ISSUE TITLE
how can I carry on a state (parameters, class instance) across the different tries

### ISSUE THREAD

**Issue by infofromca** [App-vNext/Polly#422]
At first , I think Context. but after search ,I found
```
/// <summary>
    /// Context that carries with a single execution through a Policy.   Commonly-used properties are directly on the class.  Backed by a dictionary of string key / object value pairs, to which user-defined values may be added.
    /// <remarks>Do not re-use an instance of <see cref="Context"/> across more than one execution.</remarks>
    /// </summary>

```
so, is it doable?
how can I achieve that?
thanks
andy

**Comment by reisenberger** [comment]
Hi @infofromca  Is your need to re-use a single `Context` instance/some parameter info across the multiple retries which a retry policy orchestrates for you?  Or across multiple calls into a policy?  

If you can provide a brief code sketch of what you are looking to achieve, we can probably help in more detail.

**Comment by infofromca** [comment]
my use case is that I have a instance (S) to manipulate by retry system. after first (or second, or third..) retry , it has exception, now I need to get info(data)  from exception, reassign this data to that instance(S).
----
as I understand , after each retry, instance (S) will be disposed. so I think to use Context, but Context is also disposed.
What should I do?
are there any place to keep the (modified) state across retries?
thanks
andy

**Comment by reisenberger** [comment]
`Context` is fully re-usable to keep the modified state across retries of a single call through `.Execute()` or `.ExecuteAsync()` on a retry policy.

(It is not intended for re-use across multiple calls through `.Execute()` or `.ExecuteAsync()`.)

Re:
>I need to get info(data) from exception
The `onRetry`/`onRetryAsync` policy hooks allow you to do this.

**Comment by infofromca** [comment]
Thanks 
I misunderstood between each .Execute() and each retry.
I will try it today

**Comment by reisenberger** [comment]
@infofromca  Thanks for raising this.  I've clarified the intellisense, in #423 .

If you want more examples of the technique, we have a [blog post](http://www.thepollyproject.org/2017/05/04/putting-the-context-into-polly/) on this.  There's another nice example also in [this recent discussion](https://github.com/App-vNext/Polly/issues/414#issuecomment-375299669).
