### ISSUE TITLE
v6.0: Discontinue .NET4.0 support

### ISSUE THREAD

**Issue by reisenberger** [App-vNext/Polly#428]
It is intended to discontinue .NET4.0 support from Polly v6.0.  Language features and integrations intended for use with Polly v6.0 metrics are not available to .NET4.0.  

All Polly versions < v6.0 would of course remain available to .NET4.0 users.

**Comment by IsaacMorris1980** [comment]
@reisenberger will the metrics still work on .net 4.5+?

**Comment by reisenberger** [comment]
Closed via #447.  Documentation of the last version to support .NET 4.0 is in the main Polly Readme.
