### ISSUE TITLE
Policy.Execute question

### ISSUE THREAD

**Issue by taomylife521** [App-vNext/Polly#438]
when Policy.Execute ,must wrap 

try{ 
Policy.Execute()...
}catch(Exception ex){}  
flag=1;

if i am not wrap with try catch ,and "flag=1" never run;
if i want deal with the exception by myself？

**Comment by reisenberger** [comment]
@taomylife521 .  The three reactive Policy types propagate handled exceptions out of the Policy as follows:

+ **[Retry](https://github.com/App-vNext/Polly/wiki/Retry)** policies: rethrow the final exception on to your code, if all tries have failed. 
+ [**CircuitBreaker**](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker) policies [rethrow all exceptions](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker#exception-handling), even handled ones.  A circuit-breaker measures the exceptions and decides whether to introduce fail-fast breaking (break the circuit), but rethrows all exceptions.
+ [**Fallback**](https://github.com/App-vNext/Polly/wiki/Fallback) policies do not by default rethrow handled exceptions.

The wiki pages linked above for each Policy  give more information.

For the cases when a policy rethrows an exception, you can either:
+ handle it with your own `try` / `catch`; or
+ use [`.ExecuteAndCapture(...)`](https://github.com/App-vNext/Polly#post-execution-capturing-the-result-or-any-final-exception) to capture the result of execution into a `PolicyResult`, and so avoid an extra `try` / `catch`.

I'm not sure if this answers your question.  Let us know if you need anything else?

**Comment by reisenberger** [comment]
Closing.  Extra documentation PRd onto readme, in #458
