### ISSUE TITLE
Circuit breaker - on retry

### ISSUE THREAD

**Issue by pawepaw** [App-vNext/Polly#44]
Hello,

Is there any chance to define method which will should run on exception why executing method? I mean something like in retry method (onRetry) 

```Retry(this PolicyBuilder policyBuilder, int retryCount, Action<Exception, int, Context> onRetry)```

**Comment by reisenberger** [comment]
@pawepaw . This is easy to do already with existing Polly.  A circuit breaker policy rethrows the exception - or a `BrokenCircuitException` (with the triggering exception wrapped as `InnerException`), if the exception triggers breaking the circuit.  So:

```csharp
try
{
    circuitBreaker.Execute(() => Action());
}
catch (BrokenCircuitException)
{
    // Add actions on circuit-breaking here
}
catch (Exception e)
{
    // Add actions on exception here
}
```
