### ISSUE TITLE
Ensure deprecations (marked obsolete) indicate the new alternative to use

### ISSUE THREAD

**Issue by paulomorgado** [App-vNext/Polly#441]
When an element is obsoleted, the alternative should be explicit in the text.

**Comment by paulomorgado** [comment]
I had to go through the sources to find out what was the right overload.

You should consider moving those overloads to extension methods. That will keep the implementation short and precise while providing source compatibility.

Unfortunately, going from extension methods to instance methods is easy but the other way around it's impossible.

**Comment by reisenberger** [comment]
Documentation [published to wiki](https://github.com/App-vNext/Polly/wiki/Polly-v6-breaking-changes)
