### ISSUE TITLE
Can I use Polly to Handle a particular response code and invoke a method based.

### ISSUE THREAD

**Issue by rkandi590** [App-vNext/Polly#450]
Hi,
I have just started using polly and I have used it to retry so far and it is working great, however I want to know what is the best way of using polly for this scenario:

_partialSuccessResponseHandlerPolicy = Policy.HandleResult<HttpResponseMessage>
               (response => response.StatusCode == HttpStatusCode.Accepted)
              .Execute My function.

In other words, I want to execute a method which deseiralizes response and does some other work if I want like updating metrics based up on response and other kind of stuff.

Please let me know how can I do this the best way.

**Comment by reisenberger** [comment]
A Polly policy can handle a particular response code, per your clause `.HandleResult(response => response.StatusCode == HttpStatusCode.Accepted)`.  

To execute particular code when that handled condition occurs, you can use a [`FallbackPolicy`](https://github.com/App-vNext/Polly/wiki/Fallback).  When the `fallbackAction` wants to consume the result-so-far (the `HttpResponseMessage` with `HttpStatusCode.Accepted` in your case), use [this overload](https://github.com/App-vNext/Polly/blob/f4404005b5c1e4965b74b3fe01a6b4ec0642f97a/src/Polly.Shared/Fallback/FallbackSyntaxAsync.cs#L217). See the [readme](https://github.com/App-vNext/Polly#state-change-delegates-on-policytresult-policies) for how the passed `DelegateResult<HttpResponseMessage>` represents the outcome of the execution.  For example:

    var _partialSuccessResponseHandlerPolicy = 
        Policy.HandleResult<HttpResponseMessage>(response => response.StatusCode == HttpStatusCode.Accepted)
            .FallbackAsync(
                fallbackAction: async (outcome, context, cancellationToken) => await FooWhenHttpStatusCodeAccepted(outcome.Result, cancellationToken), // Processes the outcome.Result and provides an alternative HttpResponseMessage result to the caller.  This example discarded the context parameter, on assumption the execution not using the Polly.Context.
                onFallbackAsync: async (outcome, context) => { /* possible extra actions for when the policy handles an execution, such as logging */ }
            );

That describes what `FallbackPolicy` can do, but it isn't necessarily a fit for:

>I want to execute a method which deseiralizes response

FallbackPolicy is designed to provide an alternative response when an execution errors, and that alternative must be the same type as the original execution. So in the above example, `fallbackAction` can only return `HttpResponseMessage`.  So it is not a fit for deserializing the response within `fallbackAction` _and returning that different (deserialized) type_.  There could be alternatives like capturing the result of the deserialization by closing over a variable in a lambda, or `out` parameters. But plain old `if` statements to handle this case might be easier to read.

>does some other work if I want like updating metrics based up on response and other kind of stuff

`onFallbackAsync` can be a good fit for such cross-cutting concerns.

Hope that helps.

**Comment by rkandi590** [comment]
Thank you for the detailed explanation Reisenberger. That helps a lot.
