### ISSUE TITLE
NuGet dependency question.

### ISSUE THREAD

**Issue by skalinkin** [App-vNext/Polly#454]
.NETStandard brings tones of dependencies to the project when installed using NuGet.

are they necessary? 
are there any way not to have them if we are targeting framework 4.5.1?

**Comment by reisenberger** [comment]
@skalinkin Many apologies for the delayed reply.  [Polly v5.9.0](https://www.nuget.org/packages/Polly/5.9.0) includes the identical functionality to v6.0.1, and includes a direct v4.5.1 target.

In v6.0 onwards we are not (at present) considering direct .NET Framework targets as we expect to add integrated eventing/logging functionality explicitly based on some .NET Standard/Core -only interfaces going forward.
