### ISSUE TITLE
[Question] How the "execution contexts" are handled now with Polly and .NET Core 2.1 HttpClient factory?

### ISSUE THREAD

**Issue by CESARDELATORRE** [App-vNext/Polly#456]
Hey! - I'm reviewing how Polly is integrated to .NET Core 2.1 HttpClient factory when using AddHttpClient(), etc., which is great because it is very simple to use.
However, I cannot find how the "execution contexts" are handled now with this approach. Do you have any info about it, please?

Thanks,

**Comment by reisenberger** [comment]
Hey @CESARDELATORRE !  We have [Polly and IHttpClientFactory documentation in the Polly wiki](https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory). There is some discussion about [setting execution context](https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory#use-case-cachepolicy) in the section on Cache policy - you can use:

    request.SetPolicyExecutionContext(...);

When HttpClientFactory configures a logical `HttpClient` to apply Polly policies, the `policy.ExecuteAsync(...)` call is obviously eventually made [from within the delegating handler](https://github.com/aspnet/HttpClientFactory/blob/b942008a6ed1525396128c399d91d5f677f65ded/src/Microsoft.Extensions.Http.Polly/PolicyHttpMessageHandler.cs#L130), so the user doesn't have control to pass the `Context` into that call.  Given `Context` is execution-scoped, there was not much option except to find somewhere to [attach context to the `HttpRequestMessage`](https://github.com/aspnet/HttpClientFactory/blob/b942008a6ed1525396128c399d91d5f677f65ded/src/Microsoft.Extensions.Http.Polly/HttpRequestMessageExtensions.cs).

Is it Cache policy you are using with the .NET Core 2.1 HttpClient factory integration?  We are interested in people's experience around that.

**Comment by reisenberger** [comment]
Closing due to lack of further discussion.  Please re-open or start a new issue if needed!

**Comment by reisenberger** [comment]
@CESARDELATORRE  It was great to see the ASP NET Core 2.1 updates to the [eShopContainers project](https://github.com/dotnet-architecture/eShopOnContainers) and [related ebook](https://www.microsoft.com/net/download/thank-you/microservices-architecture-ebook).  We now highlight both of these [in the Polly readme](https://github.com/App-vNext/Polly/blob/master/README.md#sample-microservices-architecture-and-ebook).

**Comment by CESARDELATORRE** [comment]
Awesome! Thank you! 👍
