### ISSUE TITLE
How to donate?

### ISSUE THREAD

**Issue by yangzhongke** [App-vNext/Polly#462]
We're from rupeng.com, an online education company of China.
We developed a course on .Net Core Microservice that using Polly as resilience and transient-fault-handling library.
We want to donate Polly, but don't know how to donate.Can you provide a way for donation?
thank you.

**Comment by reisenberger** [comment]
Hi @yangzhongke . Thank you for your question!  At the moment the project is not able to take donations.  However, if something is set up to accept donations in the future, we will let you know.  Many thanks for the question.
