### ISSUE TITLE
FileLoadException with Polly 6.0.1 on .NET 4.7.1

### ISSUE THREAD

**Issue by cmeeren** [App-vNext/Polly#469]
I'm trying out Polly 6.0.1 in an F# ASP.NET Core app targeting .NET 4.7.1 (for legacy reasons I can't target .NET Core). At runtime however, I get the following exception:

```
FileLoadException: Could not load file or assembly 'Polly, Version=5.9.0.0, Culture=neutral,
PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition
does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

I have no idea where `5.9.0.0` comes from; the only reference I can find to that version is from Polly.Caching.MemoryCache 1.1.0 (which I also use), which requires Polly >= 5.9.0. I'm using that combination without issues in another F# ASP.NET Core app targeting .NET Core 2.1.

In the meantime I could use Polly 5.x as a temporary workaround, but for some reason the cache provider there throws a NullReferenceException every time the key is not found, which gets logged in my `onCacheError` callback and greatly clutters up the program output.

Let me know if I can provide further information.

**Comment by cmeeren** [comment]
Note that cleaning and deleting all my projects' `bin` and `obj` folders did not help.

**Comment by joelhulen** [comment]
@cmeeren That NuGet package (Polly.Caching.MemoryCache) is deprecated. Unfortunately, there's no easy way to mark packages as such with nuget.org. I did add a description on the page there, but that's only useful if you're actually on the site. Please try this package out instead: [https://www.nuget.org/packages/Polly.Caching.Memory](https://www.nuget.org/packages/Polly.Caching.Memory)

**Comment by cmeeren** [comment]
Thanks, my bad.

You could add a deprecation warning to the summary (or whatever it's called), which is shown in the nuget listing in VS (and most other places I'd think). I've seen many packages place "DEPRECATED, please use ..." in this field.

![image](https://user-images.githubusercontent.com/7766733/41833534-f86bdbc6-7850-11e8-97a5-f7857d9e4daf.png)
