### ISSUE TITLE
But why?

### ISSUE THREAD

**Issue by dkrikun** [App-vNext/Polly#47]
Hello,

Could you please clarify why one would like to use `Polly` instead of handling exception in a mainstream fashion?
I'm asking this because it seems to me that while using Polly will reduce boilerplate, it will be more obscure to those who read the code.

Thanks!

**Comment by joelhulen** [comment]
@dkrikun I wondered the same thing when I first came across Polly. So, I'll leave you with a use case where I implemented Polly in a way that would've cost me many more key strokes:

I developed a Xamarin-based mobile app used by field engineers to take pictures after work is done on a job site, and to fill out a quality control check sheet. The app is built to run offline or within occasionally connected scenarios. When they are ready to submit their data to the intake service, they might not have the best of connections.

Polly provides an interesting retry policy when an exception is encountered. Now, consider this: you've got 30 reasonably large photos to upload to the cloud. You may not have the most reliable data connection, but it's mostly there. You need to upload these photos while you can. So, the way I handled it is to set an exponential retry policy that waits for longer durations each time an exception is encountered before trying again. You can clearly see the exception handling here, and also easily understand the retry logic.

Here's a code sample from my project. If I were to write this from scratch, it would take a lot more time to do, so why reinvent the wheel?

```csharp
                    // Retry a specified number of times, using a function to 
					// calculate the duration to wait between retries based on 
					// the current retry attempt (allows for exponential backoff),
					// calling an action on each retry with the current exception,
					// duration and context provided to Execute()
					// In this case will wait for
					//  1 ^ 2 = 2 seconds then
					//  2 ^ 2 = 4 seconds then
					//  3 ^ 2 = 8 seconds then
					//  4 ^ 2 = 16 seconds then
					//  5 ^ 2 = 32 seconds
					await Policy
						.Handle<Exception> ()
						.WaitAndRetryAsync (5, retryAttempt => 
							TimeSpan.FromSeconds (Math.Pow (2, retryAttempt)), 
							(exception, timeSpan, context) => {
								// Send exception logging to Xamarin.Insights:
								MessagingCenter.Send<MobileServiceClient, ExceptionContainerException> (QCApp.Client, 
									Common.Constants.MessageCenterMessages.MessagingCenterError, new ExceptionContainerException { Title = "Error uploading image",
										Exception = exception
									});
								Insights.Report (exception, new Dictionary<string,string> {
									{ "Filename", "SectionViewModel.cs" },
									{ "Where", "UploadImage" },
									{ "Issue", "Error uploading image" }
								});
							}
						)
						.ExecuteAsync (async () =>
							// JDH - 04/12/2015 - Moved away from using the Microsoft.WindowsAzure.Storage SDK in
							// favor of direct REST calls due to the SDK's slowness. REST calls appear to run about
							// 15x faster for uploads!
							BlobTransfer.UploadFileAsync (picture, picture.Filename)
						);
```

Pretty clear and concise, isn't it?

BTW, implementing this exponential retry cut down failed upload attempts to almost zero.

Hopefully this helped illustrate a good use case for this excellent library.
