### ISSUE TITLE
Behaviour of ExecuteAndCapture with PolicyWrap and with Fallback

### ISSUE THREAD

**Issue by rmandvikar** [App-vNext/Polly#477]
I'm wrapping a retry policy in timeout policy. The action returns null so I want to retry. 

With `retry` policy alone, I get `result.Outcome` as `Failure` as expected. But with `timeout` policy, it is `Successful` with `result.Result` as null. Shouldn't it also be a `Failure`?

If the action throws, then I see `Failure` for both `retry` and `timeout` policies.
```
class Holder
{
	public bool done;
	public Holder holder;
}

[Test]
public async Task Polly_Result_Outcome_Should_Be_Failure()
{
	Policy<Holder> retry = Policy
				   .Handle<Exception>()
				   .OrResult<Holder>(h =>
				   {
					   var flag = !(h?.holder?.done) ?? true;
					   return flag;
				   })
				   .WaitAndRetryAsync(
					   2,
					   retryAttempt => TimeSpan.FromMilliseconds(1000));
	var timeout = Policy
				  .TimeoutAsync(10)
				  .WrapAsync(retry);
	var result = await timeout.ExecuteAndCaptureAsync(async (ct) =>
	{
		ct.ThrowIfCancellationRequested();
		//throw new Exception();
		return await Task.FromResult((Holder)null);
	}, CancellationToken.None)
	.ConfigureAwait(false);
	if (result.Outcome != OutcomeType.Successful)
	{
		// retry policy comes here as expected
		Assert.Pass();
	}
	if (result.Result == null)
	{
		// timeout policy comes here
		// why is Outcome not OutcomeType.Failure just like retry policy?
	}
	Assert.Fail();
}
```

**Comment by reisenberger** [comment]
Hi @rmandvikar . Good question; thanks for the great repro code.

Defining the behaviour of `.ExecuteAndCapture()` with `PolicyWrap` [was hard](https://github.com/App-vNext/Polly/issues/267): a `PolicyWrap` can flexibly consist of any number of policies with different handle clauses, making it hard to define the meaning of a single binary `OutcomeType.Successful` [or] `.Failure` representing "Did this policywrap handle the fault? (somewhere)".  

As such, it was decided that .ExecuteAndCapture(...) on a PolicyWrap indicates that [a given exception or result was handled by the PolicyWrap if the outermost policy in the wrap handled it](https://github.com/App-vNext/Polly/wiki/PolicyWrap#policywrap-with-executeandcapture).

With that in mind, in your sample code, a `TimeoutPolicy` is outermost in the `PolicyWrap`.  When the executed delegate returns `null`, no timeout is occurring or other exception being thrown, so `.ExecuteAndCapture(...)` considers the execution successful.  

You could get the `PolicyWrap` to give the expected results for `.ExecuteAndCapture(...)` by placing a policy which handles the same results outermost in the `PolicyWrap`.  A `FallbackPolicy` can be used for this: in the below example the `FallbackPolicy` merely returns the same result (it doesn't substitute any different value as `Fallback` often does), but it does mean `PolicyWrap.ExecuteAndCaptureAsync(...)` will treat the outcome as having been a handled fault.

```csharp
IAsyncPolicy<Holder> retry = Policy
    .Handle<Exception>()
    .OrResult(ShouldHandleResult())
    .WaitAndRetryAsync(
        2,
        retryAttempt => TimeSpan.FromMilliseconds(1000));

IAsyncPolicy timeout = Policy
    .TimeoutAsync(10);

IAsyncPolicy<Holder> fallback = Policy
    .HandleResult(ShouldHandleResult())
    .FallbackAsync(
        fallbackAction: (outcome, ctx, ct) => Task.FromResult(outcome.Result), 
        onFallbackAsync: (outcome, ctx) => Task.CompletedTask
        );

IAsyncPolicy<Holder> policyWrap = fallback.WrapAsync(timeout).WrapAsync(retry);

PolicyResult<Holder> result = await policyWrap.ExecuteAndCaptureAsync(async (ct) =>
    {
        ct.ThrowIfCancellationRequested();
        //throw new Exception();
        return await Task.FromResult((Holder)null);
    }, CancellationToken.None)
    .ConfigureAwait(false);
```

where:

```csharp
private static Func<Holder, bool> ShouldHandleResult()
{
    return h => !(h?.holder?.done) ?? true;
}
```

Adding a `FallbackPolicy` here is a bit of a workround (unless you want it for other reasons).  You could alternatively omit the `FallbackPolicy` and do something like `if (result.Outcome != OutcomeType.Successful || ShouldHandleResult(result.Result))`, to get the same effect.

**Comment by rmandvikar** [comment]
I do wrap with fallback policy to handle `TimeoutRejectedException`. I see, since timeout policy cannot handle result and policy wrap bubbles up only 1 level deep so need to repeat the `OrResult` for fallback too (fallback - timeout - retry).

**Comment by rmandvikar** [comment]
Shouldn't the outcome in this case be `OutcomeType.Failure` too since it should time out and the `timeout` policy should catch it and bubble it up to `PolicyWrap` policy?
```
[Test]
public async Task Outcome_Should_Be_Failure()
{
	var retryCount = 1000;
	var retry = Policy
			   .Handle<Exception>()
			   .OrResult<object>((result) => false)
			   .WaitAndRetryAsync(
				   retryCount,
				   ra => TimeSpan.FromMilliseconds(1000));
	var timeout = Policy
				  .TimeoutAsync(1);
	var fallback = Policy
				   .Handle<TimeoutRejectedException>()
				   .OrResult<object>((result) => false)
				   .FallbackAsync(default(object));
	var policy = fallback.WrapAsync(timeout).WrapAsync(retry);

	var time = DateTime.UtcNow;
	var retryAttempt = -1;

	var policyResult = await policy.ExecuteAndCaptureAsync(async (ct) =>
	{
		ct.ThrowIfCancellationRequested();
		retryAttempt++;
		throw new Exception();
		return await Task.FromResult(new object());
	}, System.Threading.CancellationToken.None)
	.ConfigureAwait(false);

	var actualTimeout = DateTime.UtcNow.Subtract(time).TotalSeconds;
	Assert.IsTrue(retryAttempt < retryCount);
	Assert.AreEqual(OutcomeType.Failure, policyResult.Outcome);
	Assert.IsNull(policyResult.Result);
}
```

**Comment by reisenberger** [comment]
@rmandvikar Thanks for the [great example](https://github.com/App-vNext/Polly/issues/477#issuecomment-402945772).

What is happening is that the `fallback` policy you have configured is replacing the `TimeoutRejectedException` with a replacement result of `null` (`default(object)`). This is [bubbled (as the overall result) back out to `.ExecuteAndCaptureAsync(....)`, which says](https://github.com/App-vNext/Polly/blob/f4404005b5c1e4965b74b3fe01a6b4ec0642f97a/src/Polly.Shared/Policy.Async.TResult.ExecuteOverloads.cs#L262-L269) "`null` isn't something the `FallbackPolicy` regards as a fault, so now we have a successful outcome!"   `.ExecuteAndCaptureAsync(....)` is capturing and evaluating the final outcome, after the substitution by fallback.

I would agree if you thought this behaviour of `.ExecuteAndCapture/Async(...)` with `FallbackPolicy` is subtle! But it makes sense: in your original fallback policy, you replace the failure outcome with a success outcome ... so the overall outcome should be reported as success!

If you replace the `FallbackPolicy` with one which doesn't substitute a different result, but bubbles the received result back outwards, then indeed the overall execution outcome is a fault, and the test will pass:

```csharp

        [Fact]
        public async Task Outcome_Should_Be_Failure()
        {
            var retryCount = 1000;
            var retry = Policy
                .Handle<Exception>()
                .OrResult<object>((result) => false)
                .WaitAndRetryAsync(
                    retryCount,
                    ra => TimeSpan.FromMilliseconds(1000));
            var timeout = Policy
                .TimeoutAsync(1);
            var fallback = Policy
                .Handle<TimeoutRejectedException>()
                .OrResult<object>((result) => false)
                .FallbackAsync(
                    fallbackAction: (outcome, ctx, ct) => {
                        if (outcome.Exception != null) throw outcome.Exception; // bubbles a received exception back outwards
                        return Task.FromResult(outcome.Result); // bubbles a handled result back outwards
                    },
                    onFallbackAsync: (outcome, ctx) => Task.CompletedTask
                );
            var policy = fallback.WrapAsync(timeout).WrapAsync(retry);

            var time = DateTime.UtcNow;
            var retryAttempt = -1;

            var policyResult = await policy.ExecuteAndCaptureAsync(async (ct) =>
                {
                    ct.ThrowIfCancellationRequested();
                    retryAttempt++;
                    throw new Exception();
                    return await Task.FromResult(new object());
                }, System.Threading.CancellationToken.None)
                .ConfigureAwait(false);

            var actualTimeout = DateTime.UtcNow.Subtract(time).TotalSeconds;
            Assert.IsTrue(retryAttempt < retryCount);
            Assert.AreEqual(OutcomeType.Failure, policyResult.Outcome);
            Assert.IsNull(policyResult.Result);
        }
```

What I think this demonstrates is that my previous statement (and the statement in the documentation) ... :

> .ExecuteAndCapture(...) on a PolicyWrap indicates that a given exception or result was handled by the PolicyWrap if the outermost policy in the wrap handled it.

is not precise, is misleading.  It should be something like:

> .ExecuteAndCapture(...) on a PolicyWrap captures whether the final outcome of the execution is one considered a fault by the outermost policy in the wrap.

**Comment by reisenberger** [comment]
@rmandvikar Thanks again for your great example which highlights these important points! We've updated the documentation for both [PolicyWrap](https://github.com/App-vNext/Polly/wiki/PolicyWrap#policywrap-with-executeandcapture) and [Fallback](https://github.com/App-vNext/Polly/wiki/Fallback#fallbackpolicy-with-executeandcapture) to make this clearer.

Let us know if there is anything else we can help with.

**Comment by reisenberger** [comment]
Closing this as I think we're done here, and we've updated the wiki to cover this more precisely.  However, if you do need anything else, please re-open the issue or start a fresh one.  Also updated the title of the issue for future discoverability.  Thanks for your great question!
