### ISSUE TITLE
Get Polly to returns reponse after internal server 500 error

### ISSUE THREAD

**Issue by atifmir** [App-vNext/Polly#478]
Sorry folks this might be down to my limited knowledge on Polly and may not be an issue but I will appreciate any guidance.

I am using Polly in my api I had a middleware that handles the 500 errors and send a geenric response back to user but logs the actual error in stack trace.

With Polly implemented it hits the retry after encountering the exception and eventually returns 503 (service unavailable) which is misleading as 500 did happen. How can I get polly to stop retrying on 500 and send the reponse back with my custom 500 error as is in my middleware??

 Regards

**Comment by reisenberger** [comment]
@atifmir .  We would need more details to be able to help here; there isn't enough info to tell how you have implemented Polly or what might be causing the 500 to change to 503.  To help further we would need to see  some sample code; best, a [minimum verifiable example](https://stackoverflow.com/help/mcve).

**Comment by reisenberger** [comment]
@atifmir To come briefly back to your question:

>How can I get polly to stop retrying on 500

As [shown in the readme](https://github.com/App-vNext/Polly#step-1--specify-the--exceptionsfaults-you-want-the-policy-to-handle), you can specify predicates to filter which exceptions or results you do / do not want to handle.  To exclude a 500 you might want something as simple as:

    Policy.HandleResult<HttpResponseMessage>(r => r.StatusCode != HttpStatusCode.InternalServerError)

There are many more examples in the readme.  If your scenario merits a more free-form chat, maybe try the [Polly slack channel](http://www.pollytalk.org/) (you can self-register) where we have a wider group of people available to help.  If you think something specifically is going wrong in Polly or not behaving as you expect, post more code here or ask on our slack channel.

**Comment by atifmir** [comment]
@reisenberger thanks for your reply I will read the wiki first and try out your suggestion failing that I will put some example code as you suggested. Thanks for pointing me to slack channel v useful
Cheers

**Comment by reisenberger** [comment]
Closing, but if you do require further assistance, please do re-open the issue (or a new one), and we'd be very happy to look at example code if it helps.

**Comment by atifmir** [comment]
Thanks will do

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
