### ISSUE TITLE
Logging exceptions in policies which handles both exception and return result

### ISSUE THREAD

**Issue by vsklyarov-softheme** [App-vNext/Polly#488]
I am trying to create a retry policy for a HttpClient which will retry on both HttpRequestException and some HttpStatusCode:
```
Policy
    .Handle<HttpRequestException>()
    .OrResult<HttpResponseMessage>(r => r.StatusCode == HttpStatusCode.ServiceUnavailable
        || r.StatusCode == HttpStatusCode.RequestTimeout
        || r.StatusCode == HttpStatusCode.GatewayTimeout)
     .WaitAndRetryAsync(3, retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)));
```
But I don't see how to add a logging for HttpRequestException in such policies since `onRetryAsync ` argument type in this case is `Func<DelegateResult<HttpResponseMessage>, TimeSpan, Context>`

Is there is a way to log exception in such policies?

**Comment by reisenberger** [comment]
The [documentation on `DelegateResult<TResult>` in the readme](https://github.com/App-vNext/Polly/#state-change-delegates-on-policytresult-policies) describes the property for this.  It is the property `DelegateResult<TResult>.Exception`.

**Comment by vsklyarov-softheme** [comment]
@reisenberger thanks a lot! I don't know how I missed this
