### ISSUE TITLE
Running async actions on captured synchronization context

### ISSUE THREAD

**Issue by yevhen** [App-vNext/Polly#49]
Runnng Polly inside MS Orleans grain is [not](https://github.com/dotnet/orleans/pull/875#issuecomment-145917957) possible, since Orleans uses custom TaskScheduler and due to automatically added `ConfigureAwait(false)` action escapes it and runs on different thread, thus breaking single-threaded guarantee provided by Orleans. 

Is that possible to add an overload for `RetryAsync\WaitRetryAsync` that will allow to control that behavior? 

P.S. I'll be happy to send a PR but I have no idea what feature/project type my VS15 installation is missing, that I cannot load Polly.Shared projects. It tell me that `The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.1\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.CSharp.targets` :worried: 

Is that ExpressionDesigner that need to be installed?

**Comment by johnkattenhorn** [comment]
Great catch - I'd never had figure this out in our project :-)

**Comment by yevhen** [comment]
I've figured out that I don't have Windows Phone SDK installed. Done that.

@michael-wolfenden will you accept PR that fixes aforementioned problems? We can discuss api changes before I even try or I can proceed with PR, so there will be something eligible for further discussion?

Sketching that, I think it could be implemented without any breaking changes.

**Comment by michael-wolfenden** [comment]
Sure thing @yevhen, send through the pull request and I'll check it out
