### ISSUE TITLE
"Policy execution successful" in logs

### ISSUE THREAD

**Issue by cmeeren** [App-vNext/Polly#491]
I suddenly noticed that my logs are full of "Policy execution successful" messages. I think this came after upgrading to Polly 6.1.0, but I could be wrong.

Is there any way to silence these messages? I am using Serilog and have tried `loggerConfiguration.MinimumLevel.Override("Polly", LogEventLevel.Warning)`, but I still get them.

**Comment by reisenberger** [comment]
@cmeeren Polly itself contains no code that logs the message "Policy execution successful".  Can you identify the piece of your own code around Polly (or code of any integration you may be using?) which is generating this message? It should then be possible to amend that code to silence these messages.  If we can help with that, post the relevant code.  

If you can identify something you believe that has changed in Polly v6.1.0 that may be causing changed behaviour, please post further details.  Changes between versions of Polly are detailed:
+ [in the changelog](https://github.com/App-vNext/Polly/blob/master/CHANGELOG.md)
+ by the [issues and PRs being tagged, eg in this case v6.1.0](https://github.com/App-vNext/Polly/milestone/27?closed=1)

**Comment by cmeeren** [comment]
Sorry for jumping the gun. I'll investigate and get back with more details.

**Comment by cmeeren** [comment]
Found it - it's actually from `Microsoft.AspNetCore.Cors.Infrastructure.CorsService`.

Took way too long to track down, since I tried to reproduce it using Postman, which doesn't trigger CORS unless you include the relevant headers manually. Evidently I had done so for the requests that led me to posting this issue, but not for the ones I now tried to reproduce with, so I had no idea where the message had disappeared to and could not for the life of me trigger them, neither locally nor in production. Also, CORS is rather invisible in ASP.NET Core code - there's no breakpoints you can set, as everything is pure configuration. Thankfully, Application Insights and Serilog's structured logging saved the day:

![image](https://user-images.githubusercontent.com/7766733/43951631-e90419b6-9c93-11e8-9ebf-838b88539319.png)

In any case, sorry for the wild goose chase.
