### ISSUE TITLE
How to free HttpResponceMessage in FallBackPolicy and return a new one.

### ISSUE THREAD

**Issue by elviswatkins** [App-vNext/Polly#495]
I am using a Circuit Breaker with a fallback to catch any exceptions or invalid status codes and return a new HttpResponseMessage to the client that can be interpreted as an error.  I would like the Fallback to look as follows:
```
// fall back for any exception
var fallbackForCircuitBreaker = Policy<HttpResponseMessage>
    .Handle<Exception> ()                                             // if any exception occured or
    .OrResult (response => response.StatusCode != HttpStatusCode.OK)  // if request did not succeed go to fallback
    .Fallback (() => new HttpResponseMessage(HttpStatusCode.InternalServerError)
            {
            Content = new StringContent("fallback")
            },
        onFallback: b =>
            {
            if (b.Exception == null) // got response from service
                {
                var msg = b.Result.Content.ReadAsStringAsync().Result;
                logger.ForContext("Response", msg)
                        .Error("OnFallback Status: {Status}", b.Result.StatusCode);
                }
            else
                logger.ForContext("Exception", b.Exception.Format())
                        .Error("OnFallback Exception: {ExceptionMessage}", b.Exception.Message);
            });
```

My question is, how to Dispose the current HttpResponseMessage that was created via a upstream call to HttpClient.SendAsync and return a *dummy* HttpResponseMessage.  I believe the *onFallback* delegate is called before the *Fallback* delegate.  Can I Dispose the HttpResponseMessage there before the actual *Fallback* delegate?  Or am I just missing something?

**Comment by reisenberger** [comment]
_Initial aside_: If this is for http calls through `HttpClient`, you'll [want an async policy variant](https://github.com/App-vNext/Polly/wiki/Asynchronous-action-execution), ie, use `FallbackAsync(...)`.

---

Timing-wise, the [`onFallbackAsync` runs the statement before the `fallbackAction`](https://github.com/App-vNext/Polly/blob/2ac94cff75d2a63200dfab76f90e7c462f463a3b/src/Polly.Shared/Fallback/FallbackEngineAsync.cs#L54-L56), so it is likely safe to dispose the original `HttpResponseMessage` in the `onFallbackAsync`, given your posted code doesn't use it in the subsequent `fallbackAction`.  

You do also have the option of [this overload](https://github.com/App-vNext/Polly/blob/f4404005b5c1e4965b74b3fe01a6b4ec0642f97a/src/Polly.Shared/Fallback/FallbackSyntaxAsync.cs#L217) where both the `fallbackAction` and `onFallbackAsync` are provided the `DelegateResult<HttpResponseMessage>` as an input parameter.  So (with that overload) you can also dispose the original `HttpResponseMessage` later, in the `fallbackAction`, if needed or preferred.

**Comment by elviswatkins** [comment]
Yes, I want to use async, but this is an older repository and cannot make those changes yet.  It is in the backlog for the near future.
I have gone with the second option and use the overload that takes the  `DelegateResult<HttpResponseMessage>`.  I also found a [link](https://github.com/aspnet/Security/issues/886) that says it is not necessary to dispose the HttpResponseMessage, but my old school brain cannot get around not calling Dispose.

**Comment by petrroll** [comment]
> I also found a link that says it is not necessary to dispose the HttpResponseMessage, but my old school brain cannot get around not calling Dispose.

Just as a caution for others. It is necessary, at least on some versions of .NET FW. We got bit by that on .NET FW 4.7.2 for example.
