### ISSUE TITLE
WhatIf/dry run mode for Circuit Breakers and Bulkheads?

### ISSUE THREAD

**Issue by bartelink** [App-vNext/Polly#496]
I'm implementing diverse policies such as Circuit Breakers and Bulkheads and having a great It Just Works experience so far - kudos to all along the way that got the code and docs to this point.

Question: A very useful thing (esp wrt tuning and bedding in within a large scale existing system) would be to be able to run them in some form of inert/monitoring/dry run mode before I give them teeth.

While this sort of whatiffery obviously doesn't make sense in all cases, for those two it would seem it does...

(Thinking aloud: one could even run a set of fairly loose policies, and then play what-if with a tighter set of constraints and see whether and when they would have triggered or not.)

Right now, it seems the APIs don't expose such a mechanism - i.e. my best option seems to be a mix of inspecting the state and/or catching the `CircuitBrokenException`, logging and then running anyway. (e.g. I don't see an `onRejecting` on a circuitbreaker's main API - though I have not spent a lot of time with the source or ILSpy yet so I could well be wrong)

I'm happy to expand on this to explain in more depth what sort of things would be of interest, but my first step is to see if I'm missing anything obvious in the APIs and/or whether anyone has had success approaching this problem in a way that's not jumping out at me?

I'm also happy to be told 'not our department', in which case I'll likely be along with questions and PRs wrt exposing some of the internal state and/or events to facilitate such inspection without Polly handling it itself.

**Comment by reisenberger** [comment]
Thanks @bartelink . Great q and can see how this would add value for test-in-prod or blue-green deployments.

### Immediate options

**CircuitBreaker**: You can make an inert breaker right now by configuring `durationOfBreak: TimeSpan.Zero`.  When the break threshold is met the `onBreak` delegate will be triggered and monitoring can be attached to that for whatiffery. No request will ever see the breaker as open, so it will be inert.

**Bulkhead**: You can make an inert bulkhead right now by configuring `maxParallelization: Int.MaxValue`.  You can then monitor `BulkheadAvailableCount` to determine when an imaginary bulkhead capacity of `N` would have been exceeded.

**Playing what-if with progressively tightening contraints:** [Dynamic reconfiguration during running](https://github.com/App-vNext/Polly/wiki/Dynamic-reconfiguration-during-running) (ie you can reconfigure without having to recycle the process) could support this.

**Master switch:** [PolicyRegistry](https://github.com/App-vNext/Polly/wiki/PolicyRegistry) is backed by interfaces.  You could easily implement a custom [`IReadOnlyPolicyRegistry`](https://github.com/App-vNext/Polly/blob/f4ee7442ac9cabfb54eb8b2d327e7025a643dacf/src/Polly.Shared/Registry/IReadOnlyPolicyRegistry.cs) for a master switch or "kill switch" to take Polly as a whole in/out of the mix, if desired (if that adds comfort, if experimenting in a live/prod environment).  Implementation would be a custom `IReadOnlyPolicyRegistry` which wraps the normal implementation: ordinarily it would just delegate to a wrapped [`PolicyRegistry`](https://github.com/App-vNext/Polly/blob/f4ee7442ac9cabfb54eb8b2d327e7025a643dacf/src/Polly.Shared/Registry/PolicyRegistry.cs) to return the normal policies, but if the "off" switch was set it could return [NoOpPolicy](https://github.com/App-vNext/Polly/wiki/NoOp) for every Policy (taking Polly out of the mix).

---

### Possible extensions to Polly

#### `onBreakerRejected` for CircuitBreaker

We would be happy to take a PR to add a delegate hook `onBreakerRejected` , which would operate in a similar way to `onBulkheadRejected`.  If you/anyone want to contribute this, then I can kick-start by staking out the likely new overload signatures.

---

>happy to expand on this to explain in more depth what sort of things would be of interest

Very happy to hear more ...

**Comment by bartelink** [comment]
Apologies for not replying sooner - your response helped more than you'll know. After a delayed start, I've since gotten to implement [the bulk of my intended functionality](https://github.com/jet/CallPolly/blob/master/src/CallPolly/Rules.fs) as alluded to in the question.

Firstly, I'll respond to your points based on my learnings:-

>`CircuitBreaker`: You can make an inert breaker right now by configuring `durationOfBreak: TimeSpan.Zero`. When the break threshold is met the onBreak delegate will be triggered and monitoring can be attached to that for whatiffery. No request will ever see the breaker as open, so it will be inert.

This works very well. One side issue is that `onReset` and `onHalfOpen` need to be special cased not to log as I make them do in the normal case.

>`Bulkhead`: You can make an inert bulkhead right now by configuring `maxParallelization: Int.MaxValue`. You can then monitor `BulkheadAvailableCount` to determine when an imaginary bulkhead capacity of N would have been exceeded.

This also works well. One side issue is that in tests I need to jump through a lot of hoops to verify that a dryRun mode work cleanly across multiple threads

>Playing what-if with progressively tightening contraints: Dynamic reconfiguration during running (ie you can reconfigure without having to recycle the process) could support this.

>Master switch: PolicyRegistry is backed by interfaces. You could easily implement a custom IReadOnlyPolicyRegistry for a master switch or "kill switch" to take Polly as a whole in/out of the mix, if desired (if that adds comfort, if experimenting in a live/prod environment). Implementation would be a custom IReadOnlyPolicyRegistry which wraps the normal implementation: ordinarily it would just delegate to a wrapped PolicyRegistry to return the normal policies, but if the "off" switch was set it could return NoOpPolicy for every Policy (taking Polly out of the mix).

While this is not directly useful to me (I'm effectively building my own PolicyRegistry), it does seem that your proposed scheme could achieve that. (I'm [loosely] unifying call configuration such as base urls etc. with the policies in a single config source)

>`onBreakerRejected` for `CircuitBreaker`
>We would be happy to take a PR to add a delegate hook `onBreakerRejected`, which would operate in a similar way to `onBulkheadRejected`. If you/anyone want to contribute this, then I can kick-start by staking out the likely new overload signatures.

This would be useful (including when isolated) - having access to the `Context`'s `OperationKey` is important but I'm sure you know that.
I think only adding it to advanced would probably make sense

Related is a need to have `onTimeoutRejected` (I would not be able to remove the exception filter I'm using as a trap logging without that also having such a callback (aside: the elapsed time (as opposed to the timeout, which may or may not have been honored based on the cancellation mode) is useful in there too if Polly is in a position to provide that)) 

maybe name of callback Should be `onRejected` ?

So, in summary, ordered by my perception of how useful I can imagine them being useful to others (I am not unhappy with my implementation as it is), the following extensions would be useful to me:-

- While I'm by no means blocked on this, having `onRejected` delegates added to `AdvancedCircuitBreakerAsync`, `CircuitBreakerAsync` and `TimeoutAsync` would be useful (happy to do a minimal impl of the ones I use as a base PR and then let you point out other overloads you'd like to see also have one.)
- stretch: having `ExecuteAsync`'s callback and `timeoutRejected` make a `TimeSpan sinceStart` (but ideally as a [`StopwatchInterval`](https://github.com/jet/CallPolly/blob/master/src/CallPolly/Events.fs#L7)) available (maybe via `Context` ?) would be useful
- super-stretch: I'd be able to use an `onScheduled: Action<int>` delegate arg on `BulkheadAsync` that would signal the (ephemeral) slot one got assigned in the semaphore or queue (so one can log to indicate stuff is being queued, either for real, or (where I apply an artificially unlimited `maxParallelization` value), to determine more authoritatively whether this is getting scheduled immediately or (implied by `allocatedPosition` being greater than the real `maxParallelization` or in my `dryRun` mode, the `maxParallelization` I'm simulating) (I doubt this makes any sense, but an `int allocatedPosition` parameter in the `ExecuteAsync Func<CancellatonToken,Task` callback would also serve my purposes in this instance)

In terms of how useful these are to me for my impl specifically:
- an `onRejected` avoids the need for a messy exception filter, but given he system is already incurring an exception cost, that's probably not the end of the world perf-wise
- a `sinceStart` or a `waitInterval` on `Context` would remove some slightly messy code when generating metrics
- an `onScheduled` would allow me to emit more consistent metrics in a manner that the current API does not offer me due to the [correctly] lockfree implementation of bulkhead.

I'm going to close this issue to signal that I'm not blocked and consider my question to be way more than answered already. Next step from my perspective is for you to signal (iff you wish) which, if any of the above, you'd like to see:
a) implemented (in which case we'd make an Issue ticket and I'll hopefully get around to a PR in the coming weeks)
b) spiked to show how messy they are likely to be in terms of impl (just ask and I'll make a PR to show what I mean)

**Comment by reisenberger** [comment]
@bartelink A lot of great points [in here](https://github.com/App-vNext/Polly/issues/496#issuecomment-425602845) again (thank you!).  I'll hope to respond/x-ref in extra detail later, especially when things we might do in Polly converge with this.  Briefly (to get you some initial / overview responses):

+ `onTimeoutRejected`: I _think_ what you're describing already exists as the `onTimeout`/[`onTimeoutAsync` delegate](https://github.com/App-vNext/Polly/blob/37005afd53bd8c349d2560594e6894a82266438d/src/Polly.Shared/Timeout/TimeoutTResultSyntaxAsync.cs#L377) of the timeout policies.  Does that help? 

+ A number of the proposals (`onScheduled`; capturing timing information) are a close fit with things we want to do when [adding metrics deeper into Polly](https://github.com/App-vNext/Polly/issues/326). If/when/as-soon-as I can get time to progress that, it would be great to bring you (and anyone interested) back in on the discussion of, eg, the touchpoints for emitting events from each policy. (And indeed dev help may be useful too!).

Keeping this briefer to keep things moving, but lots to come back to here.

**Comment by bartelink** [comment]
Thanks for the response!

> `onTimeoutRejected`: I think what you're describing already exists as the `onTimeout/onTimeoutAsync` delegate of the timeout policies. Does that help?

I noticed that initially but then stopped using it - while I could use it, ultimately I need to trace the time interval since the start of the overall request (which to a degree can be inferred from a ` TimeSpan`, but ultimately does not solve all my problems [TMI: I also log breaches of SLAs, and have a dryRun mode](https://github.com/jet/CallPolly/search?q=logTimeout&unscoped_q=logTimeout)). So while I likely can take advantage of it, it means stashing and passing stuff in the `Context`, which I'm seeking to minimize. (Which brings us back to having a `StopwatchInterval` on the context itself, which I'm not seeking to push as something do do separate to the overall metrics effort).

The most exact fit for my use case would mean having an `onCompleted` which is called uniformly and provides an indication of whether we are throwing or not (together with the start instant). From looking at the code, that's not something that will fit in cleanly. Additionally, I'm thinking `ExecuteAsync` providing `onCompleted` is more likely to be useful for general use (not saying very likely, just more likely).

> eg, the touchpoints for emitting events from each policy. (And indeed dev help may be useful too!).

I'm definitely watching closely, and interested to see where your metrics plans lead - essentially my library is aiming to provide just that; we have some homegrown stuff we are seeking to ultimately generalize and attach to Open Tracing based outputs, but also feed to various metrics sinks. Having a good story for a clean integration of tracing, resilience primitives and metrics is definitely something that's on my radar - I'll be watching the notifications with interest.

**Comment by bartelink** [comment]
Sounds good. Best of all, I'll hopefully be able to validate it by deleting ugly code out of CallPolly while the tests continue to pass (there's still lots of to work to do in terms of making it more approachable, i.e. readmes etc) ;)
