### ISSUE TITLE
Setting Correlation id

### ISSUE THREAD

**Issue by fatagun** [App-vNext/Polly#516]
Howdy, 

How can I set the `CorrelationId` to the correlation id i have in my request that I carry over via `X-Correlation-ID` header across my services ? This way I can have the same correlation id in all the services and clients. 

When I look at [Context](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/Context.cs)
I don't see how I can use my correlationId?

Can you please elaborate?

Is it possible to have such feature?

Thanks.

**Comment by fatagun** [comment]
Thank you for prompt response. I will look into the options.

**Comment by Crackygirly15** [comment]
KotlinDslScriptsParameter(correlationId=503205361151100, scriptFiles=[]) => StandardKotlinDslScriptsModel(scripts=[], commonModel=CommonKotlinDslScriptModel(classPath=[], sourcePath=[], implicitImports=[]), dehydratedScriptModels={}) - took 0.0 secs



Can anybody solve this problem?, Facing this problem whenever I add firebase to my application.
