### ISSUE TITLE
Circuit Breaking OnBreak/OnReset Actions

### ISSUE THREAD

**Issue by jabaran** [App-vNext/Polly#52]
Has there been thought given to providing events to fire when the circuit is broken, and when the circuit is again open?

The use case I'm thinking of is when the application is consuming from a message queue we want to tear down the message queue connection so the work goes to other services, but we also want to wire back up to the queue once the circuit is again open.

I've done a fork and I have a crude example and I'll work on a pull request if the maintainers feel that this is something that would be of value to the project as a whole and not solely a scenario I'm concerned with.

**Comment by reisenberger** [comment]
@jabaran Thank you very much for this suggestion - events on circuit state change could be a valuable addition to circuit-breaker for other reasons too - for example for performance and health monitoring.  The AppvNext team (new stewards of Polly) hopes to turn its attention to circuit-breaker shortly, so watch this space!

**Comment by reisenberger** [comment]
@jabaran A very valuable idea, not least for those (including my own team) who may wish to log - or raise more intrusive alerts to DevOps - on changes of circuit state.  Thanks for the idea.  PR coming, including this, shortly.

**Comment by jabaran** [comment]
Excited to give this a shot, thank you!

**Comment by reisenberger** [comment]
@jabaran See the full documentation now for the new circuit-breaker features at: https://github.com/App-vNext/Polly/wiki/Circuit-Breaker

Note that the `onBreak`, `onReset` and `onHalfOpen` delegates execute (necessarily) within locks held by the circuit-breaker - see the detailed documentation for greater detail.  For this reason you (naturally) do not want to execute _too_ long blocking actions during these delegates.  However, it is intended that usages such as you originally requested should work.
