### ISSUE TITLE
Inherit IReadOnlyPolicyRegistry from IEnumerable<TKey, IsPolicy>

### ISSUE THREAD

**Issue by SeanFarrow** [App-vNext/Polly#520]
It would be really nice if IReadOnlyPolicyRegistry could implement IEnumerable<TKey, IsPolicy>. This would allow one to iterate through the configured policies and also allow the use of collection initializers when constructing a writable Policy registry.
I'm happy to do this if it would be warranted, but my only question would be what tests would be warranted?

**Comment by reisenberger** [comment]
Hi @SeanFarrow This suggestion seems useful for both reasons: happy to take a PR.

I'm thinking `IEnumerable<KeyValuePair<TKey, IsPolicy>>` would be what it should implement (following the pattern of the dictionary-like semantics it already exposes).

Re:
>what tests would be warranted?

Polly's own concrete implementation `PolicyRegistry` [implements `IReadOnlyPolicyRegistry<string>` indirectly](https://github.com/App-vNext/Polly/blob/9a9da0437f368013b6a58eb673e42e5efea2bfea/src/Polly.Shared/Registry/PolicyRegistry.cs#L11), so it would certainly be necessary for the concrete `PolicyRegistry` to be extended to fulfil `IEnumerable<KeyValuePair<TKey, IsPolicy>>`, and for tests on that.  It could be nice also to have a test demonstrating the collection initializer syntax.

**Comment by SeanFarrow** [comment]
@reisenberger<https://github.com/reisenberger>,
That all makes sense. Having looked at the specs, I notice you are testing the IReadOnlyPolicyRegistry using integration-style tests. Should we test the IEnumerable<KeyValuePair<TKey, IsPolicy>> using mocks?
Essentially, I’d like to test that the  internal dictionaries GetEnumerator method is called.
We can then have a test that check that the collection initializer functionality is working as you suggest.

**Comment by reisenberger** [comment]
Happy with using Moq for this.

**Comment by SeanFarrow** [comment]
Ok, I’ll sort this in the next day or so.

What is the next planned version of Polly?

**Comment by reisenberger** [comment]
>What is the next planned version of Polly?

We could probably put out a next release (with this, 513 and 517) late this week or early next.  (I will scope 499/508 out of that release as dev time is longer)

**Comment by SeanFarrow** [comment]
Ok, I’ll work on this tomorrow.

**Comment by SeanFarrow** [comment]
@Reisenberger,

With the current design of IReadOnlyPolicyRegistry<in TKey>, we can't implement IEnumerable<KeyValuePair<TKey, ISPolicy>> as the T of IEnumerable is an out parameter and we are using TKey as an in.

Would it make sense to restrict the IReadOnlyPolicyRegistry to use a string. Is there any reason why someone would use another type as the key?

**Comment by SeanFarrow** [comment]
I realise this is a breaking change, so would have to wait until V7.

**Comment by reisenberger** [comment]
@SeanFarrow I am working towards a major release (v7) of Polly for first weeks of January.  If you wish to pick up this issue again and make a PR, we'd be happy to include that in V7.

To answer some previous points, re:

>With the current design of IReadOnlyPolicyRegistry, we can't implement IEnumerable<KeyValuePair<TKey, ISPolicy>> as the T of IEnumerable is an out parameter and we are using TKey as an in.

Happy to drop that `out` restriction for v7.

Re:

>Would it make sense to restrict the `IReadOnlyPolicyRegistry` to use a string. Is there any reason why someone would use another type as the key?

I don't think we _need_ to restrict to string keys, to deliver the `IEnumerable<KeyValuePair<TKey, ISPolicy>>` and thus collection-initializer functionality. Let me know if there's something I'm missing, though.

**Comment by SeanFarrow** [comment]
@ Reisenberger
How early is “early January”?
If we drop the out requirement, then this should work, we don’t need to restrict to string.
Cheers
Sean.

**Comment by SeanFarrow** [comment]
Hi Dylan,

Can you let me know when this has been murged.
I’ll update my fork and work on this early next week.
Is there a list as to what has changed for V7?
Cheers
Sean.

**Comment by reisenberger** [comment]
Hi Sean.  #552 has now been merged to the [v7.0.0 branch](https://github.com/App-vNext/Polly/tree/v700) and you can target any policy registry work onto that branch.

Re:

>Is there a list as to what has changed for V7?

Yep. Our usual [changelog](https://github.com/App-vNext/Polly/blob/v700/CHANGELOG.md#700) covers this.  In short:

+ A new route to creating custom policies outside Polly - doco to follow
+ Clarification of the sync/async split: full doco [already on wiki](https://github.com/App-vNext/Polly/wiki/Polly-v7-breaking-changes)

**Comment by reisenberger** [comment]
Thanks Sean!

Very happy for any duplicate tests to be cleaned out.

Re:

>I'm adding a constructor to the PolicyRegistry class that takes an `IDictionary<TKey, IsPolicy>`

If this is only to assist with testing, consider making that constructor `internal` so that we aren't adding API surface for public users.  But if we think there is a valid public use case for it, it can be public.

The test projects _do_ all have access to the `internal`s of Polly via the [`InternalsVisibleToAttribute`](https://github.com/App-vNext/Polly/blob/master/src/Polly.NetStandard20/Properties/AssemblyInfo.cs#L11), so tests would be able to access anything marked `internal`.  So that could apply for that constructor, and for the `private` property you mentioned needing reflection for too; consider marking it `internal` and tests will be able to see it.

Will be easier to answer the q whether those tests are necessary once we have a PR up, I think

Thanks again!

**Comment by SeanFarrow** [comment]
@reisenberger, 

As you will have noticed, I've submitted a PR, feel free to review/change where needed.

I'll have a look at the tests later this week to see what can be cleaned up.
Also, should we be using C# 6/7 features all over the codebase where it makes sense, given we are using vs2017 as a minimum IDE, this would make sense
I'll raise an issue to cover both as it's work that could be done at the same time, it may not make it in to V7 though, as I may be starting a new job in the new year.

**Comment by reisenberger** [comment]
Hi @SeanFarrow .  Re:

>Should we be using C# 6/7 features all over the codebase where it makes sense, given we are using vs2017 as a minimum IDE
>I'll raise an issue to cover both as it's work that could be done at the same time, it may not make it in to V7 though, as I may be starting a new job in the new year.

Very happy to take a PR for any C# 6/7 features; thanks! (I take them in where I see opps, not had time to do a complete sweep.)

Suggest we hold till after v7 is out, unless you plan a PR on that during this week.

The only element which should go to discussion before actual PR is the use of local functions. We might make some allocation wins with those, but I also did work around issue 271 which implies a different approach for the main Polly executables ... TL;DR local functions are better discussed, before you/anyone works up something which might be superseded by other developments.

Thanks again!

**Comment by SeanFarrow** [comment]
@ Reisenberger,

The changes you made to the PR seem reasonable, so I’m happy to merge.

Regarding C# 6/7, this won’t happen this week, but will happen sporadically over the next little while.
I’m not planning on using local functions, due to the work on issue #271. I agree, there could be allocation wins there, but I’d probably want to do some performance profiling to see whether it makes a real difference.

**Comment by reisenberger** [comment]
Thanks @SeanFarrow !  No problem about timing for anything; thank you for your contributions!

+1 re performance profiling.

Thanks again.
