### ISSUE TITLE
Cache only ok filter with different ttl stategy

### ISSUE THREAD

**Issue by umeshkarthik** [App-vNext/Polly#522]
Hi All,
I been using the below code to cache only OkResults
  Func<Context, IActionResult, Ttl> cacheOnly200OKfilter =
                 (context, result) => new Ttl(
                  timeSpan: ((Microsoft.AspNetCore.Mvc.ObjectResult)result).StatusCode == 200 ? ts : TimeSpan.Zero,
                  slidingExpiration: IsSliding
                 );
Now i am planing to use RelativeTtl,SlidingTtl,ContextualTtl. Do you have any suggestion on achieving this

**Comment by reisenberger** [comment]
@umeshkarthik  All of the Ttl strategies you mention - `RelativeTtl`, `SlidingTtl`, `ContextualTtl` - provide a smaller subset of functionality than the [`ResultTtl` which it looks like you are already using](https://github.com/App-vNext/Polly/wiki/Cache#caching-responses-only-selectively).  

+ To mimic `SlidingTtl`, just set `IsSliding = true` in the code you have already posted.
+ To mimic `RelativeTtl`, just pass the `ts` variable in the code you have already posted, as the timespan parameter.
+ To mimic `ContextualTtl`, you could change the `Func<Context, IActionResult, Ttl>` function you are defining to make use of data on the `context` parameter you are passing in.

**Comment by umeshkarthik** [comment]
Hi Dylan, I am trying to create a cache policy with relative Ttl which only
caches ok result. With the code I have posted I coudn’tfind a way of doing
it. Can you provide a sample code piece for this.

**Comment by reisenberger** [comment]
Hi @umeshkarthik . Here is the sample code:

    Func<Context, HttpResponseMessage, Ttl> cacheOnly200OKfilter =
        (context, result) => new Ttl(
            timeSpan: result.StatusCode == HttpStatusCode.OK ? TimeSpan.FromMinutes(5) : TimeSpan.Zero,    // ** this timespan is a relative ttl **
            slidingExpiration: false
        );

    IAsyncPolicy<HttpResponseMessage> cacheOnly200OKpolicy = 
        Policy.CacheAsync<HttpResponseMessage>(
            cacheProvider: /* the cache provider you are using */,
            ttlStrategy: new ResultTtl(cacheOnly200OKfilter),
            onCacheError: /* whatever cache error logging */
        ); // (or other richer CacheAsync overload taking an ITtlStrategy ttlStrategy)

(this is the example [from here](https://github.com/App-vNext/Polly/wiki/Cache#caching-responses-only-selectively) adjusted to `slidingExpiration: false`; same concept as the [code you posted above](https://github.com/App-vNext/Polly/issues/522#issue-374417006))

This policy will cache items with a relative time-to-live of 5 minutes (they will be kept for 5-minutes from the time of putting into the cache), provided the return value's `StatusCode == HttpStatusCode.OK`.  This code sample is exactly what you ask for:

>a cache policy with relative Ttl which only caches ok result

The code sample behaves the same as if you had configured `new RelativeTtl(TimeSpan.FromMinutes(5))`, except it does the other thing you ask for - only cache ok result.

---

If you change to `slidingExpiration: true` in the above code sample, then you have exactly equivalent to configuring `new SlidingTtl(TimeSpan.FromMinutes(5))`, except that it only caches ok results.

**Comment by reisenberger** [comment]
Hi @umeshkarthik 

>Do you have any sample code for the Contextual ttl for Ok Results?

I don't. If you need this behaviour, You could [read the 35-line source code of `ContextualTtl`](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/Caching/ContextualTtl.cs) and merge it with [the previous sample](https://github.com/App-vNext/Polly/issues/522#issuecomment-433637898) to create this quite easily for yourself, though.

**Comment by umeshkarthik** [comment]
Thanks Dylan
