### ISSUE TITLE
CircuitBreaker: handle both results and exceptions in the same policy

### ISSUE THREAD

**Issue by 4ybaka** [App-vNext/Polly#525]
**Is your feature request related to a specific problem? Or an existing feature? Please describe.**

We use CircuitBreaker in HTTP client pipeline as a separate delegating handler. The problem is that 5xx responses are transformed to exceptions outside of this pipeline and circuit breaker doesn't treat them as errors.

**Describe your proposed or preferred solution**:

I see that CircuitBreakerEngine already has shouldHandleResultPredicates parameters that should satisfy our needs. But this class is internal and AdvancedCircuitBreakerSyntaxAsync uses PredicateHelper<EmptyStruct>.EmptyResultPredicates and doesn't allow to override it. So my suggestion is to allow to override it in AdvancedCircuitBreakerSyntaxAsync.

**Describe any alternative options you've considered**: 

Make CircuitBreakerEngine  public to allow anyone create it with required params.

**Any additional info?**

**Comment by reisenberger** [comment]
@4ybaka If I have understood the question correctly, you simply need to use the existing [`.HandleResult<TResult>(...)`](https://github.com/App-vNext/Polly#step-1b-optionally-specify-return-results-you-want-to-handle) syntax to configure the circuit-breaker to handle results as well as exceptions.  The `.HandleResult<TResult>(...)` syntax shown there works with `.AdvancedCircuitBreakerAsync(...)` as well.

Here is another example, [a test](https://github.com/App-vNext/Polly/blob/a7a8c4830b35d8f863981e3a92d7a12c5ae51aea/src/Polly.SharedSpecs/CircuitBreaker/CircuitBreakerTResultAsyncSpecs.cs#L101-L122) which demonstrating configuring a circuit-breaker to handle result types.

**Comment by 4ybaka** [comment]
@reisenberger I need to handle both cases in one circuit breaker: based on exception and based on result. HandleResult method creates PolicyBuilder that handles only result while Handle method handles only exceptions. How can I create policy with both of them?

**Comment by 4ybaka** [comment]
Thanks, that's what I searched for.
