### ISSUE TITLE
Feature suggestion: Token Bucket and Leaky Bucket

### ISSUE THREAD

**Issue by sq735** [App-vNext/Polly#528]
Is it possible to add in a new version **"[Token Bucket](https://en.wikipedia.org/wiki/Token_bucket)"** and **"[Leaky Bucket](https://en.wikipedia.org/wiki/Leaky_bucket)"** policy?

**Comment by reisenberger** [comment]
Hi @sq735 . This is not something I have any current time available to develop myself.  (The time I have for Polly will likely focus on Distributed Circuit Breaker and metrics.)

We are fine with taking Pull Requests though, if you (or anyone else) wants to take this on.  (Right now we have great contributors developing InjectFault and InjectLatency, demonstrating how easy it is to add new policies.)

See also [the existing discussion in the Polly roadmap around rate-limiting policies](https://github.com/App-vNext/Polly/wiki/Polly-Roadmap#rate-limit-policy) with some other algorithm options, and related #330 .

**Comment by reisenberger** [comment]
To avoid noise on the 'up-for-grabs' labels (three similar issues), I'm closing this issue in favour of the similar #260 (and noting the ideas of Token Bucket and Leaky Bucket there).
