### ISSUE TITLE
Policy.Async.ExecuteOverloads.cs missing ConfigureAwait()

### ISSUE THREAD

**Issue by flin-zap** [App-vNext/Polly#540]
The 2 x Policy.Async.ExecuteOverloads.ExecuteAsync() functions are missing ConfigureAwait(continueOnCapturedContext) in their awaits

**Comment by flin-zap** [comment]
Policy.Async.TResult.ExecuteOverloads.ExecuteAsync() is also missing one

**Comment by reisenberger** [comment]
@flin-zap Please feel free to make a PR to correct them! (against the branch `onV611dev`)

**Comment by flin-zap** [comment]
Done, be great if you could make a release with these fixes ASAP

**Comment by reisenberger** [comment]
@flin-zap @doxakis . Thanks. That is merged to master!  Release v6.1.2 should appear on nuget in the next day or so.
