### ISSUE TITLE
Retry handler extension method.

### ISSUE THREAD

**Issue by shagilt** [App-vNext/Polly#544]
Here is my scenario:
I want to add retry for some 5XX errors(not all 5xx) and based on exception too.
I am looking an extension method for IHttpClientBuilder to add retry policy. I also looked at HandleTransientHttpError(), but it retries on all 5xx errors.
Is there an extension method which will suit my requirement?

**Comment by reisenberger** [comment]
Polly only provides the extensions methods which (it sounds like) you have already discovered.  However:

+ (1) You can still construct policies of any kind and tie them in to HttpClientFactory (without any new extension methods); and
+ (2) You can still wrap up your choices of what-to-handle in your own extensions methods, if you wish.

(1) To register an entirely bespoke Policy with HttpClientFactory, see our [Polly and HttpClientFactory documentation here](https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory#using-any-policy-configured-via-the-traditional-polly-syntax) - the first example there demonstrates exactly how to construct a policy handling your own bespoke choice of exceptions and status codes.

(2) To wrap up your choices of what-to-handle in your own extension methods:

+ Follow the [pattern here](https://github.com/App-vNext/Polly.Extensions.Http/blob/34936cf3f202810285288b6a2134058a6e882aea/src/Polly.Extensions.Http.Shared/HttpPolicyExtensions.cs) to create your own version of a method like `.HandleTransientHttpError()`.  You don't have to provide every `Or...()` variant in that file unless you want that flexibility.
+ Follow the [pattern here](https://github.com/aspnet/HttpClientFactory/blob/3e846390bd2edbd2514ebad6af05c9b5cd2eef14/src/Microsoft.Extensions.Http.Polly/DependencyInjection/PollyHttpClientBuilderExtensions.cs#L215-L236) to tie the extension method from previous bullet into an extension method on `IHttpClientBuilder`

You can code and host these extension methods in your own app.

**Comment by shagilt** [comment]
Thanks @reisenberger, I will try these.
