### ISSUE TITLE
(very edge case) Context passed to onBreak or onReset when manually break or reset the circuit, should not be shared/mutable

### ISSUE THREAD

**Issue by reisenberger** [App-vNext/Polly#546]
**Summary**: 

_An exceptionally edge-case issue unlikely ever to have been hit, but can be tided away._

Circuit-breaker state-transition delegates `onBreak` and `onReset` take a `Context` parameter, passing to the delegate the context of the execution when the circuit broke or reset.

When the circuit is broken _manually_ with the `CircuitBreaker.Isolate(...)` method, or reset manually with `CircuitBreaker.Reset(...)`, those are manual changes outside of an individual policy execution, and so the `onBreak` and `onReset` delegates invoked were passed an empty `Context`.

**Expected behavior**: 

When  `CircuitBreaker.Isolate(...)` method or `CircuitBreaker.Reset(...)` is invoked, the `Context` passed to `onBreak` and `onReset` should always be empty.

**Actual behaviour**:

The `Context` instance passed to the methods in those cases was in fact long-lived and shared between invocations of those methods. The `IDictionary` methods on `Context` could potentially have been used to add data to that long-lived, intended-to-be-empty instance of `Context`; which was never the intention.

**Comment by CharlesJoo** [comment]
![image](https://user-images.githubusercontent.com/33758199/167380934-e53900f2-b28f-4a39-a657-3e73dfc1d315.png)
I still get this issue when use CircuitBreaker.Reset(...) to reset manually with Polly 7.2.3

**Comment by martincostello** [comment]
If you are still having a problem, please create a new issue with a minimal reproducible example.
