### ISSUE TITLE
How to not include initial call in Timeout

### ISSUE THREAD

**Issue by JustinMasters** [App-vNext/Polly#547]
Trying to create a policy that applies a timeout for the retry part of the execution, but not the whole operation.

e.g. Try once, then try again for up to maxRetries or 1 minute, whichever comes first

My current code the timeout is across the entire operation

```
Policy retryPolicy = Policy.Handle(canHandle)
                    .WaitAndRetry(maxRetries, retryAttempt =>
                        TimeSpan.FromSeconds(Math.Pow(1.4, retryAttempt) * sleepSeed),
                            (exception, timespan, retryCount, context) =>
                            {
                                logger.LogWarning($"Exception caught")
							});

var timeout = Policy.Timeout(TimeSpan.FromMilliseconds(config.MaxSleepTimeInMs));

return timeout.Wrap(retryPolicy);
```

**Comment by reisenberger** [comment]
@JustinMasters That pattern isn't built in to Polly.

Two ways you could build round Polly to achieve it:

1. Place the initial try in a try-catch.  If you detect failure, then use the existing code you have for the retries.

2. Use your own `CancellationTokenSource` / `CancellationToken` pair, and calling `CancellationTokenSource.CancelAfter(...)` within the `onRetry` method from the retry policy, when `retryCount == 1`.  If you declare/create your policies in a separate place/time (eg StartUp) from where you use them (as is often the case), you will need to use the [Dictionary-like properties on `Polly.Context`](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/Context.Dictionary.cs) to pass the `CancellationTokenSource` into the execution, and to extract it from the `Context` within the `onRetry`.

Of course you can wrap either up in your own method, to package the implementation neatly.

**Comment by JustinMasters** [comment]
Thanks for that @reisenberger, I thought I was just using the wrong puzzle pieces.
