### ISSUE TITLE
Looking for a new maintainer / home

### ISSUE THREAD

**Issue by michael-wolfenden** [App-vNext/Polly#55]
Unfortunately due to new commitments, I am unable to continue to maintain this project. If anyone is interested in taking over please respond to this issue.

**Comment by joelhulen** [comment]
Michael,

What is involved? I may be interested.

**Comment by michael-wolfenden** [comment]
Basically taking complete ownership of the repository, handling issues / pull requests /updates etc. I'm looking for people committed to the ongoing maintenance of this project.

**Comment by joelhulen** [comment]
I will gladly step up if someone else who's already been involved doesn't. If anyone who's contributed to this project to date wants to take over, then they might be more suitable for the task. However, I am happy to keep it going.

**Comment by michael-wolfenden** [comment]
Thanks @joelhulen, I've put a call out on twitter. I'll leave if for a couple days and get back to you.

**Comment by ploeh** [comment]
I think I'm probably stating the obvious here, but whatever happens from here on, make sure to migrate the project to a GitHub organisation, so that in the future, ownership can be transferred without moving the repository.

(I'm not saying that @michael-wolfenden has done anything wrong by starting with a personal repository - I do that all the time myself, and most of the time, the projects never become popular enough for that to be an issue.)

**Comment by michael-wolfenden** [comment]
@ploeh Absolutely, and if you know anyone that is interested then it would be much appreciated

**Comment by joelhulen** [comment]
Good point, @ploeh! @michael-wolfenden I've got an organization of developers, of which I am part, interested in taking over the project.

**Comment by michael-wolfenden** [comment]
@joelhulen You still happy to take the reins?

**Comment by joelhulen** [comment]
Yes. I'll move it under our App vNext orb so it's not tired up in my
individual account. There are 21 of us in the group, and at least a couple
besides me are interested in maintaining the library.

**Comment by michael-wolfenden** [comment]
@joelhulen Last night I created https://github.com/PollyOrganisation and was going to move the Polly repo there, but its your call?

**Comment by joelhulen** [comment]
I'd like to move it under the App vNext organization, if you don't mind.

**Comment by michael-wolfenden** [comment]
@joelhulen Whats the github url?

**Comment by joelhulen** [comment]
https://github.com/App-vNext

**Comment by michael-wolfenden** [comment]
Hmmm.. I need admin rights to App-vNext to transfer the repo

**Comment by joelhulen** [comment]
I just invited you to my team as a member. You should be able to create the
repo, etc. Please let me know if I need to elevate your permissions.

On Wed, Nov 25, 2015 at 7:08 PM, Michael Wolfenden <notifications@github.com

**Comment by michael-wolfenden** [comment]
@joelhulen Its been successfully transferred, feel free to remove me from your organidation. Thanks again for taking over the reins, its much appreciated. I have an appveyor build setup under my name that is currently building it on pushes / pull requests. The badge in the readme is also pointing to that. You will need to set up your own appveyor project to do the same (or not). Let me know if you need any help setting it up. The readme, nuspec all point to the old repo as well, the links will need to be changed to your new repo.

**Comment by joelhulen** [comment]
Thanks so much, Michael. I'm glad to do my part :)

I'll look into the appveyor stuff and let you know if I have any questions.

On Wed, Nov 25, 2015 at 8:01 PM, Michael Wolfenden <notifications@github.com

**Comment by joelhulen** [comment]
@michael-wolfenden I have set up an appveyor project for this, and I was wondering if there are any special settings for the project within appveyor that you set, or if you are relying on the configuration files contained within the project root instead?

**Comment by joelhulen** [comment]
Also, how do I update the project information and links here: https://www.nuget.org/packages/polly?

**Comment by michael-wolfenden** [comment]
@joelhulen In regards to appveyor, as far as I remember the appveyor.yml configuration file (https://github.com/App-vNext/Polly/blob/master/appveyor.yml) should be all that is needed. It just specifies to use vs2015 to build and rund the build.ps1 script. The build script itself will do the rest of the work including setting the appveyor version (using gitversion). Note, I manually upload the packages (artifacts) produced by appveyor to nuget. Are you having issues?

The other information comes from the nuspec file (https://github.com/App-vNext/Polly/blob/master/src/Polly.nuspec), but you will need to publish a new version of Polly to nuget for the changes you've made to show. The last change I made to Polly was to add .NET Core support (following https://oren.codes/2015/07/29/targeting-net-core/) however I never published this version (2.2.4) . You could publish this if you wanted so that your not just publishing a new version to change the project details. Note, there is also a signed version of Polly that the build produces (https://www.nuget.org/packages/polly-signed)

Let me know if you have any more questions.

**Comment by joelhulen** [comment]
Thanks for the great info. That's what I figured for Appveyor, but wanted to be certain.

When I try to upload the nuget files to https://www.nuget.org/packages/upload, I receive an error message stating "The package ID 'Polly' is not available.". I believe it's because it's associated with your account right now. Do you know a way around this?

**Comment by michael-wolfenden** [comment]
@joelhulen What is your nuget username?. Looking at https://docs.nuget.org/create/managing-package-owners, I can make you an owner, and then you can remove me as an owner to basically transfer ownership.

**Comment by joelhulen** [comment]
@michael-wolfenden It's "joelhulen".

**Comment by michael-wolfenden** [comment]
Just made you an owner of both Polly and Polly-Signed

**Comment by joelhulen** [comment]
Just got the emails. Perfect!

**Comment by joelhulen** [comment]
I noticed that this NuGet package has a bunch of dependencies now, I assume as part of the .NET Core support: https://www.nuget.org/packages/Polly/2.2.4

**Comment by michael-wolfenden** [comment]
@joelhulen yep thats right
