### ISSUE TITLE
WaitAndRetryAsync(...) blocks threads with Thread.Sleep(), causes thread starvation

### ISSUE THREAD

**Issue by reisenberger** [App-vNext/Polly#56]
Aware @michael-wolfenden has said he wishes to step back (sorry to hear Michael; beautiful idiom Polly has created).  Posting still a specific issue for ongoing Polly community - plus a question it raises poss feeds in to future directions for Polly.

**Specific bug/issue**: `WaitAndRetryAsync(...)` is not very `async`/`await` friendly, because the underlying implementation blocks with `Thread.Sleep(Timespan)`. Blocking threads kind of against the grain of `async`/`await`? 

Suggest move the `RetryAndWaitAsync(...)` implementation to something non-thread-blocking 
like `await Task.Delay(Timespan)`.  Moving the `RetryAndWaitAsync()` implementation to `await Task.Delay` would also open up the possibility to solve #46 Add cancellation support (with `Task.Delay` overload taking `CancellationToken`).  

**Future directions**: this prompted the question for me whether Polly should be kept as one library trying to support all of .NET3.5, .NET4, 4.5, PCL etc; whether it should be split; or when support for earlier .NET variants should be dropped.  Obviously a plus for a library to work against various versions (as now).  However, also a concern that supporting the older variants (/all in same library) might be holding back unleashing support for some of the .NET4.5+ features, such as those which would really make async/await work...?

**Comment by reisenberger** [comment]
On the specifics of moving to `await Task.Delay(Timespan)`, have been playing with a PR, but it's a bigger change than just replacing `SystemClock.Sleep` with `Sleep = async timeSpan => await Task.Delay(timeSpan)`, because the code calling `SystemClock.Sleep` is predicated on it actually blocking the thread before moving on to the next line which returns true to trigger the next try.  The next retry might need instead to be triggered by hanging a continuation (`.ContinueWith()`) off the `Task.Delay(timeSpan)`, which seems to imply making the `RetryPolicy` attempts loop re-entrant rather than a `while (true)`; a bigger recast of the overall retry architecture.

That said, if the whole retry architecture was moved to a re-entrancy/recursion approach, this could have benefits for .NET versions lower that 4.0/4.5 too: perhaps the whole retry architecture (or earlier .NET versions) could be moved to using a `System.Threading.Timer` - which might be less blocking for all versions?

Any community thoughts?

**Comment by reisenberger** [comment]
UPDATE: I now have an implementation for `WaitAndRetryAsync(...)` using the non-blocking `await Task.Delay`, without requiring a radical recast of the retry loop (ref previous post), ie within current Polly structures.

Will aim to post the solution to a Polly fork on my github in the next few days, in case anyone else facing same problem (and for feedback).  Before posting, want to produce a small console app to prove/demonstrate that the expect benefits in thread consumption are being realised.  

Can Pull Request this as soon as new stewardship for Polly in place.  

It should make `WaitAndRetryAsync(...)` more `async`-friendly and potentially much more efficient on the thread pool.

**Comment by joelhulen** [comment]
@reisenberger I agree on removing blocking and modernizing the overall architecture to support current async/await capabilities. Your point about breaking up the library does make sense, so we can take advantage of newer .NET versions. I'd also be interested in having a .NET core version of the library that can support cross-platform development. As one of the new stewards of this project, I'd like to hear some of your ideas about structuring this project, or breaking it up to support different versions.

**Comment by reisenberger** [comment]
@joelhulen, all. See github gist https://gist.github.com/reisenberger/48b4e8e0102d0d0f6290 for small console app which demonstrates the thread starvation caused by blocking `WaitAndRetryAsync(...)`.  (Obviously to be assumed on seeing `Thread.Sleep` in async implementation, but console app provides clear demo  - and allows us to check fixes bring expected benefits.)  Run console app against current implementation to see thread starvation. Run against a fix with `await Task.Delay` (eg @yevhen's #53) and thread-usage/elapsed time is as expected.

I have a local fix too, can make into pull request, but wanted to align it with @yevhen's #53 first, for easier onward merges.  Or we simply merge #53  ...?

( @joelhulen will comment further on .NET versioning of library another time )

**Comment by reisenberger** [comment]
( @joelhulen thanks for your stewardship, great to see this all moving)

**Comment by mauricedb** [comment]
@joelhulen 

Thanks for continuing with Polly!

My PR is more about using the new capabilities of ,NET standard and having one project build to multiple targets including .NET Core.

I would not even try to finish this until the bits required are final which I am guessing is end of Q1 2016. After that we should be good with just two projects, one for the actual assembly and one for the specs. That also depends on testing tools though and I am not sue when they will be good enough for the one specs project. Guessing that will be around the same time.

As far making things more async/await friendly I guess that really depends on the compilation targets and how far you want to go. With conditional compile you can go quite far and still be backward compatible but that makes the code quite a bit harder to maintain. Personally I would be inclined to let users of older version of the .NET framework use existing versions of Polly, maybe do the occasional bug fix where needed, and build a new version for the future including CoreCLR.

**Comment by joelhulen** [comment]
It is my pleasure to help move this project along!

This is great stuff. I've also been playing around with the beta bits. Hopefully now that they're in RC, the namespacing will be more stable, as will the APIs in general. There's still a ways to go, so it's wise to hold off.

@reisenberger, the @App-vNext/core and I will be going over the project this weekend, and will review your changes as well. I'll update this thread if we have any questions.

**Comment by reisenberger** [comment]
@joelhulen At https://github.com/reisenberger/Polly/tree/AsyncSleepExperiment have committed a branch had been using to experiment with substituting `await Task.Delay` for `Thread.Sleep` in `RetryAndWaitAsync()`

At https://github.com/reisenberger/Polly/tree/AsPR53AsyncSleepTaskDelayOnly I have committed a branch taking the async-sleep elements only out of @yevhen's PR #53, just so that the async sleep elements can be seen clearly separately.  

Both branches, if run against my gist console app (see earlier in thread), show the thread starvation problem fixed.

_I would recommend merging @yevhen's version as, while his and my version are effectively identical technically, @yevhen's presentation with the partial classes is clearer for onward maintenance_.  It's the conditional compile thing as @mauricedb  says, but yevhen's presentation is neat.

You could (if happy) either merge #53, or merge from https://github.com/reisenberger/Polly/tree/AsPR53AsyncSleepTaskDelayOnly to get the async-task bit only.  If merging from reisenberger/Polly/tree/AsPR53AsyncSleepTaskDelayOnly, credit for this should go to @yevhen (don't know how to do that fancy github magic like "Person X committed with Y" to credit it ;~)

**Comment by reisenberger** [comment]
Closed via #53
