### ISSUE TITLE
New transaction is not allowed

### ISSUE THREAD

**Issue by digitalmedia34** [App-vNext/Polly#567]
**Summary**: 

I am using polly with dapper orm in one of my projects. The issue that I am getting is that sometimes when I try to do update I get error 'New transaction is not allowed because there are other threads running in the session.' I need to mention that I am creating a new 'Idbtransanction' transaction when doing this update. The update also had a retry policy on sql timeout. Trying to mitigate the issue, I removed all async code, and my suspicion is that I am encountering an error with sql server, polly is retrying (like it should) but the transaction still active. 

Has anybody encountered this issue? Any ideas on how to handle this scenario are welcome.

Ps, dont know if this is the right place to post this question. 

<br/>
<br/>

**Expected behavior**: 

<br/>
<br/>

**Actual behaviour**:

<br/>
<br/>

**Steps / Code to reproduce the problem**: 

Best is a [complete example](https://stackoverflow.com/help/mcve) or failing unit test.  It is _always_ useful to see:

+ **code of any policy declarations**, 
+ **code of calls to `.Execute/AndCapture/Async(...)`**

**Comment by reisenberger** [comment]
Hi @digitalmedia34 . Thanks for the question.  You might be better to ask this question on the Dapper repo or StackOverflow.  There will probably be some restrictions on how the SQL transaction or the dapper elements governing them should or should not be instantiated, closed again, or re-used, but that will be Dapper-specific knowledge that I can't offer with a Polly hat on.  (I have used Dapper but it was a while ago ...)

Also, your suspicions here sound reasonable based on the info given:

>my suspicion is that I am encountering an error with sql server, polly is retrying (like it should) but the transaction still active

Good idea also to post example code with a question like this.  It is hard to give any insight (spot any possible smoking guns) without an example of how the code looks.

Apologies that time will not permit me to dig into this one more deeply.  

Anyone with Dapper insight very welcome to comment!

**Comment by digitalmedia34** [comment]
Thank you I post the same question, hopefully someone has done something like this before
