### ISSUE TITLE
PolicyRegistry constructor is internal in v7

### ISSUE THREAD

**Issue by maartenoosterhoff** [App-vNext/Polly#584]
**Summary**: 
Since commit https://github.com/App-vNext/Polly/commit/9a2fcfd5b2a75d69f903804d42e792553eb23732#diff-356886a77c8ea423c5d0b791f0870a4b the public parameterless constructor of type PolicyRegistry was replaced by an internal constructor. Perhaps this one done on purpose, but now it is impossible to create an instance of said type. The breaking changes documentation of v7 does not mention this.
<br/>
**Expected behavior**: 
Succesful compilation.
<br/>
**Actual behaviour**:
A compile-time error.
<br/>

**Comment by reisenberger** [comment]
Thanks @maartenoosterhoff . That unwanted change that slipped in wasn't picked up by unit tests because of `InternalsVisibleTo` the test assembly.  

Fixed in #585 . v7.0.2 should release to nuget, fixing this, in the next few hours.

**Comment by maartenoosterhoff** [comment]
Fabulous response time, thank you very much 👍
