### ISSUE TITLE
 error CS0012: The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, 

### ISSUE THREAD

**Issue by Shilp** [App-vNext/Polly#588]
error CS0012: The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral,  
I am getting the above error while buildin my project with Polly 5.3.1 version .NET framework 4.5.2.

Please suggest solution.

**Comment by reisenberger** [comment]
@Shilp I am not sure that this is an issue with Polly.  It could be to do with how your particular .NET framework 4.5.2 project was set up.  I just created a .NET framework 4.5.2 Console App, installed Polly 5.3.1 into that, and everything worked.  Can you try that sequence?  If that works, you should look for what is different about your other .NET 4.5.2 project where you have a problem.

Also: Do you have the .NET Standard 2.0 SDK installed?  See https://blogs.msdn.microsoft.com/benjaminperkins/2017/09/20/how-to-install-net-standard-2-0/ ; https://dotnet.microsoft.com/download

**Comment by Shilp** [comment]
@reisenberger  Thanks for the response, Sorry it was a mishap form our end where we referenced .net standard Polly instead of .net 4.5. Thanks!
