### ISSUE TITLE
Polly NuSpec is missing dependencies

### ISSUE THREAD

**Issue by onovotny** [App-vNext/Polly#59]
.NET Core requires packages to specify their dependencies. It should be pretty easy to add as I've written a tool that helps.

https://github.com/onovotny/ReferenceGenerator

The docs are there but just add a ref to your project and it'll update the nuspec on build to include the right dependencies.

**Comment by joelhulen** [comment]
@onovotny I won't be able to update this until this evening. If you feel so inclined, please update the NuSpec file, and submit a PR. That should help get this resolved sooner.

**Comment by joelhulen** [comment]
@onovotny Appreciate the PR :)

One thing I just noticed is, even though the build was successful in AppVeyor, there was an error thrown by cake:

========================================
__AddDotNetReferencesToNuspecFile
========================================
Executing task: __AddDotNetReferencesToNuspecFile
C:\projects\polly\tools\Cake\Cake.exe : error RG001: project.lock.json is missing
At line:1 char:1
+ C:\projects\polly\tools\Cake\Cake.exe "build.cake" -target="Default" -configurat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (error RG001: pr...json is missing:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Finished executing task: __AddDotNetReferencesToNuspecFile


========================================
There was a new task added by your reference generator, I believe, that the above error refers to: https://github.com/App-vNext/Polly/blob/master/build.cake#L185

Are you familiar with the error above about "project.lock.json" missing?

**Comment by onovotny** [comment]
yeah... you need to call nuget restore in the appveyor script first as that lock file should never be checked in.

Here's an example I use in Humanizer: 
https://github.com/Humanizr/Humanizer/blob/dev/appveyor.yml#L7-L12

Also, I think that cake task can be removed as the build will handle it the way it's setup as part of building the pcl csproj.

**Comment by onovotny** [comment]
Ugh, this whole thing could have been a giant brain-fart/missing stuff in nuget.org. It appears to have been fine originally :(

Very sorry for the false alarm and no hard feelings if you want to revert my commits.
