### ISSUE TITLE
Switch between servers policy

### ISSUE THREAD

**Issue by maklipsa** [App-vNext/Polly#591]
**Summary: What are you wanting to achieve?**
The setup:
There are two instances of the same service. The policy calls for the request looks like this:

```            
var policy = 
	multipleServerRetryPolicy.WrapAsync(
		retryPolicy.WrapAsync(
			circuitBreakerPolicy.WrapAsync(
				timeoutPolicy
			)
		)
	)
;
```

**The problem**
<br/>
I would like to:
- do server switch in the `multipleServerRetryPolicy`.
- for the circuit breaker to be server aware. Meaning that it can be open for `ServerA`, but closed for `ServerB`

But:

- `onRetry` in `RetryPolicy` doesn't have access to `Context`
- **even** if it had, `Context.OperationKey` doesn't have a public set.

Is there a way to express this behavior using policies?

**Comment by maklipsa** [comment]
I've also tried switching the server url in the `multipleServerRetryPolicy`:
```
var multipleServerRetryPolicy = Policy
	.Handle<Exception>()
	.WaitAndRetryForeverAsync(
		sleepDurationProvider: attempt => TimeSpan.FromMilliseconds(30)
		, onRetry: (exception, attempt) =>
		{
			_serverIndex++;
			WriteLineInColor($"[MultipleServerRetry]Switching server to:{_servers[_serverIndex]}", ConsoleColor.Yellow);
			_retries++;
		}
	);
```

and executing the policy like this:
```
var serverAddress = _servers[_serverIndex % _servers.Length];
var url = serverAddress.AbsoluteUri + "api/values/" + _r.Next(0, 5);
var text = await policy.ExecuteAsync(async context =>
{
	url = serverAddress.AbsoluteUri + "api/values/" + _r.Next(0, 5);
	string msg = await client.GetStringAsync(url);
	_eventualSuccesses++;
	return msg;
}, new Context(new Uri(url).AbsolutePath));
```

but even though the url switches, the circuit breaker seas the initial `OperationKey` and it still remains open.

**Comment by reisenberger** [comment]
@maklipsa . Here is a _sketch of a concept_ to get you a quick answer (rather than leave you waiting longer for an answer).  The behaviour can be expressed with existing Polly features using a pattern such as below.  _Note:_ this is a sketch to give you all the elements of a solution; you will likely want to factor parts of this out into helper classes or methods, add defences for edge-cases etc, proper cancellation etc.

Given:

    string[] servers = new []
    {
        "http://server1.whatever.com",
        "http://server2.whatever.com",
        "http://server3.whatever.com",
    };

    const string ServerIndexKey = "ServerIndexKey";

    PolicyRegistry registry = new PolicyRegistry();

Declare policies such as:

    Func<IAsyncPolicy<string>> circuitBreakerFactory = () => Policy<string>.Handle<Exception>().CircuitBreakerAsync(3, TimeSpan.FromSeconds(10)); // Or more refined fault-handling, such as only certain exceptions; also http result-codes

    var multipleServerRetryPolicy = Policy
        .Handle<Exception>() // Or more refined fault-filtering ...
        .WaitAndRetryForeverAsync(
            sleepDurationProvider: (attempt, context) => TimeSpan.FromMilliseconds(30)
            , onRetry: (exception, timespan, context) => // Of course, can factor this out to a nicely-named method SelectAnotherServer() or similar.
            {
                int currentServer = context.GetValueOrDefault<int>(ServerIndexKey);
                currentServer = (currentServer + 1) % servers.Length;
                context[ServerIndexKey] = currentServer;
            }
        );

And execute with:

    var text = await multipleServerRetryPolicy.ExecuteAsync(async (context, token) =>
            {
                int server = context.GetValueOrDefault<int>(ServerIndexKey);
                string url = $"{servers[server]}/localpath/etc"; // Or of course, the localpath part passed in from outside ...
                var breaker = registry.GetOrAdd($"breaker{server}", circuitBreakerFactory);
                return await breaker.ExecuteAsync(() => client.GetStringAsync(url));
            }, new Context(), default(CancellationToken));

Where you have extension methods:

    public static IAsyncPolicy<TResult> GetOrAdd<TResult>(this PolicyRegistry registry, string key, Func<IAsyncPolicy<TResult>> policyFactory)
    {
        if (registry.TryGet(key, out IAsyncPolicy<TResult> policy))
        {
            return policy;
        }

        var newPolicy = policyFactory();
        registry[key] = newPolicy;
        return newPolicy;
    }

    public static T GetValueOrDefault<T>(this Context context, string key)
    {
        if (context.TryGetValue(key, out object objValue))
        {
            return objValue is T value ? value : default;
        }
        return default;
    }

---

Explanations (in relation to the solution above, and some points raised in your question):

+ Circuit-breaker state is not scoped to `OperationKey`.
+ Circuit-breaker state is intentionally scoped to circuit-breaker policy instance.  So, for separate circuit-breaking per downstream server, create, maintain and reuse an instance of a circuit-breaker per downstream server.  The above code uses [`PolicyRegistry`](https://github.com/App-vNext/Polly/wiki/PolicyRegistry) to do this. Of course, you could use other techniques like just manage an array `IAsyncPolicy<string>[]` 
+ The retry policies do have `onRetry:` overloads taking `Context` as an input parameter - shown above.

---

Let us know if that is enough info; or any questions.

**Comment by maklipsa** [comment]
Thanks for the answer.
The sketch is more than enough.
There is a problem with what solution.
In the real case, I'm wrapping the multiple retry policy in a cache policy (when preparing the issue I've stripped it out for clarity).
If then I pass a new context into the policy execution I won't have any caching.

The real policy tree looks like this:

```
            var policy = fallbackForAnyException.WrapAsync(
                cachePolicy.WrapAsync(
                    wholeRequestTimeoutPolicy.WrapAsync(
                        multipleServerRetryPolicy.WrapAsync(
                            retryPolicy.WrapAsync(
                                circuitBreakerPolicy.WrapAsync(
                                    timeoutPolicy
                                )
                            )
                        )
                    )
                )
            );
```

**Comment by reisenberger** [comment]
@maklipsa . It should still be usable with `CachePolicy`. The code sample I presented used `new Context()` at the `multipleServerRetryPolicy.ExecuteAsync(...)` call, only because I understood that was the outermost policy call.  If the execution already has a `context` instance created further out in the call chain, simply pass that existing `context` instance in to the call through `multipleServerRetryPolicy` instead of `new Context()`:

    // instance 'context' created further out in the call chain
    context[ServerIndexKey] = /* add information about the previously-used server to the context before making the execution, if you have it. */ ;
    await multipleServerRetryPolicy.ExecuteAsync(async (context, token) =>
        {
            /* as before */
        }, context, default(CancellationToken));

**Comment by reisenberger** [comment]
@maklipsa What will not be possible is to condense your goal into a single `PolicyWrap` instance, in the style illustrated in your [preceding post](https://github.com/App-vNext/Polly/issues/591#issuecomment-465283426).  A single `PolicyWrap` instance defines a fixed sequence of policies.  However, you need to vary the circuit-breaker policy instance - to select a single long-lived policy instance per downstream server - to maintain separate circuit-state per downstream server, as described in my previous post.  This cannot be achieved with `PolicyWrap`: you will need to break out of a single PolicyWrap to do so (or write a custom policy to keep it in a single `PolicyWrap`).  

Options to make that tidier:

+ still use `PolicyWrap` for everything outside `multipleServerRetryPolicy`; _or_
+ define an end-to-end `PolicyWrap` (all policies) per downstream server, with each `PolicyWrap` including the correct circuit-breaker; _or_
+ the notion of 'selecting the correct circuit-breaker policy' in [my previous comment](https://github.com/App-vNext/Polly/issues/591#issuecomment-464478516) could be encapsulated into a custom policy.  From Polly v7, it is possible for you to author policy implementations outside Polly which slot straight into Polly's `PolicyWrap`.


You could take this part of the implementation from my previous post:

    int server = context.GetValueOrDefault<int>(ServerIndexKey);
    var breaker = registry.GetOrAdd($"breaker{server}", circuitBreakerFactory);
    return await breaker.ExecuteAsync(() => client.GetStringAsync(url));

and make it the implementation for a custom `IAsyncPolicy<TResult>` following the process [in this blog post](http://www.thepollyproject.org/2019/02/13/authoring-a-proactive-polly-policy-custom-policies-part-ii/).

**Comment by reisenberger** [comment]
@maklipsa It seemed fun to try the custom policy-selector policy.  Here is a 15-line custom policy you could use with Polly v7.0 to select a policy according to information in `Context`.  You could keep your whole operation (with circuit-breaker-switcher) within one `PolicyWrap`, by making use of a custom policy-switcher like this:

    public class AsyncPolicySelector<TResult> : AsyncPolicy<TResult>
    {
        private readonly Func<Context, IAsyncPolicy<TResult>> policySelector;

        public static AsyncPolicySelector<TResult> Create(Func<Context, IAsyncPolicy<TResult>> policySelector)
        {
            return new AsyncPolicySelector<TResult>(policySelector);
        }

        private AsyncPolicySelector(Func<Context, IAsyncPolicy<TResult>> policySelector)
        {
            this.policySelector = policySelector;
        }

        protected override Task<TResult> ImplementationAsync(Func<Context, CancellationToken, Task<TResult>> action, Context context, CancellationToken cancellationToken, bool continueOnCapturedContext)
        {
            return policySelector(context).ExecuteAsync(action, context, cancellationToken, continueOnCapturedContext);
        }
    }

The `AsyncPolicySelector<TResult>` below takes a `Func<Context, IAsyncPolicy<TResult>>` to select the policy.  In your case, you would define a `Func<Context, IAsyncPolicy<TResult>>` which encapsulates retrieving (or manufacturing the first instance of) the circuit-breaker for the downstream server specified by `Context`.

**Comment by reisenberger** [comment]
Hi @maklipsa . Can we help any further with this, or do you have what you need?

**Comment by maklipsa** [comment]
I didn't have time to code it fully, but it should work. 
Thanks for all the help!
Have a great day :)

**Comment by reisenberger** [comment]
For anyone landing at this thread and looking to achieve the equivalent effect with HttpClientFactory - that is, use of a circuit-breaker instance per downstream system in policies configured on HttpClientFactory - see [this example](https://github.com/App-vNext/Polly/issues/624#issuecomment-478218169).
