### ISSUE TITLE
MemoryCache

### ISSUE THREAD

**Issue by Gladskih** [App-vNext/Polly#595]
**[Cache](https://github.com/App-vNext/Polly#cache) example incorrect**: 

On line `var memoryCacheProvider = new MemoryCacheProvider(MemoryCache.Default);`

- using `Microsoft.Extensions.Caching.Memory` I have compile-time error "'MemoryCache' does not contain a definition for 'Default'"
- using  `System.Runtime.Caching` (which MemoryCache contains Default) I have "cannot convert from 'System.Runtime.Caching.MemoryCache' to 'Microsoft.Extensions.Caching.Memory.IMemoryCache'"

**Expected behavior**: 
Code example is runing

**Actual behavior**:
Code example contains compile-time error

**Steps to reproduce the problem**: 
1. Copy code example to project
2. Add some suggested  by IDE reference (Microsoft.Extensions.Caching.Memory or System.Runtime.Caching.MemoryCache)
3. Try to build project

P.S. Project is under .Net Framework 4.6.2,
Insalled nuget packages are Polly 7.0.2, Polly.Caching.Memory 3.0.0 and Polly.Caching.MemoryCach 1.1.0 (I don't really know do I need last one or not).

**Comment by reisenberger** [comment]
Thanks @Gladskih.  Please follow the instructions at: https://github.com/App-vNext/Polly.Caching.MemoryCache#how-to-use-the-pollycachingmemory-plugin

We will update the main Polly readme to reflect those changes (or, please feel free to make a PR to do so!)
