### ISSUE TITLE
Question: HandleResult<IDisposable> with WaitAndRetry

### ISSUE THREAD

**Issue by stephenpatten** [App-vNext/Polly#609]
Hello, and thank you for Polly!

After reading through samples and the closed tickets I'm still unsure of how to accomplish what I'm looking for.

**Summary: What are you wanting to achieve?**

The ability to execute code to determine if I can get a distributed lock. The execution of the locking method returns IDisposable or null; If the method returns the IDisposable I'd like to wrap it in a using statement or the try finally semantics. On the other-hand if the result is null, then I want to wait and retry with the back-off algorithm until the max number of retries in which case I fail the request and batch it. 

**What code or approach do you have so far?**  

Lets say for instance this code was executing in the context of ASP.NET WCF with a method signature of something along the lines of

           public DoWorkResponse DoWork(DoWorkRequest request)
           {
           }

Here's the signature of the lock call:

           IDisposable handle = this.awdLock.GetLock(caseId);

this is the policy definition:

           RetryPolicy<IDisposable> lockPolicy = Policy
                .HandleResult<IDisposable>(d => d == null)
                .WaitAndRetry(6, attempt => TimeSpan.FromSeconds(0.1 * Math.Pow(2, attempt)));

Finally, here's the code that won't compile:

            using (IDisposable handle = lockPolicy.Execute(act => this.awdLock.GetLock(caseId)))
            {
                // handle is guaranteed to not be null, so do something
            }

I would also like to log from the policy when the fail condition is met, but that's extra credit :)

Thank you,
Stephen

**Comment by reisenberger** [comment]
Hi @stephenpatten . Re:

>code that won't compile

For the execute statement, use:

    using (IDisposable handle = lockPolicy.Execute(() => this.awdLock.GetLock(caseId)))

See the examples illustrating this syntax in [Readme: Step 3 Execute the policy](https://github.com/App-vNext/Polly/blob/master/README.md#step-3--execute-the-policy)

(I am not sure what `act` was in `act =>` the posted code - if I misunderstood an intention, let me know,)

---

>handle is guaranteed to not be null, so do something

`handle` could be `null`.  If all 7 tries (first try plus 6 retries) fail, the policy will return the unhandled result `null`.  More info on this [in the retry wiki](https://github.com/App-vNext/Polly/wiki/Retry#how-polly-retry-works) . 

If you want to ensure `handle` will never be `null`, you can use `WaitAndRetryForever(...)`. With the caveat obviously that your application can stall at that `WaitAndRetryForever(...)` if the success condition is never met.

---

>I would also like to log from the policy when the fail condition is met

You can do this using the `onRetry:` delegate hook of the retry policy. See the examples in [Readme: Step 3 Execute the policy](https://github.com/App-vNext/Polly/blob/master/README.md#step-3--execute-the-policy). Here a working .NET Fiddle example: https://dotnetfiddle.net/Sipste . If you need to log when all 7 tries fail, make that part of your manual check for `handle == null`.

Hope that helps.

**Comment by stephenpatten** [comment]
Hi @reisenberger,

Thank you for taking the time to answer my noob questions!

I was working through the issues I posted last night, probably about the same time as you answered the original post, and figured out most of it after reading more of the closed issues. 

Re: The act variable was my abbreviation for your action param (Func), which should have been represented by () Lambda syntax. -fixed

Re: You are correct, once I was able to start testing correctly, the handle could actually be an instance or null. -fixed

**Comment by stephenpatten** [comment]
@reisenberger  Man, you are VERY proactive! How may I help you with Polly going forward?

**Comment by reisenberger** [comment]
No worries @stephenpatten , you're very welcome!  If there is anything else we can help with, fire away (or open a new issue). We try to be very responsive and answer support queries within 24 hrs (but can't guarantee!)

Thanks for the offer of help. We tag 'up-for-grabs' items thus: https://github.com/App-vNext/Polly/issues?q=is%3Aissue+is%3Aopen+label%3Aup-for-grabs . Feel free to pick up anything if you want to (but there's no obligation).
