### ISSUE TITLE
CircuitBreaker does not throw BrokenCircuitException as expected when HandleInner() is used [BrokenCircuitException  is thrown, but masked by HandleInner]

### ISSUE THREAD

**Issue by CNBoland** [App-vNext/Polly#618]
**Summary**: 
When using Handle() to handle exceptions in a CircuitBreaker policy, a BrokenCircuitException is thrown as expected, but when using HandleInner(), the exception is not thrown.

**Expected behavior**: 
A BrokenCircuitException is thrown when the circuit is open.

**Actual behaviour**:
The handled exception is thrown when circuit is open rather than BrokenCircuitException,

**Steps / Code to reproduce the problem**: 
1. Open the repro fiddle: https://dotnetfiddle.net/guRlc5
2. Run fiddle as-is. A 'Success' message appears in the console window. This test uses the Handle() method.
3. Comment/uncomment lines 18-19, 28-29, 55-58 accordingly for Test 2.
4. Run the fiddle again and a 'Fail' message appears in the console window.

Note: I dropped and added Polly 7.1.0 package in the fiddle, so it should be using latest version.

**Comment by reisenberger** [comment]
Hi @CNBoland .  It works if you reconfigure the RetryPolicy as shown in my example here: https://dotnetfiddle.net/n4ENwo - variant Test 3

What is happening in Test 2, is that `.HandleInner(...)` aggressively extracts the inner exception matched [as described here](https://github.com/App-vNext/Polly/wiki/Handling-InnerExceptions-and-AggregateExceptions#communicating-matched-inner-exceptions-to-calling-code).  Now, the [`BrokenCircuitException` which _is_ being thrown by the circuit-breaker contains the exception which caused the circuit last to break as the `InnerException`](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker#open).  In Test 2, the `BrokenCircuitException` _is_ being thrown, it's just that the retry policy is aggressively extracting the inner `InvalidOperationException` of it.

If you resequence the handle clauses of the `retryPolicy` as shown - per my example, Test 3 - 

    .Handle<BrokenCircuitException>()           // <= Use this line for Test 3
    .OrInner<InvalidOperationException>()	    // <= Use this line for Test 3

then the retry policy matches the `BrokenCircuitException` _first_ (before the `.OrInner<>()` is evaluated), and you get the result you expect.

Let me know if this makes sense.

**Comment by CNBoland** [comment]
@reisenberger , yes, that does make sense, thank you for informative response. It seems a pattern to me that when RetryPolicy and CircuitBreaker are interacting this way that `BrokenCircuitException` should be handled first to account for the case described here. Thanks again for your response.
