### ISSUE TITLE
Document that .HandleInner() also handles top-level exception

### ISSUE THREAD

**Issue by sandersaares** [App-vNext/Polly#621]
I was wondering what the right way was to mix .Handle() and .HandleInner() but upon reading the code I realized that .HandleInner() already includes .Handle() functionality.

This is not obvious from the documentation as .HandleInner() is documented as only checking inner/aggregated exceptions. I request this be documented.

**Comment by reisenberger** [comment]
@sandersaares . Great point:

+ [Wiki](https://github.com/App-vNext/Polly/wiki/Handling-InnerExceptions-and-AggregateExceptions) already updated.
+ #622 will fix readme.
