### ISSUE TITLE
PolicyRegistry IReadOnlyPolicyRegistry interface only available in 5.6 but doc says >5.2

### ISSUE THREAD

**Issue by JoshStorkey** [App-vNext/Polly#625]
The wiki page for [PolicyRegistry](https://github.com/App-vNext/Polly/wiki/PolicyRegistry) says that it is available in 5.2 onwards and mentions IReadOnlyPolicyRegistry could be used. 

We are currently using 5.2 but IReadOnlyPolicyRegistry is not available and looks to have been made available in 5.6.

**Comment by reisenberger** [comment]
Thanks. Updated the [wiki page](https://github.com/App-vNext/Polly/wiki/PolicyRegistry). Looks from the [changelog](https://github.com/App-vNext/Polly/blob/master/CHANGELOG.md#530) and [commit](https://github.com/App-vNext/Polly/commit/f4ee7442ac9cabfb54eb8b2d327e7025a643dacf) for the [release](https://github.com/App-vNext/Polly/releases/tag/v5.3.0) as if it was added in 5.3.0

Thanks for raising.
