### ISSUE TITLE
Tweak class structure (eg distinguish CircuitBreaker and Retry types, clarify relationship between Contextual and non-Contextual)

### ISSUE THREAD

**Issue by reisenberger** [App-vNext/Polly#63]
Polly currently has a class `Policy` which does not distinguish whether the configured implementation is a retry policy or circuit-breaker policy.  

Having separate `CircuitBreakerPolicy` and `RetryPolicy` types deriving from an abstract base class `Policy` could allow library users to specify (eg in parameter types) that they expect an instance of `RetryPolicy` specifically and not a `CircuitBreakerPolicy`.  

(Use Case: In our microservices implementation, for certain calls we allow callers to pass in the retry policy or circuit-breaker policy (but specifically one or the other, in certain places) they want to use. Because the Polly library at present does not distinguish the types, we cannot use `Policy` as a parameter type and have ended up having to create our own wrapper classes to distinguish.).

Distinguishing `CircuitBreakerPolicy` and `RetryPolicy` types would also allow the introduction of functionality specific to only one type, eg #62

**Comment by reisenberger** [comment]
@joelhulen I've noticed there's a third kind, `ContextualPolicy`, that might need to be considered in this.  Need some time to read whether `ContextualPolicy` is a conceptually distinct kind.  Maybe it can only be applied to retry policies (these are the only kinds of usage in the codebase at present...), or maybe it's _intended_ to be more general ... (unless @michael-wolfenden can save time with comment/ explanation on this).

**Comment by reisenberger** [comment]
It looks to me as if `ContextualPolicy` is only used for retry policies at present, but could conceivably be used for circuit-breaker policies too.  This could lead to an overall class structure (if desired) like:

`RetryPolicy` : (abstract) `Policy`, `IRetryPolicy`
`CircuitBreakerPolicy` : (abstract) `Policy`, `ICircuitBreakerPolicy`
`RetryContextualPolicy` : (abstract) `ContextualPolicy`, `IRetryPolicy`
`CircuitBreakerContextualPolicy` : (abstract) `ContextualPolicy`, `ICircuitBreakerPolicy` // although this isn't used yet, so it might be better not to add it.

(where `IRetryPolicy` and `ICircuitBreakerPolicy` are mostly marker interfaces)

(I notice also that there are also internal classes already named `CircuitBreakerPolicy` and `RetryPolicy`, which might want renaming, to avoid confusion the codebase with the new intended public versions `CircuitBreakerPolicy` and `RetryPolicy`.)

I could code this all up and PR to demonstrate, if more useful.

**Comment by joelhulen** [comment]
@reisenberger This is going to take a little bit of time to review, but I am following your logic and like what I see so far. As an aside, the team and I met this afternoon to go over Polly in order to bring everyone up to speed. I was wondering, since you are very involved with this project and have quite a bit of experience, would you be interested in joining the core team? We could use someone like you who already is ahead on the ins and outs of the project. That way we can be a step ahead with moving forward.

**Comment by reisenberger** [comment]
@joelhulen Re:

>would you be interested in joining the core team? 

Thanks for the invite!  Could you private-mail me at software[at]reisenberger.net, for me briefly to get an idea what you have in mind / what would be involved? - and I can clarify for you what level input / commitment I might be able to bring.  Thanks! – Dylan
