### ISSUE TITLE
Support for retrying based on bool condition (-> result returned by a call)

### ISSUE THREAD

**Issue by pauldotknopf** [App-vNext/Polly#630]
I am dealing with distributed systems that are eventually-consistent.

I have to wait/block until an item exists on another external service. The service doesn't fail/throw, it just returns nothing/null.

I'd like to use Polly to continuously check the external service for the existence of the item, and continue when it is found.

Is something like this currently supported? I'd hate to throw exceptions for business logic.

**Comment by reisenberger** [comment]
@pauldotknopf . See the ReadMe: [Step 1b: (optionally) Specify return results you want to handle](https://github.com/App-vNext/Polly#step-1b-optionally-specify-return-results-you-want-to-handle).

**Comment by reisenberger** [comment]
Hi @pauldotknopf . I gave a short answer to your query earlier in the week to keep things moving. Were you able to figure out what you needed? Do you need any more assistance?

**Comment by reisenberger** [comment]
Closing as the documentation seems to cover this.  Please do comment however, or open another issue, if there's anything else we can help with. Thanks.

**Comment by pauldotknopf** [comment]
Ya, sorry for the ghosting/no response. All good!
