### ISSUE TITLE
Question: How to enable or disable a policy? 

### ISSUE THREAD

**Issue by stephenpatten** [App-vNext/Polly#634]
Hello,

**Summary: What are you wanting to achieve?**

In the definition of a policy, I'd like to be able to disable or enable the policy at run-time, versus doing it in the call site, since I may have multiple call sites.

**What code or approach do you have so far?**  

       `private RetryPolicy<IDisposable> GetRetryPolicy()
        {
            if (!this.config.DistributedLockEnabled)
            {
                NoOpPolicy<IDisposable> policy = Policy.NoOp<IDisposable>();
                return policy;
            }

            RetryPolicy<IDisposable> lockPolicy = Policy
                .Handle<TimeoutException>()
                .OrResult<IDisposable>(d => d == null)
                .WaitAndRetry(
                    this.config.WorkflowLockHandleRequestRetryAttempts,
                    attempt => TimeSpan.FromSeconds(this.config.WorkflowLockHandleRequestRetryMultiplier * Math.Pow(this.config.WorkflowLockHandleRequestRetryBase, attempt)),
                    (delegateResult, calculatedWaitDuration, attempt, context) =>
                        {
                            if (delegateResult.Exception != null)
                            {
                                this.logger.Information(
                                    "Exception {0} attempt {1} delaying for {2}ms",
                                    delegateResult.Exception.Message,
                                    attempt,
                                    calculatedWaitDuration.TotalMilliseconds);
                            }
                        });
            return lockPolicy;
        }`

But alas, this does not compile :)

Thank you,
Stephen

**Comment by stephenpatten** [comment]
After reading through the closed issues I was able to understand the impetus of the NoOp Policy and give that, here is the new signature:

    `   private Policy<IDisposable> GetRetryPolicy()
        {
            if (!this.config.DistributedLockEnabled)
            {
                Policy<IDisposable> policy = Policy.NoOp<IDisposable>();
                return policy;
            }

            Policy<IDisposable> lockPolicy = Policy
                .Handle<TimeoutException>()
                .OrResult<IDisposable>(d => d == null)
                .WaitAndRetry(
                    this.config.WorkflowLockHandleRequestRetryAttempts,
                    attempt => TimeSpan.FromSeconds(this.config.WorkflowLockHandleRequestRetryMultiplier * Math.Pow(this.config.WorkflowLockHandleRequestRetryBase, attempt)),
                    (delegateResult, calculatedWaitDuration, attempt, context) =>
                        {
                            if (delegateResult.Exception != null)
                            {
                                this.logger.Information(
                                    "Exception {0} attempt {1} delaying for {2}ms",
                                    delegateResult.Exception.Message,
                                    attempt,
                                    calculatedWaitDuration.TotalMilliseconds);
                            }
                        });
            return lockPolicy;
        }`

Which returns the Abstract base class. This makes the compiler happy, but I haven't run my tests against this change.. yet

**Comment by stephenpatten** [comment]
Works perfectly!

**Comment by reisenberger** [comment]
@stephenpatten Apologies for the lack of reply while I was on Easter vacation. Glad you got a solution! You can also declare/return the type of the policy instance as an [execution interface they fulfil](https://github.com/App-vNext/Polly/wiki/Polly-and-interfaces) (in lieu of the abstract base class), if desired, eg: 

    private ISyncPolicy<IDisposable> GetRetryPolicy()  { ... }

**Comment by stephenpatten** [comment]
Oh, I'd rather do that, thank you for the update, and Happy Easter!
