### ISSUE TITLE
Why would Optimistic timeoutPolicy automatically throw TimeoutRejectedException when it contains a retryPolicy in it?

### ISSUE THREAD

**Issue by janeliu567** [App-vNext/Polly#636]
I'm learning Polly library and I already knew that there are 2 TimeoutStrategy: TimeoutStrategy.Optimistic & TimeoutStrategy.Pessimistic.

I'm talking about TimeoutStrategy.Optimistic here. In this case, it is expected that it is the executed delegate's responsibility to respect Cancellation Token and call cancellationToken.ThrowIfCancellationRequest() to enforce the timeoutPolicy.

However, in the following code, I do not add any cancellationToken.ThrowIfCancellationRequest() manually in the executed delegate Task LongOp(CancellationToken ct), while there is still a TimeoutRejectedException caught. How did it happen?

    static async Task Main(string[] args)
    {
        AsyncTimeoutPolicy<int> timeoutPolicy = Policy.TimeoutAsync<int>(TimeSpan.FromSeconds(2), TimeoutStrategy.Optimistic);
        AsyncRetryPolicy<int> waitAndRetryPolicy = Policy<int>.HandleResult(r => r == 11) // make it always retry
                                                                .WaitAndRetryForeverAsync(retryAttempt => TimeSpan.FromMilliseconds(10));

        var policyWrap = Policy.WrapAsync(timeoutPolicy, waitAndRetryPolicy);

        int result;
        try
        {
            result = await policyWrap.ExecuteAsync(async ct => await LongOp(ct), CancellationToken.None);
        }
        catch(TimeoutRejectedException)
        {
            Console.WriteLine("timeout");
        }

        Console.WriteLine("hello world");
        Console.ReadLine();
    }

    static async Task<int> LongOp(CancellationToken ct)
    {

        Console.WriteLine("hi");

        return 11;
    }

**Comment by reisenberger** [comment]
Hi @janeliu567 . Even though your delegate doesn't respond to the `CancellationToken`, the retry policy does.  It may [honour cancellation](https://github.com/App-vNext/Polly#cancellation-support):

+ before making the next retry
+ during any wait before making a next retry.

The notes on [combining timeout with retries](https://github.com/App-vNext/Polly/wiki/Timeout#combining-timeout-with-retries) also provide more detail on how timeout policy and retry policy interact when combined.  

+ With a retry policy inside timeout policy (as you have with `Policy.WrapAsync(timeoutPolicy, waitAndRetryPolicy)`), the timeout acts as an overall timeout across all tries - thus may cancel further tries (when execution passes from your delegate back to the policy), as described above.
+ With a timeout policy inside the retry policy, the timeout acts as a timeout-per-try.  This timeout-per-try will not cancel further retries, as it controls only the individual try.

Let us know if that helps or if you have further questions.

**Comment by janeliu567** [comment]
Thank you @reisenberger . Your answer resolved the confusion. I have another question related to timeout policy, though. It's still about TimeoutStrategy.Optimistic but with its interaction with HttpClient

the code looks as below:

        static async Task Main(string[] args)
        {
            AsyncTimeoutPolicy<int> timeoutPolicy = Policy.TimeoutAsync<int>(TimeSpan.FromSeconds(2), TimeoutStrategy.Optimistic);

            int result;
            try
            {
                result = await timeoutPolicy.ExecuteAsync(async ct => await GoToThirdParty(ct), CancellationToken.None);
            }
            catch(TimeoutRejectedException)
            {
                Console.WriteLine("timeout");
            }

            Console.WriteLine("hello world");
            Console.ReadLine();
        }

        static async Task<int> GoToThirdParty(CancellationToken ct)
        {
            while (true)
            {
                using (HttpClient httpClient = new HttpClient())
                {
                    Console.WriteLine("hi");
                    await httpClient.GetAsync("https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.getasync?view=netframework-4.8#System_Net_Http_HttpClient_GetAsync_System_String_", ct);

                }
            }
        }

In the simulated situation, the httpclient will continuously sending a Get request to third party url until cancellationToken is flagged. However,  httpClient.GetAsync(url, ct) will actually throw a TaskCanceledException whenever it finds ct is no longer valid. But in my code, at the top level, only TimeoutRejectedException is caught. Is it because timeoutPolicy catches the TaskCanceledException by default and throws TimeoutRejectedException instead?

**Comment by reisenberger** [comment]
Hi @janeliu567 Re:

>Is it because timeoutPolicy catches the TaskCanceledException by default and throws TimeoutRejectedException instead?

Yes, that is exactly it. We intentionally designed TimeoutPolicy to throw its own exception (`Polly.TimeoutRejectedException`) so that it could be disambiguated/distinguished from any other kind of cancellation.  HttpClient by default only throws `TaskCanceledException` as you say, but with that, it is not possible/easy to tell if the cause of that cancellation is a timeout or some other cause for cancellation. So, we chose that TimeoutPolicy should throw a more specific exception.

If cancellation occurs and the cause of the cancellation is Polly's TimeoutPolicy, then `TimeoutRejectedException` will always be thrown.  

Any original `TaskCanceledException` thrown by the executed code responding to the `CancellationToken`, is [passed as the `InnerException` of `TimeoutRejectedException`](https://github.com/App-vNext/Polly/blob/4db50346299f62c2373ceba99d2522a8171c9e27/src/Polly/Timeout/AsyncTimeoutEngine.cs#L48-L54). So if you need it, you still have access to it.
