### ISSUE TITLE
How to wire up Polly by Autofac

### ISSUE THREAD

**Issue by Arash-Sabet** [App-vNext/Polly#637]
**Summary: What are you wanting to achieve?**

<br/>
I'd like to wire up Polly by Autofac. Are there any samples or guidelines to tell us how?
<br/>

**What code or approach do you have so far?**  

<br/>
None.
<br/>

**Comment by reisenberger** [comment]
@Arash-Sabet There are no Autofac samples. However, using any DI with Polly is fairly simple: a typical strategy is to registry an IPolicyRegistry<string> with the DI container and inject that into components which need it. Within the component, retrieve the policy you require from registry.  

If on the other hand your question concerns Polly with HttpClientFactory, then this is less straightforward:  `HttpClientFactory` is fairly tightly coupled to `Microsoft.Extensions.DependencyInjection`.  See these two threads for deeper discussion and suggestions of possible workrounds: https://github.com/aspnet/HttpClientFactory/issues/148 ; https://github.com/aspnet/Extensions/issues/1345

Anybody from the community who has Autofac samples, please feel free to chip in!

**Comment by reisenberger** [comment]
Closing due to lack of further comment
