### ISSUE TITLE
How to break out of a .WaitAndRetry when an Application starts up and I'm trying to seed a Database?

### ISSUE THREAD

**Issue by PureKrome** [App-vNext/Polly#638]
**Summary: What are you wanting to achieve?**

Hi :wave: I'm trying to setup/initialise a database with some fixed db data, when my net core application starts up. I'm doing this in the `startup.cs` `Configure` method. Now the kicker is that the database might not be ready because both the DB and the Host start at the same time (think -> `docker-compose`, etc) so I'm using Polly with `.WaitAndRetry` to handle this. Works great.

But .. if i wish to kill the Host (e.g. `ctrl-c`) the Host captures the fact that I'm trying to shutdown, but Polly keeps `.WaitAndRetry`ing until it hits the `retryCount`.

So I thought I need to somehow pass some `CancellationToken` or something to the Polly method I'm using. But I'm not sure how and what. I'm guessing it would come from the `Configure` method but again, not sure how or what.

Can anyone help? Has anyone done this before?

**Comment by reisenberger** [comment]
Hi @PureKrome . Both synchronous and asynchronous Polly policies have execute overloads taking `CancellationToken`.  

+ `WaitAndRetry/Async(...)` policy will respond to `CancellationToken` during any wait phase between retries: the wait will be cancelled immediately, and no further tries will be made.
+ Your own code which you execute through the policy, will (to state the obvious) honour the `CancellationToken` if it honours the `CancellationToken`.  

Re capturing ctrl-c, the [`Console.CancelKeyPress` event](https://docs.microsoft.com/en-us/dotnet/api/system.console.cancelkeypress?view=netcore-2.2) is listed as supported in .Net Core: as a starting assumption, could you hook something to that event to signal the relevant `CancellationTokenSource`?

There's some discussion [here](https://github.com/dotnet/coreclr/issues/8565) as well about capturing console app termination beyond ctrl-c; at a brief read, I'm not clear whether all cases are reliably covered yet for .NET core console apps. Would be interested anything you find out.

**Comment by PureKrome** [comment]
Hi @reisenberger and thanks kindly for the reply.

> Re capturing ctrl-c, the Console.CancelKeyPress event is listed as supported in .Net Core: as a starting assumption, could you hook something to that event to signal the relevant CancellationTokenSource?

That's exactly what I'm hoping someone might be able to answer for me :blush:

The closest thing I _thought_ might help is that there is an `[IApplicationLifetime](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.iapplicationlifetime?view=aspnetcore-2.2)` event which _I thought_ is fired when the application is trying to shutdown (in this case, via the `CancelKeyPress` event.

This `[IApplicationLifetime.ApplicationStopping](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.iapplicationlifetime.applicationstopping?view=aspnetcore-2.2#Microsoft_AspNetCore_Hosting_IApplicationLifetime_ApplicationStopping)` property I thought would be auto set .. meaning .. if the application was shutting down, then there would be a `CancellationToken`.

In the `Configure` method in `startup.cs` I've injected an `IApplicationLifetime` instance into that method but the cancellation tokens are always `false` (if my memory from a few days ago, serves me right).

So I'm just not doing something right -- and I'm hoping this has been a solved problem, already. 

Surely someone else has done this?

**Comment by reisenberger** [comment]
>Surely someone else has done this?

I'll leave the issue open here for a few days to see if anybody on this channel bites 🙂 .  If not, since the key issue is outside Polly, you might get more traction raising the issue on StackOverflow or the MS repo which owns the feature.

I've certainly seen `IApplicationLifetime` working successfully with the .NET Generic Host.  That wasn't as early in the startup lifecycle as `Configure(...)`, but there are plenty blogs out there suggesting that should work.

**Comment by PureKrome** [comment]
Out of interesting @reisenberger - would you know anyone we might be able to ping. Of course, @davidfowl would be a great resource but I'm not sure if he has the bandwidth to poke his head in here. Maybe there's someone else you might know/suggest and I can try and bring them into this covno?

**Comment by PureKrome** [comment]
@reisenberger Sorry to bother you again - I was trying to get some help via some people and on Twitter I got some little help. I just don't understand [what this tweet is suggesting](https://twitter.com/khellang/status/1125742229925126144):

> I think it would be better to use `WaitAndRetryAsync` and `ExecuteAsync`, then pass the `CancellationToken` to that instead.

Would you know why this would be better? I can't see how a `CTRL-C`, which is captured and starts the shutdown process ... can help, here? I thought I did this with how was checking for the `cancellationToken` once i've hit `ctrl-c`.

![](https://pbs.twimg.com/media/D59qkugU0AUE2Yq?format=jpg&name=medium)

![](https://pbs.twimg.com/media/D59qkucU8AMxVCx?format=jpg&name=medium)

![](https://pbs.twimg.com/media/D59qkufV4AA0VUR?format=png&name=small)

**Comment by reisenberger** [comment]
@PureKrome What does the call through the policy returned by `CheckRavenDbPolicy(...)` look like? - can you share that code? Is the code called through that policy synchronous or asynchronous?  

Re:

>I think it would be better to use WaitAndRetryAsync and ExecuteAsync, then pass the CancellationToken to that instead.

If the policy is intended to govern async calls, then you should (per above comment) use async Polly policies (`.WaitAndRetryAsync(...)` with `.ExecuteAsync(...)`). If the policy is intended to govern sync calls, then the sync policy you have (`.WaitAndRetry(...)`) is fine.

_Explanation:_ Using a sync Polly policy to call an async method is just like synchronously calling an async method without `await`-ing it.  The Polly policy only controls execution up to the first `await` within the async method - [more documentation on this here](https://github.com/App-vNext/Polly/wiki/Avoid-compiler-gotchas-mixing-sync-and-async-execution).

**Comment by PureKrome** [comment]
Any time I'm doing a call to RavenDb .. just substitute that out for _any_ dependency -> e.g. file/http endpoint/db/etc. So Polly is used for retrying :)

Here's the code I've got...

```
private static Policy CheckRavenDbPolicy(CancellationToken cancellationToken, ILogger logger)
{
    return Policy
        .Handle<Exception>(exception => !(exception is DatabaseDoesNotExistException) &&
                                        !(exception is AuthorizationException))
        .WaitAndRetry(15, _ => TimeSpan.FromSeconds(2), (exception, timeSpan, context) =>
        {
            logger.LogWarning($"Failed to connect to RavenDb. It may not be ready. Retrying ... time to wait: {timeSpan}. Exception: {exception.GetType()} {exception.Message.Substring(0, exception.Message.IndexOf('\n'))}");

            if (cancellationToken.IsCancellationRequested)
            {
                logger.LogWarning("  !!! Request for graceful shutdown - so we're going to stop trying ....");
                throw new OperationCanceledException();
            }
        });
}
```
and the calling code. Here i'm checking to see if I can get _any_ statistical data from the database. But this could be any call to and dependency => hit google via http or load a file or create a db on sql server, etc.

also, take note that the actual call is a SYNC call => `documentStore.Maintenance.Send(..); which was why I used `WaitAndRetry` ... unless I'm doing this all wrong (high possibility!)

```
DatabaseStatistics existingDatabaseStatistics = null;
try
{
    var checkRavenDbPolicy = policy ?? CheckRavenDbPolicy(cancellationToken, logger);
    checkRavenDbPolicy.Execute(() =>
    {
        existingDatabaseStatistics = documentStore.Maintenance.Send(new GetStatisticsOperation());
    });
}
catch (DatabaseDoesNotExistException)
{
    existingDatabaseStatistics = null; // No statistics because there's no Db tenant.
}
catch (AuthorizationException)
{
    // We failed to authenticate against the database. This _usually_ means that we
    // probably didn't have ADMIN rights against a db (so we can't do high level stuff)
    // but we could still do other stuff, like add fake data for seeding the DB.
    // SUMMARY: Db Tenant might exist, so lets assume that it does (safer bet).
    existingDatabaseStatistics = new DatabaseStatistics();
}
```

So I do have the cancellation token passed in from `statup.cs` `Configure` method, as posted above...

![](https://camo.githubusercontent.com/0ed2770e93ddd356e611cdec79ad2dfec81b66db/68747470733a2f2f7062732e7477696d672e636f6d2f6d656469612f443539716b756755304155453259713f666f726d61743d6a7067266e616d653d6d656469756d)

**Comment by reisenberger** [comment]
Thanks @PureKrome for sharing the code.  If they are sync calls, I agree that the async comment may not be relevant.

I am afraid I am unable to offer time to investigate problems which are outside Polly such as why the cancellation token `IApplicationLifetime.ApplicationStopping` may not be signalled when you terminate the application.  

---

Looking at the code: Polly does offer Execute overloads which take a `CancellationToken`, such as [this one](https://github.com/App-vNext/Polly/blob/4db50346299f62c2373ceba99d2522a8171c9e27/src/Polly/Policy.ExecuteOverloads.cs#L44-L53). These overloads allow the policy to respond to the token natively, so if you use such an overload, you could omit this from your `onRetry` delegate:

            if (cancellationToken.IsCancellationRequested)
            {
                logger.LogWarning("  !!! Request for graceful shutdown - so we're going to stop trying ....");
                throw new OperationCanceledException();
            }

and execute through the policy instead like this: 

```
DatabaseStatistics existingDatabaseStatistics = null;
try
{
    var checkRavenDbPolicy = policy ?? CheckRavenDbPolicy(cancellationToken, logger);
    checkRavenDbPolicy.Execute(token =>
    {
        existingDatabaseStatistics = documentStore.Maintenance.Send(new GetStatisticsOperation());
    }, cancellationToken);
}
catch (DatabaseDoesNotExistException)
{
    existingDatabaseStatistics = null; // No statistics because there's no Db tenant.
}
catch (AuthorizationException)
{
    // We failed to authenticate against the database. This _usually_ means that we
    // probably didn't have ADMIN rights against a db (so we can't do high level stuff)
    // but we could still do other stuff, like add fake data for seeding the DB.
    // SUMMARY: Db Tenant might exist, so lets assume that it does (safer bet).
    existingDatabaseStatistics = new DatabaseStatistics();
}
catch (OperationCanceledException oce) when (oce.CancellationToken == cancellationToken)
{
    logger.LogWarning("  !!! Request for graceful shutdown - so we stopped trying ....");
}
```

(The changes are to pass the `cancellationToken` local variable into the Execute call, and to move the logging which was originally in the `onRetry` - not necessarily better; just sharing options)

We do have [extensive tests on sync retry policies responding to cancellation](https://github.com/App-vNext/Polly/blob/4db50346299f62c2373ceba99d2522a8171c9e27/src/Polly.Specs/Retry/RetrySpecs.cs#L414-L771), so if you can get the token to signal, the policy will respond.

I hope that this is useful.

**Comment by PureKrome** [comment]
@reisenberger thanks heaps for jumping in on this thread. Totally agree that this is not a tech issue with Polly so yep, there's not much more can be discussed. I was hoping you or another polly-user might have used polly in a similar way and can provide guidance. 

The conversation and examples in this issue are great and very very helpful! big thanks!

From here, lets leave it open for a few more days/1 week to see if someone else might be able to add some final suggestions and after that, lets close it.

I'll still need to try and find someone closer to the ASP.NET team which might be able to see how to leverage both frameworks into helping solve this issue.

I still surprised that no one else has come across this .. or has said anything about it. Or more to the point, I just haven't found them yet  ... they do exist :)

**Comment by reisenberger** [comment]
@PureKrome I'm going to close this, as looks like you're sorted on the linked ASPNET Core issue.  I think they're suggesting you use the [generic host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.0) (cf my comment [few days ago](https://github.com/App-vNext/Polly/issues/638#issuecomment-489959859)). I've certainly fired one of these up myself and seen it working with the `IApplicationLifetime.ApplicationStopping` token.

**Comment by PureKrome** [comment]
All good @reisenberger - i've still not gotten v3 working locally so i'm going to try this weekend and get some love into it. But all good about closing the issue. Any further news, i'll post it in here for anyone else googling and needing answers.
