### ISSUE TITLE
AdvanceCircuitBreaker with exponential backoff

### ISSUE THREAD

**Issue by abdulwaheed05** [App-vNext/Polly#640]
Is there are way to configure an advance circuit breaker policy with exponential backoff upto a limit? In our use of circuit breaker we found it is useful to have this kind of configuration because instead of either hard coding a cooling period or randomly assigning one value to all different deployments, exponential backoffs for cooling period makes the policy much more flexible and useful

**Comment by reisenberger** [comment]
There is no such facility with Polly circuit-breaker.  You can however [configure exponential backoff with retry policies](https://github.com/App-vNext/Polly/wiki/Retry#exponential-backoff).

**Comment by reisenberger** [comment]
Closing in favour of #653, on the same topic.  On #653, I have sketched out how this could be built.

**Comment by Brondahl** [comment]
@abdulwaheed05 FYI, I'm pretty close to finishing the PR on #653 to provide this functionality (including to AdvancedCircuitBreakers). You might want to subscribe to that Issue, to get an update when it's finished.
