### ISSUE TITLE
Is that possible to catch action result instead of exception?

### ISSUE THREAD

**Issue by OleksandrBodrov** [App-vNext/Polly#643]
So, basically, I need to provide retry for some action, but it doesn't throw an exception if the action failed, but return, let's say, false.

For instance:

I have an action, which requires a retry mechanism:
```CSharp
var connectionExists = something.TryConnect();
```

TryConnect method returns true if the connection is successful, and false if it isn't. It doesn't throw any exceptions when the connection failed. But I need it to retry the connection if it dropped.
I know I can do something like this:
```CSharp
void CallTryConnect() =>
      if (!something.TryConnect())
            throw new ConnectionFailedException();

void ActualMethod() =>
      Policy
            .Handle<ConnectionFailedException>()
            .Retry(10)
            .Execute(() => CallTryConnect());
```

But it doesn't look good, so I was wondering is there some approaches to provide this kind of handling.

**Comment by reisenberger** [comment]
This is documented at Step 1b in the ReadMe: https://github.com/App-vNext/Polly#step-1b-optionally-specify-return-results-you-want-to-handle

**Comment by OleksandrBodrov** [comment]
@reisenberger Oh god, that exactly what I need. How could I forget about those? Thanks.
