### ISSUE TITLE
Retrying the execution of a whole console app using polly [can Polly integrate with Scheduled Tasks]

### ISSUE THREAD

**Issue by jonathh21** [App-vNext/Polly#650]
I have a console app that interacts with various resources and sometimes tho resources aren't available.

The console app runs as a scheduled task.

Can Polly policy be used here? It would need to apply the policy across entire executions of the console app..

Any suggestions?

**Comment by reisenberger** [comment]
If the Console App is a "black box" (not something you can change) running as a scheduled task, you'd need to use any in-built features of re-running scheduled tasks on whatever platform/server you are using to run them. Polly cannot help.

If the Console App is (or were to be) run from within C# code using `Process.Start()`, and if it returns meaningful return codes indicating success/failure in the `Process.ExitCode` property, then you could wrap a Polly policy around that `Process.Start()` execution to (for example) invoke retries based on the `Process.ExitCode` property.

If you have the source code of the Console App and can change it, you can of course introduce Polly _within_ a Console App to retry the individual operations.

(If anyone has any other ideas, please feel free to comment!)

**Comment by jonathh21** [comment]
Thanks for getting back to me.

The app is completely in my control..

However I am coming to the conclusion what I'd like to do isn't really what
Polly was created for.

My scenario is this.

We have a scheduled task that runs once every 20mins (y).

If it runs and fails it X times, then after X * y minutes, the subsequent
attempts to run won't do anything.

Remember it is a scheduled task so it'll keep running at each interval.

**Comment by reisenberger** [comment]
>If it runs and fails it X times [then don't do it again (for some period?)]

has similarities to a [circuit-breaker pattern](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker).  You would need however a durable/distributed circuit breaker (not currently available from Polly) to be able to use that across separate invocations of a scheduled task.

Yes: Polly is not designed to integrate with [Windows Task Scheduler](https://docs.microsoft.com/en-us/windows/desktop/taskschd/task-scheduler-start-page) (if that is the kind of scheduled task under discussion). Other options for scheduling background work (as part of some other running app) include libraries like [hangfire](https://www.hangfire.io/) and [quartz](https://www.quartz-scheduler.net/). One might have more control over integrating with Polly with those, but might still need a durable circuit-breaker for your use case.

**Comment by reisenberger** [comment]
Closing this as think we have discussed all the main options.  Broadly, Polly is designed for orchestrating retries within a process, rather than of a whole process.  You might have options with Polly to track failures and prevent further retries/invocations, when Polly provides a durable cross-process circuit-breaker.

Let me know if any other ideas/angles/questions, and we can re-open.
