### ISSUE TITLE
Does Polly have any guidance on eliding async?

### ISSUE THREAD

**Issue by 0shi** [App-vNext/Polly#652]
**Summary: What are you wanting to achieve?**
Does Polly have any guidance / thoughts / opinions on eliding async (e.g. https://blog.stephencleary.com/2016/12/eliding-async-await.html) when making calls through a policy? As a pass-through, it seems like this should be safe, but I'd like to understand if you feel there are Polly specific reasons why you would or would not recommend this.

**What code or approach do you have so far?**  
For our project, we surface some helper classes which provide retries in order to abstract Polly syntax away from our code and allow configuration of policies to be done outside the classes which make use of the retries.

So far I've been writing retry wrappers such as:
```
public async Task<T> Retry<T>(Func<Task<T>> code)
{
   return GetRetryPolicy().ExecuteAsync(async () =>   
   {   
      return await code().ConfigureAwait(false);
   }).ConfigureAwait(false);   
}
```
I am considering instead writing wrappers such as:

```
public Task<T> Retry<T>(Func<Task<T>> code)
{
   // Intentionally eliding async await here - Should be safe?   
   return GetRetryPolicy().ExecuteAsync(code);
}
```
Appreciate any responses.

**Comment by reisenberger** [comment]
It is absolutely safe from Polly's perspective to elide:

    .ExecuteAsync(async () =>{ return await code().ConfigureAwait(false); });

to:

    .ExecuteAsync(code);

All Polly policy implementations `await` internally the `Func<Task<..., ..., T>>` you pass to `.ExecuteAsync(...)`. And all Polly implementations use `.ConfigureAwait(false)` internally on all `await`s, unless you execute with `continueOnCapturedContext: true`.

---

Eliding:

    async Task<T> Retry<T>(Func<Task<T>> code) => { return await GetRetryPolicy().ExecuteAsync(code); }

to:

    Task<T> Retry<T>(Func<Task<T>> code) => { return GetRetryPolicy().ExecuteAsync(code); }

can cause exceptions thrown by `GetRetryPolicy()` to express differently as I'm sure you will have seen in Stephen Cleary's article.  Whether that is a concern is independent of Polly, and depends on how you are calling your wrapper method `Retry<T>(...)`.

**Comment by 0shi** [comment]
Thank you for a swift and comprehensive response, much appreciated.
