### ISSUE TITLE
Bulkhead policy could have dynamic max parallelization count

### ISSUE THREAD

**Issue by atifield** [App-vNext/Polly#664]
**Is your feature request related to a specific problem? Or an existing feature? Please describe.**

Currently, `Bulkhead` policy cannot change the max count after it is created. Should there be any system that needs parallelization changed (eg. hot-loaded configuration change), new policy needs to be created and thereby losing the current state.

**Describe your proposed or preferred solution**:

Make `MaxParallelization` as public method in `Bulkhead` policy. Getter should return the configured max count. Setter should update the `SemaphoreSlim` logic to allow max count to change. Current implementation with `SemaphoreSlim` do not allow max count to change but there has been a few suggestions on [StackOverflow](https://stackoverflow.com/questions/24067200/semaphoreslim-with-dynamic-maxcount) for customizable SemaphoreSlim with dynamic max count.

**Describe any alternative options you've considered**:

At start, we could just recreate the policy if max count changes but this is not ideal. Alternatively, we could implement above feature as custom policy.

**Any additional info?**

We realize if updated max count is lower and the current bulkhead is full, any new tasks will be load shredded until the current count is lower than the new max count. This should be expected behaviour.

MaxQueueCount could also be dynamically updated but this is lower priority for us.

**Comment by reisenberger** [comment]
Thanks @atifield , a really interesting use case and idea.  I have been through exactly the same circuits of reasoning about this before, and agree with both your description of the scenario and possible implementations.

This doesn't align with my own priorities at present, so (for clarity) I am not able to commit any time to it, but it is a great idea, and we would love to see anything you (or anyone) develops! We can then either take it into Polly as a PR or bring it into and share it via the Polly-Contrib ([github home](https://github.com/Polly-Contrib); [introduction](http://www.thepollyproject.org/2019/02/13/introducing-custom-polly-policies-and-polly-contrib-custom-policies-part-i/)). (Been a principle of Polly to date that policies are immutable once constructed, so _leaning_ towards a custom policy/Polly-Contrib, but continuing to reflect ... .)

If you're interested to get started as a custom policy, see the [custom policy template for proactive policies, here](https://github.com/Polly-Contrib/Polly.Contrib.CustomPolicyTemplates/tree/master/ProactivePolicyTemplate).

Thanks again!

**Comment by atifield** [comment]
Hi, @reisenberger thanks for looking over this feature request. I could certainly contribute to a custom policy for this. Probably going to name it `AdjustableBulkheadPolicy` unless you have better name :)

I agree with you it is better to keep the core policies simple and immutable, however I would make a case for stateful policies have the capability to update parameters after creation, or allow copy constructor so state could be transferred to a new policy. Stateless policies more or less could be recreated without issue but stateful one being immutable would have impact if we desire updating policy behaviour after creation.

I could see circuit breaker policy having similar capabilities by allowing the ability to change the measuring metrics or changing the type of errors it should handle. The important part is to keep the breaker state and transition the error metrics over. In the scenario where breaker is about to be tripped, we do not want error metrics to be reset due to updated parameters. This is a harder problem to solve and I haven't thought too deeply on a resolution yet.

Cheers!

**Comment by reisenberger** [comment]
Awesome @atifield ! Another naming option : `MutableBulkheadPolicy` ...

**Comment by atifield** [comment]
Question about reusing the internal classes in Polly.Specs.Helpers namespace. Is there a solution where I can make use of those helper classes? My goal is fork all the tests in bulkhead first in another repo but I can't reuse the internal classes. Currently I have copied over the helper classes to make things compile but hoping there's a better way for this.

**Comment by reisenberger** [comment]
Great question! Things like `TraceableAction` and `BulkheadSpecsHelper`? Or `PolicyExtensions`? (or both?).  

Not sure that at the moment I can't think of a better (/amazingly-more-efficient-without-new-engineering) way than copy them over.  We could: 

(a) port (ie copy) the most useful specs helpers also into [Polly.Contrib.CustomPolicyTemplates](https://github.com/Polly-Contrib/Polly.Contrib.CustomPolicyTemplates)? (so that at least they were available as part of the template).  Quick and easy, and they don't change often, so not so likely to diverge from source.

(b) pull a SpecsHelpers csproj/dll out of Polly.Specs and nuget it. Feels pretty niche for a nuget package (basically for this use case - testing custom policies - or users testing their own policies), but could be done.

Thoughts? Any better ideas?

**Comment by atifield** [comment]
Yes, I believe only `TraceableAction`, `ResultPrimitive` and `ResultClass`  are being used by `Bulkhead.Specs`. I would go for option (a) for simplicity for now. Having a nuget doesn't make sense until there are a few custom policies using them. Git submodule could be another option but I am not familiar with the cons.

**Comment by reisenberger** [comment]
Ok. I would suggest just copy those across to your project for now. `TraceableAction` is entirely specific to Bulkhead tests (so won't likely have further re-use).  I can copy `ResultPrimitive` and `ResultClass` to  Polly.Contrib.CustomPolicyTemplates later. Thanks!

**Comment by reisenberger** [comment]
@atifield Awesome! I'll set this up early next week, unless @joelhulen gets to it before me 😉 . We'll also send you an invite to the Polly.Contrib org!

**Comment by reisenberger** [comment]
@atifield I've made the repo for [Polly.Contrib.MutableBulkheadPolicy](https://github.com/Polly-Contrib/Polly.Contrib.MutableBulkheadPolicy) and invited you to the [Polly-Contrib org](https://github.com/Polly-Contrib/) - once you accept the invitation, you should have rights to work on that repo.

More on the CI and nuget shortly.

**Comment by reisenberger** [comment]
@atifield Once you have accepted membership of the [Polly-Contrib org](https://github.com/Polly-Contrib/) (and committed a build for the project - see our templates if not already), you should then have authorisation to add an AppVeyor CI build via https://ci.appveyor.com/account/Polly-Contrib/projects . 

I'll check re nuget publishing - may need to add some permissions when we get there.

Thanks!

**Comment by atifield** [comment]
Thank you! I will prepare the PR tomorrow for review.

**Comment by reisenberger** [comment]
Closed by initial release of Polly.Contrib.MutableBulkheadPolicy

**GitHub**: https://github.com/Polly-Contrib/Polly.Contrib.MutableBulkheadPolicy
**Nuget**: https://www.nuget.org/packages/Polly.Contrib.MutableBulkheadPolicy

Added [reference on bulkhead wiki](https://github.com/App-vNext/Polly/wiki/Bulkhead#related-projects)
