### ISSUE TITLE
Async Policy does not await async actions in sync OnRetry (use OnRetryAsync instead)

### ISSUE THREAD

**Issue by rojas8392** [App-vNext/Polly#671]
**Summary: What are you wanting to achieve?**

<br/> We added a policy to an API call. When that API call fails, we need to make another API call BEFORE we retry. The code we are currently using is not waiting for the policy to handle the exception before it retries it. What is the right way to set this up?
<br/>

**What code or approach do you have so far?**  

<br/>

```
var linearSleepProvider = retryAttempt => TimeSpan.FromSeconds(1 * retryAttempt).AddJitterPercentage();

var policy = Policy.Handle<Exception>(exception => exception.StatusCode >= HttpStatusCode.BadRequest)
.WaitAndRetryAsync(retryCount, linearSleepProvider , onRetry: (context) => 
{
await AnotherApiCall(params)
}).WithPolicyKey("PolicyKey");

var resultOfMainApiCall = await policy.ExecuteAsync(
async (context, cancellationToken) => await MainApiCall(params, cancellationToken),
new Polly.Context("MainCallContext), cancellationToken);
```

**Comment by reisenberger** [comment]
@rojas8392 You have used an overload of `.WaitAndRetryAsync(...)` which takes a synchronous `onRetry:` delegate. That `onRetry:` delegate will only be called synchronously by the policy, so it will behave like an `async void` - it will return synchronously at the first `await` - not awaiting the call within it before the calling thread continues, as you observe.

Switch to using an overload of `.WaitAndRetryAsync(...)` where you specify an asynchronous, `onRetryAsync:`. For example [this overload](https://github.com/App-vNext/Polly/blob/4db50346299f62c2373ceba99d2522a8171c9e27/src/Polly/Retry/AsyncRetrySyntax.cs#L381) (there are also many other variants if that is not exactly the one you need).

**Comment by rojas8392** [comment]
Thanks so much this fixed it!
