### ISSUE TITLE
Update Readme.MD and Wiki to use OperationKey instead of ExecutionKey 

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [App-vNext/Polly#673]
In V6. ExecutionKey was renamed to OperationKey (https://github.com/App-vNext/Polly/issues/426).
However in Readme.md and Wiki some examples still refer to ExecutionKey.
It will be better to change the samples to have documentation up-to-date

**Comment by reisenberger** [comment]
Thank you for spotting this. Please feel free to contribute a PR to correct the examples in the readme.

The wiki is open access to edit: please feel free to contribute corrections to those wiki examples, if you get to them before me.

Thanks.

**Comment by reisenberger** [comment]
Closed by wiki edits and #682
