### ISSUE TITLE
Is there a global setting for enabling continueOnCapturedContext by default ?

### ISSUE THREAD

**Issue by GreatFireWall** [App-vNext/Polly#676]
Add `continueOnCapturedContext` to each `ExecuteAsync` call is exhausted.

**Comment by reisenberger** [comment]
>Is there a global setting for enabling continueOnCapturedContext by default ?



There is no such global setting. However, if your typical/only usage is continueOnCapturedContext: true, you could create your own extension methods for the overloads you use, to chain on with continueOnCapturedContext: true.

I’m interested to hear more about the use cases where people are using continueOnCapturedContext: true, if you want to describe the scenario.

**Comment by GreatFireWall** [comment]
Okay.. Thank you.

**Comment by GreatFireWall** [comment]
Hi @reisenberger, I am creating an extension methods for the overloads for `continueOnCapturedContext: true`, but I don't understand Polly internal implementation, is the following practice a good implementation? Will it causing any problems?

```cs
public static class PollyExtensions {
    public static Task<TResult> ExecuteExAsync<TResult>(this AsyncPolicy<TResult> policy, 
                                                        Func<Task<TResult>> action) {
        return policy.ExecuteAsync(_ => action(), 
                                   CancellationToken.None, 
                                   continueOnCapturedContext: true);
    }
}
```

**Comment by reisenberger** [comment]
@GreatFireWall Yes, your code for adding an overload to call Polly always with `continueOnCapturedContext: true` looks absolutely fine.  Lots of the execute overloads within Polly are [nearly identical](https://github.com/App-vNext/Polly/blob/5a5502b055248af43ca049ab1cabc91c4883da90/src/Polly/AsyncPolicy.TResult.ExecuteOverloads.cs#L19-L21) 🙂 

One question people sometimes ask about this kind of method is whether it is ok to omit `async` and `await` (as your code does).  For this simple pass-through method, it is fine to omit `async` and `await`.  [Stephen Cleary's article on async/await elision](https://blog.stephencleary.com/2016/12/eliding-async-await.html) has a great discussion of this.

**Comment by GreatFireWall** [comment]
Thank you for you clarify. 🙂

**Comment by sunniejai** [comment]
We are using Microsoft Orleans and that has a special scheduler for it's grains that gurantees that its single threaded. We are also using Polly for a bunch of retry logic, but it's a very easy trap to just call ExecuteAsync() instead of using an extension method that expclitly sets continueOnCapturedContext to be true.

more info on Orleans scheduling here https://dotnet.github.io/orleans/docs/grains/external_tasks_and_grains.html

Is there anyway to expose DefaultContinueOnCapturedContext so that we can set that to be true instead of false?
