### ISSUE TITLE
How does polly do application and interface fusing?

### ISSUE THREAD

**Issue by leeshuiwua** [App-vNext/Polly#678]
Call different applications for the same system. How to achieve application level melting?

**Comment by reisenberger** [comment]
@leeshuiwua . I am not sure I have fully understood the question. If I have not understood, please could you explain in more detail, perhaps with an example?

Is your question about (for example) how to share the same circuit-breaker for calls to different endpoints on the same downstream system? If this is your question, see: https://github.com/App-vNext/Polly/wiki/Statefulness-of-policies ;

**Comment by leeshuiwua** [comment]
知道了，谢谢

**Comment by leeshuiwua** [comment]
got it,thanks!

**Comment by leeshuiwua** [comment]
Got it,thank you ! What is the specific switching process from the open state to the half state?

**Comment by leeshuiwua** [comment]
got it,thank you!
