### ISSUE TITLE
What is the specific switching process from the open state to the half state?

### ISSUE THREAD

**Issue by leeshuiwua** [App-vNext/Polly#679]
e.g:
from open state to half open state, is it a certain proportion of the release rate to see the success rate, then switch to the close state or wait for the fuse cycle to pass once to request the request to succeed or fail to switch the fuse state? Don't know if you understand this?
thank you !

**Comment by reisenberger** [comment]
@leeshuiwua . The Polly wiki documentation describes this in detail:

+ [How the Polly Circuit Breaker works](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker#how-the-polly-circuitbreaker-works) and [diagram](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker#putting-it-all-together-)
+ [How the Polly Advanced Circuit Breaker works](https://github.com/App-vNext/Polly/wiki/Advanced-Circuit-Breaker#definition)

If you have further questions after reading that documentation, please reply with the questions, and we can re-open the issue.  Thank you.
