### ISSUE TITLE
broken link for separate sync and async policies

### ISSUE THREAD

**Issue by bgawale** [App-vNext/Polly#686]
**Summary**: 
The documentation contains the broken link i.e. for separate sync and async policies. 
<br/>
<br/>

**Expected behavior**: 
It should redirect to the correct page.
<br/>
<br/>

**Actual behaviour**:
The page to which it currently redirects i.e. http://www.thepollyproject.org/2017/06/09/polly-and-synchronous-versus-asynchronous-policies/ yeilds into the 404 error.
<br/>
<br/>

**Comment by reisenberger** [comment]
Thanks @bgawale (removed, as the referenced article was out of date and no longer exists)
