### ISSUE TITLE
FYI, you can use DebuggerStepThrough in UnitTest method so that VS does not break on user-unhandled exception

### ISSUE THREAD

**Issue by pnmcosta** [App-vNext/Polly#691]
Hi,

This is more of an FYI, than an actual how to question/request.

After reading https://github.com/App-vNext/Polly/wiki/Debugging-with-Polly-in-Visual-Studio I tested the DebuggerStepThrough attribute on a method of my Unit Test and can confirm that VS2019 will not break on method that has it.

This is great if you don't want to ask other developers to disable the break on user-unhandled exceptions before running the tests.

Here's and example on my service library unit tests:

```cs
[TestMethod]
public void Service_ExecuteRetries3Times()
{
    var service = (PollyRetryServiceClient)container.Resolve<IPollyRetryServiceClient>();

    int tries = 0;

    service.Execute((ctx, ct) =>
    {
        tries++;
        FailOperation();
    }, CancellationToken.None, "Service_ExecuteRetries3Times");

    Assert.AreEqual(4, tries);
}

[DebuggerStepThrough]
private void FailOperation()
{
    throw new Exception("Fail the operation");
}
```

:)

**Comment by reisenberger** [comment]
Thanks @pnmcosta ! :+1:  I've updated the [section on `[DebuggerNonUserCode]` and `[DebuggerStepThrough]` attributes in that wiki page](https://github.com/App-vNext/Polly/wiki/Debugging-with-Polly-in-Visual-Studio#the-debuggernonusercode-and-debuggerstepthrough-attributes) to make it clear this works in VS2019.

If you think that page can still be improved, please feel free to make/suggest further changes (you should be able to click the 'Edit' button at the top of that wiki page; the wiki is open-access for updates!).

Thanks again!
