### ISSUE TITLE
How to log successful retries? [with Polly and HttpClientFactory]

### ISSUE THREAD

**Issue by shagilt** [App-vNext/Polly#692]
**How to log successful retries?**

<br/>
<br/>

We are using AddPolicyHandler extension to add timeout and retry policies.
I have below code in my policy selector to log retry failures. But how to capture if a retry is successful? 
<br/>
`onRetryAsync: async (response, delay, retryCount, context) =>
                            {
                                Log.Retry(…);
                            }
                     );
`
<br/>
<br/>
I was thinking to add a handler before PolicyHandler to capture the metric.
Is there any build-in metric for retries?

**Comment by reisenberger** [comment]
@shagilt Short answer: The `Polly.Context` which is scoped to (unique to) each execution is passed to the `onRetryAsync`.  And the retry count is also passed to the `onRetryAsync`.  So, in the `onRetryAsync`, you can capture on `Polly.Context` how many retries were used:

    context["retriesUsed"] = retryCount;

You could then have a handler before (outside) the PolicyHandlers, which uses: 

    var context = requestMessage.GetPolicyExecutionContext();

to get the `Polly.Context` _after_ the execution. If `context["retriesUsed"]` is set, retries have been used, and that can be logged.  

As you want only to log that when the execution succeeded overall, you might also need to check the `HttpResponseMessage` for success/failure status before logging.

There's a fairly [similar example here in our Polly and HttpClientFactory documentation](https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory#use-case-exchanging-information-between-policy-execution-and-calling-code)

Let me know how you get on - or if I can provide any further information!

**Comment by reisenberger** [comment]
@shagilt Did this work for you? Do you need any further information?

**Comment by shagilt** [comment]
@reisenberger yes, my original plan was to add a new DelegatingHandler too. I will try this and get back to you. Thank you for your help!

**Comment by shagilt** [comment]
@reisenberger I implemented this approach and works fine. Thanks again!
