### ISSUE TITLE
Improve Wait Policy Documentation

### ISSUE THREAD

**Issue by LucaBlackDragon** [App-vNext/Polly#712]
The WaitAndRetry policy (and similar ones) provides an overload allowing users to determine the sleep duration on runtime with a `sleepDurationProvider` function.
For instance:

```csharp
//
// Summary:
//     Builds a Polly.Policy that will wait and retry retryCount times calling onRetry
//     on each retry with the raised exception, current sleep duration and context data.
//     On each retry, the duration to wait is calculated by calling sleepDurationProvider
//     with the current retry number (1 for first retry, 2 for second etc) and execution
//     context.
//
// Parameters:
//   policyBuilder:
//     The policy builder.
//
//   retryCount:
//     The retry count.
//
//   sleepDurationProvider:
//     The function that provides the duration to wait for for a particular retry attempt.
//
//   onRetry:
//     The action to call on each retry.
//
// Returns:
//     The policy instance.
//
// Exceptions:
//   T:System.ArgumentOutOfRangeException:
//     retryCount;Value must be greater than or equal to zero.
//
//   T:System.ArgumentNullException:
//     sleepDurationProvider or onRetry
public static RetryPolicy WaitAndRetry(this PolicyBuilder policyBuilder, int retryCount, Func<int, Context, TimeSpan> sleepDurationProvider, Action<Exception, TimeSpan, Context> onRetry);
```
The `sleepDurationProvider` function in this case is called with three parameters:
- an integer (which counts the attempts made at executing the code wrapped by the policy)
- a context object
- a timespan

**Questions (unanswered by the [documentation](https://github.com/App-vNext/Polly/wiki/Retry)):**
- Does the attempts counter start from 0 or 1?
- What is the meaning of the properties of the context object?
- What does the timespan value represent?

**Comment by m1nkeh** [comment]
I support this, I also had to guess

**Comment by reisenberger** [comment]
Thanks @LucaBlackDragon !  [Documentation added](https://github.com/App-vNext/Polly/wiki/Retry#configurable-policy-delegates) to the wiki page :+1:
