### ISSUE TITLE
Cert invalid for ThePollyProject.org

### ISSUE THREAD

**Issue by SeanKilleen** [App-vNext/Polly#718]
**Summary**: 

Was looking into converting some `http` URLs to `https` in the MS docs. 

When navigating to <https://thepollyproject.org/> ....

**Expected behavior**: 

Site loads with https

**Actual behaviour**:

> ![cert error](https://user-images.githubusercontent.com/2148318/67996048-f4a4b280-fc23-11e9-910b-a2805d4544da.png)

Looks like the cert is only set up to cover `https://thepollyproject.azurewebsites.net/`

If this project is a .NET Foundation project, I believe you are eligible for a [free SSL cert for your domain](https://dotnetfoundation.org/about): 

> We've partnered with DigiCert to provide SSL certificates for the .NET Foundation OU. We set your project up in Digicert's system, you request the certificate for your website, and they're paid for centrally by the foundation.

Or, since you're on the azure app service, if you're willing to spend a few bucks, the [setup for an SSL cert there isn't too tough](https://docs.microsoft.com/en-us/azure/app-service/web-sites-purchase-ssl-web-site). I've done it before; let me know if I can be of help.

Wanted to drop this here in case it's useful; feel free to close if not. Thanks!

**Comment by joelhulen** [comment]
Thanks for the heads-up!

I've been thinking about changing up this site anyway to be statically hosted and served up for free using GitHub or similar. Then just accept PRs to update the site content. I think this might be a good excuse to get in there rework the site.

**Comment by SeanKilleen** [comment]
If you're interested in help on the conversion, feel free to create a repo and grant me push access; I currently run my site on GitHub pages via Jekyll and I think we could do a 1:1 conversion reasonably quickly.

**Comment by joelhulen** [comment]
Thanks. We're using ghost for the blog so I'm not sure what the upgrade path is.

**Comment by SeanKilleen** [comment]
Likely something along the lines of:

* Get basic Jekyll up & running and deployed on GitHub pages
* If you find a Jekyll theme that gets pretty close to your current layout, that'd probably be the easiest because then a lot of minutiae is handled by updating a `_config.yml` file.
* Otherwise, get the CSS, JS, etc. going with a few test pages & posts
* Import the rest of the posts with https://import.jekyllrb.com/docs/ghost/
* Get the author profiles set up if you're still trying to link to them
* Check the SEO, redirects, etc. (jekyll imports for this)
* Add a `CNAME` file in the root of the repo
* Change your registrar to point to GitHub pages
* Get set up with a Netlify account (fantastic build & preview functionality for PRs)
* Set up Netlify CMS (free library, integrates with GH pages, allows CMS-like feel of Ghost)

If you want to throw CloudFlare in front of it while you're at it, [I've got an older post on those steps](https://seankilleen.com/2016/12/now-running-on-cloudflare/).

**Comment by 304NotModified** [comment]
Any news on this? Plain http is a bit strange nowadays. I really like to see https everywhere

**Comment by SimonCropp** [comment]
@SeanKilleen this seems to be fixed?

**Comment by SeanKilleen** [comment]
Looks like it! This can be closed.

**Comment by martincostello** [comment]
Looks like it expired again @joelhulen.

/cc @scottthurlow

**Comment by SeanKilleen** [comment]
Bumping just because I assume someone still wants to see it and get it fixed 👍

**Comment by joelhulen** [comment]
I realized that I only had SSL binding set up for www.thepollyproject.org and not thepollyproject.org. It is now resolved. Thanks for bringing this back up!
