### ISSUE TITLE
ExecuteAndCapture not possible when using WaitAndRetry overloaded with onRetry parameter (with context?)

### ISSUE THREAD

**Issue by jmattw42350** [App-vNext/Polly#72]
I understand that if a task is being executed after each attempt, it is possible to capture the information surfaced in the policyresult, but if the business logic during retry attempts differs from the business logic after final attempt, I would like to still have a policyresult object after execution.

Thanks!

**Comment by reisenberger** [comment]
Hi @jmattw42350 .  Many apologies, but I have not completely understood the question.  Could you perhaps explain in more detail, or show a code example of what you would like to see working?

**Comment by reisenberger** [comment]
@jmattw42350 : In Polly (as now), policy execution captures exceptions thrown by the delegate supplied to `.ExecuteAndCapture()`, but does not capture exceptions thrown by the `onRetry` delegate. Exceptions thrown by the `onRetry` delegate propagate as normal, and so are not captured into a `PolicyResult` instance.  

Is this related to your question?

**Comment by reisenberger** [comment]
@jmattw42350 : I believe I erred in my previous assessment that `.ExecuteAndCapture()` would not capture exceptions thrown by an `onRetry` delegate.  Those exceptions should be captured, but would be identified as `ExceptionType.Unhandled` in the returned `PolicyResult`.

Let us know if we can help further with your original question (supplying a code example of what you would like to achieve may help in understanding)

**Comment by nedstoyanov** [comment]
@reisenberger I believe what this relates to is that `ContextualPolicy` does not have an `ExecuteAndCapture` method. I came across this as well today when doing:

            public static readonly Func<ContextualPolicy> NotificationSendPolicy = () =>
             Policy
             .Handle<Exception>()
             .WaitAndRetry(
                 NotificationSendMaxRetries,
                 GetExponentialBackoffTimeToWait,
                 (ex, t, c) =>
                 {
                      // Log error and retry count
                 }); 

You appear to be only able to call `Execute` on the `ContextualPolicy`, not `ExecuteAndCapture`.

**Comment by reisenberger** [comment]
Thanks @nedstoyanov !  I've opened that (just for clarity) as a separate issue #78 (although I agree it could relate).  I spotted this also while investigating #63 .
