### ISSUE TITLE
Handle (retry) Two Possible Exceptions Differently

### ISSUE THREAD

**Issue by m1nkeh** [App-vNext/Polly#720]
Hi,

I have an Api call that given a certain response needs to `WaitAndRetry`, and then given another different response should simply `Retry`.

Is PolicyWrap the correct approach to this? The SDK of the Api will return the same Exception in both scenarios, but the attributes of that Exception will differ slightly.. currently i am considering simply checking for that attributes, but it feels clunky.

Thoughts?

**Comment by reisenberger** [comment]
You can use `PolicyWrap` to functionally-compose two separate retry policies (as you mentioned).

Or you can handle both exceptions in one policy, but vary the wait-before-retry according to which exception is thrown:

+ Use the [`.Or<>()` syntax](https://github.com/App-vNext/Polly#step-1--specify-the--exceptionsfaults-you-want-the-policy-to-handle) (if necessary) to specify the second exception to handle. (If they differ only by attributes, a single `.Handle<>()` clause which captures both cases might suffice.)
+ Use [this overload of .WaitAndTry()](https://github.com/App-vNext/Polly/blob/5a5502b055248af43ca049ab1cabc91c4883da90/src/Polly/Retry/AsyncRetrySyntax.cs#L653-L654) to choose the duration of wait-before-retry based on the exception.  Just return `TimeSpan.Zero` as the duration to wait for the case where you don't want to wait.  A similar overload exists for both sync and async versions of the retry policy.

Code example and discussion of related issues in [this StackOverflow question](https://stackoverflow.com/a/58043863/)

**Comment by m1nkeh** [comment]
Nice, that SO post is exactly what i need actually, thanks so much!
