### ISSUE TITLE
Add Attempt count to PolicyResult [general: expand info on Policy execution available in PolicyResult]

### ISSUE THREAD

**Issue by TrevorPilley** [App-vNext/Polly#73]
We are using `ExecuteAndCapture` in our application, the policy is defined in configuration but executed elsewhere. I'd like to log whether a retry has happened (and how many) but all I have is `PolicyResult` to work from.

In one part of the app, we define a function which builds a policy:

```
config.BuildExceptionPolicy(() => Policy.Handle<IOxception>().RetryAsync(2));
```

And execute it in another:

```
var policy = step.BuildExceptionPolicy();
return policy.ExecuteAndCaptureAsync(async () => { ... } );
```

If the outcome is Failure, I log the final exception but along side that I'd like to log the number of attempts that were taken.

**Comment by reisenberger** [comment]
Hi @TrevorPilley.  

Because of the way the Polly execute methods are generalised, capturing the number of attempts into the `PolicyResult` is not that straightforward.  `.ExecuteAndCaptureAsync(...)` is agnostic to (and has no knowledge of) whether what is being run underneath is a retry policy, circuit-breaker policy without retries (or indeed some new kind of action-transforming policy in the future).

An approach in the meantime could be something like :

```
int attempts = 0;
var policy = step.BuildExceptionPolicy();
var result = policy.ExecuteAndCaptureAsync(async () => { 
   attempts++;
   //  ... 
} );
```


@joelhulen : I suggest we leave this issue open for a while so that others can comment if they would also like additional execution metadata in`PolicyResult`.

**Comment by TrevorPilley** [comment]
Could you not just add `public int Attempts {get;set;}` to `PolicyResult`  and do `Result.Attempts++;` to the code which executes the delegate passed to `ExecuteAndCaptureAsync`?

**Comment by reisenberger** [comment]
@TrevorPilley.  I looked at this in more depth in the intervening week, and agree that this would not be as difficult to integrate into Polly as initially feared: the `attempts++` approach could be pushed down to the core Polly codebase.  
 
We have also to consider how this would play in the context of both Retry and CircuitBreaker policies, but I think this would be ok. For CircuitBreaker, the `PolicyResult.Attempts` (or similar) property would just indicate 1 if the call was attempted, and 0 if it was not (due to the circuit being broken).
 
Discussing this one further with the core App vNext team, and hope to come back on this in the coming days.

**Comment by reisenberger** [comment]
Just updating thinking on this issue:
 
_Current conclusion:_ having set out the longer-term vision for Polly in the [Roadmap](https://github.com/App-vNext/Polly/wiki/Polly-Roadmap), it became clearer that Retry was just one policy among a larger/growing set of eventual envisaged policies.  In that context, reluctant to add `AttemptCount` (which makes most sense for retry) to `PolicyResult` (which has to make sense for all policy types) at this stage.  

In particular, for the Polly Pipeline (functional composition of policies in a nested wrap), the possible meaning of `AttemptCount` is unclear at this stage in thinking: some policies in the overall Policy wrap might have attempted execution of their next-inner delegate, others not ... what would overall `AttemptCount` represent and how should it be interpreted?
 
Not to say that this might not be added later - something like `DelegateInvocationCount` could still perhaps be useful as a 0 or 1 value for policies like `Cache`, `ParallelThrottle` - however, this will be easier to reason about once the wider range of policies is in place.

**Comment by reisenberger** [comment]
**Looking at this problem more broadly**: We _are_ looking more widely at ways Polly can expose information about how the Policy executed.  For example, all policies could emit events that could be observed as a Reactive Extensions event stream via `Observable<PolicyEvent>` or similar.  This would provide the ability for the various kinds of policy to emit events specific to their type – `FallbackValueProvided`, `CacheValueProvided`, `TimeoutExceeded` etc – as well as opening up wider possibilities for health monitoring and telemetry.  In this vision, `PolicyResult` retains its current focus on properties common to _all_ types of Policy execution (success/fail outcome, last exception, result [for funcs]), while behaviour specific to individual policies can be emitted as observable events.
 
This could also open up a more generalised form of the add-`AttemptCount`-to-`PolicyResult` idea.  For example, maybe `PolicyResult` could include an `IEnumerable<PolicyEvent>` of all events which occurred during execution.  This generalised approach would work for all policy types, and could be mined for all sorts of data - how many attempts were made, was the cache used, etc etc.
 
Community views on any of this welcome ...

**Comment by reisenberger** [comment]
@TrevorPilley Polly v5.1.0 just released now provides a way to do what you originally asked: define a policy in one part of the codebase, have the `onRetry` delegate of that policy do something (akin to `attempts++`), and access that in the `PolicyResult` returned by `ExecuteAndCapture/Async()`, in a completely different part of the codebase.

This is achieved in v5.1 by having all delegates used by Polly able to take as a parameter the `Context` flowing with each execution.  You can then manipulate any properties on the context:, eg do `context["retries"]++` in the `onRetry`.  Or define your own custom `MyContext` class subclassing `Context` and `context.Retries++` directly.  The `PolicyResult` returned by `ExecuteAndCaptureAsync()` then exposes `PolicyResult.Context`.  Blogged more [here](http://www.thepollyproject.org/2017/05/04/putting-the-context-into-polly/).

While we could have exposed `public int Attempts {get;set;}` directly on `PolicyResult`, this would have implied the limitation that only one retry policy could be used in a `PolicyWrap`.  In general, we wanted to reject the limitations imposed by a Hystrix-type approach where the structure of what can be used in an overall resilience strategy is pre-defined or has limitations in this way.  We chose with Polly instead to go for a fully flexible `PolicyWrap`, in which more than one retry policy might be used (for example to handle different exceptions differently) - which wouldn't have played with a direct `Attempts` property on `PolicyResult`

Thanks for the original suggestion!

**Comment by rvvincelli** [comment]
I think the proper way to do this now is with a [context](https://www.stevejgordon.co.uk/polly-using-context-to-obtain-retry-count-diagnostics).
