### ISSUE TITLE
Alternatives to consuming Polly via nuget.org

### ISSUE THREAD

**Issue by jodyford** [App-vNext/Polly#730]
My development work is done on a disconnected corporate network.  Their support for Nuget packages right now is nil.  I would appreciate another method of installation for Polly beyond a Nuget Package.

Thanks,

Jody

**Comment by reisenberger** [comment]
We additionally make [Github releases](https://github.com/App-vNext/Polly/releases) comprising source code, symbols and the nuget package, auto-tagged with the commit from which they were built.  Organisations where `nuget.org` is proscribed, or with more stringent adoption/validation requirements, can:

+ Consume the `.nupkg` from there manually; or place it on an internal nuget-feed.
+ Download, then rename the `.nupkg` to `.zip` (it's just a zip file underneath), open it as a zip file, extract the `.pdb` you want to use in your project, and include that `.pdb` manually in your project.
+ Build from source (run the `build.bat` in the root of the project), if the organisation prefers not to rely on a pre-generated `.pdb`.
+ Run static code analysis against the release, if desired. (Some organisations require to inspect source code or run code through static analysis tools before consuming nuget packages.)

Do any of these options meet your needs?

**Comment by reisenberger** [comment]
Closing due to no response. If you have further requirements, please post again and we can reopen.
