### ISSUE TITLE
Applying policies by attributes

### ISSUE THREAD

**Issue by jjxtra** [App-vNext/Polly#735]
This feature request is related to policies.

I would like to be able to annotate my class and interface methods with attributes that represent Polly policies, such as retry, circuit breaker, caching, etc. Something like this:

```cs
[Cache(...)] // cache ALL the methods of this interface unless overridden
[Retry(...)] // retry ALL the methods on this interface unless overridden
public interface IWebInterface
{
    [Cache(...)]
    [Retry(...)]
    [CircuitBreaker(...)]
    [Bulkhead(...)]
    Task<string> FetchJson1Async(string param1);

    [PollyIgnore] // ignore all polly attributes for just this method
    Task<string> FetchJson2Async(string param1);

    // this method inherits cache and retry from the interface definition
    Task<string> FetchJson3Async(string param1);
}
```

These attributes would inherit from a `PollyBaseAttribute` class. This saves having to type the policies everywhere the function is called. You could also provide a "uber" attribute that allowed specifying all the policies in a single attribute with named parameters. I could see people making some attribute sub-classes that setup all the policies they care about and then applying those attributes as needed.

The attributes would provide all the necessary properties to create a policy automatically. For example, the `Cache` attribute could provider a Key string property. If left null, an automatic key could be created using the full type name plus method name.

If a class implements an interface or overrides base class methods with Polly attributes, the class implementation would always get priority for Polly attributes.

The attributes would be applied in order. With the attributes, the interface call could work one of two ways:

1] Have an expression tree based utility method that allows calling the interface method through a Polly helper method, like Policy.Execute already does. The helper method would take care of finding the attributes and applying the appropriate Polly policies. There is still some repetition of code, since a Polly helper method would be needed anywhere you want to call a method with Polly attributes.

Example:

```cs
IWebInterface baseInterface = new WebInterface(); // WebInterface class implements IWebInterface
string result = await Polly.Execute(obj => obj.FetchJson1Async(param1)); // finds Polly attributes and adds appropriate policies to the method call
```

The `Polly.Wrap` call would take care of finding the attributes and applying policies. You could cache the type and method name for fast attribute lookup.

2] Use TypeBuilder and allow generating a Polly wrapper on an interface. For example:

```cs
IWebInterface baseInterface = new WebInterface(); // WebInterface class implements IWebInterface
IWebInterface wrappedInterface = Polly.Wrap(baseInterface); // MOQ style interface wrapper builder magic
string result = await wrappedInterface.FetchJson1("param1"); // wrappedInterface provides Polly policies using TypeBuilder magic.
```

Once that is done, you could call wrappedInterface and the Polly policies would be called automatically. This requires either building up an interface at runtime that wraps the existing interface, or having some sort of code generator that could generate a C# class that wraps the interface. Frameworks like MOQ do this already. This eliminates all the redundant calls to Polly and helper methods, and would be my ideal solution.

`TypeBuilder` documentation: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.typebuilder?view=netcore-3.1

I'd love any thoughts or feedback on this proposal.

**Comment by reisenberger** [comment]
Thanks @jjxtra for the suggestion! Declarative attributing to apply policies is an interesting idea, and came up once before.

The biggest potential drawback I can see - if the attributes configure the policies themselves - is that attributes require parameters to be compile-time constants (eg `[Retry(3)]`).  This tends either to preclude or not play well with various other policy features - driving policies from external config; using any policy-callback features like `onRetry`; using anything dynamic at runtime like enumerables for delay-between-retries, eg for [jitter](https://github.com/App-vNext/Polly/wiki/Retry-with-jitter); and DI/separation-of-concerns and unit-testing. 

We have tended to adopt/recommend injecting policies or a [PolicyRegistry](https://github.com/App-vNext/Polly/wiki/PolicyRegistry) into consuming code by DI, to decouple the operation governed from the policy applied to it; which in turn facilities various dimensions of [unit-testing](https://github.com/App-vNext/Polly/wiki/Unit-testing-with-Polly---with-examples). Using PolicyRegistry can also enable [dynamic reconfiguration during running, driven by config changes](https://github.com/App-vNext/Polly/wiki/Dynamic-reconfiguration-during-running).

Are there ways an attribute-declarative approach could bridge those issues?  One idea could be an attribute which simply applies a policy from a PolicyRegistry:

    [ApplyPolicy(string policyKey)]
    Task<string> FetchJson1Async(string param1);

This could have the benefit that there is only one attribute to build 🙂 , and give flexibility to vary policies at runtime and in unit tests. The attribute would need to be able to statically access a common PolicyRegistry - could lead to that PolicyRegistry being a process-wide singleton (ambient-context pattern) or similar?

Thoughts welcome!

We'd love to see more on this if this is something you (or anyone) want/s to develop and contribute as a [Polly-Contrib](https://github.com/Polly-Contrib/) project. (For clarity, I am not expecting to spend any of my own time on this, compared to other Polly priorities I have.)

---

You might also be interested to dig around the [PollyNator project](https://github.com/Pro-Coded/Polly.Contrib.Pollynator). This takes a Roslyn-code-generation approach to generating a Polly decorator for an interface.

**Comment by jjxtra** [comment]
PollyNator does wrap an interface using Roslyn so that's interesting. It does not use attributes but rather a class-wide policy. With a little work it could probably be tweaked to do attributes instead. That would cover #2 suggestion.

For #1 suggestion, your idea of using a policy key seems like it would work well, allowing the policy to be configured and injected at runtime.

Thanks for your well thought out response, Polly is an amazing library, I have only stumbled upon it recently and have been using it for https://ipban.com back-end :)

**Comment by MartinYl** [comment]
This idea is great！Is there a plan?

**Comment by djechelon** [comment]
> The biggest potential drawback I can see - if the attributes configure the policies themselves - is that attributes require parameters to be compile-time constants (eg [Retry(3)]). This tends either to preclude or not play well with various other policy features - driving policies from external config; using any policy-callback features like onRetry; using anything dynamic at runtime like enumerables for delay-between-retries, eg for jitter; and DI/separation-of-concerns and unit-testing.

We could use the best of both worlds. My preferred item for comparison is [Java's Spring Retry](https://docs.spring.io/spring-retry/docs/api/current/org/springframework/retry/annotation/Retryable.html) annotation, where you **can't** set a configurable policy but are restrained to compile-time retry policy.

So the new Polly-Contrib project could allow both a compile-time and registry policy giving priority to any if both are chosen (or error).

As for the very implementation in DI framework, as a very experienced Spring contributor, I'd investigate how can .NET Core DI handle AOP (Aspect Oriented Programming) via interception, something like `PollyNator does wrap an interface` statement.

We should make plans, I'm interested in this topic for my company.

**Comment by ndrwrbgs** [comment]
[Fody](https://github.com/Fody/Fody) could satisfy the AOP requirement above.

Some [features](https://github.com/castleproject/Core/issues/145) requested to [Castle.Core.AsyncInterceptor](https://github.com/JSkimming/Castle.Core.AsyncInterceptor) (which is runtime generated rather than compile time like Fody) allow for re-entrancy, which would be required to wrap with Polly, so it should be doable there (there's an issue [discussing that scenario](https://github.com/JSkimming/Castle.Core.AsyncInterceptor/issues/52))

With Fody, ideally we'd not be manipulating IL directly since there are [many](https://github.com/csnemes/tracer/issues/88) difficult [problems](https://github.com/csnemes/tracer/issues/81)

**Comment by ndrwrbgs** [comment]
backref to `duplicate`: https://github.com/vescon/MethodBoundaryAspect.Fody/issues/91

**Comment by SimonCropp** [comment]
@martincostello think we should close this. IMO AOP is not really something Polly should dable in

**Comment by martincostello** [comment]
I would agree that this isn't something that should really live in the core - it would add a lot of additional complexity and support burden (IMHO).

Seems like a candidate for something that builds on top of Polly in the [Polly-Contrib](https://github.com/Polly-Contrib) to me.
