### ISSUE TITLE
PR builds fails on second Appveyor build, for merge-commit

### ISSUE THREAD

**Issue by reisenberger** [App-vNext/Polly#737]
**Summary**: 

A PR typically builds twice on AppVeyor - for the branch and then the merge-commit of the PR. The second build often fails with:

```
========================================
__UpdateAppVeyorBuildNumber
========================================
Executing task: __UpdateAppVeyorBuildNumber
Build with specified version already exists.
```

The cake build script intends to set the build number from the git metadata `FullSemVer` and this repeats for the second build.

More analysis at: https://github.com/Polly-Contrib/Simmy/issues/56

**Expected behavior**: 

Both the branch-build and the merge-commit-build of a PR pass.

**Actual behaviour**:

The merge-commit-build of a PR often fails with above error, even if branch build has passed.

**Steps / Code to reproduce the problem**: 

Make a PR against any non-`master` branch, without changing `gitversionconfig.yml`

**Comment by reisenberger** [comment]
Fixed by #738

**Comment by martincostello** [comment]
This is still happening.

**Comment by martincostello** [comment]
I think #921 resolved this once and for all.
