### ISSUE TITLE
Where's the code of AddTransientHttpErrorPolicy?

### ISSUE THREAD

**Issue by mind0n** [App-vNext/Polly#743]
My company's policy requires to review the 3rd part framework's code before allowing devs to use the frameworks in case there's any weakness within the code.
Currently I'm asked to provide the code for AddTransientHttpErrorPolicy method for security department to review.
Do you know where to find the source code of AddTransientHttpErrorPolicy method?
I cannot find it in Polly.sln

**Comment by reisenberger** [comment]
`AddTransientHttpErrorPolicy(...)` is owned and published by Microsoft, as part of the `IHttpClientFactory` implementation mastered in `https://github.com/aspnet/Extensions`.

See: https://github.com/aspnet/Extensions/blob/master/src/HttpClientFactory/Polly/src/DependencyInjection/PollyHttpClientBuilderExtensions.cs#L215-L236

_Note_: That is a link to Microsoft's current `master` branch.  You may need to look at the `release/X.Y` branch for the release you are consuming.

The wider code that Microsoft own as part of the `IHttpClientFactory` integration is all found within https://github.com/aspnet/Extensions/tree/master/src/HttpClientFactory/Polly

Hope that helps 🙂

**Comment by mind0n** [comment]
Thanks

**Comment by tomkerkhove** [comment]
It took me a while to figure it out, but turns out you need [`Microsoft.Extensions.Http.Polly`](https://www.nuget.org/packages/Microsoft.Extensions.Http.Polly/) package.

**Comment by tomkerkhove** [comment]
Clearly misread the first section - https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory#step-1-reference-the-aspnet-core-21-packages

I'm a moron.
