### ISSUE TITLE
Exposing a Circuit-Breaker state via .NET Core Health Checks

### ISSUE THREAD

**Issue by endeffects** [App-vNext/Polly#747]
I'd like to use health checks to get notified if a circuit breaker gets active. Is there any option to combine this?

**Comment by reisenberger** [comment]
@endeffects Yup.  Here's a [public commit](https://github.com/reisenberger/Diagnostics/commit/af79e3713ef78976d675f280571024c50d7e8467) of how wiring up a healthcheck for a specific circuit-breaker policy could look.

**Comment by endeffects** [comment]
Thank you :)
