### ISSUE TITLE
Log and Debug each attempt made by an AsyncPolicy

### ISSUE THREAD

**Issue by GhimpuLucianEduard** [App-vNext/Polly#749]
**Summary: What are you wanting to achieve?**

I'm trying to handle all 401 responses with an **AsyncRetryPolicy**.

Some notes:

* I'm using **Xamarin.Forms**
* I'm using **Refit** but with no **HttpClientFactory**

My idea was that in case of a 401 to retrieve a new token. Which it seems to work fine but the HTTP request made on each retry attempt seems to be using the same old token. Now I'm not sure if that's true because I cannot log or debug the HTTP request.

<br/>
<br/>

**What code or approach do you have so far?**  

Here's the retry policy:

```csharp
var unauthorizedPolicy = Policy.Handle<ApiException>(ex => ex.StatusCode == HttpStatusCode.Unauthorized)
    .RetryAsync(3, async (exception, retryCount) =>
    {
        Logger.Instance.Info($"Unauthorized, token probably expired, retry count: {retryCount}");
        try
        {
            Logger.Instance.Error(exception.Message);
            Logger.Instance.Info("Retrying request and retrive refresh token");
            var token = await _authService.SignInSilentlyAsync();
            await SecureStorage.SetAsync(Constants.PreferencesNames.Token.Value, token);
        }
        catch (Exception ex)
        {
            Logger.Instance.Error(ex.Message);
            Logger.Instance.Info("SignInSilentlyAsync failed, going to login page");
            NavigationService.ReplaceRoot(new LoginPageViewModel());
        }
    });

```

This is executed in another class:

```chasrp
result = await _taskManager._defaultPolicyForHttpRequests // the above defined unauthorizedPolicy
    .ExecuteAndCaptureAsync<T>(async () => await task)
    .ConfigureAwait(false);
```

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/VxMnr.jpg

As you can see from the logs, the token is successfully retrieved, yet I think the old one is used when retrying the call. I cannot be sure because the call is no longer logged and I cannot debug the code (to be more precise the task that should be executed, I can still log and debug OnRetry func from the policy, but not the actual task which handle the HTTP call).

I'm been looking at other issues but it looks like everybody is using **HttpClientFactory** and all the answers are related to it.

**Comment by reisenberger** [comment]
Cross-posted with StackOverflow: https://stackoverflow.com/questions/59951017/polly-retryasync-not-working-and-code-is-not-logged

The answer Stephen Cleary has given on StackOverflow is exactly correct.
