### ISSUE TITLE
How to dynamically change what time out policy a client uses

### ISSUE THREAD

**Issue by ScottH-IQ** [App-vNext/Polly#750]
**Summary: What are you wanting to achieve?**
<br/>Is it possible to dynamically change what time out policy a HTTP client uses based on some logic unrelated to the client itself? Basically, I have two logic paths resulting in a GET call by a HTTP client. The only difference between the two different calls is the time-out time. The current HTTP client is declared at startup and is therefore not directly accessible by my class that contains the code where I want to choose what policy to use. Is there any way to choose between policies from a PolicyRegistry or something like that?

<br/>

**What code or approach do you have so far?**  

Currently, the HTTP client that I am using is created upon startup of the app.

```
services.AddHttpClient<ITaxServiceClient, TaxServiceClient>().AddPolicyHandler(
                PollyUtils.GetTimeOutRetryPolicy(Convert.ToDouble(configuration["ResilienceConfiguration:TaxServiceTimeOutInSeconds"]),
                Convert.ToInt32(configuration["ResilienceConfiguration:CommonRetryAttempt"])));
```

Then, I have logic in a separate class in another directory which eventually calls `httpClient.SendAsync(message)`

However, I am having trouble finding a way to dynamically changing the time-out time of the client. I'm not looking for a fallback policy, but instead just want to change the time out.

**Comment by reisenberger** [comment]
@ScottH-IQ  See [this similar StackOverflow question](https://stackoverflow.com/questions/59898639/overriding-the-httpclientfactory-policies-defined-with-polly).  You can either define two different logical clients, or use `.AddPolicy...(...)` overloads which allow the policy/selection-of-policy to vary based on the `HttpRequestMessage`.  You can pass custom information from your call site to the policy-selection logic using [`HttpRequestMessage.Properties`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestmessage.properties?view=netcore-3.1)

Our Polly and HttpClientFactory documentation also covers this, here: https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory#selecting-policies-dynamically

**Comment by ScottH-IQ** [comment]
Alright, I had found those two options and was trying to see if there were any other ways of approaching this issue that I have, but since it doesn't look like it I'll have to go with one of those options.

Thanks for the clarification and quick reply.
