### ISSUE TITLE
Accessing the original HttpRequestMessage within DelegateResult even when an exception occurs

### ISSUE THREAD

**Issue by ericbeaudry** [App-vNext/Polly#752]
As opposed to any other transient error, when an exception occurs, it's not possible to access the original HttpRequestMessage that is otherwise available through the result member.

<br/><br/>

I understand that when an exception occurs, it's impossible to provide a valid HttpResponseMessage but would it be possible to create a dummy response with the original HttpRequestMessage attached to it? Or better, add a member to DelegateResult that provides access to the original request so we can manipulate it before it's retried.

<br/><br/>

Only alternative I can think of is to use the context to pass the original HttpRequestMessage but I find it redundant and cumbersome since everything is already in place to provide easy access to the request.

**Comment by reisenberger** [comment]
Hi @ericbeaudry, thanks for the question. 

Polly is not uniquely dedicated to being used for Http calls with `HttpRequestMessage` and `HttpResponseMessage`.  Polly can be used with any underlying delegate of any kind.  So we cannot build something on `DelegateResult<TResult>` specific to `HttpRequestMessage`.  

(The `HttpRequestMessage` in fact [isn't passed directly to the policy by the HttpClientFactory integration](https://github.com/dotnet/extensions/blob/26d51a47593e08a0f27fd411684d99119f3c1596/src/HttpClientFactory/Polly/src/PolicyHttpMessageHandler.cs#L130) (only within a delegate closed over), so the policy doesn't have access to it.)

You could build your own `DelegatingHandler` to construct a dummy `HttpResponseMessage` when an exception occurs, if that approach suited your use case.

**Comment by ericbeaudry** [comment]
Thanks for the quick answer. I'll be looking into the DelegatingHandler.
