### ISSUE TITLE
Polly cache policy and dependency injection for IAsyncCacheProvider

### ISSUE THREAD

**Issue by jjxtra** [App-vNext/Polly#757]
**Summary: What are you wanting to achieve?**
I want to be able to pass a factory method into Policy.Cache instead of a concrete object, that way I can return a dependency injected object, allowing me to create and register cache policies during service setup/registration in .net core.

**What code or approach do you have so far?**  
I pass the actual service provider into the constructor of my implementation of IAsyncCacheProvider, and it uses a Lazy to create the actual objects to deal with caching later. I would rather pass those interfaces into the constructor of my class implementing IAsyncCacheProvider, but I didn't see a way to do that from the docs.

Example:
```csharp
Polly.CacheAsync(new CacheProvider(ServiceProvider));
// ServiceProvider is a singleton that holds a null property of IServiceProvider that is populated later once the IServiceProvider is available and service registration is built.
// In the CacheProvider class, I have Lazy objects that wrap the type of interface I need which is pulled out of the IServiceProvider on demand. This feels very hacky :)

// Desired pattern:
Polly.CacheAsync((serviceProvider) => { ... }) or Polly.CacheAsync<CacheProvider>() 
```
Not sure how this registers with .net core dependency injection and where does polly get the IServiceProvider from?

**Comment by reisenberger** [comment]
If I understand correctly, you should be able to achieve your goal, without any changes to existing Polly, using any of the DI configuration overloads already provided by .NET Core which take an implementation factory with `IServiceProvider` as an input parameter - such as [this overload](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicecollectionserviceextensions.addsingleton?view=dotnet-plat-ext-3.1#Microsoft_Extensions_DependencyInjection_ServiceCollectionServiceExtensions_AddSingleton__2_Microsoft_Extensions_DependencyInjection_IServiceCollection_System_Func_System_IServiceProvider___1__)

For example:

    services.AddSingleton<CachePolicy>(sp => Polly.Cache(sp.GetRequiredService<ISyncCacheProvider>(), /* etc */);

**Comment by jjxtra** [comment]
How would I register multiple cache policies with different behavior?

**Comment by reisenberger** [comment]
>How would I register multiple cache policies with different behavior?

[`PolicyRegistry`](https://github.com/App-vNext/Polly/wiki/PolicyRegistry) is a string-keyed registry of policies.  It can be configured and initialised at DI-configuration time with multiple  policies of any kind, including multiple cache policies. See the [linked documentation]((https://github.com/App-vNext/Polly/wiki/PolicyRegistry)) for more.

**Comment by jjxtra** [comment]
Makes sense, thanks!
