### ISSUE TITLE
NullReferenceException from CircuitStateController

### ISSUE THREAD

**Issue by shagilt** [App-vNext/Polly#758]
**Summary**: 
I am using below circuit breaker policy
`
this.CircuitBreakerPolicy = Policy.HandleResult<Boolean>(e => e)
                .AdvancedCircuitBreaker(
                    failureThreshold, 
                    samplingDuration,
                    minimumThroughput,
                    durationOfBreak,
                    onBreak: (ex, state, breakDelay, context) =>
                    {
//Logging
                    },
                    onReset: (context) =>
                    {
//Logging
                    },
                    onHalfOpen: () =>
                    {
                    }
               );`
<br/>
<br/>

Sometime I see null reference exception while running circuit breaker Execute(). Is this a known issue? I am using Polly 6.1.0

`CircuitBreakerPolicy.Execute((cxt) =>
                    {
                        return !status;
                    },
                            new Context("GetEndPoint", new Dictionary<string, object>() { { "Ep", Host }, { "ServiceName", this.ServiceName } })
                            );`
<br/>
<br/>
**Error**
  Message: 
    System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace: 
    CircuitStateController`1.GetBreakingException()
    CircuitStateController`1.OnActionPreExecute()
    CircuitBreakerEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldHandleExceptionPredicates, IEnumerable`1 shouldHandleResultPredicates, ICircuitController`1 breakerController)
    <>c__DisplayClass5_0`1.<AdvancedCircuitBreaker>b__0(Func`3 action, Context context, CancellationToken cancellationToken)
    Policy`1.ExecuteInternal(Func`3 action, Context context, CancellationToken cancellationToken)
    Policy`1.Execute(Func`3 action, Context context, CancellationToken cancellationToken)
	---Removed stack---

**Comment by reisenberger** [comment]
Thanks @shagilt for raising this. It looks to be due to a race, where one thread closes the circuit (resetting `_lastOutcome`) while another is executing the `HalfOpen` or `Open` cases of [this switch statement](https://github.com/App-vNext/Polly/blob/061a159d159bbaca4e8fe86d5bbe33411ac93aa4/src/Polly/CircuitBreaker/CircuitStateController.cs#L146-L154). Polly v8 plans to remove `_lastOutcome` / `LastOutcome` for another (similar) reason, and will fix this.

**Comment by shagilt** [comment]
Thanks @reisenberger 

FYI(not sure if this can give you more insight)

I changed my circuit breaker definition to this and same test is passing
`this.CircuitBreakerPolicies = Polly.Policy.Handle<Exception>(e =>  this.IsCircuitImpactingError(e))
                .AdvancedCircuitBreaker(
                    failureThreshold, //A double between 0 and 1
                    samplingDuration,
                    minimumThroughput,
                    durationOfBreak,
                    onBreak: (ex, state, breakDelay, context) =>
                    {
                        //Logging                    },
                    onReset: (context) =>
                    {
                        //Logging                    },
                    onHalfOpen: () =>
                    {
                    }
               );
`

**Comment by reisenberger** [comment]
Fixed by #770, released as [v.7.2.1](https://www.nuget.org/packages/Polly/7.2.1).
