### ISSUE TITLE
Url in README is broke

### ISSUE THREAD

**Issue by SurajGupta** [App-vNext/Polly#76]
http://thatextramile.be/blog/2008/05/the-circuit-breaker

**Comment by reisenberger** [comment]
Noticed this too - haven't found any new address to which the article has been moved - will remove link in due course.  Many thanks.

**Comment by SurajGupta** [comment]
great project, BTW!  so easy to drop Polly into my code.

**Comment by joelhulen** [comment]
Thanks for the heads up about the broken link! Perhaps we could replace it with this? [http://blog.jaywayco.co.uk/circuit-breaking-with-polly/](http://blog.jaywayco.co.uk/circuit-breaking-with-polly/)

**Comment by maverix** [comment]
https://web.archive.org/web/20160106203951/http://thatextramile.be/blog/2008/05/the-circuit-breaker

**Comment by joelhulen** [comment]
Thanks, @maverix! I've updated the readme file to include this link.

**Comment by reisenberger** [comment]
Thanks @maverix @joelhulen  !  

@maverix @SurajGupta  / anyone else interested: The readme now also includes further CircuitBreaker articles from Martin Fowler at Thoughtworks, and the Microsoft Patterns and Practices team.

**Comment by StefanBols** [comment]
@joelhulen the link is broken again

**Comment by joelhulen** [comment]
@StefanBols it looks like that link is permanently gone. I've removed it and added a link to a great circuit breaker-focused article by Andrew Lock (added to the Blob post section of the readme file). Also added two  links to new videos discussing Polly, under the Videos section.
