### ISSUE TITLE
ExecuteAsync Should take both Context and CancellationToken

### ISSUE THREAD

**Issue by stricq** [App-vNext/Polly#761]
**Is your feature request related to a specific problem? Or an existing feature? Please describe.**

I need to have the Context on the onRetry action, but there is no overload for ExecuteAsync that accepts BOTH Context and CancellationToken.

<br/><br/>

**Describe your proposed or preferred solution**:

There should be a method overload for ExecuteAsync that accepts both Context and CancellationToken.

<br/><br/>

**Describe any alternative options you've considered**:

I can use the CancellationToken directly in the action being executed but then Polly won't cancel until all the retries have completed.

<br/><br/>

**Any additional info?**

**Comment by reisenberger** [comment]
There are many `.ExecuteAsync(...)` overloads taking both `Context` and `CancellationToken`, such as [this one](https://github.com/App-vNext/Polly/blob/master/src/Polly/AsyncPolicy.ExecuteOverloads.cs#L65); and many similar variants for when executing an asynchronous function returning a `TResult`.
