### ISSUE TITLE
Unable to build Polly from source against .NET Core 3.1.201

### ISSUE THREAD

**Issue by SeanFarrow** [App-vNext/Polly#762]
I've just cloned polly on a fresh machine with .Net Core 3.1.201 installed and I'm unable to build from source.

I'm getting a tonne of errors from the microsoft.build.tasks.git NuGet package.

My source folder is not on the C drive due to space, but I don't think this should make a difference.
Is thee anyway I can capture the output from the PowerShell script run to provide more context?

Thanks,
Sean.

**Comment by SeanFarrow** [comment]
On further investigation, it appears the issue is caused by the fact Polly uses a beta of the microsoft.build.tasks.git package.

I've included a log file to illustrate the problem, but upgrading this package to V1.0.0 seems to fix the issue
[pollyFailure log.txt](https://github.com/App-vNext/Polly/files/4455888/pollyFailure.log.txt)
.

**Comment by reisenberger** [comment]
Thanks for highlighting this. That `microsoft.build.tasks.git` beta will be being pulled in by the [beta version of `SourceLink`](https://github.com/App-vNext/Polly/blob/061a159d159bbaca4e8fe86d5bbe33411ac93aa4/src/Polly/Polly.csproj#L27).  We can upgrade SourceLink to v1 RTM at the next Polly release, to fix this.

**Comment by SeanFarrow** [comment]
Would you like a PR to fix this?
Should we consider upgrading our other NuGet dependencies?
Thanks,
Sean.

**Comment by reisenberger** [comment]
Fixed by #770.
