### ISSUE TITLE
FallbackValue delegate access to Exception?

### ISSUE THREAD

**Issue by ronMilne** [App-vNext/Polly#767]
Within the FallbackValue delegate one cannot access the exception that has been raised. When constructing default return values it may be beneficial to extract information from the exception to pre-populate the default.

Within the supplied context make the Exception available. It appears to be available within the OnFallBack?

Currently I'm wrapping the operation in an ExecuteAndCapture; and creating the actual 'default' value there.

**Comment by reisenberger** [comment]
Existing overloads allow you to access the exception thrown within the fallback value delegate:
+ [`.Fallback(Action<Exception, Context, CancellationToken> fallbackAction, Action<Exception, Context> onFallback)`](https://github.com/App-vNext/Polly/blob/061a159d159bbaca4e8fe86d5bbe33411ac93aa4/src/Polly/Fallback/FallbackSyntax.cs#L120)
+ [`.Fallback<TResult>(Func<DelegateResult<TResult>, Context, CancellationToken, TResult> fallbackAction, Action<DelegateResult<TResult>, Context> onFallback)`](https://github.com/App-vNext/Polly/blob/061a159d159bbaca4e8fe86d5bbe33411ac93aa4/src/Polly/Fallback/FallbackSyntax.cs#L286)
+ [`.FallbackAsync(Func<Exception, Context, CancellationToken, Task> fallbackAction, Func<Exception, Context, Task> onFallbackAsync)`](https://github.com/App-vNext/Polly/blob/061a159d159bbaca4e8fe86d5bbe33411ac93aa4/src/Polly/Fallback/AsyncFallbackSyntax.cs#L78)
+ [`.FallbackAsync<TResult>(Func<DelegateResult<TResult>, Context, CancellationToken, Task<TResult>> fallbackAction, Func<DelegateResult<TResult>, Context, Task> onFallbackAsync)
        {`](https://github.com/App-vNext/Polly/blob/061a159d159bbaca4e8fe86d5bbe33411ac93aa4/src/Polly/Fallback/AsyncFallbackSyntax.cs#L207)

Hope that helps. If you have further qs, just post again and we can re-open.
