### ISSUE TITLE
Is it safe to use Polly retry to handle HTTP errors for longer time intervals

### ISSUE THREAD

**Issue by mohandeblaze** [App-vNext/Polly#777]
I trying to implement my own version of WebHooks for my application. When a user registers their URL hook (assume its wrong URL or will not respond with 2XX code), i would like to retry up to five times in an custom exponential interval say 5 mins, 30 mins, 2 hrs, 4 hrs and 16 hrs. I have implemented using Polly WaitAndRetryAsync but there are some concerns.

My question is,

1) In worst case is it safe to extend up to 16 hrs for 5th retry?

2) Is it thread safe (Docs says it is thread safe as long as my code is thread safe) but my concerns is 16 hrs long intervals.

3) Say many requests are failed and all the requests are retrying in their own interval. So, increasingly more requests are failed after some time does the server thread pools will become full and unable to accept any new requests?

4) Due to longer intervals is it really worth using Polly or better go for CRON job schedulers?

My implementation details are very similar or identical to Polly's official example IHttpClientFactory ([link](https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory#using-polly-with-ihttpclientfactory)).

Thanks for you suggestion.

**Comment by AhmadAlMunajjed** [comment]
Hi @martincostello, did you mange to implement the webhook system with retry mechanism using Polly?
Any suggestions?
