### ISSUE TITLE
Polly Retry always throws System.AggregateException instead of custom exception

### ISSUE THREAD

**Issue by calin-cozmin** [App-vNext/Polly#778]
As the title says, I created a retry mechanism using Polly. The problem is that I always get a System.AggregateException instead of my own custom exception. I will add the code here.

This is the polly static class which I created:

```
    public static class PollyExtension
    {
        public static Task<T> RetryRequestWithPolicyAsync<T,T1>(
            Func<Task<T>> customAction,
            int retryCount,
            TimeSpan pauseSecondsBetweenFailures) where T1 : Exception
        {
            return 
                Policy
                .Handle<T1>()
                .WaitAndRetryAsync(retryCount, i => pauseSecondsBetweenFailures).ExecuteAsync(() => customAction?.Invoke());
        }
    }
```

Here is that actuall call of the retry polly:

```
       var result= await PollyExtension.RetryRequestWithPolicyAsync<int, CustomException>( () =>
            {
                if (1 + 1 == 2)
                {
                    throw new MyException("test");
                }
                else
                {
                    throw new CustomException("test");
                }
            },
           1,
            TimeSpan.FromSeconds(1));

```
My expectations are that if I throw MyException then, polly will also throw MyException to the caller method. Instead the exception thrown is System.AggregateException.

What I am doing wrong here ? Thanks

EDIT 1: after more debug it seems that AggregateException has as inner exception MyException. Is this intended behaviour or I am doing something wrong ?
+ **code of any policy declarations**, 
+ **code of calls to `.Execute/AndCapture/Async(...)`**

**Comment by SimonCropp** [comment]
@calin-cozmin i cant seem to replicated this on the current codebase

![image](https://user-images.githubusercontent.com/122666/120986361-da4b9700-c7bf-11eb-82e1-cc3f0f3cfd5b.png)

it is possible it has been fixed by other changes. If you can still repro it, can you possibly share a failing unit test as a PR?

**Comment by martintmk** [comment]
This should be fixed in V8.
