### ISSUE TITLE
 Policy.Handle<Exception>().WaitAndRetryForeverAsync()  doesnot allow to pass execution context.

### ISSUE THREAD

**Issue by sowmyabhuvanapalli** [App-vNext/Polly#779]
**Is your feature request related to a specific problem? Or an existing feature? Please describe.**

<br/><br/>

**Describe your proposed or preferred solution**:

<br/><br/>

**Describe any alternative options you've considered**:

<br/><br/>

**Any additional info?**

**Comment by martintmk** [comment]
This is no longer an issue in v8 as all generators accept the context. 
Will be closed once v8 is released.

**Comment by martintmk** [comment]
The alpha is released, and you can try this out.

https://www.nuget.org/packages/Polly

Closing the issue.
