### ISSUE TITLE
How to use circuit breaker for EF Core

### ISSUE THREAD

**Issue by RajasekarPR** [App-vNext/Polly#783]
I have to access Postgresql using circuit breaker policy?

How to do that. Any code samples ?

**Comment by SimonCropp** [comment]
wouldnt this be better suited to using [EnableRetryOnFailure](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency)

**Comment by SimonCropp** [comment]
closing since EF has this kind of functionality
