### ISSUE TITLE
Method not found: 'System.Threading.Tasks.Task`1<Polly.PolicyResult`1<!!0>> Polly.Policy.ExecuteAndCaptureAsync(System.Func`

### ISSUE THREAD

**Issue by naveenjangra-gep** [App-vNext/Polly#788]
I am getting following exception from Polly...

Method not found: 'System.Threading.Tasks.Task`1<Polly.PolicyResult`1<!!0>> Polly.Policy.ExecuteAndCaptureAsync(System.Func`2<Polly.Context,System.Threading.Tasks.Task`1<!!0>>, Polly.Context)'.
I am using Polly 7.2.1
I cant put the code here but structure is something like this--
I am calling a function inside API controller
public IActionResult GetSomething(long x)
{
     var result = httpClient.PostAsync<JObject>(param1, payload, param2, true).ConfigureAwait(false);   //Getting exception here
     if (CheckResponse(result ))
     {return true;
       }
           return false;
}

**Comment by SimonCropp** [comment]
it is not possible to diagnose this without a stand alone solution that reproduces the issue. will close for now due to age, and will reopen if someone supplies a repro

**Comment by martincostello** [comment]
We didn't receive a complete repro, so no.

If you are also experiencing this issue then please provide us with a minimal reproducible repro demonstrating the problem and we can take a look.
