### ISSUE TITLE
ability to  auto-refresh Cache on schedule before it expires

### ISSUE THREAD

**Issue by MNF** [App-vNext/Polly#794]
It will be good to have an ability to  auto-refresh Cache on schedule before it expires similar as It is asked in https://stackoverflow.com/questions/44723017/in-memory-caching-with-auto-regeneration-on-asp-net-core and https://stackoverflow.com/questions/56412143/lazycache-regularly-refresh-cached-items

**Describe your proposed or preferred solution**:
Add optional Action<Context, string> onCacheExpired or

Action<Context, string> onCacheAboutToExpire and configuration aboutToExpireTimespan ( e.g. to start action 1 min before cache is expired)

Similar idea was discussed by @phatcher in https://github.com/App-vNext/Polly/issues/648#issuecomment-504660192

**Comment by jackbond** [comment]
I'd love to see this feature as well. If one of the goals of caching is to reduce latency, it seems insane to wait for a cache item to expire, and then repopulate its value on the first request following expiration. I'm sure there are some use cases where caching an item takes several seconds, as opposed to milliseconds to retrieve a cached item.

**Comment by phatcher** [comment]
@jackbond Issue with refreshing pre-emptively is that your cache grows monotonically i.e. you never remove anything from the cache.   You might also need a cache counter so you only pre-emptively load if the item is frequently used.

The multi-second first hit can't typically be avoided since you might need the latest.

I'm about to hit this sort of stuff again on my project so I'll provide some feedback here once I have a result

**Comment by jackbond** [comment]
@phatcher I thought about your "you never remove anything" point, and perhaps this feature wouldn't make sense for some Ttl strategies. But couldn't a SlidingTtl have a refresh interval which doesn't cause the expiration time to be extended? If the cache isn't hit, that new value gets thrown out pretty quick, but if it's retrieved, the expiration time is updated as it normally would?

**Comment by jackbond** [comment]
Update

**Comment by martincostello** [comment]
This is a feature we're unlikely to build into future releases of Polly.

A more likely scenario is a package that builds on top of the [.NET caching functionality](https://learn.microsoft.com/aspnet/core/performance/caching/memory) might be made available (see #1127) where such functionality would be associated with the cache itself and Polly would itself not need to concern itself with any optimistic re-hydration of the cache.
