### ISSUE TITLE
FEATURE: Fallback policy

### ISSUE THREAD

**Issue by mfjerome** [App-vNext/Polly#80]
As I understand it today, if I use Polly to setup a circuit breaker in my policy and that the circuit does break, I will receive a BrokenCircuitException. As a user of the framework, I need to handle this exception and write some code to specify how I want to react to this event. I would prefer to give to Polly that code and let it execute it if the circuit is broken. It would be better performance-wise, and much cleaner.

```
Policy
  .Handle<DivideByZeroException>()
  .CircuitBreaker(2, TimeSpan.FromMinutes(1))
  .WhenBroken(
  () => throw new BrokenCircuitException(); //Or another fallback method specific to my app.
)
```

**Comment by mfjerome** [comment]
The code above is just an example to illustrate the issue and I don't know if it possible to do it fluently this way. In Hystrix, by Netflix, the framework provides an interface that the user must implement with, among other things, a function "GetFallBack". That method will be called if the command execution fails because the circuit is open (short-circuited). Beforehands, this client implementation must be registered to Hystrix through data annotations.

https://github.com/Netflix/Hystrix/wiki/How-it-Works#8-get-the-fallback

**Comment by reisenberger** [comment]
@mfjerome, Thank you for the valuable suggestion.  You will see that this has now been incorporated in the [Roadmap](https://github.com/App-vNext/Polly/wiki/Polly-Roadmap) in a more general form - we think this could be used not only for CircuitBreaker.

**Comment by mfjerome** [comment]
Agreed! The fallback method, if provided, could be executed whenever the main task is not accomplished, even without the usage of CircuitBreaker. Thanks for the feedback.

**Comment by robertbaker** [comment]
I have a scenario for web requests.

Say I make a httpClient call that throws a 403. On a 403, I want to call my authenticate method first then  retry the method.

I don't think this is possible currently with polly. If it is please give me an example!

**Comment by reisenberger** [comment]
# Proposal: Fallback policy

## Purpose

To provide a fallback result or fallback delegate to be executed, if a handled exception is thrown or handled result returned. 

Encourages developers to think what the fallback strategy should be, for a potentially failing operation, at the point of initial coding.

## Scope

+ Support all sync and async variants
+ Support non-result-returning invocations (`Action`) and result-returning (`Func<TResult>`)
+ Support `Execute(...)` and `ExecuteAndCapture(...)` variants.  

## Configuration syntax

#### For Policy&lt;TResult&gt; forms

```cssharp
FallbackPolicy<TResult> fallbackPolicy = Policy
  .Handle<Whatever>(...)
  .OrTResult<TResult>(...)
  .Fallback<TResult>(Func<TResult> fallbackFunc);
```

#### For non-generic Policy 

While the most obvious use of a fallback policy is in the `TResult` case (as above), a non-generic form could also be useful, for providing an alternative `Action` to execute if a governed `.Execute(Action)` failed.

```cssharp
FallbackPolicy fallbackPolicy = Policy
  .Handle<Whatever>(...)
  .Fallback(Action fallbackAction);
```

## Operation


```cssharp
// TResult form
TResult result = fallbackPolicy
  .Execute(Func<TResult> executionFunc);

// void form
fallbackPolicy
  .Execute(Action executionFunc);
```

+ Calls/returns value from `executionFunc`.  
+ If `executionFunc` raises a handled fault: invoke/return value from `fallbackFunc` instead.
+ If `fallbackFunc` raises any kind of fault: no special handling; rethrow / pass fault result to caller.


# Comments? 

Comments?  Alternative suggestions?  Extra considerations to bear in mind?  

Got scenarios to share where you'd use this? (could inform development)

**Comment by SeanFarrow** [comment]
How would this work in the ExecuteAndCapture cases?
Also, I assume the Or<TResult> allows the user to specify that the fallback action should only execute if the TResult is not the expected one passed in? If yes, I'm hoping this could be a Func<TResult>.

**Comment by reisenberger** [comment]
@SeanFarrow Good catch - hadn't worked-through `ExecuteAndCapture()` in detail for this.

The intuitive implementation seems like:

+ The whole purpose of `FallbackPolicy` is to substitute the value/action from `fallbackFunc` if the governed `executionFunc` fails.  So if the governed `executionFunc` fails, `ExecuteAndCapture()` shouldn't step in and return a `PolicyResult` capturing `executionFunc`'s failure: the policy should invoke `fallbackFunc` and aim to substitute its outcome.

+ But the point of `ExecuteAndCapture()` is _never_ to fail on the handled faults (eg to avoid having to have another try-catch round the policy execution), so if `fallbackFunc` fails _with a handled fault_, then ExecuteAndCapture() should return that fault.

Does this sound like it makes sense?

---

I haven't quite followed your question about the `Or(...)`, but post a code example if it helps clarify.  If it helps:

+ `Handle<TResult>()` and `Or<TResult>` are treated in the codebase exactly as `Handle<TException>()` and `Or<TException>`, ie the values matched by `TResult`-predicates are treated as if faults.  So yes, if any `TResult`-predicate matched, the `fallbackFunc` would be executed.
+ `Handle<TResult>()` and `Or<TResult>` do already have `Func<TResult, bool>` overloads (was that the question?)

**Comment by SeanFarrow** [comment]
It does make sense, however, it would be nice to know if the governed func failed with ExecuteAndCapture and with what exception.

**Comment by mfjerome** [comment]
```
var result = Policy
  .Handle<Whatever>(...)
  .Fallback(() => throw new Exception2());
  .ExecuteAndCapture(() => throw new Exception1())
```
So if I understand correctly, in this case, the captured `PolicyResult` should contain information about `Exception2` as it is the final outcome of the policy execution. And I agree with this behaviour.

But what @SeanFarrow is saying is that we would lose  the original `Exception1`. One way or another, I also agree we need to be able to see and log the information of this fault.

Could it be the fallback responsability to actually perform some action about this original fault it is trying to cover/replace? Just thinking out loud.

**Comment by SeanFarrow** [comment]
Maybe, where the func being executed provides a result, we could do something similar to what ExecuteAndCapture already does and have a FallbackResult<TResult>, this could then contain an exception, or an Exceptions property detailing the faults, in order that led to the fallback being executed.

**Comment by reisenberger** [comment]
@mfjerome @SeanFarrow Great question from both of you, that I've kind-of answered [here](https://github.com/App-vNext/Polly/issues/140#issuecomment-232182080) . We could expose the `Exception1` in your example in several places:

[1] in the captured `PolicyResult` somehow (but complicated)
[2] (later) as part of an event stream
[3] in a simple `onFallback` delegate (perfect for logging)
[4] to the `fallbackFunc` as well 

In detail:

[1] `PolicyResult<TResult>` could contain an `IEnumerable<Exception>` property as @SeanFarrow says, that details other exceptions before the fallback (or anything else if part of a bigger wrap) was invoked.  A few issues I see with this as stated [here](https://github.com/App-vNext/Polly/issues/140#issuecomment-232182080): there may be duplicates, it's hard (in a broader wrap context) to connect which exception occurred with which policy-in-the-wrap, and it's actually quite hard to implement in the wrap unless I'm missing something (you kind-of want both-at-the-same-time to capture the exception into some `PolicyResult` you pass back to capture in the enumerable, but also throw the exception to outer layers at the same time so they can handle it ... you can't capture and throw at the same time??)

[2] Eventually we can capture all manner of policy behaviour as an event stream as suggested [here](https://github.com/App-vNext/Polly/issues/73#issuecomment-217643979) (but not soon).

[3] We offer an _additional_ overload taking a simple `onFallback` delegate, so:

```csharp
FallbackPolicy<TResult> fallbackPolicy = Policy
  .Handle<Whatever>(...)
  .Fallback<TResult>(Func<TResult> fallbackFunc, Action<DelegateResult<TResult>> onFallback); // for async variants, Func<DelegateResult<TResult>, Task> onFallbackAsync
```

This is my preferred option: simple, available now, and parallels the `onRetry` and `onBreak` delegates already well known to users on the retry and circuit-breaker policies.  The classic solution in Polly for logging faults as the policy operated.  Shall we go with this?

[4] A final option is to combine [3] with what @mfjerome suggested, ie offer the `DelegateResult` to the `fallbackFunc` too, ie offer additional overloads:


```csharp
FallbackPolicy<TResult> fallbackPolicy = Policy
  .Handle<Whatever>(...)
  .Fallback<TResult>(Func<DelegateResult<TResult>, TResult> fallbackFunc);
// and
FallbackPolicy<TResult> fallbackPolicy = Policy
  .Handle<Whatever>(...)
  .Fallback<TResult>(Func<DelegateResult<TResult>, TResult> fallbackFunc, Action<DelegateResult<TResult>> onFallback); // for async variants, Func<DelegateResult<TResult>, Task> onFallbackAsync
```

I'm not sure at the moment if this adds value (maybe somebody really wants to include details of the exception in the fallback value...), or just confusion (too many overloads).  Either way, I propose we keep [3].

**Comment by SeanFarrow** [comment]
3 sounds good and makes the most sense!

**Comment by mfjerome** [comment]
Agreed the idea will be uniform across policies such as  `onRetry`, `onBreak`, etc
