### ISSUE TITLE
Handle Exceptions based on Context

### ISSUE THREAD

**Issue by abc-moviestarplanet** [App-vNext/Polly#800]
**.NET Core 3.1**
**Polly 7.2.1**

**Summary: What are you wanting to achieve?**

I want a Circuit Breaker Policy, that handles `TaskCanceledException`, where the `CancellationToken` property is not equal to the token passed into the method.

I could pass the cancellation token to the Context object, but I would need to use that data inside the `Handle<TaskCanceledException>` method.

The issue is that, when an external service is down, we sometimes see a wave of TaskCanceledExceptions thrown by `System.Net.Http.ConnectHelper.ConnectAsync`. The only way I can distinguish that these exceptions are caused by a service outage or timeout, and not by a client request actually cancelling, is by checking if the cancellationToken in the exception is equal to the token passed into my method.

Are there ways of doing this that I'm missing?

**What code or approach do you have so far?**  

Currently, I cannot do this logic in the policy. So I am catching the exception manually - but then I cannot trigger the circuit breaker logic:

```csharp
public async Task MyFunction( CancellationToken token )
{
    try
    {
        return await policy.ExecuteAsync( .. );
    }
    catch (BrokenCircuitException)
    {
        ...
    }
    catch (TaskCanceledException e)
    {
        // cancelled likely due to timeout
        if ( e.CancellationToken != token)
        {
             // trigger circuit breaker logic here
        }
}
```

My policy declaration currently:

```csharp
var policy = Policy.Handle<HttpRequestException>()
                   .CircuitBreakerAsync( 10, TimeSpan.FromSeconds( 30 ) );
```

I wish I could do:
```csharp

var policy = Policy.Handle<HttpRequestException>()
                   .Or<TaskCanceledException>( (ex, context) => ex.CancellationToken != context["CancellationToken"] );
                   .CircuitBreakerAsync( 10, TimeSpan.FromSeconds( 30 ) );
```

Any help would be greatly appreciated.

(on a side note: It seems that netcore5 will be fixing this issue with a better exception)

**Comment by jpo-tu** [comment]
> It seems that netcore5 will be fixing this issue with a better exception

What does this mean?

**Comment by martincostello** [comment]
I believe they’re referring to this change that was made to the behaviour of `HttpClient` in .NET 5: https://github.com/dotnet/runtime/pull/2281

**Comment by abc-moviestarplanet** [comment]
> I believe they’re referring to this change that was made to the behaviour of `HttpClient` in .NET 5: [dotnet/runtime#2281](https://github.com/dotnet/runtime/pull/2281)

Yes that was what I was referring to - I should have linked it.

In any case, the solution to the issue is also to disable the default http client timeout (by setting it to `Timeout.InfiniteTimeSpan` and use the Polly timeout policy, which will throw a `TimeoutRejectedException`.
