### ISSUE TITLE
Passing a logger to all HttpClient requests

### ISSUE THREAD

**Issue by rmiller3** [App-vNext/Polly#802]
**Summary: What are you wanting to achieve?**
We're using a 3rd party library that has many APIs that wrap many http requests to their service.  We have a client wrapping their library.  I'd like to be able to test the polly http extensions on a mock client as well as configure polly by the test settings overrides. 
<br/>
<br/>

**What code or approach do you have so far?**  
When using the tips on the documentation here, there is a good example of setting up a polly policy on an http client, however you need to fully know the config during startup, before any tests can override it.   https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory#using-any-policy-configured-via-the-traditional-polly-syntax.

I the test overrides to work, but my team agrees that it is kind of a hack, and I haven't figured out how to use a mocked httpClientBuilder in a test that verifies polly was connected properly. 

```
services.AddSingleton(provider =>
            {
                var mySettings = provider.GetService<IOptions<MySettings>>().Value;

                // Required since the provider was updated in ConfigureMyHttpClient
                // Normally the policy and client configuration would take place just before
                // the "services.AddScoped<IMyClient, MyClient>();".  It was moved here to allow
                // test overrides as it wasn't apparent how else to update the httpClient.
                ConfigureSiftHttpClient(services, mySettings);
                IServiceProvider updatedProvider = services.BuildServiceProvider();

                var httpClientFactory = updatedProvider.GetService<IHttpClientFactory>();
                var httpClient = httpClientFactory.CreateClient(nameof(MyClient));

                return new Client(siftSettings.ApiKey, httpClient);
            });          

// Normally Polly init to HttpClientBuilder goes here

services.AddScoped<IMyClient, MyClient>();
```

I got it working and can even configure Polly using the test overrides this way, but it seems like a hack to have to re-obtain a serviceProvider in a delegate that takes a serviceProvider.  

Is there a better approach?  Any recommendations for how to test this using a mocked MyClient that still has Polly applied to it?  Thanks!

**Comment by martintmk** [comment]
@rmiller3 Polly v8 has built-in telemetry support and you can easily access `IServiceProvider` from any callback:
 
See this example:
https://github.com/App-vNext/Polly/blob/v8-fixed-issues/src/Polly.Extensions.Tests/Issues/IssuesTests.OnCircuitBreakWithServiceProvider_796.cs

This issue will be closed once v8 is released.

**Comment by martintmk** [comment]
The alpha is released, and you can try this out.

https://www.nuget.org/packages/Polly

Closing the issue.
