### ISSUE TITLE
Update system.net.http to 4.3.4 for dotnet.core 3

### ISSUE THREAD

**Issue by rjvkothari** [App-vNext/Polly#804]
**Summary**: 
Certain security vulnerabilities have been detected in 4.3.0 version of System.net.http 
<br/>
<br/>

**Expected behavior**: 
Version is set to 4.3.4
<br/>
<br/>

**Actual behaviour**:
version is on 4.3.0
<br/>
<br/>

**Steps / Code to reproduce the problem**: 

Best is a [complete example](https://stackoverflow.com/help/mcve) or failing unit test.  It is _always_ useful to see:

+ **code of any policy declarations**, 
+ **code of calls to `.Execute/AndCapture/Async(...)`**

**Comment by SimonCropp** [comment]
closing this since this project doesnt reference system.net.http.
