### ISSUE TITLE
How do I get the HttpRequestMessage for a request that threw an exception?

### ISSUE THREAD

**Issue by lesscodetxm** [App-vNext/Polly#805]
I have a retry policy configured and I want to log a warning-level message whenever a retry is triggered, with the message containing the Uri of the request that failed.

Seems easy enough with `WaitAndRetryAsync`, but the `onRetry` delegate takes a `DelegateResult<HttpResponseMessage>`, so it seems that the `Result` is only populated when the failed request actually returned a response (eg 500 InternalServerError). When a request eg times out or a connection is refused, there's no `Result` to inspect.

The `Context` passed to the delegate also doesn't seem to have any information about the request.

Am I missing something?

**Comment by martintmk** [comment]
If timeout or connection is refused there can be no response to inspect. It's not something that can be addressed in Polly. As an alternative you can catch those exceptions and as a fallback create a "dummy" response.

**Comment by lesscodetxm** [comment]
OK thanks - we started down the route of using `HttpRequestMessage.SetPolicyExecutionContext`, but since we're configuring retry policy via Asp.Net Core's `HttpClientFactory` mechanism, it meant changing thousands of call sites to add the context (and remembering to do so for every new call site). so we've delayed until we have time to rearchitect to abstract out a shared generic invocation service.
