### ISSUE TITLE
Why am I losing my DefaultRequestHeaders when Polly retries?

### ISSUE THREAD

**Issue by BretMishler** [App-vNext/Polly#809]
**Summary**: 

I have a Named Client with the `DefaultRequestHeaders` being added at configuration level, a Polly rety policy attached, and a custom DelegatingHandler appended. When stepping through the override in my custom delegate of `SendAsync`, my `DefaultRequestHeaders` are there. 

**Expected behavior**: 

1. WeatherService client calls GetAsync()
2. ValidateHeaderHandler delegates, calling `base.SendAsync(request, cancellationToken);`
3. Polly intercepts the HttpResponse, seeing the transient error
4. Polly retries
5. This retry calls ValidateHeaderHandler's base.SendAsync and all DefaultRequestHeaders from the original request are preserved

**Actual behavior**:

On step 5, no DefaultRequestHeaders added in configuration are preserved. We can confirm this in the ValidateHeaderHandler when it interrogates the request before sending it.

**Steps / Code to reproduce the problem**: 

**Startup.cs**
```
// In Configuration
IAsyncPolicy<HttpResponseMessage> retryPolicy = HttpPolicyExtensions
      .HandleTransientHttpError()
      .WaitAndRetryAsync(3, _ => TimeSpan.FromMilliseconds(1000));

services.AddTransient<ValidateHeaderHandler>();
services.AddHttpClient("WeatherService", client =>
{
    client.BaseAddress = new Uri("http://localhost:50264/");
    client.DefaultRequestHeaders.Add("Accept", "application/json");
    client.DefaultRequestHeaders.Add("Authorization", "abc");
})
    .AddPolicyHandler(retryPolicy)
    .AddHttpMessageHandler<ValidateHeaderHandler>();

```

**ValidateHeaderHandler.cs**
```
public class ValidateHeaderHandler : DelegatingHandler
    {
    public ValidateHeaderHandler() { }
    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
 {
        if (!request.Headers.Contains("Authorization"))
        {
            ... refresh the authorization token ...
        }
        return await base.SendAsync(request, cancellationToken);
        }
    }
```

**Comment by SimonCropp** [comment]
@BretMishler can you share minimal solution that reproduces this issue?
