### ISSUE TITLE
Document bulkhead queue default behaviour

### ISSUE THREAD

**Issue by matthias-schuchardt** [App-vNext/Polly#810]
**Is your feature request related to a specific problem? Or an existing feature? Please describe.**

I had a problem in understanding the default value of the queue-parameter of the bulkhead policy. I assumed that leaving it out would imply an infinite queue. However, just the opposite is the case. Without the queue-parameter set, it is [set to 0 per default](https://github.com/App-vNext/Polly/blob/d95959fe1449407603c8605282fbba97041fd026/src/Polly/Bulkhead/AsyncBulkheadSyntax.cs#L19) and thus load-shedding kicks in as soon as the `maxParallelization`-limit is reached.
<br/><br/>

**Describe your proposed or preferred solution**:

Can the default behaviour be documented in the xml-comments and the wiki of the bulkhead-policy more clearly? Especially the following points I would consider important.
- When leaving out the `maxQueuingActions`-parameter, it defaults to 0.
- This implies that an `BulkheadRejectedException` is thrown as soon as the limit set in `maxParallelization` is reached.
<br/><br/>

**Any additional info?**

This is not a deal breaker, but rather a speed bump when trying to understand how the bulkhead policy works. So one could also leave it as it is and have developers run into the exception.

**Comment by martintmk** [comment]
Hey @danbopes, Polly v8 now has built-in support for [System.Threading.RateLimiting](https://devblogs.microsoft.com/dotnet/announcing-rate-limiting-for-dotnet/) which has much better documentation and replaces the Bulkhead found in v7. 

https://github.com/App-vNext/Polly/tree/v8-fixed-issues/src/Polly.RateLimiting

This issue will be closed once v8 is released.

**Comment by martintmk** [comment]
Alpha released, please try the new `Polly.RateLimiting` package:

https://www.nuget.org/packages/Polly.RateLimiting/
