### ISSUE TITLE
Why PollyHttpClientBuilder extensions require IAsyncPolicy?

### ISSUE THREAD

**Issue by shagilt** [App-vNext/Polly#811]
**Summary**: 
We are using this policy extension method to add timeout policy - `AddPolicyHandler(this IHttpClientBuilder builder, Func<IServiceProvider, HttpRequestMessage, IAsyncPolicy<HttpResponseMessage>> policySelector)`

And my Function is doing something like this, NOTE: we don't have any async operation inside it
```
Policy.TimeoutAsync<HttpResponseMessage>(
                timeout: value,
                timeoutStrategy: TimeoutStrategy.Optimistic,
                onTimeoutAsync: async (context, timespan, task) =>
                {
                    // logging
                    // throw a specific error;
                });
```

**Question:** Why all AddPolicyHandler extensions **require** IAsyncPolicy? Why cant I use ISyncPolicy? With my above example, I just need to log when timeout happen.
<br/>
<br/>
\

**Comment by martincostello** [comment]
`HttpClient` is fundamentally async (the `SendAsync` method does the requests), so sync policies wouldn't work correctly.

**Comment by shagilt** [comment]
Thanks. Yes, I saw policy's ExecuteAsync() invocation inside  PolicyHttpMessageHandler.cs
