### ISSUE TITLE
Read HealthCount of Circuit Breaker

### ISSUE THREAD

**Issue by kaiohenrique** [App-vNext/Polly#825]
Any time in future will HealthCount be public for reading (for monitoring purposes)? 

https://github.com/App-vNext/Polly/blob/master/src/Polly/CircuitBreaker/HealthCount.cs

**Comment by martincostello** [comment]
Duplicate of #647.

See here for more information: https://github.com/App-vNext/Polly/issues/647#issuecomment-497938998
