### ISSUE TITLE
Documentation references to unresolvable domains

### ISSUE THREAD

**Issue by babackman** [App-vNext/Polly#826]
**Is your feature request related to a specific problem? Or an existing feature? Please describe.**
The wiki contains references to www.thepollyproject.org and www.pollytalk.org, neither of which are currently DNS-resolvable.
<br/><br/>
**Describe your proposed or preferred solution**:
Fix the sites above so they resolve again, or update the links in the wiki to point to the replacements for those sites.
<br/><br/>

**Describe any alternative options you've considered**:
Remove the links from the wiki.

**Comment by joelhulen** [comment]
@babackman thank you for raising this issue. The DNS host somehow cleared all the DNS settings for these two domains. I have now fixed this issue.
