### ISSUE TITLE
Retry Just That Line

### ISSUE THREAD

**Issue by ayseff** [App-vNext/Polly#827]
I have a codeset which involves complicated interaction with another application.  It is bug-free but due to the indeterminate nature of the circumstance the code always fails at some point.  Retrying a second or two later always solves the issue.  Thus, the resilience which I need is a simple wait and retry.

The problem is that the code can fail at at point, arbitrarily, making hard to figure out how to arrange the resilience.  For example, when I wrap only one given line of code in an RetryPolicy.Execute or ExecuteAndCapture, Polly is successful at handling the error and retyring, but then a different line may fail.  Theoretically, I can wrap each and every line of code in its own Retry, but that would make the code highly unmaintainable and unreadable.  Conversely, if I wrap the entire code in one big retry, then the error would in fact be caught successfully.  However, the retry would then set the executing statement to the first line in the block, effectively rerunning lines of code which already run successfully, which should not be re-run.

Is there any way to create a block of code, and say something to the effect of:  If any line of code fails within this block, wait, and rerun, starting only from the point of failure and onward?

**Comment by SimonCropp** [comment]
@ayseff i dont think this is possible. essentially u want something similar to "on error resume next" from VB, but "on error retry. dotnet doesnt support this.

Will close this one for now
