### ISSUE TITLE
The Polly Website is Not Reachable

### ISSUE THREAD

**Issue by andrewlock** [App-vNext/Polly#831]
**Summary**: 

The Polly website (www.thepollyproject.org) is not reachable

**Expected behavior**: 

The website should be reachable

**Actual behaviour**:

The site can't be reached. The domain does not appear to exist

![image](https://user-images.githubusercontent.com/18755388/107873028-212b1f00-6ea7-11eb-8ef2-62f03f45455d.png)

**Steps / Code to reproduce the problem**: 

Visit http://www.thepollyproject.org/ in the browser

**Comment by martincostello** [comment]
Duplicate of #826.

This is something we're aware of, but we need the person who owns the domain to fix it for us.

**Comment by andrewlock** [comment]
Ah ok, didn't find that in my searching, as long as you're aware!
