### ISSUE TITLE
The result will not display when you are using Polly

### ISSUE THREAD

**Issue by jt4000** [App-vNext/Polly#838]
Goal:  
Show the message "show error" after 3 attempt.

Problem:  
What part of the code do not work in order to achieve the goal.

Other:
*Using asp.net core 3.1, VS 2019

+ **code of any policy declarations**, 

`using Polly;
using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace ConsolePollyTest2
{
    class Program
    {
        static void Main(string[] args)
        {
            var maxRetryAttempts = 3;
            var pauseBetweenFailures = TimeSpan.FromSeconds(2);

            Policy
                .Handle<HttpRequestException>()
                .Or<TaskCanceledException>()
                .WaitAndRetryAsync(maxRetryAttempts, i => pauseBetweenFailures)
                .ExecuteAsync(PersistApplicationData2)
                .ContinueWith(x =>
                {
                    if (x.Exception != null)
                    {
                        Console.WriteLine("show error");

                    }
                });
        }

        private static async Task PersistApplicationData2()
        {
            int ddfd = 3;
            var df = ddfd / 0;

            Console.WriteLine("Show data");
            await Task.FromResult<object>(null);
        }

    }
}`

**Comment by martincostello** [comment]
Your code isn't very well formatted, but it _seems_ like you aren't actually awaiting your asynchronous operation, which means no code ever runs and the program will just exit.

Change your Main method declaration to `static async Task Main(string[] args)` and then await the policy `await Policy`.

If that's what you're describing, that that should solve your problem - if it isn't, then please explain in more detail so we can understand and try to help you further.

**Comment by joelhulen** [comment]
@jt4000, were you able to try what Martin suggested? We will close this issue if we don't hear back from you within a few days.

**Comment by SimonCropp** [comment]
time to close?
