### ISSUE TITLE
Reintroduce SleepDurationProvider DelegateResult<TREsult> overload on WaitAndRetryAsync

### ISSUE THREAD

**Issue by esbenbach** [App-vNext/Polly#840]
**Is your feature request related to a specific problem? Or an existing feature? Please describe.**

I am trying to handle HTTP 429 as discussed in #414 - specifically using the sleepdurationprovider overload that takes `DelegateResult<TResult>` as an input. 

It seems like this used to exist: https://github.com/App-vNext/Polly/blob/9c133b6303ca70d2879fddf16fb201c209eb6fd2/src/Polly.Shared/Retry/RetryTResultSyntaxAsync.cs#L615

It "seems" to exist on `WaitAndRetryForeverAsync` - but i don't want to wait forever :)

**Describe your proposed or preferred solution**:

Add a new overload that allows me to examine the result in the sleepdurationprovider :)

**Describe any alternative options you've considered**:

My workaround is to "hack" it by placing the wait logic inside the `onRetry`

**Comment by martincostello** [comment]
Which version of Polly are you using?

This method still exists in the latest release, it's just that the return type is different for async policies now.

https://github.com/App-vNext/Polly/blob/52968c25f2e13e2708898174c15aafc9cb915020/src/Polly/Retry/AsyncRetryTResultSyntax.cs#L652-L653

**Comment by esbenbach** [comment]
I am running on polly 7.1.0. Tried upgrading to 7.2.2. Which does seem to have the mentioned overload. Not really sure why I didnt try that before.

I guess we can just close this again :)
