### ISSUE TITLE
Project Abandoned

### ISSUE THREAD

**Issue by jmanico** [App-vNext/Polly#841]
There have been no commits since May 2020 and this project seems abandoned. Is there a new repot you moved to or is there other work being done?

**Comment by martincostello** [comment]
Hi - if you look at the [`v722-or-v730`](https://github.com/App-vNext/Polly/tree/v722-or-v730) branch you'll see that there are still things being done, as well as some issues (like this one) being replied to.

Free time to work on it at the moment is a lot less though for various reasons.
