### ISSUE TITLE
Flowing the Context Object....

### ISSUE THREAD

**Issue by kabua** [App-vNext/Polly#849]
**Summary**: 
Trying to pass a logger throughout the policy but can't because the context object isn't 100% supported throughout all the calls.
For example: `Handle<T>` and the  `OrResult`,  doesn't support the context object.

**Expected behavior**: 
We expect the context object to flow through the entire policy structure.

**Actual behaviour**:
The context object **does not** flow through the entire policy structure, as suggested in the documentation.

**Comment by martintmk** [comment]
@kabua 

This issue is fixed in v8 where all callbacks and predicates receive the context object and you can use them.

See example:
https://github.com/App-vNext/Polly/blob/v8-fixed-issues/src/Polly.Core.Tests/Issues/IssuesTests.FlowingContext_849.cs

**Comment by martintmk** [comment]
The alpha is released, and you can try this out.

https://www.nuget.org/packages/Polly

Closing the issue.
