### ISSUE TITLE
Use Polly for rate-limiting the HttpClient

### ISSUE THREAD

**Issue by dlidstrom** [App-vNext/Polly#851]
**Summary: What are you wanting to achieve?**

I am a new user of Polly and I've successfully used a few of the policies (timeout, circuitbreaker, retry). Now, I have a need to try to rate limit on the client end, and I'd like to fit this in with the policies I have in place. Is there a way to rate limit on the client end?

**What code or approach do you have so far?**  

My approach has been to used a custom DelegatingHandler, as such: https://github.com/dlidstrom/Snittlistan/blob/master/Snittlistan.Web/Infrastructure/RateHandler.cs
I can continue that approach but first I'd like to know if this can be handled within Polly?

**Comment by martincostello** [comment]
Rate limiting is not currently supported.

There is an open draft Pull Request #666 to add it in a future version.

**Comment by dlidstrom** [comment]
Thanks @martincostello !
