### ISSUE TITLE
Polly Attribute

### ISSUE THREAD

**Issue by eaba** [App-vNext/Polly#87]
For a large project PollyAttribute could be very handy!

**Comment by reisenberger** [comment]
@eaba How would you like to see such an attribute used?  

You may also be interested to know that Brighter is already adopting an attribute-based approach with Polly, to apply policies.  See: http://iancooper.github.io/Paramore/PolicyRetryAndCircuitBreaker.html
(I haven't evaluated this implementation in detail, but there is much interesting-looking material within Brighter, including the ability to apply policies within a pipeline)

**Comment by reisenberger** [comment]
Closing due to no further community comment/request for 2 years.

Anyone please reopen if further interest in or ideas for an attribute-based approach to applying policies.
