### ISSUE TITLE
Is there a way to overwrite existing cache belongs to a context in Polly cache?

### ISSUE THREAD

**Issue by piyumi25** [App-vNext/Polly#873]
**Summary: What are you wanting to achieve?**
I am new to Polly and I am using Polly to save response from API call. I am using .net standard library project. I am able to save cache. But I need to overwrite cache item after any update occurred to that resource.

**What code or approach do you have so far?**  
This is how I configured for polly caching.
```
services.AddMemoryCache();
			services.AddSingleton<IAsyncCacheProvider, MemoryCacheProvider>();
			services.AddSingleton<IReadOnlyPolicyRegistry<string>, Polly.Registry.PolicyRegistry>((serviceProvider) =>
			{
				var registry = new PolicyRegistry();
				registry.Add("exchangeCachePolicy",
					Policy.CacheAsync(
						serviceProvider
							.GetRequiredService<IAsyncCacheProvider>()
							.AsyncFor<List<OutlookCategory>>(),
						new SlidingTtl(TimeSpan.FromMinutes(5))));
				return registry;
			});
```
I used following code to read from cache

```
var existingMasterCategories =  await _policyRegistry.Get<IAsyncPolicy<List<OutlookCategory>>>("exchangeCachePolicy")
													.ExecuteAsync(async context => await GetMasterCategoriesAsync(exchangeUserId), new Context($"GetOutlookMasterCategories-{exchangeUserId}"));
```
It is _always_ useful to see:

+ **code of any policy declarations**, 
+ **code of the calls to `.Execute/AndCapture/Async(...)`**

**Comment by martincostello** [comment]
From a quick look at the code, seems like you'd want to resolve `IAsyncCacheProvider` from your IoC container when you want to do an update, and then use the `PutAsync` method to update what's in the cache based on your specific requirements:

https://github.com/App-vNext/Polly/blob/509b34f6964c400a8abd836b0821fb3295b3b2e5/src/Polly/Caching/IAsyncCacheProvider.cs#L33

**Comment by piyumi25** [comment]
> From a quick look at the code, seems like you'd want to resolve `IAsyncCacheProvider` from your IoC container when you want to do an update, and then use the `PutAsync` method to update what's in the cache based on your specific requirements:
> 
> https://github.com/App-vNext/Polly/blob/509b34f6964c400a8abd836b0821fb3295b3b2e5/src/Polly/Caching/IAsyncCacheProvider.cs#L33

@martincostello I am not much clear about what you said, is there any sample code to refer?

**Comment by martincostello** [comment]
Not that I'm aware of. I mean something like this:

```csharp
public class MyThingThatUpdatesTheCache
{
    private readonly IAsyncCacheProvider _cacheProvider;

    public MyThingThatUpdatesTheCache(IAsyncCacheProvider cacheProvider)
    {
        _cacheProvider = cacheProvider;
    }

    public async Task MethodThatICallWhenIWantToUpdateTheCacheAsync(
        List<OutlookCategory> value,
        CancellationToken cancellationToken)
    {
        await _cacheProvider.PutAsync(
            "exchangeCachePolicy",
            value,
            new SlidingTtl(TimeSpan.FromMinutes(5)),
            cancellationToken,
            false); // Not sure whether this should be false or true
    }
}
```

**Comment by piyumi25** [comment]
Thanks @martincostello  , I will try for this.

**Comment by piyumi25** [comment]
@michael-wolfenden I tried to use but I got following error
`cannot convert from Polly.Caching.SlidingTtl to Polly.Caching.Ttl`
according to method signature it is expectiong Ttl
`Task PutAsync(string key, object value, Ttl ttl, CancellationToken cancellationToken, bool continueOnCapturedContext)`
Can I have an idea about "continueOnCapturedContext"?

**Comment by martincostello** [comment]
Then just change it to an appropriate type - I wrote the snippet by hand in the GitHub comment editor and copy-pasted it from your example of configuring the policy.

Regarding `continueOnCapturedContext`, I don't know which one is preferred without digging into the code, hence the comment in the example.

**Comment by piyumi25** [comment]
@martincostello  So How this will update the details related to context, because PutAsync there is no context specified.I tried and cache will not updated when I retrieving next time.

**Comment by martincostello** [comment]
I don't know without investigating how the code works myself. You'd have to see how the Polly context etc. gets turned into the cache key, and then just make sure the cache keys match.

The implementation (I assume) you're using is here: https://github.com/App-vNext/Polly.Caching.MemoryCache/blob/master/src/Polly.Caching.Memory/MemoryCacheProvider.cs

**Comment by piyumi25** [comment]
```
var messageWithCategory = new Message();
				var outlookCategoryColor = (CategoryColor)Enum.Parse(typeof(CategoryColor), categoryColor);

				// check for master categories in polly cache and get it, else call GetMasterCategoriesAsync()
				var existingMasterCategories =  await _policyRegistry.Get<IAsyncPolicy<List<OutlookCategory>>>("exchangeCachePolicy")
													.ExecuteAsync(async context => await GetMasterCategoriesAsync(exchangeUserId), new Context($"GetOutlookMasterCategories-{exchangeUserId}"));

				var a3SyncCategory = existingMasterCategories.FirstOrDefault(x => x.DisplayName.Equals(categoryName, StringComparison.InvariantCultureIgnoreCase));
				
				if (a3SyncCategory == null)
				{
					// create master category
					a3SyncCategory = await CreateMasterCategoryAsync(exchangeUserId, categoryName, outlookCategoryColor);
					//update cache
				}
				else
				{
					//check if category has same color
					if (!a3SyncCategory.Color.Value.Equals(outlookCategoryColor))
					{
						//update category color
						a3SyncCategory = await UpdateMasterCategoryAsync(exchangeUserId,a3SyncCategory.Id, categoryName, outlookCategoryColor);
						//update cache
						var cancellationToken = new CancellationToken();
						var updatedMasterCategories = await GetMasterCategoriesAsync(exchangeUserId);
						await _cacheProvider.PutAsync(
								"exchangeCachePolicy",
								updatedMasterCategories,
								new Ttl(TimeSpan.FromMinutes(5)),
								cancellationToken,
								true);
					}
				}
```
Above is the part of the method I am using to integrate with polly cache
