### ISSUE TITLE
CircuitBreakerPolicy Throws on First Exception When Using Execute

### ISSUE THREAD

**Issue by mattrhoden** [App-vNext/Polly#875]
**Summary**: 
I am testing out the circuit breaker policy for use in our production system and am finding that it does not wait for a consecutive number of exceptions before throwing. 

I would like to log each exception and continue on. If there are 3 consecutive exceptions, then open the circuit and escalate. 

**Expected behavior**: 

Synchronous order of events:
1. Execute, throw new TimeoutException
2. Error is logged and continue.
3. Execute, throw new ArgumentNullException
4. Error is logged and continue.
5. Execute, throw new ArgumentOutOfRangeException
6. Error is logged and continue.
7. Execute, throw new Exception
8. Circuit is now open, exception is re-thrown.

**Actual behaviour**:

1. Execute, throw new TimeoutException
2. Circuit is now open, exception is re-thrown.

**Steps / Code to reproduce the problem**: 
Using this code in a console application should reproduce the issue at hand:

```csharp
namespace PolyTestProject
{
    class Program
    {
        static void Main(string[] args)
        {
            CircuitBreakerBug();
        }
        
        static void CircuitBreakerBug()
        {
            try
            {
                var circuitBreakerPolicy = Policy
                    .Handle<TimeoutException>()
                    .CircuitBreaker(3, TimeSpan.FromSeconds(1), (exception, span) =>
                    {
                        var current = Console.ForegroundColor;
                        Console.ForegroundColor = ConsoleColor.Cyan;
                        Console.WriteLine("Why do we fall sir? So that we can learn to pick ourselves up.");
                        Console.WriteLine(exception);
                        Console.ForegroundColor = current;
                    }, () => Console.WriteLine("Resetting!"));
                
                circuitBreakerPolicy.Execute(() =>
                {
                    Console.WriteLine("Executing TimeoutException type.");
                    throw new TimeoutException("Too long!",
                        new HttpRequestException("Inner Exception!"));
                });

                circuitBreakerPolicy.Execute(() =>
                {
                    Console.WriteLine("Executing ArgumentNullException type.");
                    throw new ArgumentNullException("name",
                        new HttpRequestException("Inner Exception!"));
                });
                
                circuitBreakerPolicy.Execute(() =>
                {
                    Console.WriteLine("Executing ArgumentOutOfRangeException type.");
                    throw new ArgumentOutOfRangeException("Shouldn't be like this!",
                        new HttpRequestException("Inner Exception!"));
                });
                
                circuitBreakerPolicy.Execute(() =>
                {
                    Console.WriteLine("Executing exception type.");
                    throw new Exception("Exception!",
                        new HttpRequestException("Inner Exception!"));
                });
            }
            catch (Exception e)
            {
                var current = Console.ForegroundColor;
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine(e);
                Console.ForegroundColor = current;
            }

            Console.WriteLine("Done!");
        }
    }
}
```

Console output:

```shell
Executing TimeoutException type.
System.TimeoutException: Too long!
 ---> System.Net.Http.HttpRequestException: Inner Exception!
   --- End of inner exception stack trace ---
   at PolyTestProject.Program.<>c.<CircuitBreakerBug>b__2_2() in /Users/matt.rhoden/Projects/PolyTestProject/PolyTestProject/Program.cs:line 76
   at Polly.Policy.<>c__DisplayClass108_0.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token)
   at Polly.CircuitBreaker.CircuitBreakerPolicy.<>c__DisplayClass8_0`1.<Implementation>b__0(Context ctx, CancellationToken ct)
   at Polly.CircuitBreaker.CircuitBreakerEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, ICircuitController`1 breakerController)
   at Polly.CircuitBreaker.CircuitBreakerPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Implementation(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute(Action action)
   at PolyTestProject.Program.CircuitBreakerBug() in /Users/matt.rhoden/Projects/PolyTestProject/PolyTestProject/Program.cs:line 73
Done!
```

I might have the number of exceptions off by one, inclusive vs exclusive. However it doesn't seem to get past the first one before raising. If I use `ExecuteAndCapture`, this will return a result with the exception attached to it. However it's still not breaking after 3 times and seems like the less ideal result.

**Comment by mattrhoden** [comment]
I should note that I am using the latest release of Polly v7.2.2

**Comment by martincostello** [comment]
There's two issues with your code here that explain the behaviour you're observing vs. what you expect.

1. A circuit breaker policy does not retry. For retries, you would use a [retry policy](https://github.com/App-vNext/Polly#retry). A [circuit breaker](https://github.com/App-vNext/Polly#circuit-breaker) policy will throw any exception observed out to the caller _unless_ the circuit breaks - at which point it throws `BrokenCircuitException`. This is why your code fails at the first step, because the code it is executing throws an exception. With enough failures, the circuit breaker would bypass the delegate you pass to `Execute()`, and just throw `BrokenCircuitException`.
2. Your policy only handles `TimeoutException`, so even if it behaved as you expected, it wouldn't retry or circuit break for any of the other cases because they do not throw `TimeoutException` (or an exception derived from it), so would throw the exception to the calling method and not trigger any circuit breaking behaviour.

From your sample, it seems like you want to use a [policy wrap](https://github.com/App-vNext/Polly#policywrap) composed of a retry policy wrapped with a circuit breaker that stops all calls if too many calls fail.

**Comment by mattrhoden** [comment]
I was trying out different exception types, sorry that made it more confusing. I am not attempting to re-try, actually what I am doing is trying to process messages in a queue. If too many messages in the queue are raising exceptions I would like to stop processing all together. This is to prevent messing up several thousand messages and having to manually fix them. 

I carefully re-read the documentation with your notes in mind. There's still one part I'm not understanding. 

If I re-write the example above, incorporate your feedback, and make it a little more concise; it would look like this:
```csharp
using System;
using System.Net.Http;
using Polly;
using Polly.CircuitBreaker;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading;

namespace PolyTestProject
{
    class Program
    {
        static void Main(string[] args)
        {
            CircuitBreakerExample();
        }

        static void CircuitBreakerExample()
        {
            try
            {
                var circuitBreakerPolicy = Policy
                    .Handle<Exception>()
                    .CircuitBreaker(3, TimeSpan.FromSeconds(5), (exception, span) =>
                    {
                        Console.WriteLine($"Circuit broken: `{exception.Message}`");
                    }, () =>
                    {
                        Console.WriteLine("Resetting circuit.");
                    });

                var messagesFromQueue = new[]
                {
                    1, 2, 3, 4
                }.Select(n => new {id = n});
                var count = 0;

                foreach (var message in messagesFromQueue)
                {
                    try
                    {
                        count++;
                        circuitBreakerPolicy.Execute(() =>
                        {
                            Console.WriteLine($"Begin processing message: {message.id}");
                            throw new Exception("Serious failure to process message.");
                        });
                    }
                    catch (BrokenCircuitException) // Circuit breaker is warning us, let's stop here.
                    {
                        Console.WriteLine($"Broken circuit exception on attempt number {count}");
                        throw;
                    }
                    catch (Exception e) // Prevent exceptions, from message processing, from bubbling up.
                    {
                        Console.WriteLine($"Error, message {e.Message}");
                        if(count == 3)
                            Thread.Sleep(TimeSpan.FromSeconds(6)); // Attempt to wait out the break timespan.
                    }
                }
            }
            catch (BrokenCircuitException e) 
            {
                // Change the color so it's obvious I am at the "highest" level.
                var current = Console.ForegroundColor;
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine(e);
                Console.ForegroundColor = current;
            }

            Console.WriteLine("Done!");
        }
    }
}
```

Here's what the output looks like:

```
Begin processing message: 1
Error, message Serious failure to process message.
Begin processing message: 2
Error, message Serious failure to process message.
Begin processing message: 3
Circuit broken: `Serious failure to process message.`
Error, message Serious failure to process message.
Begin processing message: 4
Circuit broken: `Serious failure to process message.`
Error, message Serious failure to process message.
Done!
```

I might be miss-understanding, but I assumed that the try catch and timeouts I'm supplying around the execute were supposed to be what the policy does. I am not sure what other policy I could combine with this. It's not a parallel execution type of problem. These messages are executed one after the other in a serial fashion. 

Maybe I'm over thinking this and the simple try catch with count is all I need. :)

**Comment by mattrhoden** [comment]
@martincostello I thought I would follow up. Is there another policy I can wrap this with to avoid doing the try/catch and timeout's myself? Thanks for your help!

**Comment by martincostello** [comment]
You would typically use a [PolicyWrap](https://github.com/App-vNext/Polly#policywrap) to combine different policies together.

**Comment by mattrhoden** [comment]
I guess there's no option and circuit breaker just wasn't meant for this scenario. Thanks anyway.
