### ISSUE TITLE
Introduce Hedging Strategy

### ISSUE THREAD

**Issue by laura-mi** [App-vNext/Polly#876]
We are working on the development of a generic `HedgingPolicy` to use as part of our `HttpClient` Resilience pipeline.
Since the hedging as a policy is not yet supported by Polly we consider setting up a new package dedicated to the generic implementation of such policy. Please let us know if you are interested in having this and how we could proceed further.

*Summary*
The hedging policy will allow the sequential and delayed execution of a set of tasks, until one of them completes successfully or until all of them are completed. 
First task that is successfully completed triggers the cancellation and disposal of all other tasks and/or adjacent allocated resources. 

General structure of polly policy:
- The `Async<PolicyName>Syntax` exposes extension method for the `PolicyBuilder` which builds new instances of the `Async<PolicyName>`:
   - e.g. for Hedging: `AsyncHedgingSyntax` exposes methods to create `AsyncHedgingPolicy` instances.
- The generic `Async<PolicyName>Policy` is the actual policy, which:
  - Inherits the `AsyncPolicy<TResult>` base class
  - Exposes internal constructor and it is created only via the  `Async<PolicyName>Syntax` extensions.
  - Implements the abstract method of the base class, ` Async<PolicyName>Syntax` which contains the actual implementation, i.e.
    ```
    Task<TResult> ImplementationAsync(
        Func<Context, CancellationToken, Task<TResult>> action,
        Context context, 
        CancellationToken cancellationToken,
        bool continueOnCapturedContext)
    ```
    - e.g. for Hedging: `AsyncHedgingPolicy`
________________________________________________________________________________

## Hedging policy configuration
The base implementation will take:
- `HedgingDelay` - how long shall one wait before spawning a new hedged request;
- `OnHedgingAsync` - task performed after every spawning a hedged request; [can be used for logging & telemetry]
- A list of `hedgedTaskFunctions` - the tasks performed via hedging if the primary execution delegate fails.

____________________________________________________________________________
## Hedging logic
Steps:
1. Start executing task [first one first] 
2. Wait up to HedgingDelay ms 
3. If the request is: 
  - A. Completed: 
    - If result is an exception 
      - If ShouldHandleException - GOTO [B] 
      - else - GOTO [4.] 
    - If result is not exception 
      - If ShouldHandleResult - GOTO [B] 
      - else - GOTO [4.] (e.g. result is successful, so return result).
  - B. Not Completed: 
    - Next task will be executed - GOTO [1.] 

4. The result of the execution can be: 
  - [Success]
    - First request to complete successfully triggers the cancellation of all others
    - Return successful result.
  - [Failure]
    - No request completed successfully, and all requests have been executed. 
    - Return the failure of the first task. 
____________________________________________________________________________

## Exposed API for policy creation:
```
 var hedgingPolicy = Policy
                .Handle<Exception>()
                .OrResult<string>(_ => false)
                .AsyncHedgingPolicy(
                    hedgedTaskFunctions,
                    defaultHedgingDelay,
                    onHedgingAsync);

```

**Comment by martincostello** [comment]
Sorry for the delayed reply.

This sounds interesting, but at this time I don't think this is something we'd have the bandwidth to add to a shipping version of Polly any time soon, but does sound like a candidate for something over in https://github.com/Polly-Contrib.

I don't know what the policies etc. are for dealing with that, I don't have access to that.

Maybe @joelhulen, @DreamOfTheRedChamber, @mebjas or @vany0114 could help you out.

**Comment by joelhulen** [comment]
I also apologize for the late reply. I just saw this issue.

I can help you get up and running under Polly-Contrib, which is our officially recognized community projects that extend Polly's core functionality. Any Polly.Contrib NuGet packages are recognized as part of the Polly organization as well. Please reach out to me at joelhulen at gmail.com

Thanks!

**Comment by alexhcheng** [comment]
@joelhulen : sent you an email, we are interested in this feature as well and can contribute.

**Comment by laura-mi** [comment]
@joelhulen I sent you an email last month, not sure if you got it. Please let me know :).

**Comment by joelhulen** [comment]
I have created a new repo generically for Hedging vs. the more specific RequestHedging I had previously created (and archived). @laura-mi, I've added you as an admin to this repo: https://github.com/Polly-Contrib/Polly.Contrib.Hedging per your request.

**Comment by juraj-blazek** [comment]
Since the hedging strategy will be implemented by us as maintainers and it doesn't have any additional dependencies, we were discussing to include hedging directly in the new `Polly.Core` package. We wouldn't need to setup all the build and test infra and it will also simplify future maintenance.
@joelhulen, @martincostello, @laura-mi any objections?

**Comment by martincostello** [comment]
No objections from me.

**Comment by joelhulen** [comment]
I have no objections, either. In fact, I find that any contrib project migrating to core is a win :)

**Comment by martintmk** [comment]
The hedging will be adopted directly in `Polly.Core` for V8. The API will be adjusted to conform to v8 shape. 

- Options based
- Hedging extensions for `ResilienceStrategyBuilder`

**Comment by johnib** [comment]
> The hedging will be adopted directly in `Polly.Core` for V8. The API will be adjusted to conform to v8 shape.
> 
> * Options based
> * Hedging extensions for `ResilienceStrategyBuilder`

Is it still possible to use the Contrib.Hedging nuget somehow? I recall it had the ability to issue the hedging request if the duration crossed the duration of some percentile.

I.e. the hedging policy would record what is the pXX and use it as the threshold for issuing the hedging request.

I don't see this in the v8 docs anymore.

Thank you !

**Comment by martintmk** [comment]
I don't think there is any hedging available for Polly V7.
It was considered but never published.

**Comment by johnib** [comment]
> I don't think there is any hedging available for Polly V7. It was considered but never published.

are you sure? I remember a repo `Polly.Contrib.Hedging`, which is actually mentioned here, and I recall the code was implemented there, long before Polly 8 was released.

Is it possible to get access this code somehow?

**Comment by martincostello** [comment]
The repo is here, and it's been archived: https://github.com/Polly-Contrib/Polly.Contrib.RequestHedging

The contrib stuff is maintained independently from the core Polly library.
