### ISSUE TITLE
Tag release revisions

### ISSUE THREAD

**Issue by TrevorPilley** [App-vNext/Polly#88]
Are you able to tag releases so that we can easily diff the changes between versions?

There isn't an easy way for me to see what's new between 3.0 and 4.0 except the comments in the nuget package but it would be useful to be able to see what has actually changed in the library code wise to see if there are changes to anything I use.

**Comment by joelhulen** [comment]
@TrevorPilley I'll look into doing this. It is a very good suggestion.

**Comment by reisenberger** [comment]
Agree @TrevorPilley @joelhulen great idea!

**Comment by reisenberger** [comment]
In the meantime, @TrevorPilley , here's a github compare view which shows the differences between v3.0 and v4.0: https://github.com/app-vnext/polly/compare/86f887ed1bd53743086fbc3dd70ab9fd578630fc...cd3434467ca4639141b6f2088dae7c5ba25977e9
(not as good a reading experience as it could be, given the [necessary] file renames, and the highly repetitive content of the syntax classes)

Let us know if you think there are further ways we can support explaining new features.  The intent so far has been to stick to the original, concise documentation in the readme (see the changes there - they should cover everything).  However, given the new layers of functionality in the circuit-breaker, we'd like (given time) to blog about them more fully on the wiki next week.

**Comment by joelhulen** [comment]
@TrevorPilley @reisenberger For now, I've tagged the closed PRs that contributed to both version 3.0 and 4.0. You can view them by looking at [the closed PR list](https://github.com/App-vNext/Polly/pulls?q=is%3Apr+is%3Aclosed) and see the v3.0.0 or v4.0.0 milestone next to each PR name (or the details within if you open it).

Does this suffice? Is there a need to tag minor versions as well, or just major versions, like 3.0 and 4.0?

**Comment by reisenberger** [comment]
@joelhulen I'm all for tagging minor vers too, if we can just make it part of our workflow.

**Comment by TrevorPilley** [comment]
@joelhulen I tend to tag every release, even if it's a 1 liner defect fix and then turn that tag into a github release with a link to diff against the previous version. It's a small amount of effort each time but I think it gives a good experience to anyone who wants to know what's changed and what the potential impact may be of updating a package which can still be a concern even if people follow semver

**Comment by reisenberger** [comment]
@TrevorPilley Thanks for this great suggestion.  Closing this issue now, as we are adopting your suggestion going forward (tho feel free to remind us if we forget! :smiley: )
