### ISSUE TITLE
Context values change unexpectedly

### ISSUE THREAD

**Issue by thornfish9** [App-vNext/Polly#890]
**Summary**: 
Values stored in the context in the onRetry function are not present after the retried delegate function executes for the last time

**Expected behavior**: 
Values stored in the Polly.Context by code in the OnRetry func of a Policy should still be present after delegate function executes for the last time

**Actual behaviour**:
Values stored in the Polly .Context are available up until the time that the delegate function returns for the last time. Then they disappear.

**Steps / Code to reproduce the problem**: 
The following xUnit test fails, demonstrating the problem and a workaround

[Fact]
		private async Task IsolatedPollyContextProblem()
		{
			// Demonstrate that a dictionary wrapped in a Polly.Context item successfully preserves values changed in the policy.WaitXX.onRetry
			const string KeyInnerDictionary = "KeyInnerDictionary";
			const string KeyTimesRetried = "KeyTimesRetried";
			const int TimesRetriedInitialValue = 100;
			var innerDictionary = new Dictionary<string, object>() { { KeyTimesRetried, 100 } };
			var outerContext = new Context() { { KeyInnerDictionary, innerDictionary } };

			await Policy
				.HandleResult<bool>(r => r)
				.WaitAndRetryAsync(
					retryCount: 1,
					sleepDurationProvider: (num) => TimeSpan.FromMilliseconds(100),
					onRetry: (outcome, retryNumber, context) =>
					{
						var innerDictionary = (Dictionary<string, object>)context[KeyInnerDictionary]; // unwrap the inner dictionary from the outer Polly.Context
						int timesRetried = (int)innerDictionary[KeyTimesRetried];
						timesRetried++;
						innerDictionary[KeyTimesRetried] = timesRetried;
						context[KeyTimesRetried] = timesRetried;
					}
				)
				.ExecuteAsync(
					contextData: outerContext,
					action: async (c) =>
					{
						await Task.CompletedTask;
						return true;
					}
				);

			// the wrapped value returns the correct result, but the value stored directly in the Polly Context is not retained
			var expectedValue = TimesRetriedInitialValue + 1;
			Assert.Equal(expectedValue, innerDictionary[KeyTimesRetried]);
			Assert.Equal(expectedValue, outerContext[KeyTimesRetried]); // this test fails
		}

**Comment by thornfish9** [comment]
As shown in the failing xUnit test above, I have worked around this problem by adding a Dictionary<string, object> as an item in the Context. 

Thank you for your consideration

**Comment by martincostello** [comment]
Please open a new issue if this is issue is still present in Polly v8.
