### ISSUE TITLE
Request Hedging

### ISSUE THREAD

**Issue by alexhcheng** [App-vNext/Polly#891]
**Is your feature request related to a specific problem? Or an existing feature? Please describe.**
Our backend services can have high variance in latency due to various factors (hardware, uneven load, etc) and one way of addressing that is to use the Request Hedging technique.  We essentially send the first request, and after n ms (say n is set based on 99 percentile latency), then a second request is sent.  Hopefully, one of the 2 requests will return before the ultimate timeout.  Take whichever result that comes back first and return to client.

Background Info: [Request Hedging](https://medium.com/star-gazers/improving-tail-latency-with-request-hedging-700c77cabeda)

**Describe your proposed or preferred solution**:
I think one way of handling this is to use the Pessimistic timeout strategy and continue to wait on the first request (onTimeout/onTimeoutAsync) while the retry strategy sends the 2nd request.  But I don't see an easy way to bubble the result back.

**Describe any alternative options you've considered**:

**Any additional info?**

**Comment by martincostello** [comment]
Related to #876.

**Comment by alexhcheng** [comment]
thanks.  I'll close this and connect on the other thread.
