### ISSUE TITLE
Error installing package on dotnet core 5 project

### ISSUE THREAD

**Issue by mario-galindo** [App-vNext/Polly#892]
**Summary**: 

I got errors in my .net core web api project when I try to install Microsoft.Extensions.Http.Polly using nuget manager running the following command

**dotnet add package Microsoft.Extensions.Http.Polly --version 5.0.1**

**Expected behavior**: 

No errors on package installation 

**Actual behaviour**:

<img width="1053" alt="Screen Shot 2021-10-03 at 14 33 17" src="https://user-images.githubusercontent.com/14081810/135770745-440989bf-60e2-47a2-8793-154ec5a32fbb.png">

**Steps / Code to reproduce the problem**: 

Run: dotnet add package Microsoft.Extensions.Http.Polly --version 5.0.1 on web api project using .net core 5

Best is a [complete example](https://stackoverflow.com/help/mcve) or failing unit test.  It is _always_ useful to see:

+ **code of any policy declarations**, 
+ **code of calls to `.Execute/AndCapture/Async(...)`**

**Comment by martincostello** [comment]
This package is provided by Microsoft from the dotnet/aspnetcore repo. You'll need to raise the issue with them if this isn't an issue with certificate trust on your local computer.

Considering the dates in the screenshot (actual text would be preferable to a screenshot) being months ago, it would suggest to me this is a local issue to you or this issue from a few months ago in NuGet: https://github.com/NuGet/Home/issues/10491

In either case, this is not an issue with a package provided by the Polly maintainers, nor an issue we can resolve.
