### ISSUE TITLE
Wait and Retry - Dependent on Response Content in HttpClientFactory

### ISSUE THREAD

**Issue by altmank** [App-vNext/Polly#893]
So I'm using Polly with the HttpClientFactory (using the extension package mentioned here https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory) and trying to add a reactive policy using AddPolicyHandler. The purpose of the policy is to identify when a rate limit has been hit and then do exponential back-off retry. 

The catch is that the external API for which I am calling, they return the API rate limit status as a response content body, they don't use message level status codes. So I have to read & deserialize the body content in order to determine if that was the reason for the error in order to know if I need to retry.

So far I haven't figured out how to do this. I saw some examples involving HandleRequest but they didn't seem to be compatible with AddPolicyHandler and also weren't async. So if anyone could point me in the right direction it would be helpful. 

I thought this might be a common use case as many API providers provide a response object and just always return 200 OK and the failure details may only be in the response object.

**Comment by martincostello** [comment]
Polly v8 contains improvements that should support this scenario of acting based on response headers in the context of retries.

https://github.com/App-vNext/Polly/blob/f6e09cc99baf3ea892c53580cd90509704a9dfff/samples/Retries/Program.cs#L101-L112

**Comment by altmank** [comment]
@martincostello I don't understand how functionality to act on response headers addresses this issue, which is talking about response body content being the trigger for retry. This feature doesn't seem to address the issue I raised at all.

**Comment by martincostello** [comment]
The example is using headers, but the same functionality should be usable to look at another part of the result, no?
