### ISSUE TITLE
Polly and persistence

### ISSUE THREAD

**Issue by mnabe** [App-vNext/Polly#899]
**Summary: What are you wanting to achieve?**
I want to use Polly to fire a webhook event. If the response is not 200, I want to retry. However, in the case of server crash or similar, I need to know, if the event was eventually fired or not.

Does Polly offer some sort of persistent storage, that could help you keep track of state and helps you survive server restarts/crashes etc.?

**Comment by martincostello** [comment]
No, Polly does not contain any functionality to do this.

We're unlikely to add such functionality either, as there as pretty much an unbounded number of ways this could be implemented based on apps' own unique requirements for their persistence.

**Comment by mnabe** [comment]
Thanks for the quick answer. 🙂
