### ISSUE TITLE
ServerCertificateCustomValidationCallback callback is not invoked

### ISSUE THREAD

**Issue by 7amou3** [App-vNext/Polly#906]
I'm using Polly to send https requests to an external server, the probleme is the ServerCertificateCustomValidationCallback is never invoked:

```
public class CustomeHttpClient : HttpClientHandler {
  ...
  ...
 protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) {

  ServerCertificateCustomValidationCallback = (requestMessage, certificate, chain, sslError) =>
  {
    // this callback should be invoked for each request
  };
   return await Policy
               .Handle<Exception>()
               .WaitAndRetryAsync(_retryPolicy.RetryCount,
                                  retryAttempt => TimeSpan.FromMilliseconds(_retryPolicy.MillisecondsBeforeRetry),
                                  (ex, t, retryCount, ctx) => _logger.LogWarning("Retry attempt SendAsync {OutgoingRequestUri}", request.RequestUri))
               .ExecuteAsync(async () => 
               {
                   return await base.SendAsync(request, cancellationToken);
               });
 }
}
```

the ServerCertificateCustomValidationCallback callback is invoked only when I send request without Polly,
Any idea how to solve this issue?
Thanks

**Comment by martincostello** [comment]
This isn't a Polly issue, this will be related to your usage of `HttpClient`.

From the code sample you've provided, the callback is not registered anywhere. It needs to be set on the `HttpClient`/`HttpClientHandler` you're using with your custom delegating handling.

**Comment by martincostello** [comment]
Sorry, just noticed you're assigning it to the property directly, so it is assigned.

In any case, this is still external to Polly, and you probably don't want to be assigning the callback on every HTTP request through the handler, but when it's created initially.

**Comment by 7amou3** [comment]
Thanks for your response,
But I don't understand why it's external to Polly, the callback gets invoked properly when I remove Polly, but when I wrap the SendAsync request inside Polly the callback does not trigger

**Comment by martincostello** [comment]
I'm not sure, but the HttpClient infrastructure will be what will calls the callback for the certificate validation, not Polly. Polly has no idea about its existence.
