### ISSUE TITLE
CircuitBreaker documentation

### ISSUE THREAD

**Issue by tasoss** [App-vNext/Polly#916]
Hello.
I have a question about something related to polly's documentation.
https://github.com/App-vNext/Polly/wiki/Advanced-Circuit-Breaker
says
> subsystem within at most 10 seconds (see discussion below)

Can you please clarify how 10 seconds are calculated?
As it seems , 2.5 seconds (according to the give configuration)
is enough to trigger the system.
Thanks!

**Comment by martincostello** [comment]
Note how the documentation says "_**at most** 10 seconds_", not "_**in** 10 seconds_".

A more detailed discussion is given at the bottom of the wiki page you have referenced [here](https://github.com/App-vNext/Polly/wiki/Advanced-Circuit-Breaker#detailed-operation-of-failure-statistics).

> Internally, the circuit-breaker measures statistics with a rolling statistical window. The configured samplingDuration T is divided into ten slices, such that statistics for 10% of the period T are discarded every time T / 10. This smooths the calculation of failure rates to acceptable tolerances (compared to disposing 100% of the statistics every time T).
>
> The samplingDuration is not however further subdivided into slices if samplingDuration is set below 200 milliseconds. This prevents excessively frequent recalculation when there is little responsiveness gain.

Depending on how the advanced circuit breaker is configured, it either uses a fixed window of time, or a rolling window of time. The time is calculated in either case based on the progression of the wall clock time from the system clock via `DateTime.UtcNow`.

https://github.com/App-vNext/Polly/blob/cd3d697ab844bbf916a23e236c62210909d6a1a4/src/Polly/CircuitBreaker/AdvancedCircuitController.cs#L25-L27

https://github.com/App-vNext/Polly/blob/cd3d697ab844bbf916a23e236c62210909d6a1a4/src/Polly/CircuitBreaker/SingleHealthMetrics.cs#L39-L40

https://github.com/App-vNext/Polly/blob/cd3d697ab844bbf916a23e236c62210909d6a1a4/src/Polly/CircuitBreaker/RollingHealthMetrics.cs#L65-L66

https://github.com/App-vNext/Polly/blob/cd3d697ab844bbf916a23e236c62210909d6a1a4/src/Polly/Utilities/SystemClock.cs#L31

**Comment by tasoss** [comment]
Hello and thanks for replying.
I have noticed "most" and i have read the documentation but still i couldn't get it.
Let me give it a try again , after reading the code , and ask you again in case of any questions.
Thanks!
