### ISSUE TITLE
RateLimiter does not appear to respect low values

### ISSUE THREAD

**Issue by grahambunce** [App-vNext/Polly#927]
**Summary**: 

Using the rate limiter with low values in a multi-second window does not appear to allow the correct number of calls through.

Polly 7.2.3

**Actual behaviour**:

The test below would be expected to allow 3 calls in a 10 second window through. It only allows 1 call through.

**Steps / Code to reproduce the problem**: 

```        [TestMethod]
        public void Correct_calls_allowed_through_limiter()
        {
            var count = 0;
            var policy = Policy.RateLimit(3, new TimeSpan(0, 0, 10));
            for (var i = 0; i < 5; i++)
            {
                try
                {
                    policy.Execute(() =>
                    {
                        count++;
                    });
                }
                catch (RateLimitRejectedException)
                {
                }
            }
            Assert.AreEqual(3, count);
        }

**Comment by martincostello** [comment]
I think what's happening here is that you haven't configured the policy to support bursts. This means by default there is one call allowed each 0.333... seconds (3 requests / 10 seconds). As your `Execute()` method effectively executes in negligible time as it is only incrementing an integer, you're consuming the "whole 1" execution within that 333 millisecond window.

More information about this is available in the wiki [here](https://github.com/App-vNext/Polly/wiki/Rate-Limit#allow-for-bursts).

Let me know if the documentation can be clarified further.

**Comment by grahambunce** [comment]
@martincostello Thanks for this. I read about bursts and maybe I misunderstood them but I think they may work around the issue but it could also cause undesirable effects would it not? The condition is that only 3 are ever allowed in a 10 second window but a burst allows me to go over that limit. This explains the implementation:

> For example, a policy that allows a rate limit of 10 executions per second will only allow an execution to succeed once every 100 milliseconds

but then the limiter isn't really as described at the beginning

> Provides a policy which limits the number of executions which can be performed during a rolling window of time.

Which is fine as far as it goes as the limiter is effectively means that the limit isn't really 3 in 10 seconds, it's 1 every 0.333 seconds which is not the same thing at all.

Have I misunderstood something?

**Comment by martincostello** [comment]
It's possible I confused things myself when writing the documentation for the new policy. I didn't implement it myself, but did get it over the line for merge/release and wrote up the documentation for it.

The rolling window of time is correct, but I guess it's not correct in all the possible use cases (_"...which **can** be..."_ (emphasis mine)).

I'll have a think about how I could update the documentation to make this clearer.
