### ISSUE TITLE
Deleting a file throws exception when is use, despite of using Polly

### ISSUE THREAD

**Issue by kouwerp** [App-vNext/Polly#929]
[](https://stackoverflow.com/posts/71257113/timeline)I'm trying to create some sort of prototype of a C# application. My goal is to delete a file when it becomes available, so not locked by another process. Lots of times I need to read/delete/move files which are still in use cause they are being written by another application on the network. Network-delay causes the file-in-use exception.

For my demo I created another console application which writes every 5 sec. a line to the same file and in the mean time it keeps the file open, so this will work.

So I want to wrap the delete/move action in a Polly policy, but when I'll try there is still the IOException: file in use by another process. I assumed this was captured by Polly, but apparently I'm wrong...What's wrong in this code ? When I take a look at the InnerException, it's NULL ?
```

 static void Main(string[] args)
    {
         
        var MAX_RETRIES = 5;

        Console.WriteLine($"Attempting to delete the file {fileName}\r\nPress any key to continue....");
        Console.ReadKey();

        //Build the policy
        var retryPolicy = Policy
            .Handle<IOException>()
            .Or<Exception>()
            .Retry(MAX_RETRIES);

        //Execute the error prone code with the policy
        retryPolicy.Execute(() =>
        {
            Console.WriteLine($"Starting File-deleting on {fileName}");
            if (File.Exists(fileName))
                File.Delete(fileName);      // <== here's where the exception occurs !

            Console.WriteLine("File deleted");
        });

        Console.WriteLine("Press any key to quit");
        
        var s=Console.ReadLine();
        if (s == "quit");
        Environment.Exit(0);

    }
```

The code above is just for testing, **not** production-ready

**Comment by martincostello** [comment]
I would expect the IDE to show the exception be thrown on the `Execute()` line when the retries are exhausted, not in the lambda where the exception would be thrown before any retry is attempted.

Is your IDE configured to break when an exception is thrown, rather than only when it is _unhandled_?

**Comment by kouwerp** [comment]
These are the setting of the exception, visible from the exception itself
***@***.***

**Comment by martincostello** [comment]
I'm not sure what you meant by that comment.

If you run your code outside the debugger, how many times does it print "Starting File-deleting on..."?

Does it print the message saying to press any key to exit?

**Comment by kouwerp** [comment]
Sorry for my unclear reply….


I now unchecked the box ( not quite sure what this does), but it seems to work right now. The file isn’t removed untill I closed the writing application.
