### ISSUE TITLE
How to use RateLimit with HttpClientFactory?

### ISSUE THREAD

**Issue by alexandrejobin** [App-vNext/Polly#931]
**Summary: What are you wanting to achieve?**
The remote APIs that I would like to call have RateLimit as follow:
* max 30 requests per second
* max 400 requests per minute
* max 10000 requests per hour
* max 15000 request per day

I would like to throttle my HttpClient so I don't get a http code 429 but the only example i've found is to put a policy at the time you send a request to the API. What I would like to do is to put a policy at the http client and whatever api it call, it will be throttled.

**What code or approach do you have so far?**  

```
services
    .AddHttpClient<IMspGeoClient, MspGeoClient>()
    // define how much time to wait before timeout
    .AddPolicyHandler(Policy.TimeoutAsync<HttpResponseMessage>(TimeSpan.FromSeconds(10)))
    // catch network failures (System.Net.Http.HttpRequestException), HTTP 5XX and 408 status code and apply the policy
    .AddTransientHttpErrorPolicy(policyBuilder =>
        policyBuilder.WaitAndRetryAsync(2, // number of retry before fail
            retryAttempt => TimeSpan.FromMilliseconds(300) // wait before retry
    ));
```

**Comment by martincostello** [comment]
In the first instance, considering using the [rate-limit](https://github.com/App-vNext/Polly#rate-limit) or [bulkhead](https://github.com/App-vNext/Polly#bulkhead) policies.

However trying to replicate the rate limit 1:1 locally will never be 100% consistent with the remote party, so you'll still need to code to deal with HTTP 429 responses from the remote service to be resilient.

**Comment by alexandrejobin** [comment]
I tried to use the rate-limit but I don't see how to add it to the http client. I only see examples to use the policy and call a function but not to add it to the http client. Or I'm blind?

**Comment by martincostello** [comment]
Policies of any type can be configured with HttpClientFactory via the `AddPolicyHandler()` extension method as described in this article on docs.microsoft.com: [_How to use Typed Clients with IHttpClientFactory_](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#how-to-use-typed-clients-with-ihttpclientfactory)

```csharp
services.AddHttpClient<ICatalogService, CatalogService>(client =>
{
    client.BaseAddress = new Uri(Configuration["BaseUrl"]);
})
    .AddPolicyHandler(GetRetryPolicy())
    .AddPolicyHandler(GetCircuitBreakerPolicy());
```

They can also be added via the `AddPolicyHandlerFromRegistry()` extension method, like in [this code](https://github.com/martincostello/alexa-london-travel/blob/c85ee08e74358f908608d32e2da3cfc8f83988e3/src/LondonTravel.Skill/Extensions/IHttpClientBuilderExtensions.cs#L30-L36), where the policy to use is retrieved from a policy registry where the policy to use has [been previously configured](https://github.com/martincostello/alexa-london-travel/blob/326dc36bb16b561545d48f16546d3b59de166f6b/src/LondonTravel.Skill/Extensions/PollyServiceCollectionExtensions.cs#L24-L38).

**Comment by alexandrejobin** [comment]
Ok... i've just found out why I wasn't able to add the RateLimitPolicy. I was using this code but the RateLimitAsync was missing the type <HttpResponseMessage>.

```
services
    .AddHttpClient<IMspGeoClient, MspGeoClient>()
    .AddPolicyHandler(Policy.RateLimitAsync(20, TimeSpan.FromSeconds(1)))
    .AddPolicyHandler(Policy.TimeoutAsync<HttpResponseMessage>(TimeSpan.FromSeconds(10)))
    .AddTransientHttpErrorPolicy(policyBuilder =>
        policyBuilder.WaitAndRetryAsync(2, // number of retry before fail
            retryAttempt => TimeSpan.FromMilliseconds(300) // wait before retry
    ));
```

The good code is:
```
services
    .AddHttpClient<IMspGeoClient, MspGeoClient>()
    .AddPolicyHandler(Policy.RateLimitAsync<HttpResponseMessage>(20, TimeSpan.FromSeconds(1)))
    .AddPolicyHandler(Policy.TimeoutAsync<HttpResponseMessage>(TimeSpan.FromSeconds(10)))
    .AddTransientHttpErrorPolicy(policyBuilder =>
        policyBuilder.WaitAndRetryAsync(2, // number of retry before fail
            retryAttempt => TimeSpan.FromMilliseconds(300) // wait before retry
    ));
```
