### ISSUE TITLE
Logical Timeout/Slow Response Policy?

### ISSUE THREAD

**Issue by znelson32** [App-vNext/Polly#935]
**Summary: What are you wanting to achieve?**
Isolating slow responses / logical timeouts on a service call which contribute to the opening of a circuit breaker, however, accomplishing this by allowing the service calls to complete. For ex., if a service call exceeds a Timespan, allow it to continue (_because it may ultimately be successful_) but logically fail the call in regards to the circuit breaker's perspective such that if enough calls are slow the breaker will open. The use case could be slow database queries where after n-seconds you want to stop additional calls from piling up on the database server but you want the initial few calls to complete (_or ultimately fail outright but that part is already something Polly does_).

**What code or approach do you have so far?**  
Nothing. Unsure of how to implement this in a custom AsyncPolicy<T> as it appears the mechanism to open a breaker (_or vote for its opening_) is either throwing exceptions (_which would terminate the service call_) or fully opening the breaker via Isolate() which any given thread should not be able to do on its own. 

It is _always_ useful to see:

+ **code of any policy declarations**, 
+ **code of the calls to `.Execute/AndCapture/Async(...)`**

**Comment by martincostello** [comment]
@martintmk Is there anything in v8 that would fulfil this feature request?
