### ISSUE TITLE
RateLimiter improvements: 60 requests per minute, is not 1 request per second

### ISSUE THREAD

**Issue by danbopes** [App-vNext/Polly#937]
**Is your feature request related to a specific problem? Or an existing feature? Please describe.**
See: https://github.com/App-vNext/Polly/issues/936

**Describe your proposed or preferred solution**:
If I'm given 60 requests per minute, that equates to 1 request per second. It's not 1 request per second, it's 60 requests per minute. If I queue up 500 requests, 60 should execute (Let's say these take 5 seconds), and then all future requests should throw `RateLimitRejectedException` with a 55 second retry after. Setting the burst window to 60, doesn't result in the same behavior.

Proposed Solution: Add other rate limiter engine that supports a true "If I'm allocated this many executions, I'll try to execute as many as possible, as soon as I can".

**Comment by martintmk** [comment]
Hey @danbopes, Polly v8 now has built-in support for [System.Threading.RateLimiting](https://devblogs.microsoft.com/dotnet/announcing-rate-limiting-for-dotnet/) which is much more flexible and supports the scenario above. 

https://github.com/App-vNext/Polly/tree/v8-fixed-issues/src/Polly.RateLimiting

This issue will be closed once v8 is released.

**Comment by martintmk** [comment]
The alpha is released. Please try it out:
https://www.nuget.org/packages/Polly.Core/

Closing because this issue was addressed in V8.
