### ISSUE TITLE
How to access cancellation token from onRetryAsync?

### ISSUE THREAD

**Issue by devlie** [App-vNext/Polly#941]
**Summary: What are you wanting to achieve?**
Get access to `cancellationToken` from `onRetryAsync` delegate. I have a retry policy that refreshes connection string from `onRetryAsync` when a call hits authorization error. The connection string is retrieved asynchronously, and I'd like to pass in `cancellationToken` to make it cancellable.

```csharp
_authRetryPolicy = Policy
      .HandleInner<CosmosException>(e => e.StatusCode == HttpStatusCode.Unauthorized)
      .RetryAsync(
          retryCount: 1,
          onRetryAsync: async (ex, retryNumber) => await RefreshAuthKeyAsync(accountName)); // <-- pass in ct here
```

```csharp
return await _authRetryPolicy.ExecuteAsync(async ct =>
{
      await DoSomethingAsync(..., ct);
},
cancellationToken, false);
```

**What code or approach do you have so far?**  
I have to pass in the original `cancellationToken` using PolicyContext which makes the calling code clunky. Am I missing an obvious overload or is this really the only way to do it? Thank you.

**Comment by martincostello** [comment]
Yes, your approach using the `Context` is the only way to achieve this at the moment.

This could probably be improved in a future major release, but the current design has too many overloads as it is to add more to handle this scenario, particularly when it's still achievable with what's available today, albeit more "clunky".
