### ISSUE TITLE
.Net 6 Version

### ISSUE THREAD

**Issue by larrywa** [App-vNext/Polly#942]
**Is your feature request related to a specific problem? Or an existing feature? Please describe.**
Do you have a .Net 6 version of this app?

**Describe your proposed or preferred solution**:

**Describe any alternative options you've considered**:

**Any additional info?**

**Comment by martincostello** [comment]
We have to-date found no need to make a version of Polly that specifically targets `net6.0` because there aren't any compelling new APIs we could use to justify doing so. This would also introduce additional multitargeting complexity.

The latest version of Polly is fully compatible with .NET 6.

**Comment by larrywa** [comment]
> We have to-date found no need to make a version of Polly that specifically targets `net6.0` because there aren't any compelling new APIs we could use to justify doing so. This would also introduce additional multitargeting complexity.
> 
> The latest version of Polly is fully compatible with .NET 6.

Thank you for your quick reply!
