### ISSUE TITLE
Stop excecution of WaitAndRetry policy on subsequent identical Exceptions 

### ISSUE THREAD

**Issue by toms12334234** [App-vNext/Polly#949]
**Is your feature request related to a specific problem? Or an existing feature? Please describe.**
My feature request is related to the WaitAndRetry policy. A lot of our colleagues use Polly internally from console applications to various servers of ours. We use WCF connections so Exceptions on servers pop up as System.ServiceModel.FaultException with an InnerException set. 

Exceptions are cause by these categories: 
1: Exception due to server being unavailable because it's doing work.
2: Exception due to one of my colleagues making an error with setting up the action in the console application. This can be one of our exception classes, but also a NullReferenceException.
3: Exception due to an error in on of our various software products, thrown on the server. These can be any Exception

For categories 2 and 3 we would like to skip retries because a retry would cause the same exception.
On category 1, we want to retry because the retry might succeed.

**Describe your proposed or preferred solution**:
On a WaitAndRetry I would like to compare subsequent caught exceptions. I would then be able to compare these. If these are similar,  I would like to be able to stop the WaitAndRetry Policy and not do any further retries. It might be a strange pattern, but for us this could work out great. And maybe it could for others?

**Describe any alternative options you've considered**:
It might be possible to raise proper Exceptions differentiate between different Types of Exceptions. This might be the proper way of doing this. Please tell me if it is.

Now that I come to think of it, I could probably save the subsequent Exceptions through the onRetry delegate. But then I can't think of how to stop the policy from doing any more Retries.

**Any additional info?**

**Comment by johnib** [comment]
Why isn't configuring the retry policy to be only on category 1?

Categories 2 and 3 won't be retried at all. 

Polly exposes the relevant methods for checking the inner exception. You should be able to configure it per your described needs.

**Comment by toms12334234** [comment]
> Why isn't configuring the retry policy to be only on category 1?
> 
> Categories 2 and 3 won't be retried at all.
> 
> Polly exposes the relevant methods for checking the inner exception. You should be able to configure it per your described needs.

Because both categories 1, 2 and 3 could throw ie, a NullReferenceException. And the easiest (or possibly only) way to distinguish would be to compare to the previous Exception.

Now this might be possible by saving the Exceptions in a common Dictionary in the delegate. And then halting in another wrapped policy when this Exception is present in that Dictionary.

It's either that, or rewriting our code to always throw proper Exceptions I guess. Then I understand it's up to us!
