### ISSUE TITLE
two exception conditions together on CircuitBreaker policy

### ISSUE THREAD

**Issue by ritikaadit2** [App-vNext/Polly#952]
I am trying to put two exception conditions together on CircuitBreaker policy. It's OR condition:

Something like this:  `HttpStatusCode>(c => c == HttpStatusCode.InternalServerError) ` OR   `HttpRequestException`

I attempted something like this but gives syntax error:
```
            var CircuitBreakerPolicy = Polly.Policy
                .HandleResult<HttpStatusCode>(c => c == HttpStatusCode.InternalServerError) 
                .OrInner<HttpRequestException>(e => e != null)
                .CircuitBreaker(10, TimeSpan.FromSeconds(60), OnBreak, OnReset);
```

What's the correct syntaxt to write this?  I should be able to write OnBreak and OnReset need to work as well.

**Comment by martincostello** [comment]
What syntax error do you get?

**Comment by taleleuma** [comment]
@martincostello, never mind. I panicked. This was error on my part.  Earlier, I was attempting to use `.HandleResult` and  `.OrResult` together with OnBreak delegate and struggling with syntax.  ` .HandleResult` and  `.OrInner<`  worked for me. 
Thank you for your quick response, though.
