### ISSUE TITLE
Can Polly (Distributed) Caching be persuaded to support ETags?

### ISSUE THREAD

**Issue by vpopescu** [App-vNext/Polly#953]
**Summary: What are you wanting to achieve?**

Standard (minimal) e-tag support: https://en.wikipedia.org/wiki/HTTP_ETag

In my service, I'd like to reply with an etag associated with the cached item and return a 304 if the If-None-Match header matches the etag of an item in the cache.  Basically I want to save returning large payloads if the client already has them.

**What code or approach do you have so far?**  

I don't have anything working, this is more of a "is it doable" and "where do I start" type question. I couldn't find anything relevant in the polly code or in the Issues.

My questions are:
1. is this doable? Or on the roadmap?
2. Any recommendations on:
     a. How do I associate an e-tag with a cached entry, so I calculate it at insertion time and return it to the client?
     b. How do I short circuit a read if the If-None-Match value matches a stored item's etag, so I can return 304? A filter could work, but that's two cache reads on a miss, instead of one (one by the filter, and one by polly)

I'm using Polly 7 with Redis as distributed cache.

**Comment by martincostello** [comment]
Sorry for the delayed response.

I'm not aware of any prior art to do this. The closest I could find was this documentation that describes using policies to customise the TTL based on the HTTP status code: https://github.com/App-vNext/Polly/wiki/Cache#caching-responses-only-selectively

**Comment by vpopescu** [comment]
Thank you. I can close this, or you are welcome to close it, not sure what the protocol is. 

Would be nice to consider adding some facilities to implement patterns such as etags or populating cache-control headers efficiently. For the latter, it would be nice if we could get the cached item and its remaining ttl at the same time (since under the hood the library could do it more optimally by pipelining commands, at least when using Redis)

**Comment by vpopescu** [comment]
I'll close it, feel free to reopen it if it needs to be tracked.
