### ISSUE TITLE
how to stop a task in pessimistic timeout?

### ISSUE THREAD

**Issue by li-zheng-hao** [App-vNext/Polly#957]
i am using timeout policy in my project, but i dont know how to stop a running task after being timeout

```csharp
var policy=Policy.TimeoutAsync(1, TimeoutStrategy.Pessimistic, (context, timespan, task) =>
{
    
    Console.WriteLine("time out !");

    // how to stop task here ?
   
    return Task.FromResult("handled");
    
});

policy.ExecuteAsync(async () =>
{
    Console.WriteLine("begin");
    // too long time even no end
    await Task.Delay(99999);
    Console.WriteLine("end");

});
```

**Comment by martincostello** [comment]
For these two examples as-is, there is no way to stop the task. The best practice is to use `TimeoutStrategy.Optimistic` in conjunction with a `CancellationToken` to signal to the method to stop performing work, which is documented [here in the wiki](https://github.com/App-vNext/Polly/wiki/Timeout#optimistic-timeout).

If you cannot do this, then information about what happens to the abandoned task is available [here in the same wiki page](https://github.com/App-vNext/Polly/wiki/Timeout#what-happens-to-the-timed-out-delegate).

**Comment by li-zheng-hao** [comment]
There is a problem in optimistic mode: if a step in the loop listening process is stuck, then the task will not be finished for a long time，code sample is here:

```csharp
var timeoutPolicy = Policy.TimeoutAsync(5, TimeoutStrategy.Optimistic, (context, timespan, task) =>
{
    Console.WriteLine(
         $"timeout triggered");
    return Task.FromResult("finised");
});
await timeoutPolicy
   .ExecuteAsync(
     async ct =>
     {
         Console.WriteLine("begin");
         while (true)
         {
             if (ct.IsCancellationRequested)
                 ct.ThrowIfCancellationRequested();
             // do some job with random time, if Random function return 999999 , application will be stucked here!
             await Task.Delay(new Random().Next(100,999999));
         }
         Console.WriteLine("end");

     },
    CancellationToken.None
);
```

If the random function gets a very large value, the task will not exit for a long time! how to avoid this situation?

**Comment by martincostello** [comment]
By passing the `CancellationToken` to the call to [`Task.Delay(int, CancellationToken)`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.delay?view=net-6.0#system-threading-tasks-task-delay(system-int32-system-threading-cancellationtoken)) instead of `Task.Delay(int)`.

**Comment by li-zheng-hao** [comment]
What if the function is not `Task.Delay` and it  cannot receive the `CancellationToken`?  like `DoSomethingFunc(int a,int b)`,and i can't modify the function (ex: calling functions from third-party libraries)

**Comment by martincostello** [comment]
Then the guidance in the wiki about the abandoned task applies. If you cannot change the code to observe the cancellation token, then there is no way to force it to end.
