### ISSUE TITLE
Circuit breaker fires onReset even if successful

### ISSUE THREAD

**Issue by bunceg** [App-vNext/Polly#96]
Hi,

Not sure if this is an issue or not but when I use the circuit breaker, the onReset call always appears to fire on each invoke of the circuit breaker wrapper method. Is this correct?

The name infers it should only fire after a circuit has been broken and has now been cleared (i.e. reset to good).

Thanks

**Comment by reisenberger** [comment]
Hi @bunceg .  Thank you for picking this up.  You are right: the onReset delegate is currently firing too often.  A pull request will fix this very shortly.

**Comment by reisenberger** [comment]
Hi @bunceg . Thanks again for picking this up.  Revised nuget packages fixing this should be available from [nuget](https://www.nuget.org/packages/polly) in the next hour or so - soon as it says 4.1.2 there.

**Comment by joelhulen** [comment]
The updated NuGet packages have been published, as is indicated by the 4.1.2 version displayed on the Polly home page as well as on [nuget.org](https://www.nuget.org/packages/polly)
