### ISSUE TITLE
How to get state in new Polly syntax for HttpClientFactory (AddTransientHttpErrorPolicy)

### ISSUE THREAD

**Issue by quico14** [App-vNext/Polly#960]
**Summary: What are you wanting to achieve?**
I want to access to the CircuitState of the policy using the new syntax for HttpClientFactory configuration way with
`AddTransientHttpErrorPolicy`.

**What code or approach do you have so far?**  

I have seen that the AddTransientHttpErrorPolicy offers `OnBreak `and `OnReset`, but wanted to make sure if there is a way to get directly the state of the circuit and not get notified on the transitions. I would like to get just the state but I do not want to make anything on the transition (OnBreak, OnReset).

I have seen it is possible to be done through the [traditional Polly syntax](https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory#using-any-policy-configured-via-the-traditional-polly-syntax), but wanted to know if it is possible with the new syntax. 

Thanks.

**Comment by PeterCsalaHbo** [comment]
I think an alternative could be to register the Circuit Breaker policy into a registry and then use the `AddPolicyHandlerFromRegistry`.

### Policy definition
```cs
var cbPolicy = HttpPolicyExtensions.HandleTransientHttpError()
           .CircuitBreakerAsync(...);
```
### Policy registration
```
PolicyRegistry registry = new()
{
    { "CB", cbPolicy }
};
services.AddPolicyRegistry(registry);
services.AddHttpClient().AddPolicyHandlerFromRegistry("CB");
```

### Policy retrieval
```
public class XYZClient 
{
    private readonly ICircuitBreakerPolicy cb;
    public XYZClient(..., IReadOnlyPolicyRegistry<string> registry, ...)
    {
       ...
       var policy = registry.Get<IAsyncPolicy<HttpResponseMessage>>("CB");
       cb = policy as ICircuitBreakerPolicy;
    }

   public async Task<HttpResponseMessage> GetAsync()
   {
       if (cb.CircuitState == CircuitState.Open)
       ....
   } 
}    
```
