### ISSUE TITLE
"Unable to resolve service for type 'Polly.IAsyncPolicy' while attempting to activate 'SqlDapperClient'."

### ISSUE THREAD

**Issue by santoshpatro** [App-vNext/Polly#963]
Hi Team,

Need help on the issue. All the details are mentioned at : https://stackoverflow.com/questions/74065832/unable-to-resolve-service-for-type-polly-iasyncpolicy-while-attempting-to-act?noredirect=1#comment130772536_74065832

Thanks,
Santosh

**Comment by martincostello** [comment]
Added comment to the question.
