### ISSUE TITLE
Support fixed window with rate limiter

### ISSUE THREAD

**Issue by paulhickman-a365** [App-vNext/Polly#965]
I'd like an option on the rate limiter to be able optionally specify a fixed start time for the window in which rate limiting occurs.

**Use Case:**

A 3rd party web service has a limit of X calls per calendar day. I wish to rate limit my requests to not exceed this limit, and therefore need to synchronize the rate limiting window with the start of the day in a specific time zone.

**Suggested improvement** 

The rate limit policy takes an optional sliding windowStartTime parameter. If supplied then, a sliding window will not be used and the Nth rate limiting window will be from time ````windowStartTime + N * perTimeSpan <= time < windowStartTime + (N+1) * perTimeSpan````, when N starting at 0.

**Comment by martintmk** [comment]
Hey @paulhickman-a365, Polly v8 now has built-in support for [System.Threading.RateLimiting](https://devblogs.microsoft.com/dotnet/announcing-rate-limiting-for-dotnet/) which is much more flexible and supports the scenario above. 

https://github.com/App-vNext/Polly/tree/v8-fixed-issues/src/Polly.RateLimiting

This issue will be closed once v8 is released.

**Comment by martintmk** [comment]
The alpha is released. Please try it out:
https://www.nuget.org/packages/Polly.Core/

Closing because this issue was addressed in V8.
