### ISSUE TITLE
Why a Thread.Sleep() is needed in all the example?

### ISSUE THREAD

**Issue by iqoOopi** [App-vNext/Polly#966]
![image](https://user-images.githubusercontent.com/46897552/201787021-a5ac1212-2fec-46ab-a4e3-9264ddaebe25.png)
I downloaded the Polly example, wondering why this Thread.Sleep(500) is needed?

Thanks

**Comment by martincostello** [comment]
They're just there to make the samples easy for a human to follow when they're running and printing to the console.

Otherwise they'd run as fast as they can, and flood the console with content that's scrolling by too fast to read.
