### ISSUE TITLE
How does the memory cache handle multiple threads entering when the cache is expired?

### ISSUE THREAD

**Issue by ccfoo242** [App-vNext/Polly#970]
**Summary: What are you wanting to achieve?**
I'm trying to figure out if my use of a semaphore is even needed. 

**What code or approach do you have so far?**  
my policy is basically:
```
Policy.CacheAsync<T>(cacheProvider: cacheProvider.AsyncFor<T>(),
                    ttl: TimeSpan.FromMinutes(cacheMinutes),
                    onCacheError: onCacheError);
```

```
private readonly SemaphoreSlim _usersLock; 
...
_usersLock = new SemaphoreSlim(1, 1); 
...

await _usersLock.WaitAsync(cancellationToken);
try
{                     
    var cacheResult = await _cache.ExecuteAndCaptureAsync(async (_, _) =>
                            await _masterDataApi.GetUserAccountsAsync(new UserAccountLookupDto(), cancellationToken), 
                            new Context(UsersCacheKey), 
                            cancellationToken);
    
    cacheResult.ThrowIfFailure(_masterDataApi.GetType(), nameof(_masterDataApi.GetUserAccountsAsync));
    
    return cacheResult.Result;
}
finally
{
    _usersLock.Release();
}
```

I did this a while back because I thought if multiple threads tried to read when the cache was expired then I would get multiple http calls. I'm pretty sure I had tested this but it was a few years ago. I was going over my code and got to wondering if this was needed at all anymore (or ever was)?

**Comment by ccfoo242** [comment]
A little more context:
The way I have this written in another service that is currently running in production, I am calling ExecuteAsync() and catching and logging any errors. As luck would have it, we started having a permissions problem with Azure yesterday. I have two instances listening for messages on Azure Service Bus. Each can have up to 20 message handlers/threads. 

The http client has this policy:
```
public IAsyncPolicy<HttpResponseMessage> CreateAsyncHttpRetryPolicy(ILogger logger, bool useCircuitBreaker = false)
{
    var retryPolicy = HttpPolicyExtensions
        .HandleTransientHttpError()
        .OrResult(msg => !msg.IsSuccessStatusCode)
        .WaitAndRetryAsync(
        retryCount: RetrieveDataRetrySleepSeconds.Length,
            sleepDurationProvider: (i) => TimeSpan.FromSeconds(RetrieveDataRetrySleepSeconds[i - 1]),
            onRetry: (response, timeSpan) => logger.LogError(response.Exception,
                "Retrying service call after {RetryDelaySeconds} seconds: {StatusCode} {RequestUri}",
                timeSpan.TotalSeconds,
                response?.Result.StatusCode,
                response?.Result.RequestMessage.RequestUri));

    if (useCircuitBreaker && CircuitBreakerAllowedEvents > 0)
    {
        return HttpPolicyExtensions
            .HandleTransientHttpError()
            .OrResult(msg => !msg.IsSuccessStatusCode)
            .CircuitBreakerAsync(CircuitBreakerAllowedEvents, TimeSpan.FromSeconds(CircuitBreakerDurationSeconds))
            .WrapAsync(retryPolicy);
    }
    return retryPolicy;
}
```
(I am passing true so it also uses the circuit breaker)

Yet I am seeing hundreds of errors being logged:
![image](https://user-images.githubusercontent.com/6061719/207629068-f8cc9587-7878-48b5-8283-2e3c83b88828.png)

I get the feeling I am using the policies wrong. Each thread must be adding its own copy of the policy as I didn't set that up as a singleton.

Anyway, that is just distracting from my original question. If you have any insight to offer for this issue as well I would appreciate it.

**Comment by joelhulen** [comment]
Since you are dealing with potentially multiple instances accessing the same limited resource, I suggest looking into the [Distributed Circuit Breaker](https://github.com/Polly-Contrib/Polly.Contrib.AzureFunctions.CircuitBreaker) pattern. This sample project shows how to implement a distributed circuit breaker in Azure Functions (using Durable functions), where you use a circuit breaker id with each call by your instances to share the circuit breaker state. Otherwise, if you don't share the circuit breaker state, then each instance only knows about its own state and not the state of other instances also trying to access the resource, as you have seen.

My caveat here is that the sample implementation I linked you to is about three years old, so you'll want to update the SDK versions, but theoretically, it should still work. If you want to go down this path and need some help getting it to work, please let me know.

**Comment by ccfoo242** [comment]
> Since you are dealing with potentially multiple instances accessing the same limited resource, I suggest looking into the [Distributed Circuit Breaker](https://github.com/Polly-Contrib/Polly.Contrib.AzureFunctions.CircuitBreaker) pattern. 

I am ok with the two instances dealing with it on their own. But would setting the existing circuit breaker policy up as a singleton not work for the threads used in each instance?
