### ISSUE TITLE
Optimistic Timeout Should Require an `ExecuteAsync` Overload Taking a `CancellationToken`

### ISSUE THREAD

**Issue by WalkerCodeRanger** [App-vNext/Polly#975]
**Is your feature request related to a specific problem? Or an existing feature? Please describe.**
The optimistic timeout feature requires that "[delegates you execute support co-operative cancellation (ie honor CancellationTokens), and that the delegates express that timeout by throwing `OperationCanceledException` (as is standard for most .NET library code).](https://github.com/App-vNext/Polly/wiki/Timeout#optimistic-timeout)" This requires that an overload of `ExecuteAsync` that passes a `CancellationToken` to the delegate be used. However, it is a common mistake to use an overload that doesn't pass a cancellation token to the delegate. For example see #907 and #629. I believe there is never a situation where it makes sense to use an overload without a cancellation token for an optimistic timeout policy.

**Describe your proposed or preferred solution**:
I think that using an `Execute`, `ExecuteAsync`, `ExecuteAndCapture`, or `ExecuteAndCaptureAsync` overload with a delegate that does not take a cancellation token with an `TimeoutStrategy.Optimistic` timeout should throw an `InvalidOperationException` immediately with an exception message saying that an overload using the cancellation token needs to be used.

For example, I think the following code should throw an exception:
```csharp
var policy = Policy.TimeoutAsync(TimeSpan.FromSeconds(1), TimeoutStrategy.Optimistic);

// Recommend InvalidOperationException on next line since it is clearly a bug
await policy.ExecuteAsync(() => Task.Delay(TimeSpan.FromSeconds(5)));
```

**Describe any alternative options you've considered**:
We tried to use the [`Microsoft.CodeAnalysis.BannedApiAnalyzers`](https://github.com/dotnet/roslyn-analyzers) project to ban the use of Polly execute methods that do not pass a cancellation token to the delegate (our code base never uses pessimistic timeout). However, there are too many overloads and the banned API analyzer requires you to ban on both the interface and the concrete type (e.g. `IAsyncPolicy` and `AsyncTimeoutPolicy`). So it just wasn't feasible to use the banned API analyzer in this case.

**Comment by PeterCsalaHbo** [comment]
I do understand your struggle but I think your request won't be fulfilled. Here is my reasoning:
 - Policy definition and its execution are separated by design 
    - In order to fulfil your requirement the policy or a chain of policies should be accessed to spot that there is somewhere a `Timeout` policy  (in the chain) with optimistic strategy
    - Let's suppose you have following chain of policies: Timeout > Retry > Circuit Breaker > Timeout
      - The outer most timeout is defined as _pessimistic_, the inner most timeout is defined as _optimistic_
      - Should we throw an `IOE`?
 - The same bug would remain if you would use the good overload but forgot to pass the token down
 ```cs
 await policy.ExecuteAsync((ct) => Task.Delay(TimeSpan.FromSeconds(5)), token);
 ```
