### ISSUE TITLE
Rename default branch

### ISSUE THREAD

**Issue by martincostello** [App-vNext/Polly#981]
It would be preferable to rename the default branch of the project from its current value to `main`.

**Comment by joelhulen** [comment]
I've renamed the branch to `main` and am updating the CI/CD builds to target the new branch.

To update your local repo clone, execute the following:

```cli
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by martincostello** [comment]
Thanks Joel!
