### ISSUE TITLE
Add Dependabot

### ISSUE THREAD

**Issue by martincostello** [App-vNext/Polly#982]
To keep our dependencies up-to-date and require less manual maintenance (e.g. #973, #974), it would be good to enable Dependabot on the repository.

Assuming others are happy to do so, I can submit a PR to add the configuration for it for an agreed cadence (daily/as-needed, weekly, monthly?).

**Comment by joelhulen** [comment]
I think this is a good idea with the upcoming v8 in mind. In my opinion, for now, weekly is fine.
