### ISSUE TITLE
CircuitBreaker - Unexpecte HalfOpen state

### ISSUE THREAD

**Issue by mxa0079** [App-vNext/Polly#99]
Hello,

I am creating a redirection layer for my circuit braker needs as recommended in [jayconway's blog post](http://blog.jaywayco.co.uk/circuit-breaking-with-polly/) but adapted for the async world ( see `ICircuitBreaker` and `PollyCircuitBreaker` in [the accompanying gist](https://gist.github.com/mxa0079/431af8205beaf7ff199d) ). 

However, when the exception limit is reached the circuit ends in a `HalfOpen` state instead of the expected `Open` state. If I implemented the policy directly, I get the expected behavior.

Any ideas?

[Full gist sample here](https://gist.github.com/mxa0079/431af8205beaf7ff199d)

**Comment by reisenberger** [comment]
Hi @mxa0079 
I have not run the code, but in the gist sample, you have two repeated lines:

```
BreakOnNumberOfExceptions = breakOnNumberOfExceptions; 
BreakOnNumberOfExceptions = breakOnNumberOfExceptions; 
```

Was this meant to be:

```
BreakOnNumberOfExceptions = breakOnNumberOfExceptions; 
BreakCircuitForSeconds = breakCircuitForSeconds; 
```

?

As the gist stands, it looks like your `PollyCircuitBreaker` wrapping class will be creating a CircuitBreaker to break for TimeSpan.FromSeconds(0), which will be why it is transitioning from `Closed` to `HalfOpen` immediately, in certain cases.  (Why certain cases return `Closed` and others `HalfOpen` may be a race condition between TimeSpan.FromSeconds(0) and the test code; preferring to reply quickly, I haven't investigated that.)  Anyway: Adding ```BreakCircuitForSeconds = breakCircuitForSeconds;``` should fix it?

Your issue does point up that the original circuit-breaker code doesn't have a guard condition on breaking for a zero TimeSpan.  If that was in place, your issue would have been spotted sooner.  We'll consider adding that!

**Comment by mxa0079** [comment]
Duh! It always helps to get a second set of eyes. Good spot.

Abstraction is now working as expected. Thanks for the quick reply!

And yes, it would be nice to have that check in place.
