### ISSUE TITLE
Circuit open is not happening 

### ISSUE THREAD

**Issue by Meenakshise** [App-vNext/Polly#994]
**Summary**:

This is the configuration I have. And the circuit break is not happening.

```xml
<RetryDelay>1</RetryDelay>
<MaxRetryCount>7</MaxRetryCount>
<CircuitBreakDuration>120</CircuitBreakDuration>
<MaxExceptionsBeforeCircuitBreak>20</MaxExceptionsBeforeCircuitBreak>
```

**Steps / Code to reproduce the problem**:

Here is the code that creates the policy. It is singleton and I am storing it inside the policy registry. 

```csharp

{
    [RegisterAsPerContainerLifetime]
    public class StandardPolicyProvider : IPolicyProvider
    {
        private readonly static ILogger _log = LogFactory.GetLoggerForClass<StandardPolicyProvider>(); // with context
        private readonly IPollyResilienceSettings _stdPollySettings;
        private readonly IAsyncPolicy _asyncPolicy;

        public StandardPolicyProvider(IPollyResilienceSettings stdPollySettings)
        {
            _stdPollySettings = stdPollySettings;
            _asyncPolicy = CreatePolicy();
        }
        protected HttpStatusCode[] statusCodesWorthSkipping = {
               HttpStatusCode.NotFound, // 404
            };
        protected HttpStatusCode[] statusCodesWorthTrying = {
               HttpStatusCode.BadGateway, // 502
               HttpStatusCode.ServiceUnavailable, // 503
               HttpStatusCode.RequestTimeout, // 408
               HttpStatusCode.GatewayTimeout, // 504
            };

        public IAsyncPolicy ResiliencePolicy => _asyncPolicy;

        public int i = 1;
        public ResilienceTypes ResilienceType => ResilienceTypes.StandardResilience;

        public virtual PolicyBuilder RetryPolicyBuilder()
        {
            return Policy.Handle<FailedRequestException>(ex =>
           ((!(statusCodesWorthSkipping.Contains((HttpStatusCode)(ex.Status)))) || (statusCodesWorthTrying.Contains((HttpStatusCode)ex.Status))));
        }

        public virtual PolicyBuilder CircuitPolicyBuilder()
        {
            return Policy.Handle<FailedRequestException>(ex =>
           ((!(statusCodesWorthSkipping.Contains((HttpStatusCode)(ex.Status)))) || (statusCodesWorthTrying.Contains((HttpStatusCode)ex.Status))));
        }
        private IAsyncPolicy CreatePolicy()
        {
            var retryPolicy = CreateRetryPolicy();
            var circuitBreakerPolicy = CreateCircuitBreakerPolicy();
            return Policy.WrapAsync( circuitBreakerPolicy, retryPolicy);
        }

        public AsyncRetryPolicy CreateRetryPolicy()
        {
            var delays = Backoff.DecorrelatedJitterBackoffV2(medianFirstRetryDelay:
            TimeSpan.FromSeconds(_stdPollySettings.RetryDelay), retryCount:
            _stdPollySettings.MaxRetryCount);
            Random jitterer = new Random();
            return RetryPolicyBuilder()
                .WaitAndRetryAsync(delays, (exception, timespan) =>
                {
                    _log.Warn("Standard policy : retry meena occurred", exception);
                });

        }
        public AsyncCircuitBreakerPolicy CreateCircuitBreakerPolicy()
        {
            return CircuitPolicyBuilder()
                 .CircuitBreakerAsync(_stdPollySettings.MaxExceptionsBeforeCircuitBreak, TimeSpan.FromSeconds(_stdPollySettings.CircuitBreakDuration), (exception, timespan) =>
                 {
                     _log.Warn("Standard policy : asdfsdfs circuit opened",exception);
                 },
                () =>
                {
                     _log.Info("Standard policy : asdfsdfs circuit closed");
                });
        }
    }
}
```

Here is how I am adding it to the PolicyRegistery

```csharp
PolicyRegistry policyRegistery = new PolicyRegistry();
policyRegistery.Add(ResilienceTypes.StandardResilience.ToString(), _pollyPolicyProviders.Where(x => x.ResilienceType == ResilienceTypes.StandardResilience).First().ResiliencePolicy);
```

 Am I doing anything wrong here? Retry and circuit break is not working correctly. Circuit open sometimes comes with small number and sometimes that too doesn't work. For ex, retry count if i keep as 3 and maxcircuitbreakexception 4 then the circuit open happens in the same request itself and it works.  But if I keep retry count as 7 and maxcircuitbreakexception 20 then the retry count has to span across multiple requests (atleast 4 req. 7 * 4) to reach or exceed 20 exceptions. 

Can you please let me know where the mistake is. I am unable to find out.

**Comment by Meenakshise** [comment]
I am using the same Policy for all my requests. Meaning I have multiple API's. to call all of them I am using the same policy. They are 5 different microservices. Is this what you say as multiple call sites? How does polly works in that case? 

If i use the same policy circuit open state will be only for that microservice or is it shared for all the microservices?

**Comment by martincostello** [comment]
Could you create a simpler repro that demonstrates the problem you're seeing, as well as the _behaviour_ you seeing?

My _guess_ is that your retries are counting to your circuit breaking count in a way that makes it look like there's less attempts than you think.

Typically the order of a policy wrap is [`Policy.Wrap(retry, breaker)](https://github.com/App-vNext/Polly#policywrap), not `Policy.WrapAsync( circuitBreakerPolicy, retryPolicy)` which is what your code is doing.

**Comment by martincostello** [comment]
> If i use the same policy circuit open state will be only for that microservice or is it shared for all the microservices?

One instance of a circuit breaker will be shared across whatever you use it with. If you use the same instance with 5 services, then it will break requests to all five services.

**Comment by Meenakshise** [comment]
Yeah I was using this only Policy.Wrap(retry, breaker). Was trying multiple things to see where the issue was.

**Comment by Meenakshise** [comment]
I will give you a sample app in sometime. In the meanwhile can you clear my doubt?

When should we use the same policy? In case of multiple call sites should I use 1 policy for each site or the same policy should be used for all the sites?
What is the use case that 1 policy or multiple policies to be used. Please explain

**Comment by martincostello** [comment]
How many policies you need to use is entirely up to your specific use case, so that's for you to apply your own judgement and decide what's appropriate.

Typically you would use a different circuit breaker per external dependency. For example, if you shared a circuit breaker policy between service A for operation X and service B for operation Y, you wouldn't want unavailability of service A opening the circuit breaker to make operation Y unavailable for the unrelated service B.

**Comment by martincostello** [comment]
Personally, I would have one per service (i.e. 10), but if you don't have any fallback behaviours if any of the 10 services go down then you could implement it with 1 if you wished.

I see circuit breakers more for protecting calls to a _dependency_, rather than protecting an _operation_, which is why I would have 10. The fact that your code cannot fulfil its intended use case if any of the 10 services are unavailable is more of an implementation detail to your use case.

This is how things would look with one circuit breaker shared between all the services:

```mermaid
sequenceDiagram
    title: One Circuit Breaker
    Caller->>+Circuit Breaker: 
    Circuit Breaker->>+Your code: 
    Your code->>Service 1: 
    Service 1-->>Your code: 
    Your code->>Service 2: 
    Service 2-->>Your code: 
    Your code->>Service N: 
    Service N-->>Your code: 
    Your code-->>-Circuit Breaker: 
    Circuit Breaker-->>-Caller: 
```

This is how it would look if you had one per service:

```mermaid
sequenceDiagram
    title: Circuit Breaker Per Service
    Caller->>+Your code: 
    Your code->>+Circuit Breaker 1: 
    Circuit Breaker 1->>Service 1: 
    Service 1-->>Circuit Breaker 1: 
    Circuit Breaker 1-->>-Your code: 
    Your code->>+Circuit Breaker 2: 
    Circuit Breaker 2->>+Service 2: 
    Service 2-->>Circuit Breaker 2: 
    Circuit Breaker 2-->>-Your code: 
    Your code->>+Circuit Breaker N: 
    Circuit Breaker N->>+Service N: 
    Service N-->>Circuit Breaker N: 
    Circuit Breaker N-->>-Your code: 
    Your code-->>-Caller: 
```

**Comment by Meenakshise** [comment]
<StandardPollyResilienceSettings>
		<RetryPolicyName>StandardPollyPolicy</RetryPolicyName>
		<RetryDelay>1</RetryDelay>
		<MaxRetryCount>3</MaxRetryCount>
		<CircuitBreakDuration>120</CircuitBreakDuration>
		<MaxExceptionsBeforeCircuitBreak>6</MaxExceptionsBeforeCircuitBreak>
	</StandardPollyResilienceSettings>

When the max exception has to span more than 1 request to trigger the circuit open it is not working. In the above case, I have hit the request 2 times then it will have more than 6 exception and then the circuit opens. But with this settings it is not working. 

But 
	<StandardPollyResilienceSettings>
		<RetryPolicyName>StandardPollyPolicy</RetryPolicyName>
		<RetryDelay>1</RetryDelay>
		<MaxRetryCount>3</MaxRetryCount>
		<CircuitBreakDuration>120</CircuitBreakDuration>
		<MaxExceptionsBeforeCircuitBreak>4</MaxExceptionsBeforeCircuitBreak>
	</StandardPollyResilienceSettings>

In this case, it is working perfectly because it is just 1 request. And the exception has reached 4. 

When does the retry count resets? 
Does this field MaxExceptionsBeforeCircuitBreak value has to be reached within a stipulated time? If yes as part of which property in the policy we have to configure this. 


I tried my code in a sample application and it is working perfectly. But in our project the 1st use case is not working. Because it takes some time to call that 4 to 5 apis to get the result.
